- Sources/StreamChatUI/CommonViews/BaseViews.swift
- docusaurus/docs/iOS/basics/getting-started.md
- docusaurus/docs/iOS/controllers/channels.md
- docusaurus/docs/iOS/controllers/messages.md
- docusaurus/docs/iOS/controllers/users.md
- docusaurus/docs/iOS/guides/importance-of-synchronize.md
- docusaurus/sidebars-ios.json
CIS-1281
The improvements for `synchronize`. This PR is phase 1 of this project to really start improving how customers use `synchronize` and more importantly _when_ to use it. This PR is mainly focussing our documentation and guides as we move across to a more sustainable architecture in the near future.
Mainly documentation, I have implemented a whole new guide focussed solely on `synchronize()` and added these tips throughout other documentation pieces. I have also added inline docs for the use of `setUp()`.
The testing here is mainly in the docs, have I covered everything?
> [CIS-1281] Improve `synchronize` messaging

- Makefile
- StreamChat-XCFrameworks.podspec
- StreamChat.podspec
- StreamChatArtifacts.json
- StreamChatUI-XCFrameworks.podspec
- StreamChatUI.podspec
https://stream-io.atlassian.net/browse/CIS-1355
https://stream-io.atlassian.net/browse/CIS-1356
https://stream-io.atlassian.net/browse/CIS-1366
For now, xcframeworks/Module stable binaries are going to be soft launched to make sure it is working as expected without widely announcing it.
- Main podspec definitions point to OSS
- Artifacts don't contain `xcframework` in the name for Carthage not to pick them automatically
- Add json to reference artifacts from Carthage
> [CIS-1355, CIS-1356, CIS-1366] Use OSS as default integration source

- CHANGELOG.md
- Sources/StreamChat/Workers/TypingEventSender_Tests.swift
- Sources/StreamChat/Workers/TypingEventsSender.swift
It was not possible to call `stopTyping` after calling `startTyping` in `TypingEventSender`. It was designed around `keystroke`, with `startTyping` being used as a helper
`startTyping` or `stopTyping` now doesn't depend on `keystroke`, tested with new unit tests, which do fail without the changes.
Run `TypingEventSender_Tests`
> Fix TypingEventSender inconsistencies

- docusaurus/sidebars-ios.json
There was a bad JSON validation happening on the sidebar for Docusaurus.
Remove the trailing ","
> [CIS-1391] Fixing bad JSON on Docusaurus

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Mock.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/WebSocketClient/ConnectionStatus.swift
- Sources/StreamChat/WebSocketClient/ConnectionStatus_Tests.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- Sources/StreamChat/Workers/ChatClientUpdater_Tests.swift
Task: CIS-1319
Sub-task: CIS-1362
Store the source of disconnection. This info is needed for CIS-1319 to decide whether the LLC should reconnect automatically when:
- app goes from background to foreground
- the Internet connection comes back
1. Introduced `initialized` state to be clear that there was no attempt to connect yet.
2. When disconnection is initiated by the client/user the disconnection source get stored as the associated value in the `disconnected` state
Unit tests are updated to cover the changes.
N/A
> [CIS-1362] Store web-socket disconnection source

- Scripts/removePublicDeclaracions.sh
- Sources/StreamChat/StreamStarscream/Engine/Engine.swift
- Sources/StreamChat/StreamStarscream/Framer/FrameCollector.swift
- Sources/StreamChat/StreamStarscream/Framer/Framer.swift
- Sources/StreamChat/StreamStarscream/Framer/HTTPHandler.swift
- Sources/StreamChat/StreamStarscream/Security/Security.swift
- Sources/StreamChat/StreamStarscream/Server/Server.swift
- Sources/StreamChat/StreamStarscream/Starscream/WebSocket.swift
- Sources/StreamChat/StreamStarscream/Transport/Transport.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptions.swift
- Sources/StreamChatUI/Deprecations.swift
Get rid of compile-time warnings
* Check the CI log for any occurrences of compile-time warnings
* Replace conformances of `class` with `AnyObject`.
* Publicize previously deprecated convenience `ChatMessageLayoutOptions` APIs to not cause warnings in integrators project
> [BW] Resolves compile time warnings, including publicizing the previously deprecated ChatMessageLayoutOptions APIs

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageReactionDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
- Sources/StreamChat/Workers/Background/MessageSender.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
Optimistic reactions introduced a regression on the reactions for the current user. WS events never include the `own_reactions` field populated and this was not handled correctly leading to showing incorrect reaction status.
The code that saves messages now exposes a `syncOwnReactions` parameter, this allows us to not sync `own_reactions` when handling events and vice versa when receiving messages from API responses.
Manually add reactions from different devices was enough to reproduce this problem.
> [CIS-1405] Fix own reactions regression

- CHANGELOG.md
- Sources/StreamChat/Utils/Logger/Destination/BaseLogDestination.swift
- Sources/StreamChat/Utils/Logger/Destination/LogDestination.swift
- Sources/StreamChat/Utils/Logger/Logger.swift
- StreamChatSample/LogStore.swift
Our Logger is flexible and one can add new destinations easily, using `LogConfig.destinations`. But there's a limitation: adding a new destination using existing LogConfig parameters is hard. Consider the scenario, where you create a new destination:
```swift
class CoolLogDestination: BaseLogDestination {
override func write(message: String) {
// CoolLoggingSystem.log(message)
}
}
```
and you want to use this destination. You do:
```swift
LogConfig.destinations = [CoolLogDestination()]
```
then the new destination gets initialized with default params of `BaseLogDestination`, which is not what we want, we want it to get initialized with `LogConfig` parameters, which we can customize.
The other way is to initialize it by passing all params:
```swift
LogConfig.destinations = …
```
> Introduce `LogConfig.destinationTypes`

- docusaurus/docs/iOS/swiftui/components/message-reactions.md
- docusaurus/docs/iOS/swiftui/components/message-threads.md
- docusaurus/sidebars-ios.json
https://stream-io.atlassian.net/browse/SWUI-46
Added docs for the Message Threads feature implemented in the SwiftUI SDK.
Updated the docs to reflect the current state of the SwiftUI SDK.
Run the docs locally with docusaurus.
- [] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
> Added docs for Message Threads in SwiftUI

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionAuthorsVC/ChatMessageReactionAuthorsVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- Sources/StreamChatUI/CommonViews/AvatarView/ChatChannelAvatarView.swift
- Sources/StreamChatUI/CommonViews/Suggestions/ChatSuggestionsVC.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Sources/StreamChatUI/Gallery/GalleryVC.swift
- Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift
- Sources/StreamChatUI/Utils/Array+SafeSubscript.swift
- Sources/StreamChatUI/Utils/Array+SafeSubscript_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
https://stream-io.atlassian.net/browse/CIS-1378
Because of the nature of the core of our chat message list, we sometimes have crashes because we are accessing indexes of messages that are not present anymore. The purpose of this PR is not to fix the core nature of this edge cases, but instead make sure that we don't fail when this happens.
It also introduces a custom assertion, together with a log whenever this happens.
A new extension over Collections will allow safe subscripts by checking whether the index is within the bounds of the collection. If it is not there, it would return nil, instead of crashing.
> [CIS-1378] Safely access indexes of collections

- docusaurus/docs/iOS/swiftui/components/attachments.md
- docusaurus/docs/iOS/swiftui/components/inline-replies.md
- docusaurus/docs/iOS/swiftui/components/message-reactions.md
- docusaurus/sidebars-ios.json
[JIRA](https://stream-io.atlassian.net/browse/SWUI-47?atlOrigin=eyJpIjoiYjlhNWNlNTQ0NTUzNDRiM2I1Nzk0Yjk4OWY4NTE4ODIiLCJwIjoiaiJ9)
Docs to reflect the new inline replies feature in the SwiftUI SDK.
Updated the docs.
Only text changes.
Test locally on docusaurus.
> Added docs for inline replies in the SwiftUI SDK

- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
This PR fixes an out of bound problem where we would reload a previous row that is not present in the message list
You could reproduce this on a channel with 26 messages 🙈
> Fix reload rows out of bounds

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptions.swift
- Sources/StreamChatUI/Deprecations.swift
Fix some bad conflict resolutions of `ChatMessageLayoutOptions`. These functions should not be deprecated.
> Move unwanted deprecated functions from `ChatMessageLayoutOptions`

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/ChannelQuery.swift
- Sources/StreamChat/Query/QueryOptions.swift
Allowing users to explicitly start/stop watching a channel, and make Channel queries without `watch`ing.
The functionality were there but hidden, now exposed.
Already tested in `ChannelController_Tests`
> Expose `QueryOptions` and `start/stopWatching`

- .gitignore
- .gitmodules
- Scripts/updateDependency.sh
Given the amount of issues that we started encountering by having submodules in our repo, this PR removes the need for those
Instead of having submodules in our repo, the Makefile keeps track of the dependencies versions that we are using. Whenever we are in the need of updating dependencies, running update_dependencies will clone the needed repos and remove them just after.
> Move away from submodules

- Sources/StreamChat/Database/DTOs/MessageDTO.swift
Change Fetch Request to exclude deleted thread replies from showing up in the main channel. When a reply message is deleted, its type changes from "reply" into "deleted", we can still use the `parent_message_id` field to determine if the. message is a reply or not.
> CIS-1339 Exclude deleted replies correctly

- fastlane/Fastfile
Update lane to push all specs
The new recursive function now includes the possibility to pass in `sync`, `podspec` and `dry` parameter.
The `push_pods` lane that wraps logic around pod trunk pushing all the specs now accetps `sync` and `dry` parameter.
If `dry` parameter is specified you can test the lane without firing the `pod trunk push` logic.
```
bundle exec fastlane push_pods sync:0 dry:1
```
`push_pods` now pushes all current podspecs - OSS + XCFramework counterparts.
Verify that running the below lane prints out all 4 podspecs without running the actual push.
`NOTE`:
Don't run the `bundle exec fastlane push_pods sync:0` without `dry:1` parameter specified.
```
bundle exec fastlane push_pods sync:0 dry:1
```
> Pod trunk push all specs

- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelMuteDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelReadDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageReactionDTO.swift
- Sources/StreamChat/Database/DTOs/MessageSearchQueryDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/ChatMessage.swift
- Sources/StreamChat/Models/MuteDetails.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageImageGallery+UploadingOverlay.swift
[CIS-1273](https://stream-io.atlassian.net/browse/CIS-1273)
A number of differences between the Core Data model and the ManagedObjects were present. This pull request removes those issues. When applicable a sensible default is chosen for what Core Data describes as primitive types.
Several model definitions were changed, several managed object classes were changed, several sensible default values were chosen.
Run through the app. No crashes should occur.
_Add relevant screenshots or videos showcasing the changes._
> [CIS-1273] Ensure optional Core Data attributes map to optional Swift types

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/Utils/UIScrollView+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
CIS-1367
Fix sending multiple unnecessary pagination requests when `ChannelListVC` and `ChannelVC` are shown.
This PR makes sure that only 1 API call is made to load both `ChannelListVC` and `ChannelVC`
Before this PR `ChannelListVC` was calling the Query Channels endpoint 3 times!
**ChannelListVC**
- Pagination was incorrectly firing the request to load another page 
- The `make` method was calling the `setUp` method (which calls `synchronize`)
**ChannelVC**
- Pagination was incorrectly firing the request to load another page
> [CIS-1367] Remove unnecessary API calls from `ChannelVC` and `ChannelListVC `

- Makefile
- StreamChat-XCFramework.podspec
- docusaurus/docs/iOS/basics/integration.md
- fastlane/Fastfile
None
While I was doing the release for 4.6.0, I spotted some deficiencies in our automated processes. This PR intends to fix those
- Make sure LICENSE is present in the zipped artifacts for CocoaPods not to complain
- Update Carthage OSS integration documentation to require --no-use-binaries
- Fix release's changelog and target branch
- Remove redundant tag creation executions in Fastfile's publish_release
- Improve order of podspecs publishing to avoid waiting too long
- Remove macOS references in StreamChat-XCFramework for CocoaPods not to fail because of missing macOS slice in the binary. This will be addressed in https://stream-io.atlassian.net/browse/CIS-1433
- Outline XCFrameworks as preferred integration method for Carthage
> Fix Release creation/automation issues

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/ChannelListQuery_Tests.swift
CIS-1446
`member_limit` was added to API some time ago but iOS SDK didn't include it.
Enable logs in DemoApp and use this controller:
```swift
// Channels with the current user
let controller = ChatClient.shared
.channelListController(query: .init(filter: .containMembers(userIds: [userCredentials.id]), messagesLimit: 0, membersLimit: 0))
```
you'll see that no messages or channels are returned.
> [CIS-1446] Add `ChannelListQuery.membersLimit` param

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
CIS-1444
Support passing `extra data` for messages & replies from `ComposerVC`.
* `ComposerVC`'s content is now extended with `extraData` field that is passed along down to `MessageUpdater`.
* Contains bugfix for `cid` key appearing in the `extraData` payload.
* TableView properly reloads edited messages when `extraData` changes.
Subclass `ComposerVC` and try to pass the extra data eg when editing the message.
```
import Foundation
import StreamChat
import UIKit
final class CustomComposerVC: ComposerVC {
override func editMessage(withId id: MessageId, newText: String) {
content.extraData["myKey"] = .string("myValue")
super.editMessage(withId: id, newText: newText)
}
}
```
> [CIS-1444] Support passing the extra data along with the message

- CHANGELOG.md
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
When you load a thread we perform 4 API calls:
- getMessage by ID (for the parent message)
- getReplies
- userSearch
- queryChannel
There are a number of issues here that this PR resolves:
- The getReplies is called even when the parent messages has `reply_count` == 0
- The userSearch call is call for no good reason (probably a leftover from previous version)
- The queryChannel API call comes from calling `channelController.synchronize` that seems to be also not necessary 
- In most cases `ChatThreadVC` already gets a `ChatMessage` 
End result (based on demo app):
- 0 API calls when you open a thread for the first time
- 1 API call when you open a thread that has > 0 replies
> [CIS-1431] Make only necessary API calls in threads

- .github/workflows/publish-release.yml
- fastlane/Fastfile
This PR uses COCOAPODS_TRUNK_TOKEN to push pods updates in the name of Stream Chat Bot
This GHA shows how proper Trunk access has been given: https://github.com/GetStream/stream-chat-swift/actions/runs/1634183563
> [Release Improvements] Push pods from CI

- DemoApp/AppDelegate.swift
Simply disable Atlantis until we have dynamic configuration in place
> Disable Atlantis until Demo App Configuration is complete

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/MemberEvents_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
- Sources/StreamChat/WebSocketClient/Events/NotificationEvents_Tests.swift
- Tests/StreamChatTests/MockEnpointResponses/Events/Notification/NotificationAddedToChannel+MissingFields.json
- Tests/StreamChatTests/MockEnpointResponses/Events/Notification/NotificationAddedToChannel.json
CIS-1227
CIS-1430
CIS-1227 : 
`Channel.membership` was not parsed / removed in all cases. Some WS events were not handled correctly.
CIS-1430 :
`MemberListController` didn't report `member.added` and `notification.added_to_channel` events correctly.
`MemberEventsMiddleware` now correctly handles all events.
We cannot add members to a `MemberListQuery` if the query has a filter, since we can't verify if the member matches the filter.
Unit tests are implemented.
> [CIS-1227] [CIS-1430] Channel.membership correct handling

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView.swift
- Sources/StreamChatUI/Utils/ImageCDN.swift
- Sources/StreamChatUI/Utils/ImageCDN_Tests.swift
- Sources/StreamChatUI/Utils/ImageLoading/NukeImageLoader.swift
- Sources/StreamChatUI/Utils/NukeImageProcessor.swift
https://stream-io.atlassian.net/browse/CIS-1475
Fixes: https://github.com/GetStream/stream-chat-swift/issues/1541
It's been reported several times that we were randomly showing low resolution images. We recently discovered it was due to a combination of an image and a message quoting an image that this was reproducible. Our image cache was not properly distinguishing between the two, and in the event of the quoted message being downloaded before the full resolution image, it would use the cached quoted image in the full size version too.
This PR changes the cacheKey to use the url with the size parameters, when possible. It will also keep the original image size if `preferredSize` is not passed, to make sure we don't have conflicting caching keys
> [CIS-1475] Fix wrong image resolution when images are being quoted

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC_Tests.swift
CIS-1288
Fix a crash that happened when switching channels very quickly, and when the messages were not prefetched from a channel list.
Call `reloadData()` when the data source of the message list is changed. When switching channels in quick succession it could happen that there were conflicts in the message list with the old data.
N/A
Steps to reproduce this:
1. Apply this patch: [dontSaveChannelListMessages.patch.zip](https://github.com/GetStream/stream-chat-swift/files/7841000/dontSaveChannelListMessages.patch.zip)
2. Open the demo app with an iPad (Easier to quickly switch channels)
3. Quickly switch channels
4. Observe there are no crashes.
In order to reproduce the crash, make sure to revert this PR and delete the `reloadData()` from here: …
> [CIS-1288] Fix Message List NSInternalInconsistencyException Crash

- CHANGELOG.md
- Sources/StreamChatUI/Gallery/GalleryVC.swift
CIS-1489
When sharing a video or image, it should not share an URL, but the asset itself.
When it is an image, we share the actual `UIImage`. When it is a video, we share the actual video file.
https://user-images.githubusercontent.com/12814114/149010574-930e9d90-3eac-4235-ac04-1e257b279286.MP4
- Tap on a video/image
- Tap share
- Click on "mail"
- The video/image should appear on the content of the email instead of an URL
> [CIS-1489] Fix Image and Video sharing behaviour

- CHANGELOG.md
- DemoApp/ChatPresenter.swift
- Sources/StreamChatUI/ChatChannel/StreamModalTransitioningDelegate.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- StreamChat.xcodeproj/project.pbxproj
CIS-1491
https://github.com/GetStream/stream-chat-swift/issues/1307
Introduces a custom modal transition to workaround the inverted table view on the message list. This custom transition should be used if you as a customer need to present the `ChatChannelVC` in a modal. 
```swift
// Make sure to have a reference to the delegate or it will be instantly deallocated.
let streamModalTransitioningDelegate = StreamModalTransitioningDelegate()
func showChannelVC() {
let vc = ChatChannelVC()
vc.channelController = client.channelController(for: cid)
let navVC = UINavigationController(rootViewController: vc)
navVC.transitioningDelegate = streamModalTransitioningDelegate
navVC.modalPresentationStyle = .custom
navigationController?.present(navVC, animated: true, completion: nil)
}
```
Adds a new …
> [CIS-1491] Add custom modal transition for message list

- CHANGELOG.md
- Sources/StreamChat/Utils/Timers.swift
- Sources/StreamChat/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
- Sources/StreamChat/WebSocketClient/WebSocketPingController.swift
- Sources/StreamChat/WebSocketClient/WebSocketPingController_Tests.swift
CIS-1525
_Provide a description of the implementation._
* `WebSocketPingController` is run on specific engineQueue
* URL socket client calls delegate methods on dedicated `callbackQueue`
* Few renamings & doc updates
_Describe the steps how this change can be tested (or why it can't be tested)._
> [CIS-1525] Crashfix for hanging DispatchWorkItem reference in WebSocketClient

- Sources/StreamChatUI/Appearance+Formatters/ChannelNameFormatter.swift
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/Utils/ChatChannelNamer.swift
Fix compiler warnings of the `ChatChannelNamer` deprecation.
> Avoid compiler warnings in the `ChatChannelNamer` deprecation

- CHANGELOG.md
- Sources/StreamChat/Models/ChannelId.swift
CIS-1549
Simple one-liner, just to fix the `ChannelId.rawValue` access control. 
Change `ChannelId.rawValue` access control to public. 
N/A
N/A
> [CIS-1549] Make `ChannelId.rawValue` public

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/SendButton/SendButton.swift
CIS-1554
Currently, the animation of SendButton is done on the didSet observer of the `SendButton.isEnabled`, the problem with this is that the `didSet` implementation is not overridable. We need to extract the animation to a different function so that the customer can override it.
Extract the animation to a different function so that the customer can override it.
N/A
N/A
> [CIS-1554] Make `SendButton` animation overridable

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC_Tests.swift
CIS-1557
Change the default logic of `shouldAddNewChannelToList` and `shoudListUpdatedChannel`. Currently, whenever a user removes itself from the channel, the channel is still present in the channel list. This shouldn't be the default use case, because most customers want the opposite to happen. This will reduce the customer support tickets we are having.
Move the `DemoApp` implementation to be the default one.
N/A
- Go to a channel
- Click on the Debug icon
- Remove yourself from the members
- Channel list should remove the channel
> [CIS-1557] Fix channel not removed from channel list when user leaves the channel

- CHANGELOG.md
- Examples/SlackClone/ChatClient.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- StreamChat.xcodeproj/project.pbxproj
CIS-1393
Fix a crash on iOS 12 that whenever the app was launched, it would instantly crash.
The crash was happening because of a mismatch between `UserDTO.teams` property marked as `[String]?` in db schema but being a `Set<String>?` in managed object subclass. Exactly what the error was saying: 
```
reason: 'Object of class Swift.__EmptySetSingleton is not among allowed top level class list (
NSArray,
NSDictionary,
NSString,
NSNumber,
NSDate,
NSData,
NSURL,
NSUUID,
NSNull
)'
```
The `teams` property is updated to be an array, made non-optional, and ensured to exist at the moment the `UserDTO` is saved to the persistent store.
N/A
- Run Slack Clone App on iOS 12
> [CIS-1393] Fix crash on iOS 12 when local storage enabled

- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/APIClient/APIClient_Mock.swift
- Sources/StreamChat/APIClient/APIClient_Tests.swift
- Sources/StreamChat/APIClient/CDNClient_Mock.swift
- Sources/StreamChat/APIClient/RequestDecoder.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncOperations_Tests.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/Repositories/SyncRepository_Tests.swift
- Sources/StreamChat/Utils/Atomic.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation_Tests.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChatTestTools/ChatClient_Mock.swift
- Sources/StreamChatTestTools/Spy.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Shared/WaitUntil.swift
Part of https://stream-io.atlassian.net/browse/CIS-1484
The goal of this PR is to move the APIClient to use an OperationQueue to handle incoming requests
Requests queue: Concurrent operations. Gives us the option to stop the queue and to easily queue a request.
> Offline Support - APIClient with OperationQueue

- CHANGELOG.md
- Sources/StreamChat/Utils/CoreDataLazy.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
CIS-1558
Make it easier to debug the cryptic `Date._unconditionallyBridgeFromObjectiveC` crashes
These crashes happen (not exclusively) when there's a model object belonging to an old user session. Since we evaluate models lazily (using our `CoreDataLazy` wrapper), when we keep a reference to a model, and then try to access a lazily evaluated property of that model, the DTO data is fully empty if the persistent store is recreated. This doesn't cause a crash for primitive types (Strings are "", numbers are 0), but for Date, it causes this crash.
We print a big, fat error telling what happened. This should (hopefully) help the users debug their issues.
Open `DemoChatChannelListRouter` and add this property:
```swift
var someMessage: ChatMessage?
```
In the `showCurrentUserProfile` func, add …
> [CIS-1558] Add increased logging for CoreData crashes

- Sources/StreamChat/APIClient/APIClient_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/EndpointPath.swift
- Sources/StreamChat/APIClient/Endpoints/EndpointPath_Tests.swift
Offline Support's Head branch was failing on Xcode 12. This was due to the fact that before Swift 5.5 we did not have syntesized Codable implementations for enumerations with associated objects.
See proposal here: https://github.com/apple/swift-evolution/blob/main/proposals/0295-codable-synthesis-for-enums-with-associated-values.md
> Implement missing syntesized Codable methods for EndpointPath on Swift < 5.5

- CHANGELOG.md
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController/UserSearchController.swift
- Tests/StreamChatTests/Controllers/SearchControllers/UserSearchController/UserSearchController_Tests.swift
Use IndexPath's item instead of row for macOS compatibility
- [] New code is covered by unit tests
_Please provide a suitable gif that describes your work on this pull request_
> Use IndexPath's item instead of row for macOS compatibility

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/Requests/MessageReactionRequestPayload.swift
- Tests/StreamChatTests/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Requests/MessageReactionRequestPayload_Tests.swift
https://stream-io.atlassian.net/browse/CIS-1679
Reported here: https://github.com/GetStream/stream-chat-swift/issues/1856
Using `enforce_unique` when adding a reaction was not producing the expected results.
This was basically due to the fact that the value was wrongly sent in the body
Move `enforce_unique` to be at the top level of the body
> [CIS-1679] Fix payload for reaction when using enforce_unique

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/StreamChatTests/Models/Attachments/AttachmentTypes_Tests.swift
CIS-1592
- Align the file mime-types with the other SDKs
- When adding a file from the File Picker, resolve the correct attachment type
- Fix the incorrect mime-type and add missing ones
- When adding a file in the composer, resolve the attachment type through the file extension
**Adding an image through the file picker:**
https://user-images.githubusercontent.com/12814114/159786027-e060d590-7330-476b-9b3e-ca9e357dcbac.mp4
**Scenario 1**:
1. Open a chat
2. Add a file attachment with extension `.rtf`
3. Check the HTTP Request - mime-type should be `text/rtf`
**Scenario 2**:
1. Open a chat
2. Add an image from the File Picker (Instead of Photo & Video Picker)
3. Composer should preview the image
4. Image should be added to the message list successfully
**Note:** When importing audio files …
> [CIS-1592] Fix file mime-types and attachment type 

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
Fixes #1872
CiS-1699
Pasting a long text into composer should display maximum text size.
Currently, pasting a long text does not call `setTextViewHeight` so text height is not correct.
| --- | --- |
| ![Simulator Screen Recording - iPhone 13 Pro - 2022-03-24 at 15 17 36](https://user-images.githubusercontent.com/770464/159936408-b25c0202-4b70-4435-a88c-08da0dc5dbe4.gif) | ![Simulator Screen Recording - iPhone 13 Pro - 2022-03-24 at 15 16 41](https://user-images.githubusercontent.com/770464/159936379-aee1ff10-ef40-464a-878c-bee016724848.gif) |
Test with this text:
> Really long message Really long message Really long message Really long message Really long message Really long message Really long message Really long message Really long message Really long message Really …
> [CIS-1699] Fix pasting long text into composer won't update input height

- docusaurus/docs/iOS/common-content/components-note.md
- docusaurus/docs/iOS/uikit/custom-components.md
- docusaurus/sidebars-ios.json
None
Currently, this documentation was hidden in a subsection of "CoreComponents". This documentation is very important and should be at the main level.
> [Docs] Move UI Kit Customizing Components doc to main level

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChat/Workers/EventNotificationCenter.swift
CIS-1737
Fix deadlock when accessing CoreDataLazy properties from the Events Delegate.
The current fix makes sure that the `EventNotificationCenter.postintEventQueue` is always called async to avoid any deadlock. Currently, there's no reason the call needs to be synchronous.
- Run the App
- Open a Channel
- Send a new message
- App should not be frozen
**Note:** An event handling and accessing `message.author` was introduced in the demo app so that we can test this often and there are no regressions.
> [CIS-1737] Fix deadlock when accessing some properties from Events Delegate

- Gemfile.lock
None
Update cocoapods to fix a vulnerability found by Github bot.
> [Security] Update cocoapods to fix Command Injection vulnerability

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelReadDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Deprecations.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTestTools/Mocks/Models + Extensions/ChannelUnreadCount_Mock.swift
- Tests/StreamChatTestTools/TestData/DummyData/MessagePayload.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelReadDTO_Tests.swift
- Tests/StreamChatTests/Models/ChatChannel_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
[CIS-1729](https://stream-io.atlassian.net/browse/CIS-1722)
⚠️ The PR is targeting the feature branch for message delivery status ⚠️
Fix the bug when silent messages/thread replies stay **unread** until the message that increments unread counts is posted to the channel.
Keep track of unread silent messages/thread replies and call `channels/***/read` endpoint if there's at least 1 unread message.
- Update `ChannelReadUpdaterMiddleware` to account silent message/thread replies
- Update `ChatChannel.isUnread` to check all kind of unread messages, not only messages that increment unread badge
- Expose `silentMessage/threadReplies` on `ChannelUnreadCounts`
- Rename `mentionedMessages` to `mentioningMessages` in `ChannelUnreadCounts` 
**Before:**
**After:**
**GIVEN** I'm in the channel
**AND** …
> [CIS-1729] Call read endpoint when only silent messages/thread replies are posted

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
CIS-1747
https://github.com/GetStream/stream-chat-swift/issues/1905
Fix audio files not rendering previews.
Currently, we don't support audio files. And with the file-type fixes, now the audio files don't render any preview. So until we support audio files, we need to fall back the audio files to normal files.
| --- | --- |
| <img width="335" alt="image" src="https://user-images.githubusercontent.com/12814114/162263040-8e807b61-c9ca-4a32-a80b-a8ae11b385f5.png"> | <img width="331" alt="image" src="https://user-images.githubusercontent.com/12814114/162262788-06eb635d-d613-474b-9631-f72246b49fa5.png"> |
- Open a Chat
- Tap on the attachment icon
- import an Audio File
- Audio File should render a preview
> [CIS-1747] Fix audio files not rendering previews

- StreamChatUITestsAppUITests/Tests/Messaging_Tests.swift
- StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
- Tests/StreamChatTests/APIClient/ChatPushNotificationContent_Tests.swift
- Tests/StreamChatTests/Query/FilterDecoding_Tests.swift
- Tests/StreamChatTests/Query/FilterEncoding_Tests.swift
- Tests/StreamChatTests/Query/Filter_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/Utils/JSONDecoder_Tests.swift
- Tests/StreamChatTests/Utils/JSONEncoder_Tests.swift
- Tests/StreamChatTests/Utils/Operations/AsyncOperation_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserChannelBanEventsMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserTypingStateUpdaterMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserWatchingEventMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketConnectPayload_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/CommonViews/ContainerStackView_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
- Tests/StreamChatUITests/Utils/String+Extensions_Tests.swift
Unify test function names across our test suite
- tests funcs in our unit & UI test targets now leverages the `test_THEN_WHEN` pattern when applicable.
> [BW] Test functions do follow test_ pattern across the whole test suite

- docusaurus/docs/iOS/guides/working-with-attachments.md
None
Fix a missing step from the custom attachments guide.
> [Docs] Add missing ChatMessageAttachment typealias in custom attachments guide

- Sources/StreamChatUI/Gallery/GalleryVC.swift
- Sources/StreamChatUI/Gallery/ZoomAnimator.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift
Request from customer.
Improve the ease of use of our APIs
* Exposes references to our own declared `UIView`s in `GalleryVC` and `ChatMessagePopupVC`
* Adds missing accessibility labels
* Safely unwraps optional image in `ZoomTransitionAnimator`
Before:
```swift
class CustomGalleryVC: GalleryVC {
override func setUpLayout() {
super.setUpLayout()
/// Gain access to reference of `bottomBarContainerStackView`
if let bottomBarContainerStackView = shareButton.superview as? ContainerStackView {
/// Removes shareButton from bottom bar
bottomBarContainerStackView.removeArrangedSubview(shareButton)
/// Gain access to reference of `topBarContainerStackView `
if let topBarContainerStackView = topBarView.subviews.first as? ContainerStackView {
/// Adds shareButton to top bar …
```
> [BW] Allows UI customization via exposing references to views in GalleryVC & ChatMessagePopupVC

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- Tests/StreamChatTestTools/SpyPattern/Spy/ChannelListUpdater_Spy.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/Workers/ChannelListUpdater_Tests.swift
CIS-1624
Fix a channel not receiving new messages and unread count updates, when a user is added as a member and the user is in the channel list.
When a new channel is inserted into the channel list we now make sure that not only do we link the channel but also start watching it.
1. Log in to two different accounts (e.g.: Leia on one device and C-3PO on another one)
2. Create a new channel using one of those accounts inviting another one
3. Send a message on the new channel
> [CIS-1624] Fix not watching channel when added as a member

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- Tests/StreamChatTestTools/SpyPattern/Spy/SyncRepository_Spy.swift
- Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
- Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
- Tests/StreamChatTests/Workers/ChatClientUpdater_Tests.swift
CIS-1764
Fix connection recovery issues, mainly:
- recovery flow is triggered on the first login
- recovery flow is not canceled when `ChatClient` is deallocated
- recovery flow is not canceled on disconnect 
- active components are not untracked when chat client is connected with another user
- `/sync` cooldown is applied to connection recovery flow
Update `SyncRepository` to run recovery flow only for further connections. If it's the 1st connection, the `lastSyncedAt` is set to the current timestamp and will be used as a reference date for `/sync` endpoint when the web socket is reconnected.
N/A
N/A
Use `LogConfig.level = .debug; LogConfig.subsystems = [.offlineSupport]` in DemoApp
Run `DemoApp` on the device
**Recovery flow is not triggered for the 1st session:**
1. Sign in as any user …
> [CIS-1764] Fix connection recovery issues

- CHANGELOG.md
- Sources/StreamChatUI/Gallery/GalleryVC.swift
Bugfix for incorrectly called viewWillAppear inside the viewWillDissapear life-cycle function inside GalleryVC.
* Open and close photo gallery
> [BW] Fix incorrectly called viewWillAppear inside viewWillDissapear

- README.md
None
Dynamically display the current SDK sizes in the README. We often have customers asking for the size of each SDK, with this, it will be available just by reading our README 🙂 
This is was a fun project, and the source of the implementation is here: https://github.com/GetStream/stream-sdks-size-badges
More details about the implementation are in the repo above, specifically [here](https://github.com/GetStream/stream-sdks-size-badges#implementation-details).
Just preview the README from this branch.
> Update README to include SDK size badges

- CHANGELOG.md
- Examples/SlackClone/SlackChatMessageContentView.swift
- Examples/YouTubeClone/MessageOptionsResolver/YTMessageLayoutOptionsResolver.swift
- Examples/YouTubeClone/YTChatMessageContentView.swift
- Examples/iMessageClone/iMessageChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptions.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- Tests/StreamChatUITests/ChatMessage_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
- Tests/UISDKdocumentationTests/ChatMessageContentView_Documentation_Tests.swift
Fixes: CIS-1724
Unblocks: CIS-1732
- Fix regression when `only visible for you` indicator is not shown for ephemeral messages
- Unblock CIS-1732. Handling deleted messages outside options resolver does not allow to write `ChatMessageContentView's` snapshot tests for deleted messages when visibility part is in `ChatMessageListVC`.
- Fix `only visible for you` indicator missing for ephemeral message
- Fix `ChatMessageListVC's` lifecycle being triggered by assigning the delegate before it has a parent 
- `ChatMessage.isOnlyVisibleForCurrentUser` has been deprecated
Move deleted message visibility check to `ChatMessageLayoutOptionsResolver`. Populate deleted messages setting on resolver from `chatClient.config` as the first thing on the message list.
| …
> [CIS-1724] Fix `only visible for you` badge not shown for ephemeral messages

- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/MockServer/MessageResponses.swift
- StreamChatUITestsAppUITests/MockServer/WebsocketResponses.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
- StreamChatUITestsAppUITests/Tests/StreamTestCase.swift
- https://stream-io.atlassian.net/browse/CIS-1794
The goal is to link the tests in the source code to TestOps scenarios
- Provided a way to add a TestOps `id` to the test:
```swift
func test_sendsMessage() throws {
linkToScenario(withId: 3)
let message = "test message"
GIVEN("user opens the channel") {
userRobot.login().openChannel()
}
WHEN("user sends the message: '\(message)'") {
userRobot.sendMessage(message)
}
THEN("the message is delivered") {
userRobot.assertMessage(message)
}
}
```
- Provided a way to add the tags to any test suites or test cases:
```swift
override func setUpWithError() throws {
try super.setUpWithError()
addTags([.messageReceipts])
}
```
> [CIS-1794] Link UI tests to TestOps scenarios

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
Provide a convenient way to exclude empty channels from the channel list query. 
Add `nonEmpty` filter.
Update the controller creation code to be:
```
controller = ChatClient.shared.channelListController(
query: .init(
filter: .and([
.containMembers(userIds: [userCredentials.id]),
.nonEmpty
])
),
filter: { channel in
channel.membership != nil && channel.lastMessageAt != nil
}
)
```
1. Apply the code snippet above to `DemoAppCoodrinator`
1. Run `DemoApp`
1. Sign in as any user 
1. Create an empty group channel
**Expected result:**
Created group channel does not appear in channel list as it's empty
> Add `nonEmpty` filter for channel list query

- .github/workflows/publish-release.yml
- .github/workflows/smoke-checks.yml
- https://stream-io.atlassian.net/browse/CIS-1770
Fixing an issue when Sonar can't post Slack messages due to a lack of webhook url.
> [CIS-1770] Move slack url to smoke-checks workflow

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelMuteDTO.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTestTools/Mocks/Models + Extensions/ChannelUnreadCount_Mock.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- Tests/StreamChatTestTools/TestData/DummyData/MessagePayload.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelMuteDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/CurrentUserDTO_Tests.swift
- Tests/StreamChatTests/Models/ChatChannel_Tests.swift
- Tests/StreamChatTests/StreamChatIntegrationTests/ChannelEvents_IntegrationTests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
CIS-1763
- Fix local unread counts going out of sync with the remote
- Fix channel not being marked as read when it's muted OR when all messages after last read are thread replies/silent/from muted users
Fix unread counts being **incremented** when:
- the channel is muted
- the message author is muted
Fix unread counts not being **decremented**:
- the message is hard deleted
- Add handling of missing cases to `ChannelReadUpdaterMiddleware`
- Move channel mutes from `UserDTO` to `CurrentUserDTO`
- Rename `mentionedMessages` to `mentioningMessages` in channel unread counts
- Remove unused parts of `ChannelMuteDatabaseSession`
Message in muted channel does not increment unread counts:
**GIVEN** I'm on the channel list
**AND** The channel is muted
**WHEN** Channel member sends a new message …
> [CIS-1763] Fix unread counts bumping logic 

- Sources/StreamChatUI/CommonViews/ContainerStackView.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionControl.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
None
Fix feedback loop in `ContainerStackView` inside Thread Replies. 
Applies `insetsLayoutMarginsFromSafeArea = false` only on the popup view, so that it doesn't influence other container stack views.
Create a thread reply, it shouldn't crash.
> Fix feedback loop in ContainerStackView

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
- Tests/StreamChatTests/Models/Attachments/ImageAttachmentPayload_Tests.swift
CIS-1827
Make it possible to attach/handle actions on `image` attachments.
Expose `actions` on `ImageAttachmentPayload`.
> [CIS-1827] Expose `actions` on image attachment payload

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Filter.swift
- Tests/StreamChatTests/Query/ChannelListFilterScope_Tests.swift
Our web team uses these filters for one of the chats in our product:
```
{
type: 'messaging',
team: { $eq: null },
members: {
$in: [store.me?.id!]
}
}
```
It is currently not possible to do this with the Swift SDK, as `.team` is a `FilterKey<Scope, TeamId>`and as such, can't take in `nil` as a parameter. This PR aims to change that behavior.
Another example of this use can be seen in [the docs](https://getstream.io/chat/docs/ios-swift/multi_tenant_chat/?language=javascript#query-channels)
* Changes `.team` in `FilterKey`'s extension to `FilterKey<Scope, TeamId?>`
* Adds an extension to `Optional` to conform to `FilterValue` when its `Wrapped` is `TeamId`
> Adds a way to query for channels with no teams

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/Controllers/Controllers/ChatChannelListController_Mock.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- Tests/StreamChatTestTools/SpyPattern/Spy/ChannelListUpdater_Spy.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
- Tests/StreamChatTests/Workers/ChannelListUpdater_Tests.swift
https://stream-io.atlassian.net/browse/CIS-1734
When in a paginated channel list, if the sync was executed (eg. backgrounding the app and opening it), the channels were left in the list but showing "No messages".
The issue described above was caused because we were only cleaning those channels, instead of deleting them.
Not we are properly deleting them.
While fixing this issue, other issues surfaced, which are tackled in #1984 
Pre-requisite: Make sure chat is disconnected when going to background
1. Open the DemoApp
2. Select a user
3. Scroll to paginate channels list
4. Background the app
5. Reopen the app
- Channels out of the first page should be deleted.
> [CIS-1734] Paginated channels are left without messages when sync is executed

- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
CIS-1849
Stop showing new thread reply in channel preview when it's submitted for sending.
Check if the message is a thread reply before making it a channel preview.
**GIVEN** I'm in the channel with `read events` enabled
**WHEN** I submit the new thread reply for sending
**AND** I go back to the channel list before it's sent
**THEN** The channel preview shows the last non-deleted message (not the newly submitted pending thread reply)
**GIVEN** I'm in the channel with `read events` enabled
**WHEN** I submit the new thread reply for sending
**AND** Sending of thread reply fails
**AND** I go back to the channel list before it's sent
**THEN** The channel preview shows the last non-deleted message (not the submitted failed thread reply)
> [CIS-1849] Fix making new thread reply a channel preview

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/Models/Attachments/ImageAttachmentPayload_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
CIS-1845
Make `actions` key usable as an extra data key in all attachments
`actions` is a custom key, used in ephemeral messages (giphy attachments) for attachment actions. We considered it as built-in but didn't expose the key in other attachments, making the key unusable for other attachments.
`actions` is only parsed for Giphy attachments.
Send giphys in channels
The PR also fixes the previewMessage update issues introduced recently. No CHANGELOG is added for those fixes since the feature isn't released.
The PR fixes a long time bug where `alwaysVisible` visibility shows ephemeral messages in the Message List.
> [CIS-1845] Expose attachment `actions` as extra data, fix issue with deleted ephemeral messages

- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageDeliveryStatusView.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsApp/DebugMenu.swift
- StreamChatUITestsApp/StreamChat/CustomChatMessageListRouter.swift
- StreamChatUITestsApp/StreamChat/StreamChatWrapper.swift
- StreamChatUITestsApp/StreamChat/ThreadVC.swift
- StreamChatUITestsApp/ViewController.swift
- StreamChatUITestsAppUITests/MockResponses/http_channels.json
- StreamChatUITestsAppUITests/MockResponses/ws_events_user.json
- StreamChatUITestsAppUITests/MockServer/ChannelConfig.swift
- StreamChatUITestsAppUITests/MockServer/ChannelResponses.swift
- StreamChatUITestsAppUITests/MockServer/MessageResponses.swift
- StreamChatUITestsAppUITests/MockServer/MockServerAttributes.swift
- StreamChatUITestsAppUITests/MockServer/StreamMockServer.swift
- StreamChatUITestsAppUITests/MockServer/User.swift
- StreamChatUITestsAppUITests/MockServer/WebsocketResponses.swift
- StreamChatUITestsAppUITests/Pages/ChannelListPage.swift
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/BackendRobot.swift
- StreamChatUITestsAppUITests/Robots/ParticipantRobot.swift
- StreamChatUITestsAppUITests/Robots/Robot+CustomAssertions.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/StreamTestCase.swift
- fastlane/README.md
CIS-1720
Automate `To Be Automated` scenarios for Message Delivery Status.
This work brings UI tests for `Message Receipts` feature.
Here's the list of automated scenarios
* Delivery status shows clocks when the last message is from the current user and it’s in the pending send state
* Delivery status shows error when sending fails for the last message from the current user
* Delivery status shows a single checkmark when the last message is from the current user and it is sent
* Delivery status shows double checkmark when the last message is from the current user and it is seen by a channel member
* Delivery status is hidden for own channel preview messages when reads are disabled
* Delivery status is hidden if the preview message is from another user
* Clocks are shown for local message …
> [CIS-1720] UI Scenarios for Message Delivery Status

- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/Utils/CollectionUpdatesMapper.swift
CIS-1862
Fix message list not scrolling to the bottom when a message from the current user was inserted (Only on non-diffing solution).
- When a reloadData() happens, also scroll to bottom if a new message was inserted by the current user
- Refactor the `ChatMessageListView` and use performBatchUpdates to update the message list. 
- Open the Demo App (Not the StreamDevelopers Scheme)
- Select a user
- Open a channel
- Scroll up
- Send a message
- Should scroll to bottom
> [CIS-1862] Fix not scrolling to bottom when inserting own message

- StreamChat.xcodeproj/project.pbxproj
Fixes StreamChatTestToolsTests not compiling because of "VirtualTime" file was not included in the Schema
> Fix StreamChatTestToolsTests not compiling

- .github/workflows/publish-release.yml
Use `macos-11` in release workflow to get Xcode 13.0 used for xc-frameworks
Use `macos-11` in release workflow to get Xcode 13.0 used for xc-frameworks
> Fix mac-os version in release workflow

- fastlane/Fastfile
Fixing workflow on `push` to `develop`. Currently, it fails because Github does not allow us to search for changed files on `push`.
> [BW] Fix smoke-checks on push

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ConnectionController/ConnectionController.swift
- Sources/StreamChat/Utils/EventBatcher.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- StreamChatUITestsApp/StreamChat/StreamChatWrapper.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/ChatClientUpdater_Mock.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/Utils/EventBatcher_Mock.swift
- Tests/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/WebSocketClient_Mock.swift
- Tests/StreamChatTests/Controllers/ConnectionController/ConnectionController_Tests.swift
- Tests/StreamChatTests/Controllers/SearchControllers/UserSearchController/UserSearchController_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
- Tests/StreamChatTests/Utils/EventBatcher_Tests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketClient_Tests.swift
- Tests/StreamChatTests/Workers/ChatClientUpdater_Tests.swift
CIS-1873
Fix crash happening when the chat client is connected with another user. The issue was connected to the last batch of events from the previous user posted **after** the new user is connected. The crash's root cause were models held by events that no longer exist after database removal.
Add `completion` to disconnection methods called after processing the last batch of events.
> [CIS-1873] Wait for last events batch to be processed to disconnect

- CHANGELOG.md
- DemoApp/AppDelegate.swift
- DemoApp/DemoAppCoordinator.swift
- DemoApp/DemoChatChannelListRouter.swift
- DemoApp/DemoUsers.swift
- DemoApp/LoginViewController.swift
- DemoApp/SceneDelegate.swift
- DemoApp/UserDefaults+Shared.swift
- DemoAppPush/NotificationService.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChatUI/Navigation/ChatChannelListRouter.swift
- StreamChat.xcodeproj/project.pbxproj
- docusaurus/docs/iOS/uikit/components/channel-list.md
CIS-1869
Discussion in slack: https://getstream.slack.com/archives/CRB9P6L03/p1652798185424229
1. When DemoApp is launched offline, the error alert is displayed and the only action logs out the user, making DemoApp unusable offline.
1. The alerts displayed are very ugly
1. DemoApp doesn't have login caching, requires user to "Login" on each app start.
1. We decided to skip the alert if we know we're offline
1. The alerts should display the error message (or reason), not the whole error.
1. DemoApp already has login caching, used for push notification app starts. We can use the same mechanism to login on app start.
https://user-images.githubusercontent.com/12818985/170296163-c5f1c253-0623-404d-8a9e-09b8ca804ce8.mov
**GIVEN** user logs in as a `built-in` user
**AND** user kills the app …
> [CIS-1869] Fix launching DemoApp in offline state

- StreamChatUITestsAppUITests/Robots/ParticipantRobot.swift
- StreamChatUITestsAppUITests/Robots/Robot+CustomAssertions.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
- StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
- StreamChatUITestsAppUITests/Tests/SlowMode_Tests.swift
- TestTools/StreamChatTestMockServer/MockServer/MessageList.swift
- TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
- TestTools/StreamChatTestMockServer/MockServer/StreamMockServer.swift
- TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift
N/A
To make UI tests more stable
From now on user and participant will wait for http request and websocket after sending a message:
-  `waitForHttpMessage()`
- `waitForWebsocketMessage()`
> [BW] Workaround for flaky UI tests

- .github/workflows/smoke-checks.yml
- https://stream-io.atlassian.net/browse/CIS-1911
- https://github.com/GetStream/stream-chat-swift/pull/2033
- To run Sonar Analysis on `push` to `main` and `develop`
- Return Sonar Analysis on push
- Remove slack actions that had a condition to fire on `push`
> [CIS-1911] Return Sonar Analysis on push

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Config/TokenProvider.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- TestTools/StreamChatTestTools/Extensions/UserConnectionProvider+Invalid.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- Tests/StreamChatTests/Config/TokenProvider_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
- Tests/StreamChatTests/Workers/ChatClientUpdater_Tests.swift
- docusaurus/docs/iOS/uikit/getting-started.md
CIS-1185
Make it possible to pass a `tokenProvider` when connecting the chat-client.
1. chat client has `connect` method that takes a token provider as an argument (the same as on other platforms)
1. chat client still has `connect` method that requires a token but with the note that a token must not expire
1. chat client no longer have `tokenProvider` exposed
⚠️ The **3rd** change is a **breaking** one but it might be OK to ship it: 
- customers who is using **non-expiring** tokens will not be affected by this change
- customers who is using **expiring** and a `tokenProvider` that was removed would be glad to hear that the whole flow is simplified:
**Before**:
```swift
// 1. Get a user
let user = 
// 2. Create a token provider
let tokenProvider: TokenProvider = { completion in …
```
> [CIS-1185] Token provider

- CHANGELOG.md
- Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift
Reported through Slack: https://getstream.slack.com/archives/C01FT5767AS/p1654165950668659
Fix hidden cell content after reacting to a message
There was an edge case where, in ChatMessageActionsTransitionController, we would set the alpha of the cell content to 0 during an animation, and never reset it back to 1.
The previous logic on the transition controller was looking for the cell both at the beginning of the animation and at the end of it. It was basically looking at the visible cells, and finding the first matching the cell content id.
In some cases, the cell content that was used at the beginning of the animation and the one that was used after were different references. That led to some cells staying with alpha 0.
This PR changes this logic by keeping a local reference to the cell …
> Fix hidden cell content after popover transition

- Sources/StreamChat/Utils/Logger/Destination/BaseLogDestination.swift
- docusaurus/docs/iOS/common-content/reference-docs/stream-chat/utils/logger/destination/base-log-destination.md
For there to be one less typo in the documentation. 😂
1. Removed mistyped word.
2. Inserted correctly typed word.
😂 
See GIF above 😂
> Fixed a typo in the `BaseLogDestination` documentation

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- DemoApp/DemoChatChannelListRouter.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/Events/ChannelEvents.swift
- Sources/StreamChat/WebSocketClient/Events/EventPayload.swift
#2039 
Channel hiding/appearing mechanism was broken with the introduction of offline caching
This PR contains multiple fixes for multiple bugs.
1. DemoApp keeps a reference to last displayed ChannelVC
1. Duplicated pinned message saving in MessageDTO (performance)
1. channel.hidden event fails to decode
1. Locally saved hidden channels do not re-appear when they should
1. Hidden channel messages re-appear seemingly randomly
1. Hidden channel messages leak via channel list preview 
1. Querying a hidden channel makes the channel un-hide
1. _DemoApp keeps a reference to last displayed ChannelVC_
We were always using splitVC, which keeps the ref to latest displayed VC, which keeps it alive. We should use the old logic and only use splitVC when we detect an iPad
Keeping a ref to ChannelVC …
> Multiple fixes for channel hiding/appearing logic

- CHANGELOG.md
- Sources/StreamChat/Database/DatabaseSession.swift
- Tests/StreamChatTests/Database/DatabaseSession_Tests.swift
None. Issue found in QA.
Fix a crash when the participant of a message list, hard deletes a message.
Change the hard deleting of a message from an event to just switch the `isHardDelete = true` instead of actually deleting the message from the database. This has some data privacy concerns, so this should be addressed properly in another ticket:  https://stream-io.atlassian.net/browse/CIS-1963
1. Open a Channel with messages
2. Send a message to user A
3. Send a message wth user B
4. User B hard deletes a message
5. 💣
> Fix crash when participant hard deletes message

- CHANGELOG.md
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChat/WebSocketClient/Events/Event.swift
- Sources/StreamChat/Workers/EventNotificationCenter.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/Utils/ListChangeUpdater/CollectionViewListChangeUpdater.swift
- Sources/StreamChatUI/Utils/ListChangeUpdater/ListChangeIndexPathResolver.swift
- Sources/StreamChatUI/Utils/ListChangeUpdater/TableViewListChangeUpdater.swift
- Tests/StreamChatTests/ListChangeAggregator_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListVC_Tests.swift
- Tests/StreamChatUITests/Utils/ListChangeIndexPathResolver_Tests.swift
None
Switching the `ListChangeAggregator` to the `newIndexPath` caused multiple crashes. In Apple documentation, they use the `oldIndexPath`, so this PR reverts that change and also stops checking for conflicts between Inserts and Updates to avoid unnecessary reload data.
- Reverts the ListChangeAggregator Update IndexPath. Switches back to the oldIndexPath.
- Don't treat Insert<->Updates has conflicts in `ListChangeIndexPathResolver`
> Revert ListChangeAggregator newIndexPath on Updates

- CHANGELOG.md
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
https://getstream.slack.com/archives/CRB9P6L03/p1654667559058219
A customer has reported that calling `addDevice` causes a deadlock
Calling `addDevice` twice, once from background queue and once from main queue causes deadlock:
background queue -> acquires the lock (semaphore), waits on main queue because of performAndWait
main queue -> waits on the lock, cannot perform any work
`EntityDatabaseObserver` uses `viewContext` for its DB operations, both in tests and production code. This is because it needs to be performant.
When you try to access `EntityDatabaseObserver.item` from background queue, since it's an `Atomic`, it acquires the lock & calls `viewContext.performAndWait` (to convert DTO to Model) which waits for main queue to complete some work
If you try to access …
> Fix possible deadlock in `CurrentChatUser` functions

- Sources/StreamChat/Utils/KeyedDecodingContainer+Array.swift
None
Improve the error logging of failed parsed elements from an array. We were not logging any failed parsed events from the Missing Events Payload.
Added a way to log errors from `decodeArrayIgnoringFailures`.
```
🚨 2022-06-09 12:53:00.476 [ERROR] [com.apple.NSURLSession-delegate] [KeyedDecodingContainer+Array.swift:26] 
[decodeArrayIgnoringFailures(_:forKey:)] > Failed decoding elements from array:
["dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"events\", intValue: nil),
_JSONKey(stringValue: \"Index 0\", intValue: 0), CodingKeys(stringValue: \"message\", intValue: nil),
MessagePayloadsCodingKeys(stringValue: \"type\", intValue: nil)], debugDescription: \"Cannot initialize MessageType from
invalid String value \", underlyingError: nil))", …
```
> Add logging to failed parsed elements from an array

- CHANGELOG.md
- Sources/StreamChat/Utils/Logger/Logger.swift
`LogConfig` persisted `destinations` so any change made after it was created did not take affect
After the DemoApp restructure, `Logger` initialized before we set `level` on it, and it persisted the default level (`error`)
Investigation showed that `Logger` initializes when we create an `APIKey`, and `destinations` persist so changing `level` do not create new `destinations`
Try to change `LogLevel.level = .debug` and observe it doesn't work
> Fix Logger persisting config after usage

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Workers/TypingEventsSender.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift
- TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/TypingEventsSender_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Workers/TypingEventSender_Tests.swift
#1828 
CIS-425
Thread typing indicators were introduced to backend long time ago, and iOS client should support them
* Typing-related functions now accept `parentMessageId: MessageId?`
* `ChatThreadVC` now shows typing users within a thread
Feature is implemented with API-parity in mind. Now, typing related functions in `ChannelController` accept `parentMessageId: MessageId?` and this param is passed to backend in typing events. Receiving part was already implemented so this PR does not touch there.
|  ![Simulator Screen Recording - iPhone 13 Pro - 2022-06-09 at 17 08 36](https://user-images.githubusercontent.com/770464/172880852-74afc419-123b-4a8a-b6d4-aaba91573bbf.gif)   |  ![Simulator Screen Recording - iPhone 13 Pro - 2022-06-09 at 17 09 …
> [CIS-425] Thread typing indicators

- CHANGELOG.md
- Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Query/Sorting/ChannelListSortingKey_Tests.swift
https://getstream.zendesk.com/agent/tickets/24329
`ChannelListSortingKey.unreadCount` cannot be used as sorting predicate in CoreData, since `unreadCount` does not exist in `ChannelDTO`
`unreadCount` is a calculated property. We'd need to persist it to be able to use `unreadCount` as a sorting param, this is for another time.
Create a ChannelListQuery with unreadCount sorting and run the app. It'll crash.
> Fix ChannelListSortingKey.unreadCount crash

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/Events/EventDecoder.swift
- Sources/StreamChat/WebSocketClient/Events/EventPayload.swift
`EventPayload` decoding errors, which happen when an expected field in an event payload is missing, are too generic.
They look like:
> `Swift.KeyPath<StreamChat.EventPayload, Swift.Optional<StreamChat.MemberPayload>>` field can't be `nil` for the `EventPayload` event.
This doesn't have the context, which key is missing from which payload type.
There's no elegant way to get a "field" string from KeyPath.
The commonly suggested
```swift
NSExpression(forKeyPath: keyPath).keyPath
```
does not work since our KeyPaths are not marked `@objc`.
Per https://stackoverflow.com/a/46555654, a private extension to manually expose path make the errors much nicer.
Now they look like:
> `memberContainer` field can't be `nil` for the `notification.added_to_channel` event.
Paste this in `EventPayload_Tests`: …
> Make EventPayload decoding errors more verbose

- DemoApp/StreamChat/Components/DemoChatMessageActionsVC.swift
- DemoApp/StreamChat/Components/DemoChatMessageContentView.swift
- DemoApp/StreamChat/Components/DemoChatMessageLayoutOptionsResolver.swift
- DemoApp/StreamChat/StreamChatWrapper.swift
- StreamChat.xcodeproj/project.pbxproj
Pinned messages are hard to debug since we don't have the message action and/or a UI to indicate the message is pinned
DemoApp has custom pinned message logic to pin/unpin the messages and indicate if a message is pinned
All UI is DemoApp only and is implemented with what's possible with the SDK.
The design is not 1-1 to actual design that will get implemented in the SDK in the future, and it doesn't cover all cases, but it'll make debugging easier for now.
Actual design can be found [here](https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Design-Kit---Current-version?node-id=12713%3A142209)
The same chat:
|  ![SCR-20220617-n4h](https://user-images.githubusercontent.com/770464/174320174-8260535c-786b-48e6-9621-359f9e6fa0ce.jpeg)   | …
> Implement Pinned Message UI in DemoApp

- fastlane/Sonarfile
- N/A
- As discussed in Tech Discussion, we are going to return a previous SDK version as a new code definition on SonarCloud on push to `develop`
> [BW] Set up a previous version as a code definition on develop

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/ChannelMemberListQuery.swift
- Tests/StreamChatTests/Query/ChannelListFilterScope_Tests.swift
Add missing Channel List and Member List filter keys so they can be used in a type-safe manner (and autocompletion rocks)
We were missing a couple of Channel List filter keys:
https://getstream.io/chat/docs/ios-swift/query_channels/?language=javascript#channel-queryable-built-in-fields
and Member list filter keys:
https://getstream.io/chat/docs/ios-swift/query_members/?language=javascript#member-queryable-built-in-fields
Those are added to the already-existing filter infra, and comments are updated to reflect which operators are possible (this info already exists in our docs)
Hypothetically, we can implement `var supportedOperators: [FilterOperator]` to `FilterKey` so we can know exactly which filter is usable with which operator. This is a bit more complicated, specifically because …
> Add missing channel / member list filters

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageLinkAttachment.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Models/Attachments/GiphyAttachmentPayload_Tests.swift
CIS-2017
#2120
Make it possible to send giphy messages programmatically
This change exposes initializer of `GiphyAttachmentPayload` & `LinkAttachmentPayload`. This change allows the integrator to create new giphy messages in chat.
Example:
```swift
...
let gifURL = media.url(rendition: .fixedWidth, fileType: .gif)
// StreamChat part
let attachment = GiphyAttachmentPayload(title: "Title of the giphy", previewURL: gifURL)
let attachments = [AnyAttachmentPayload(payload: attachment)]
channelController?.createNewMessage(
text: "",
attachments: attachments)
)
```
> [CIS-2017] Make it possible to send giphy messages programmatically

- CHANGELOG.md
- Sources/StreamChat/Config/BaseURL.swift
- Sources/StreamChat/Config/ChatClientConfig.swift
Leverage single `https://chat.stream-io-api.com/` mediator.
Previously the integrator could select the endpoint to connect to based on the preferred location. 
By providing a single endpoint the client no longer needs to think about the closest proxy server. 
New endpoint acts as a mediator that connects the end-user to the closest server with the best latency.
Run the app and verify all works fine.
> One endpoint to rule them all

- CHANGELOG.md
- Sources/StreamChat/Utils/Codable+Extensions.swift
- Tests/StreamChatTests/Utils/JSONDecoder_Tests.swift
This is an alternative take to PR #2115
JSON decoding bottleneck appears to be parsing Date objects from string. There are many repeated User payloads, each UserPayload has 3 Dates to be decoded, which is the most expensive primitive to decode.
That being said, User-level caching during decoding has many problems:
1. When do we invalidate the cache?
1. What happens if there are 2 decoding happening in multiple threads?
1. User payload is not always sent it full. For example, `role` field is scope-dependent, `teams` field is not always sent. Which fields can be cached and which fields will always exists is not clear enough.
These problems make User-level caching too complex and dangerous, it can lead to incorrect-parsing in unexpected places. Instead, date-level caching is much simpler, …
> Implement date-level caching for JSON decoding

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/Utils/KeyedDecodingContainer+Array.swift
CIS-1407
https://getstream.zendesk.com/agent/tickets/24700
* JSON decoding should be much more robust
* JSON decoding errors must be more understandable
This PR makes it so a single deformed entity in JSON arrays won't disable decoding for the whole entity itself, but will print a fat, very verbose error instead.
We already have `decodeArrayIgnoringFailures` which decodes the array elements where decodable and prints the error where they are deformed. This was used for Event decoding. We can safely use this for any array decoding.
The error function didn't print understandable information. The errors look like:
> 2022-06-27 11:41:05.837 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:79] [decodeRequestResponse(data:response:error:)] > …
> [CIS-1407] Improve JSON decoding robustness

- .github/workflows/cron-checks.yml
- .github/workflows/smoke-checks.yml
- README.md
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/SlowMode_Tests.swift
- TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift
- fastlane/Allurefile
- fastlane/Fastfile
- https://stream-io.atlassian.net/browse/CIS-1961
- Run E2E tests by cron on multiple iOS versions
- Run Unit tests by cron on multiple Xcode versions
- `cron-checks` will be executed `"At 03:00 every night"`
- Readme now points to `cron-checks` instead of `smoke-checks`
- Unit tests executed using `xcode: [12.5.1, 13.1, 13.4.1]`
- E2E tests executed using `ios: [12.4, 13.7, 14.5, latest]`
- E2E tests are adopted to older iOS versions
- Building sample фззы and SPM/Cocoapods integration checks will be skipped if the changes do not affect the source code
- N/A
> [CIS-1961] Run E2E & Unit tests by cron on multiple iOS & Xcode versions

- CHANGELOG.md
- Sources/StreamChat/APIClient/CDNClient.swift
- Tests/StreamChatTests/APIClient/StreamCDNClient_Tests.swift
None
The backend now supports a 100MB file size. This changes that config.
> Change upload file size limit to 100MB

- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
Each test takes around 15 secs (1.5 sec times 10 iterations), we can keep them disabled and use them locally when needed
> Disable CoreData performance tests

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
https://stream-io.atlassian.net/browse/CIS-1600
https://stream-io.atlassian.net/browse/CIS-1781
_Allow for move operations to scroll to the bottom of the message list_
> Allow for move operations to scroll to the bottom of the message list

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
CIS-2044
https://github.com/GetStream/stream-chat-swift/discussions/1612
Add an option to hide the history of the channel when adding a new member.
- `ChannelController.addMembers()` has now a new `hideHistory: Bool` argument to hide the history of the channel for that member. By default it is false.
1. Open a Channel
2. Tap on the 🐞 button
3. Tap on "Add Member w/o history"
4. Select a user id to add, ex: lando_calrissian
5. Login with lando_calrissian
6. Verify that the channel doesn't have any messages
> [CIS-2044] Add hide history option when adding a new member

- Sources/StreamChat/Query/Pagination.swift
- StreamChatUITestsAppUITests/Pages/ChannelListPage.swift
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
- TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
- https://stream-io.atlassian.net/browse/CIS-1882
- Add support for pagination in Channel List, Message List and Thread List
- Automate related test-cases
- From now on the mock server supports pagination in Channel List and Message List ([here is a blocker](https://stream-io.atlassian.net/browse/CIS-1583) for Thread List pagination)
1. Generate channels and/or messages using the mock server, e.g.:
```swift
backendRobot.generateChannels(count: 1, messagesCount: 60)
```
2. Freeze the test app:
```swift
sleep(10000)
```
3. Manually Open a Channel List / Message List and load the history
4. Observe pagination requests
> [CIS-1882] Support pagination in mock server

- CHANGELOG.md
- DemoAppPush/NotificationService.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
CIS-1634
https://github.com/GetStream/stream-chat-swift/issues/1827
Details of the issue are here: https://github.com/GetStream/stream-chat-swift/issues/1827
The way this is currently solved is that we monitor in the Channel if the app has become active again from the background, when this happens, we recreate the database observers and reload the data of the message list. 
- In the initial screen, change the configuration of the app to stay connected in the background to false
- Open a channel
- Go to background
- Open the same channel in another device with a different user
- Send a message
- In the initial device, open the app again (Don't click on the Push Notification)
- Observe the new message is there
> [CIS-1634] Fix Channel missing messages from NSE push updates

- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Attachments_Tests.swift
- StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
- N/A
- Cron checks on iOS 12 work like a charm
- Turn off some e2e tests on iOS 12 and link bug reports
- Remove test case with id `239` due to XCUITest periodically does not tap on the `Cancel` button. The test case will be marked as `manual`.
> [BW] Deal with flaky tests on iOS 12

- DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
[JIRA](https://stream-io.atlassian.net/browse/CIS-2042)
Fix in the demo app, when going back to the channel list, sometimes the channels remained selected.
Call deselect item on when the collection view selection method is invoked.
Run the app, open few channels, and come back. The channel shouldn't be selected anymore.
> Fix channel stays selected when coming back to list

- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
https://stream-io.atlassian.net/browse/CIS-2079
Brings back check for truncation in ChannelDTO.willSave for the information to be broadcasted
There was an issue during Release QA where truncation was not broadcasting information to the FRC, and thus leaving the content of the channel there until reentering it.
- User A creates a channel
- Users A and B fill it with messages
- Both users A and B stay in the chat
- User A truncates the channel
- Both users A and B should not see the history
> [Release Bug] Bring back check for truncation in ChannelDTO.willSave

- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- N/A
- Make `Cron checks` green again
- There is no image preview element details in the hierarchy tree on iOS < 15
> [BW] Fix link preview tests on lower iOS versions

- docusaurus/sidebars-ios.json
Some docs links were lost after the docs restructuring.
Brought the links back. We need to have a single source of truth in the docs.
Run the docusaurus locally.
> Fixed lost links after docs restructuring

- CHANGELOG.md
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- Tests/StreamChatTests/Utils/Operations/AsyncOperation_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2086
A user reported that there was a race condition in BaseOperation. This was not an issue at the moment, but we were indeed allowing different threads to mutate the values that formed the state of the Operation.
This PR adds thread safety guards to ensure no more data races happen
> [CIS-2086] Make BaseOperation thread safe

- .github/workflows/cron-checks.yml
- StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
- N/A
- `Truncation without message` test is failing on multiple iOS versions. We need to fix it
- Split up the test into two separate ones, it might help
- Then:
- `test_messageList_and_channelPreview_AreUpdatedWhenChannelTruncatedWithoutMessage`
- Now: 
- `test_messageListIsUpdatedWhenChannelTruncatedWithoutMessage`
- `test_channelPreviewIsUpdatedWhenChannelTruncatedWithoutMessage`
- Cron checks [result](https://github.com/GetStream/stream-chat-swift/actions/runs/2759347255) ✅
> [BW] Split up truncation test

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelWatcherListController/ChatChannelWatcherListController.swift
- Sources/StreamChat/Controllers/ConnectionController/ConnectionController.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/EventsController/EventsController.swift
- Sources/StreamChat/Controllers/MemberController/MemberController.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
- Sources/StreamChat/Controllers/UserController/UserController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift
Several GH issues and questions about iOS 16 support.
Fix the build issues we have on Xcode 14 beta versions.
Lazy variables using @available are no longer supported. This is not an Xcode beta bug, but a 5.7 Swift feature: https://github.com/apple/swift/pull/41112.
Workaround is to use a backing storage with a computed variable. In order to avoid force unwrapping, another init is called as a fallback. If you have a better idea, please share it.
Channel publisher works in SwiftUI. Let's see where else we could test this.
> Fixed build issues on Xcode 14

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatMessageActionsVC.swift
- Sources/StreamChat/APIClient/ChatRemoteNotificationHandler.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/MessageRepository_Spy.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2087
It's been a while that we randomly get reports of inconsistencies when retrieving a message from a Push Notification
ChatRemoteNotificationHandler was using MessageController to retrieve the message that was coming from a Push Notification. This was both unreliable and overcomplex. This PR move the responsibility of doing so to the MessageRepository, to ensure we don't rely on the DB to return it.
MessageRepository now has a new method, getMessage, that returns a ChatMessage object. ChatRemoteNotificationHandler directly requests the message to MessageRepository, reducing inconsistencies
> [CIS-2087] Improve consistency when retrieving Message after Push Notification

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
Related to https://stream-io.atlassian.net/browse/CIS-2048
Mitigate crash when accessing unread count for a channel
The crash suggests that there are values that are null when trying to evaluate the predicate. This smells like a predicate being evaluated on a deleted object. Because the unread count is accessed on demand, and not when creating ChatChannel, it can be that the DTO is deleted whenever the values is accessed.
Whenever a DTO is deleted, its values are reset to defaults. BUT, CoreData is not able to represent a `Date?` whenever this happens, leading to a crash.
All the above is just a theory, and there was no way to consistently reproduce the scenario where it crashed. In any case, it adds a safety net.
We now check if the ChannelDTO is valid before performing any lazy fetch …
> [CIS-2048] Make sure ChannelDTO is still valid when accessing Lazy blocks

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2083
Fix an issue where hidden history would be visible for some time after hiding a channel
There was an error in the logic to handle incoming truncatedAt values from the Backend, setting an old value for it. This is because we currently use `truncatedAt` for both hiding and truncating channels.
The value for `truncatedAt` is now only updated if the backend returns a date for `truncatedAt` AND if that date is older than the currently set in the DTO
1. Create a 1-1 channel
2. Send few messages
3. User A hides the channel, clearing history
4. User B sends more messages
- Only the new messages are shown
Previous result:
- Some old messages were shown
> [CIS-2083] Fix hidden channels showing past history

- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
- https://stream-io.atlassian.net/browse/CIS-2081
- Update E2E and Unit tests so that they work stably on iOS 16
- Perform a manual smoke test on iOS 16
**Smoke test:**
- it went well, no unforeseen problems were found
**Unit tests:**
- there is only one failing test, an assumption is that it's failing because of the bug in Xcode 14 beta 4: `test_defaultDecoder_isStreamDecoder`. We will keep an eye on it in the following betas
**E2E tests:**
- Test case [#277](https://streamio.testops.cloud/project/1/test-cases/277) becomes manual => [#286](https://streamio.testops.cloud/project/1/test-cases/286)
- Long-press time increased for iOS 16 from 1 to 2 sec
- Provided a workaround for the new "Paste" menu item
- Pagination on channel list timeout was bumped due to scroll time was significantly …
> [CIS-2081] Update tests to work on iOS 16

- Sources/StreamChat/ChatClient.swift
Updating the docs for the ChatClient init method, which were outdated.
> Fixed wrong docs for the ChatClient init method

- Package.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsApp/Settings.swift
- StreamChatUITestsApp/StreamChat/MessageActionsVC.swift
- StreamChatUITestsApp/StreamChat/StreamChatWrapper.swift
- StreamChatUITestsApp/ViewController.swift
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Pages/Settings.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
- TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
- TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
- TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift
- TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift
- https://stream-io.atlassian.net/browse/CIS-2014
- Support message hard/soft deletion in Mock Server
- Automate related scenarios
- The mock server fully supports message hard/soft deletion
- Related scenarios are automated
- A couple of additional unrelated scenarios have also been automated
- Test app was updated accordingly
- iOS 16 workarounds have been removed as issues with XCTest have been fixed on `Xcode 14 beta 5`
> [CIS-2014] Support message hard/soft deletion in Mock Server

- .github/workflows/cron-checks.yml
- StreamChat.xcodeproj/project.pbxproj
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChat.xcscheme
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
- fastlane/Fastfile
- https://stream-io.atlassian.net/browse/CIS-2027
- Create a new test plan exclusively for flaky tests
- Set up a retry strategy for flaky tests
- `Debug` configuration is removed from `Fastfile` as it's set up in `Scanfile`
> [CIS-2027] Deal with flaky unit tests

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift
CIS-1591
https://github.com/GetStream/stream-chat-swift/issues/1793
Fix the message list scrolling when popping the message list from the navigation stack.
The reason this happened was that the Keyboard hide notification is still triggered when popping from the navigation stack, and the keyboard is dismissed but there's no animation, only the message list animates. To fix this, on the keyboard handler we check if the view controller is still present in the navigation stack. If not, we don't hide the keyboard.
|  <video src="https://user-images.githubusercontent.com/12814114/185121501-01f8bb92-d1a7-4474-947f-f5e445635c52.mov"/>  |  <video src="https://user-images.githubusercontent.com/12814114/185127580-486a01ac-bf06-4499-801a-aef747f63f31.mp4"/>  |
- …
> [CIS-1591] Fix message list scrolling when popping from navigation stack

- CHANGELOG.md
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
None
There are some tests from Message Sender that keeps failing. So, moved all Message Sender tests to the flaky test plan.
Bonus: Also updates Changelog with a forgotten item.
> Move all messager sender tests to flaky test plan

- CHANGELOG.md
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
None
This PR reverts this change: https://github.com/GetStream/stream-chat-swift/pull/2177 which caused a deadlock in `@CoreDataLazy `because of the usage of `@Atomic`. Besides this, that change also makes the Channel List Loading less performant because the LazyCachedCollection is not really being used, and it is not lazy with that change.
With the newly introduced `logout()` the fix above is not needed anymore, since we can guarantee there won't be nullable items.
> Fix deadlock caused by ListDatabaseObserver.startObserving() changes

- DemoApp/DemoAppCoordinator.swift
- DemoApp/PushNotifications.swift
When opening a chat push notification, if the app was closed, it was not navigating to the chat as the Push Notification delegate was not set.
With the app closed, send a push notification.
It should land on the chat, with the content preloaded
> [DemoApp] Properly navigate to chat when opening a notification

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
https://stream-io.atlassian.net/browse/CIS-2150
https://stream-io.atlassian.net/browse/CIS-2115
This PR fixes a case where quoting or pinning old messages can lead to broken pagination
When we fetch a page, it can contain pinned and/or quoted messages. Those are also saved in the database.
Because those messages meet the current criteria of our DB listener, they appear in the channel.
If there is a case where the quoted/pinned message is old, we were using it as the last id to fetch the following page.
That meant that we were leaving a gap in some cases.
This PR addresses the above-mentioned issue by keeping track of the last *fetched* message id. This id will be the one used, instead of the last visible one.
When scrolling really fast, you might see the old messages at the top while …
> [CIS-2150, CIS-2115 ] Fix broken pagination when quoting or pinning old messages

- README.md
- docusaurus/docs/iOS/swiftui/getting-started.md
- docusaurus/docs/iOS/uikit/getting-started.md
No ticket available.
The links to the UIKit and SwiftUI tutorials from both our `README.md` and the docusaurus docs (found in the `getting-started` sections) are linking to the wrong paths.
Apparently, the tutorials have been moved:
* We currently point towards: https://getstream.io/chat/docs/sdk/tutorials/ios-chat/
* The correct path is: https://getstream.io/tutorials/ios-chat/
I searched through the project and these were the only links pointing towards there.
Due to the fact that the new path to the tutorials is not part of our docusaurus docs anymore, I needed to switch from relative links to absolute ones.
To my knowledge there is no downside in doing this, if there is, please let me know.
Run docusaurus locally (with `npx stream-chat-docusaurus -i -s`) and check the links from the …
> Fix links to UIKit and SwiftUI tutorials

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/IdentifiablePayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MemberPayload.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/Events/MemberEvents.swift
- Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
- TestTools/StreamChatTestTools/Fixtures/JSONs/Events/Notification/NotificationRemovedFromChannel.json
- TestTools/StreamChatTestTools/TestData/DummyData/MemberPayload.swift
- TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/MemberPayload_Tests.swift
- Tests/StreamChatTests/Controllers/MemberListController/MemberListController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelReadDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MemberModelDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
- Tests/StreamChatTests/Database/DatabaseSession_Tests.swift
- Tests/StreamChatTests/ListChange_Tests.swift
- Tests/StreamChatTests/Query/ChannelMemberListQuery_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- Tests/StreamChatTests/WebSocketClient/Events/MemberEvents_Tests.swift
- Tests/StreamChatTests/WebSocketClient/Events/NotificationEvents_Tests.swift
- Tests/StreamChatTests/Workers/ChannelMemberListUpdater_Tests.swift
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2251
In the `notification.removed_from_channel` event, the `user` field is not present inside the `member` field, although the `user_id` is. This PR adds a fallback so that if the `user` is not present, we use the id from the `user_id` property. 
The backend will change this meanwhile, and make sure the `user` field is always present. But since we don't have an ETA for this, it makes sense to add this fallback.
> Fix parsing `member` field in `notification.removed_from_channel` event

- .github/workflows/smoke-checks.yml
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Smoke tests running on Xcode 12 are failing because xcversion fails to find the application.
Reason described here: https://github.com/xcpretty/xcode-install/issues/465
We are preparing old SDK smoke tests to run on Xcode 13 instead of 12, but disabling them for now until Xcode 14 is used.
> [Internal] Move Old SDK tests to 13 - Currently disabled

- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- Tests/StreamChatTests/Controllers/MemberListController/MemberListController_Tests.swift
- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
CIS-2151
On iOS 12, when the message list is empty or with only 1 message, the UI is not updated for the next inserted messages.
After quite some time debugging this issue, I could not find the root cause of it, so it seems it is a bug on iOS 12 somehow.  So the solution is to use reloadData() whenever the message list is below 2 items and if the user is on iOS 12.
Note: No need to update the changelog, since this is a regression after introducing DiffKit.
- Use iOS 12 Simulator on UI Test App
- Open an empty channel or with only 1 message
- Send new messages
> [CIS-2151] Fix messages not inserted on iOS 12

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- TestTools/StreamChatTestTools/Extensions/Unique/ChannelId+Unique.swift
- TestTools/StreamChatTestTools/Extensions/Unique/ChatUser+Unique.swift
- TestTools/StreamChatTestTools/Mocks/Models + Extensions/ChatMessage_Mock.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
CIS-2162
Fix a crash when inserting a message in an empty message list on iOS Below 15.
It would try to attempt reloading a cell that does not exist, when the message list was empty or with 1 message.
> [CIS-2162] Fix message list crash when inserting message in empty list [iOS <15]

- CHANGELOG.md
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
CIS-1583
Fix not loading more replies in Threads
- Fixes threads not loading more replies because of the controller state not being remote fetched (which is not needed)
- Fixes threads and channels not loading more messages when initialized offline
None
- Open a Channel Thread with multiple replies
- Scroll to the top
- Should load more messages
> [CIS-1583] Fix Thread not loading more replies

- Sources/StreamChat/Controllers/BackgroundListDatabaseObserver.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- Sources/StreamChat/Utils/ThreadSafeWeakCollection.swift
Closes https://github.com/GetStream/stream-chat-swift/issues/2299
Use concurrent queues for internal queues.
As reported in https://github.com/GetStream/stream-chat-swift/issues/2299, we were wrongly creating serial queues for internal queues when the purpose was to allow concurrent reads, but block the queue while there is a write.
Just add the `.concurrent` attribute in the creation of the queue.
> [Internal] Use concurrent queues for internal queues using async(flags: .barrier)

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2168
https://github.com/GetStream/stream-chat-swift/issues/2284
Do not mark channels as read when the controller is not in the stack
There was a temporary leak during the execution of ChatChannelVC.synchronize that was keeping the ChatController alive. That was translated into the controller marking the channel as read even if the chat was not visible on screen.
2. Go back to the channel list
3. From another device, send a message
4. Wait until the unread count show as 1 in the list
Previous result:
The unread count was showing 1 for a second, and then going back to 0
The unread count should stay as 1
> [CIS-2168] Do not mark channels as read when the controller is not on screen

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Workers/ChannelMemberListUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2169
This PR aims to stop showing, in most situations, old messages not belonging to the chronological order when scrolling to older messages.
Whenever we query a channel page, the payload returns the channel, its messages, and its pinned messages. It can also be that the returned messages contain quoted messages.
Those quoted/pinned messages can or cannot be part of the current page, but in order for those to be displayed when requested, they have to be stored in the database . They can be way older than the page we are requesting (Imagine there is a message that is quoting a message from 10 months ago, we need it in the DB, but we should not be showing the original message alone, just show it as part of a quote)
Because Stream relies on the …
> [CIS-2169] Do not show old messages not belonging to the history when paginating

- docusaurus/docs/iOS/guides/importance-of-synchronize.md
We have a broken link here: https://getstream.io/chat/docs/sdk/ios/guides/importance-of-synchronize/. 
The referenced page doesn't seem to exist anymore. I've provided an alternative, open to suggestions for a better fit.
> Fixed a broken link in the synchronize docs

- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
We have additional flaky test: test_createCall_propagatesResultFromUpdater, moved it to that test plan.
> Updated the flaky tests

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/Events/EventType.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Fixtures/JSONs/Events/User/UserGloballyBanned.json
- TestTools/StreamChatTestTools/Fixtures/JSONs/Events/User/UserGloballyUnbanned.json
- Tests/StreamChatTests/WebSocketClient/Events/UserEvents_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2183
Properly handle Global Ban events
Seems like at some point we did a mistake and removed the handling to handle Global Ban events. The models were there, but were not used 🙃 
When receiving `user.banned` / `user.unbanned` events, we try to parse it using the channel ban model, otherwise, we try with the global ban.
1. Create an EventsController and listen to events
2. From the dashboard, globally ban a user
You should receive a UserGloballyBannedEvent in the EventsController handler.
> [CIS-2183] Handle Global Ban Events

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
None
Make the `ChatMessageListVC.tableView(heightForRowAt:)` open so that it can be overridable and for example return 0 if a message is deleted.
N/A
> Make `ChatMessageListVC.tableView(heightForRowAt:)` open

- .github/actions/bootstrap/action.yml
- .github/workflows/cron-checks.yml
- .github/workflows/docusaurus-prod.yml
- .github/workflows/docusaurus-staging.yml
- .github/workflows/emerge.yml
- .github/workflows/publish-release.yml
- .github/workflows/smoke-checks.yml
- .github/workflows/testflight.yml
- .gitignore
- Scripts/bootstrap.sh
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsApp/StreamChat/StreamChatWrapper+TestApp.swift
- StreamChatUITestsAppUITests/Pages/SpringBoard.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
- StreamChatUITestsAppUITests/Tests/PushNotification_Tests.swift
- TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
- TestTools/StreamChatTestMockServer/MockServer/DeviceRemoteControl.swift
- TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
- TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
- TestTools/StreamChatTestMockServer/MockServer/StreamMockServer.swift
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
- fastlane/Fastfile
- fastlane/sinatra.rb
- https://stream-io.atlassian.net/browse/CIS-2215
- Create a way to attach logs and video recordings of the failed tests to have a better idea of the failures
- Video attachments are collected via custom implementation using `sinatra`, the same way as we automated push notification testing
- Log attachments are collected via `xcparse` tool
- Both logs and videos can be found in the `Summary` section of the failed Github Actions run
- Small refactoring was done of the testing framework and the mock server (required for SwiftUI repo)
- Bump retry count due to `CIS-1737`, unfortunately, it's getting flakier
- Github Actions warnings were resolved:
- `cache` and `checkout` actions versions were bumped
- `set-output` method was transformed to `$GITHUB_OUTPUT` variable
> [CIS-2215] Implement UI tests attachments

- .github/workflows/smoke-checks.yml
- fastlane/Fastfile
- https://stream-io.atlassian.net/browse/CIS-651
- Extract failing snapshots from CI 
- Parse `xcresult` via `xcparse` and grab the snapshots
- [Example](https://github.com/GetStream/stream-chat-swift/actions/runs/3319910374)
> [CIS-651] Extract failing snapshots from CI

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
None
While testing Ban and Unban issues, there was no way to test this in the Demo App, so this PR introduces that capability.
Also, it exposes the `EntityChange.item` property so that it is easier to access the model which the entity change represents.
- Open a channel
- Tap on Debug icon
- Ban a member
- Unban a member
- Should not have any alert error
> Ban/Unban Demo App Example + Expose `EntityChange.item`

- CHANGELOG.md
- DemoApp/DemoAppConfiguration.swift
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/Shared/Token+Development.swift
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/APIClient/RequestEncoder.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Errors/ClientError.swift
- Sources/StreamChat/Errors/ErrorPayload.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Utils/InternetConnection/Error+InternetNotAvailable.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- Sources/StreamChat/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/SpyPattern/Spy/ConnectionDetailsProviderDelegate_Spy.swift
- Tests/StreamChatTests/APIClient/RequestEncoder_Tests.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
- Tests/StreamChatTests/Utils/Operations/AsyncOperation_Tests.swift
- Tests/StreamChatTests/Workers/ChatClientUpdater_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2234
https://stream-io.atlassian.net/browse/CIS-2239
https://stream-io.atlassian.net/browse/CIS-1727
https://stream-io.atlassian.net/browse/CIS-2172
Improve overall logic around Authentication
- Make sure waiters for token and connectionId timeout after certain time to avoid never completing calls to `connect()`
- Stop spamming errors to console while we refresh tokens upon expiration
- Update documentation around `currentUser` stating that a non-nil value does not mean that it is authenticated and the token is valid
- Add a development only way to test refresh token mechanisms
- Allow calling `connect()` after calling `setToken()`. This was an issue before as it was not creating background workers.
- Token/ConnectionId requests are by default …
> [CIS-2234, CIS-2239, CIS-1727, CIS-2172] Improve Authentication Logic

- CHANGELOG.md
- Sources/StreamChatUI/Utils/ListChangeUpdater/CollectionViewListChangeUpdater.swift
- Sources/StreamChatUI/Utils/ListChangeUpdater/ListChangeUpdater.swift
- Sources/StreamChatUI/Utils/ListChangeUpdater/TableViewListChangeUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
https://stream-io.atlassian.net/browse/CIS-2264
UIKit does not reload rows when they are moved. This is really bad for us because when we receive a .move update, it comes with changes to the cell itself. In most of the cases, because of other events, this is not an issue. But in edge cases, the cell stays with the old state until a new event comes in.
This PR ensures that whenever those .move events come, we always update the cell just in case.
- Unified logic for CollectionViewListChangeUpdater and TableViewListChangeUpdater so that we don't need to repeat the code around
- Ensured cells are reloaded after a move
1. Open the channel list
2. Send A SINGLE message to a channel that is on screen, but it is not in the first position.
- The channel should move to the first …
> [CIS-2264] Make sure to reload rows after moving them

- CHANGELOG.md
- Sources/StreamChat/Config/Token.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Config/Token_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2382
CIS-2287
Fix development tokens not working, it errors with Missing Token Provider.
When creating a development token, we were incorrectly setting the expiration to "distantFuture". We actually need to set it to `nil`. Since there is no expiration at all. With this, the `connectUser` now works correctly.
N/A
> [CIS-2287] Fix connecting user with non-expiring tokens

- docusaurus/docs/iOS/swiftui/channel-list-components/channel-list-header.md
- docusaurus/docs/iOS/swiftui/channel-list-components/helper-views.md
Add links to [the Channel List blog post](https://getstream.io/blog/customize-chat-channel-list-with-swiftui/#customize-the-list-divider) from Amos in the documentation where it fits.
Added the links.
Run the docs locally (`npx stream-chat-docusaurus -s`).
> [Docs] Add links to the Channel List blog post in the docs

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
- Tests/StreamChatUITests/Mocks/Navigation/ChatMessageListRouter_Mock.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
CIS-2232
https://github.com/GetStream/stream-chat-swift/issues/2343
Fixes message actions popup not opening in thread replies, after restarting the app (loading replies from the local cache).
When calling `didSelectMessageCell()` the router would not be called because `message.cid` would be `nil`. This should not happen, and replies from the local cache should have the `cid` property. For now, as a workaround, we will use the cid from the data source, so that it is more reliable. I spent quite a lot of time trying to understand why the channel is not attached to the thread reply in the local database, so for now, we will go with the workaround approach.
- Open a Channel
- Send a message
- Send a thread reply
- Open the thread
- Restart the app (To make sure the threads are loaded from …
> [CIS-2232] Fix message actions popup in cached thread replies

- CHANGELOG.md
- DemoApp/SceneDelegate.swift
- DemoApp/Shared/DemoAppCoordinator.swift
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/StreamChat/DemoAppCoordinator+DemoApp.swift
- Sources/StreamChat/ChatClient.swift
- StreamChatUITestsApp/AppDelegate.swift
- StreamChatUITestsApp/StreamChat/DemoAppCoordinator+TestApp.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
https://stream-io.atlassian.net/browse/CIS-2243
https://stream-io.atlassian.net/browse/CIS-2244
https://github.com/GetStream/stream-chat-swift/issues/2381
Avoid race conditions or crashes originated after calling log out
`logOut` does not finish all the "clean up" synchronously, which can potentially create issues when interacting with the SDK just after calling it.
Synchronous `logOut` and `disconnect` calls are deprecated in favour of its asynchronous version
> [CIS-2243, CIS-2244] Increase Safety by making Log Out and Disconnect async operations

- CHANGELOG.md
- Sources/StreamChat/Query/MessageSearchQuery.swift
- Tests/StreamChatTests/Query/MessageSearchQuery_Tests.swift
CIS-2212
https://github.com/GetStream/stream-chat-swift/issues/2363
Provide an easy way to filter messages with any attachment type or without any attachments at all.
N/A. Unit tests were provided to make sure the query is built correctly.
> [CIS-2212] Add message search filter to query messages with/without attachments

- CHANGELOG.md
- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/APIClient/RequestDecoder.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- StreamChatUITestsApp/StreamChat/ChannelList.swift
- StreamChatUITestsApp/ViewController.swift
- StreamChatUITestsAppUITests/Pages/ChannelListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Authentication_Tests.swift
- Tests/StreamChatTests/APIClient/APIClient_Tests.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
- fastlane/sinatra.rb
Fix E2E tests which were failing due to missing retries after a token fetch failure
This PR adds retries when a token fetch process fails. It does it under the following circumstances:
- If the fetched token is expired
- If there is an error returned
- All the above is done a up to a maximum of 10 times
In order to do that, it also removes state tracking of token attempts refresh from the APIClient.
Now, whenever the Authentication Repository is fetching a token, it notifies the APIClient so it can temporarily suspend the queue. In the case where requests are already in the queue and are being executed, those will be requeued as soon as an expired token is received, to then be relaunched when the queue is resumed.
To be quicker detecting expired tokens, we also try to refresh tokens when …
> [Internal] Add retries to Authentication Repository

- CHANGELOG.md
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
Reported through Github: #2435 
Allow clients to update user information when connecting a user.
Due to a bug introduced in 4.25.0, we are no longer updating the user information when connecting a user.
> [#2435] Fix UserInfo not being updated on connect

- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
N/A
Fix the issue spotted in 4.26.0 QA, where some paginations would be missing from Threads.
For now, we are disabling the batchSize implementation until we update how we refresh the objects which don't contain changes to minimize the risk of the release
1. Open Release 4.26.0 Channel
2. Open the first thread
3. Leave the thread
4. Comeback to the thread
5. All pages should be loaded
> Fix missing messages in thread pagination

- CHANGELOG.md
- Sources/StreamChat/Models/ChatMessage.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2451
Fix the message cell not being updated when custom data in attachments are different.
We now use all the available data in the attachments for the diffing, instead of trying to be smart and only choosing some properties. The reality is that each customer will have different logic here, so there can't be any assumptions.
N/A, it is hard to manually test this one right now. (Soon we will add custom attachments to the DemoApp)
But unit tests have been added to prove it works.
> Fix message cell not updated when custom attachment data is different

- docusaurus/docs/iOS/uikit/components/message-list.md
The sample code for custom message lists is missing reference to message list VC
I was copy & pasting code in and ran into some unknown vars. I think this is the spirit of the docs
Sample code update
> Message List: Fix sample code

- docusaurus/docs/iOS/swiftui/chat-channel-components/message-composer.md
There was an old method signature for the custom attachments in SwiftUI.
> Fix outdated docs for custom attachments

- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
I've noticed that sometimes the mock server fails on start on CI ([example](https://streamio.testops.cloud/launch/3341/tree/321654)). Hope this change will help.
> [BW] Retry mock server start on CI

- DemoApp/Screens/Create Chat/CreateChatViewController.swift
The app is crashing due to a race condition that is happening while the tableView updates its contents and the SearchController updates its users state.
We want to fix the race condition and effectively update the UI without crashing.
When the user is trying to create a new channel and type back and forth queries on the search box the Demo app is crashing.
The issue is being caused because the SearchController state (that asynchronously fetches users) is the same as the UI state in the CreateChatViewController. The solution to the problem is to decouple the 2 states and only rely on the delegate calls from the SearchController to update the users state in the CreateChatViewController and thus update the UI.
1. Open the Create Channel
2. Wait until the user list is populated
3. Type …
> [Fix]Crash on Demo when user creates channel

- docusaurus/docs/iOS/swiftui/message-components/message-reactions.md
https://github.com/GetStream/stream-chat-swiftui/issues/270
Fix a wrong code sample in the SwiftUI Docs, as reported by a customer.
> Fixed wrong code sample in the SwiftUI docs

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/Models + Extensions/Attachments/ChatMessageImageAttachment_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- TestTools/StreamChatTestTools/TestData/AnyEndpoint.swift
- Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/AttachmentDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/NSManagedObject+Validation_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/313
Add skip push support when sending a message 
Adds a new `skipPush: Bool` argument to
- `channelController.createNewMessage()` 
- `messageController.createNewReply()`.
- Open a Channel
- Tap the Debug Button
- Tap "Send message with skip push" action
- Write a message
- Click "OK"
- Should send a message without triggering a push notification to the members of the channel
> Add skip push support when sending a message 

- fastlane/Fastfile
`Then` prepare_simulator lane was not triggered on cron checks
`Now` it will
> [BW] Prepare simulator before first scan

- fastlane/Fastfile
`Then` fastlane was not able to pick up a commit sha on `push` event
`Now` it will be able to do so
> [BW] Fix emerge lane on push

- Sources/StreamChat/APIClient/ChatRemoteNotificationHandler.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Utils/NotificationExtension+Lifecycle.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/EventMiddlewares/NotificationExtensionLifecycle_Mock.swift
- Tests/StreamChatTests/APIClient/ChatPushNotificationContent_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/Utils/Database/NSManagedObject_Tests.swift
- Tests/StreamChatTests/Utils/NotificationExtensionLifecycle_Tests.swift
- Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
Resolves https://github.com/GetStream/stream-chat-swift/issues/2309
Resolves https://github.com/GetStream/ios-issues-tracking/issues/264
Make channel unread counts accurate
Unread counts were not accurate when the app was in the foreground handling the updates both using WS events and Push Notifications
This PR stops the notification extension from saving data to the DB if the host app is connected through WS, and processing those events.
This communication is done using a shared UserDefaults based on App Groups.
1. Open the app and leave it on the channel list
2. Using another device/simulator, send messages to the previous device
3. The unread count should have the correct amount
The issue was frequently visible when sending replies to a thread (sending those messages to the channel, as …
> Do not store messages from extension if app is receiving events

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/AttachmentDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/NSManagedObject+Validation_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
-
Add support to skip url enrichment through the SDK
Our backend allow us to send a flag to determine if the url sent in a message should be enriched or not. This PR allows this flag to be sent
Both MessageController and ChannelController allow `skipEnrichUrl` parameter when sending a message/reply
- Open a Channel
- Tap the Debug Button
- Tap "Send message without url enriching" action
- Write a message
- Click "OK"
Should send a message without url enriching
> Add support for skip_enrich_url

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Filter+ChatChannel.swift
- Sources/StreamChat/Query/Filter.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves [Link](https://github.com/GetStream/ios-issues-tracking/issues/326)
The following filter doesn't work correctly with auto filtering.
```swift
let controller = streamChatClient.channelListController(
query: ChannelListQuery(filter: .and([
.equal(.type, to: .custom("test")),
.containMembers(userIds: ["12632287"]),
]))
)
```
The issue appears to be that the filter's and DB's value type don't match and when they are being compared it fails.
To maintain our type-safe API while supporting auto-filtering, we will provide a valueMapper on the filter that will allow in cases where the filter's and DB's value type don't match, to disambiguate the problem by mapping the filter's value to the a value that matches the DB's value type.
> Fix auto-filtering when filter and DB value types don't match

- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/330
Run the test without crashing
The test is crashing due to a race condition in accessing the `sendMessageCalls`. We are using atomic writes but not reads. 
Change the access to `sendMessageCalls` to be Atomic for both writes and reads
We are going to use the Repeatable test execution on Xcode:
1. Right click on the status diamond on the left side of the test case
2. Select Run test "test_senderSendsMessage_inTheOrderTheyWereCreatedLocally" Repeatedly...
3. Set the stop after to Failure and the maximum repetitions to 1000
Execute on develop and then on this branch.
> Re-enable test

- CHANGELOG.md
- Sources/StreamChat/APIClient/RequestEncoder.swift
We had a public extension on `[URLQueryItem]` that was supposed to only be internal
ExpressibleByDictionaryLiteral's conformance requires its methods to be public, which was exposing this extension to our integrators
Removed the conformance of ExpressibleByDictionaryLiteral and created an extension over `URL` to allow passing in query parameters as dictionary, which will internally be converted into `URLQueryItem`
> Remove [URLQueryItem] public conformance of ExpressibleByDictionaryLiteral

- docusaurus/docs/iOS/common-content/reference-docs/stream-chat/chat-client.md
https://getstream.zendesk.com/agent/tickets/34723
There was a mistake in the documentation around `connectionStatus` that was suggesting to use `CurrentChatUserController` instead of `ChatConnectionController` to observe changes
> Fix connectionStatus observing documentation

- CHANGELOG.md
- Makefile
- Scripts/removePublicDeclarations.sh
- Scripts/updateDependency.sh
- Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyScanner.swift
- Tests/StreamChatUITests/Utils/DefaultMarkdownFormatter_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/334
Fix issue where an unexpected Markdown pattern was hanging forever due to an issue in SwiftyMarkdown
Forked SwiftyMarkdown, and added a defensive measure so that this scenario does not happen again.
https://github.com/GetStream/SwiftyMarkdown/commit/16b4de5804977bfb3da3b61e8443d1a180f5d2d5
Updated embedded dependencies so that our SDK has this change.
> Fix Markdown hanging forever

- CHANGELOG.md
- Sources/StreamChat/Query/Filter+ChatChannel.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/333
Fix "In" Filter only returning results when all values match.
The Mongoose style "in" operator, used by our backend API is actually an "or" operation, meaning that only one of the given values need to match, and not all of them. So this was a simple change in our side.
Unit tests were provided to cover regression.
> Fix "In" Filter only returning results when all values match

- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Tests/StreamChatTests/Models/Attachments/GiphyAttachmentPayload_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/339
Make title optional in `GiphyAttachmentPayload`
Currently, `GiphyAttachmentPayload` is the only attachment payload that unjustifiably requires `title` to be provided. This PR intends to fix this.
> [339] Make title optional in GiphyAttachmentPayload

- CHANGELOG.md
- Sources/StreamChat/Query/Filter+ChatChannel.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Fix an issue when using auto-filtering with collection operators where the array of values, contains items of types that are not directly comparably for CoreData.
The crash is caused because the values array contains items of type ChannelType which is not directly comparable for CoreData.
We are using the same approach we used to resolve the problem with the FilterKey value. We are using the valueMapper provided by the FilterKey to map the values into a CoreData comparable format.
> Fix auto filtering issue with collection operators

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
https://github.com/GetStream/stream-chat-swift/pull/2532
https://github.com/GetStream/ios-issues-tracking/issues/357
Fixes channel being marked read when the view is not visible
- Login as User A
- In the channel list, slide the channel row and change the presentation style to TabBar
- Make sure to remain at the bottom of the channel
- Then select the dummy view (right view)
- With User B, send messages to the channel
- With User A, tap on the top left arrow to return to the Channel List
- User A should see the unread counter in the channel row
> Fix channel marking read when view is not visible

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2545
Calls missing completion blocks when `loadPreviousMessages`, `loadingNextMessages` and `loadingPageAroundMessageId`.
N/A
> Fix completion blocks not called when loading more messages

- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
- StreamChatUITestsAppUITests/Tests/QuotedReply_Tests.swift
- TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/361
- Add E2E tests for bi-directional-scrolling
> Add E2E tests for bi-directional-scrolling

- .styles/xcode-line.tmpl
- StreamChat.xcodeproj/project.pbxproj
- bin/vale-lint.sh
- Add script calling Vale. If vale is not available, pass successful.
- Add docusaurus as a folder tothe xcode project, making sure it is not part of any targets. This allows error reporting to be shown in Xcode
- Add a template file containing an output config that Xcode can interpret
> Add vale linting as a build step in Xcode

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/369
With the auto-filtering implementation the filtering priorities were set to (higher to lower):
- `filter` closure
- auto-filtering
- `deprecatedFallback`, which is using the controller's delegate to determine if channel should be linked or not with a controller.
When auto-linking is enabled and no filter closure is used, we should return immediately and skip calling the controller's delegate.
Implemented the filtering hierarchy that was described in Summary.
- (with auto-filtering on) Test with a user that is not part of a public livestream that they can still access the channel.
- - (with auto-filtering off) Test with a user that is not part of a public livestream that they cannot access the channel.
_Provide a funny …
> Fix deprecatedFallback getting called when auto-filtering is enabled

- .swiftlint.yml
- Sources/StreamChatUI/ChatMessageList/ChatMessageListDateSeparatorView.swift
- Sources/StreamChatUI/CommonViews/ContainerStackView.swift
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
- Sources/StreamChatUI/Gallery/GalleryVC.swift
- Sources/StreamChatUI/Utils/Extensions/NSLayoutConstraint+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
N/A
Fix our custom swiftlint rule to ensure we write UI Components only using `.pin()` instead of the `.constraint()` so customers can override our constraints.
Bonus: Fixes swiftlint from running twice
> Fix SwiftLint regular_constraints_forbidden rule

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/375
Improve auto-filtering when using ChannelId (cid) with the `in` operator.
Due to a missing keypathMapper the comparison was unable to complete on CoreData layer.
> Add missing keypathMapper for ChannelId auto-filtering

- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/APIClient/RequestEncoder.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ConnectionDetailsProviderDelegate_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/RequestEncoder_Spy.swift
- Tests/StreamChatTests/APIClient/APIClient_Tests.swift
- Tests/StreamChatTests/APIClient/RequestEncoder_Tests.swift
- Tests/StreamChatTests/StreamChatIntegrationTests/PinnedMessagesQuery_IntegrationTests.swift
Relates to #2431 
Fix unexpected 401s produced at launch, while the chat is not yet fully connected.
The issue was produce when trying to load resources, while  connecting to the chat. 
When that happened, and if the internet connection is not ideal, it might happen that while waiting for the token to be retrieved, we end up timeout'ing. 
In that case, we were mistakenly sending the request without authentication headers and that's returning an expected 401. 
This PR forwards timeouts to the APIClient for it to handle it, instead of just returning a request without authorization that gets sent to the backend.
The APIClient will retry the request (up to a max retries limit), giving time for the connection to be fully stablished
TBD
> Prevent unauthorized requests from reaching the backend

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/271
It fixes a rare crash when getting an unread count from a logged-out/invalid user.
- Fixes a crash when getting an unread count from an invalid user
Unit Tests have been added to cover this scenario.
> Fix crash when getting unread count in invalid state

- CHANGELOG.md
- Sources/StreamChat/Repositories/OfflineRequestsRepository.swift
- Sources/StreamChat/Utils/Database/NSManagedObject+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/Database/FetchCache_Tests.swift
- Tests/StreamChatTests/Repositories/OfflineRequestsRepository_Tests.swift
https://github.com/GetStream/ios-issues-tracking/issues/385
Fix a crash where accessing FetchCache internal storage would crash
```
This fetch request (0x60000263cb60) was created with a string name (QueuedRequestDTO), and cannot respond to -entity until used by an NSManagedObjectContext
```
You cannot access NSFetchRequest’s `entity` property unless the request has been executed.
Because setting it as a key for a dictionary will access its hash value, and it internally uses `entity` to compute it, it crashes.
Same goes for the other crash we've seen, where it is calling isEqual and its internal implementation makes it crash.
NSFetchRequest is wrapped before adding it to the internal storage of FetchCache. This wrapper has its own implementation of Hashable and Equatable, which makes it …
> Avoid Crash when accessing FetchCache with an unexecuted NSFetchRequest

- CHANGELOG.md
- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- StreamChatUITestsApp/ViewController.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/APIClient/APIClient_Tests.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/389
Fix the Guest authentication
Since the SDK version 4.25.0 the Guest Authentication was failing. This PR resolves the underlying issue and ensures Guest Authentication works again as expected.
During Guest Authentication, the APIClient's operationQueue is getting suspended as it enters tokenFetching mode. Then we using APIClient to fetch the Guest Authentication Token. The request never gets executed due to the suspended operationQueue.
To overcome the issue but also provide a mechanism for similar use-cases, we are introducing a new request/operation combination on APIClient. The new request will be translated to an AsyncOperation which will be added for execution to user-provided operationQueue. The APIClient will not …
> [Fix]Guest Authentication Flow

- CHANGELOG.md
- Sources/StreamChat/APIClient/RequestEncoder.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Tests/StreamChatTests/APIClient/RequestEncoder_Tests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketClient_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/386
Fixes a crash only in the develop branch, which happens when logging out and in with an unstable network connection or the network is offline.
1. Open channel list
2. Turn off Wi-fi
3. Log out
4. Log in
5. Channel List will display an error to re-fetch the channel list
6. Turn on Wi-fi and at the same time, tap to re-fetch the channel list
> Make connect/disconnect safer when network is offline

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- StreamChatUITestsApp/ViewController.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/AuthenticationRepository_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/Logger_Spy.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
- Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/282
Make the `connectUser` call safer by logging out the user in case the user was not logged out. (If the user is a new user only)
The implementation is done in the `AuthenticationRepository`, which delegates the logging out functionality to the `ChatClient`. This is useful because only in the `AuthenticationRepository` we have a centralized function to connect the user, whereas if we did it directly in the `ChatClient`, we would need to implement this in multiple places. Besides that, it would be harder to test. With the current approach, we just need to mock the delegate to check if we logged out. 
https://user-images.githubusercontent.com/12814114/233457445-29aa52a8-c685-45e4-8fb0-fc224dab4fcb.mp4
Follow the steps in the …
> Safer `connectUser()` by logging out the user first if needed

- Examples/EdgeCases/EdgeCasesSettingsViewController.swift
Resolve a `superfluous_disable_command` rule violation.
https://realm.github.io/SwiftLint/superfluous_disable_command.html
As the title says.
> Remove a superfluous disable command

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
https://github.com/GetStream/stream-chat-swift/issues/2590
Fix InputTextView not scrolling to caret when pasting long text
https://github.com/GetStream/stream-chat-swift/assets/12814114/e91f2cff-1840-473b-b8a2-942af211de38
This is a small issue with low impact, so there is a need for Manual QA or Automated tests.
> Fix InputTextView not scrolling to caret when pasting long text

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/420
Fix a memory leak when loading more channels in `ChatChannelListController` caused strongly capturing self when calling the `ChannelListUpdater.update` completion block. This memory leak was recently introduced because of `AsyncOperation` retaining the completion blocks of the updaters. 
Tests were changed to make sure there are no regressions in this memory leak.
> Fix memory leak in ChannelListController

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
https://github.com/GetStream/ios-issues-tracking/issues/407
Allow replies for soft-deleted messages
Up until now, we were not showing the UI to access thread replies for soft deleted messages. This was not allowing a UX flow to add more replies to it.
This PR aims to allow access to a thread when there are replies to a soft deleted message
1. Send a message
2. Add a thread reply to it
3. Remove root message
Expected results:
1. The deleted message cell should indicate that there are replies to it
2. You should be able to access the thread
3. You should be able to send new replies to it
> Allow replies to soft-deleted messages

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Filter+ChatChannel.swift
- Sources/StreamChat/Query/Filter.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/423
Fix the channel list query being empty when the `.muted` and `.joined` filters were used with auto filtering enabled.
We currently have an issue with our Auto Filtering where the `.muted` and `.joined` filters do not properly map to our DB predicates.
After some analysis and discussion with @ipavlidakis, we opted for introducing a `PredicateMapper` so that a filter can override the default Predicate logic.
Unit tests were added to prove it works correctly.
> Fix muted and joined channel list queries with empty data (Auto Filtering Enabled)

- CHANGELOG.md
- DemoApp/DemoAppConfiguration.swift
- DemoApp/Screens/UserProfileViewController/UserProfileViewController.swift
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/UserUpdateMiddleware.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserUpdateMiddleware_Tests.swift
https://github.com/GetStream/ios-issues-tracking/issues/426
Handle `user.updated` events and reflect such changes in the database
We were not yet handling those events, which was resulting in changes to users information (including the current user) not being reflected during the lifecycle of the app
This PR adds `UserUpdatedMiddleware`, which updates the user in the Database according to the data received.
It also adds a new screen in the DemoApp that shows the profile, and reacts to changes to it.
https://github.com/GetStream/stream-chat-swift/assets/7887319/00e8510a-db5a-479c-9e0a-22dc8130e381
1. Open the demo app, and go to the profile.
2. From another device update the information of this user
3. The updates should be reflected on screen
> Handle `user.updated` events

- .github/workflows/cron-checks.yml
- .github/workflows/emerge.yml
- .github/workflows/smoke-checks.yml
- .github/workflows/sync-mock-server.yml
- .github/workflows/testflight.yml
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- fastlane/Fastfile
Resolves https://github.com/GetStream/ios-issues-tracking/issues/443
Bump Xcode version to 14.3 on GitHub Actions
- All jobs on GitHub Actions now use `Xcode 14.3`
- Except E2E tests which still use `Xcode 14.2` because, for some reason, authentication tests do now work on GitHub Actions on `Xcode 14.3`. Will try to run them on Xcode 14.3.1 as soon as it's released.
> Bump Xcode version

- .github/workflows/smoke-checks.yml
Xcode 13 and macOS 13 raise some weird issues on CI for E2E and Snapshot tests. For now, we decided to stick with Xcode 14.2 for these tests and with macOS 12 for Snapshot tests only.
Test:
- https://github.com/GetStream/stream-chat-swift/actions/runs/5122487122/jobs/9211654099?pr=2657
> [BW] Use Xcode 14.2 and macOS 12 for Snapshot tests

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/425
Fix shadow message making hidden channel reappear. 
It is easier to test this with this PR merged: https://github.com/GetStream/stream-chat-swift/pull/2660
1. User A shadow bans User B
2. User A hides a channel
3. User B sends a message to the channel
4. Channel should still be hidden for User A
> Fix shadow message making hidden channel reappear

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Tests/StreamChatTests/Models/Attachments/GiphyAttachmentPayload_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2629
Expose the Extra Data field in the Giphy Attachment Payload.
N/A for manual QA.
Unit Tests where added to proof it works.
> Expose Extra Data for Giphy Attachment Payloads

- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
`SyncRepository_Tests.test_syncExistingChannelsEvents_someChannels_apiSuccess_shouldStoreEvents` has failed multiple times on CI during the month.
Moving it to the flaky test suite if there are no objections.
Fixing `MessageUpdater_Tests.test_loadReplies_whenIsJumpingToMessage_shouldClearCurrentMessagesExcludingLocalOnly`
> [BW] Update test plans

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Workers/Background/AttachmentQueueUploader.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/Workers/Background/AttachmentQueueUploader_Tests.swift
Resolves: https://github.com/GetStream/stream-chat-swift/issues/2326
Resolves: https://github.com/GetStream/ios-issues-tracking/issues/208
Allow resending attachments when those fail
Up until now, when sending a resource as part of a message attachment, we would face an issue trying to resend them if those were not successfully sent at first. This is because the resources could not be found using the references that were given when initially fetching them from the SDK.
When importing resources (using Files, Photo Album or Camera) into the SDK we are given temporary URLs. Those URLs are meant to be used within the session in which those are provided, but not persisted. Those resources will not be available in subsequent launches of the app, and therefore we cannot keep those URLs as a …
> Resend failed attachments

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Workers/Background/MessageSender.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/471
Messages could enter in a limbo state if they were stuck in .sending
There was an edge case where if the app is killed while messages are being sent, they are stuck in `.sending` state. MessageSender was not trying to send them in the following session as it only looks for message is `.pendingSend` state.
This PR adds a mechanism to move those messages in `.sending` state to `.pendingState` on start up, so those can be rescued.
1. Simulate a really bad network
2. Send a message
3. Kill the app
4. Open the app again
- The message should initially not be sent (showing the clock)
- The message should be immediately sent after startup, and show the "tick" icon
> Rescue messages stuck in .sending state

- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/Pages/MessageListPage.swift
- StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- StreamChatUITestsAppUITests/Tests/Attachments_Tests.swift
Relates to https://github.com/GetStream/stream-chat-swift/pull/2680
PS: I also added `StreamChat` and `StreamChatUI` frameworks to the TestApp's embedded frameworks to be able to start the app on the device/simulator without Xcode.
> [CI] Add E2E tests for restarting attachment upload

- CHANGELOG.md
- Sources/StreamChatUI/Utils/ImageLoading/ImageLoading.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatUITests/Utils/ImageLoading_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2692
When providing a custom `ImageLoading` implementation, some of the functions were not being called. This is because the default implementations provided through the extension in the protocol were using default arguments in the declaration, and this makes Swift think that it is a different function. So the solution is to provide additional declarations without the arguments, which can have default values.
N/A for manual QA. Unit Tests were added to proof it works.
> Fix custom `ImageLoading` functions with default arguments not being called

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
https://github.com/GetStream/stream-chat-swift/issues/2699
Fix messages disappearing while searching messages. This would happen after entering a channel and coming back to the search. 
We fix this by separating the `message.cid` and the `message.channel.cid`. Before, the `message.cid` was populated through the `channel.cid`, the thing is that in some scenarios we might not have the channel in the local DB. For example, when jumping to messages we sometimes delete or unlink the channel from the local DB. This PR changes this, so now the `message.cid` is populated whether we have a channel locally or not.
This was tested in a local branch through SwiftUI.
Integration tests were also added to proof it works.
> Fix messages disappearing in search query after entering a channel

- docusaurus/docs/iOS/uikit/components/channel-list.md
- docusaurus/docs/iOS/uikit/components/channel.md
- docusaurus/docs/iOS/uikit/components/message.md
- docusaurus/docs/iOS/uikit/custom-components.md
- docusaurus/docs/iOS/uikit/data-formatting.md
- docusaurus/docs/iOS/uikit/getting-started.md
- docusaurus/docs/iOS/uikit/theming.md
Some typos I ran into while reading the UIKit docs.
Run docusaurus locally.
> Fixed typos in the UIKit docs

- .github/workflows/cron-checks.yml
Due to CI fail:
```
[03:30:10]: Simulator iPhone 14 Pro Max (16.4) not found 
Available simulators: 
["iPhone 8 (16.2)", "iPhone 8 Plus (16.2)", "iPhone 11 (16.2)", "iPhone 11 Pro (16.2)", "iPhone 11 Pro Max (16.2)", "iPhone SE (2nd generation) (16.2)", "iPhone 12 mini (16.2)", "iPhone 12 (16.2)", "iPhone 12 Pro (16.2)", "iPhone 12 Pro Max (16.2)", "iPhone 13 Pro (16.2)", "iPhone 13 Pro Max (16.2)", "iPhone 13 mini (16.2)", "iPhone 13 (16.2)", "iPhone SE (3rd generation) (16.2)", "iPhone 14 (16.2)", "iPhone 14 Plus (16.2)", "iPhone 14 Pro (16.2)", "iPhone 14 Pro Max (16.2)", "iPad Pro (9.7-inch) (16.2)", "iPad (9th generation) (16.2)", "iPad Air (4th generation) (16.2)", "iPad Pro (11-inch) (3rd generation) (16.2)", "iPad Pro (12.9-inch) (5th generation) (16.2)", "iPad Air (5th …
```
> Set up the latest iOS version for macos-12

- DemoApp/Extensions/UIViewController+Alert.swift
- DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
None
Fix demo app crash when tapping filter channels on iPad.
- Open Demo App with iPad
- Tap on Channel Filters (right top corner icon)
- Should not crash
> Fix Demo App crash when tapping filter channels on iPad

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelListSearchVC.swift
- Sources/StreamChatUI/ChatChannelList/Search/ChatMessageSearchVC.swift
None
Some customers had to disable this explicit to avoid some issues. This will make sure that for Search we don't use channel list states, and also that we don't add the empty view twice to the hierarchy.
N/A. There is no impact on the Demo App.
> Make sure that channel list states are disabled for Search

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListItemView_Tests.swift
N/A
Fix the channel name being blank in Message Search when the channel name exists but is empty.
N/A. A test was added to prove it works.
> Fix blank channel name in Message Search

- CHANGELOG.md
- Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
- Sources/StreamChat/Audio/AudioSessionConfiguring.swift
- Tests/StreamChatTests/Audio/StreamAudioSessionConfigurator_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/441
Make sure all voice messages are played using the loud speaker
AudioSession does not allow overriding the speaker output unless the category is set to `.playAndRecord`. When we were tying to do so, an error was triggered, leaving the whole Audio Player in an inconsistent state which would result in all the voice messages being played from the earpiece.
- Changed the category to `.playAndRecord` for playback.
- Removed unnecessary guards 
- Open message list
- Play audio
- Audio plays from Loud Speaker
- Record Audio Message
- Play any audio
- All audio is coming from the loud speaker
> Make sure loud speaker is always used for playback

- CHANGELOG.md
- PrivacyInfo.xcprivacy
- StreamChat.xcodeproj/project.pbxproj
- fastlane/Fastfile
Resolves https://github.com/GetStream/ios-issues-tracking/issues/516
- Align with new Apple privacy requirements
- [Privacy manifests](https://developer.apple.com/wwdc23/10060)
- [Digital signatures](https://developer.apple.com/wwdc23/10061)
- Inject `PrivacyInfo.xcprivacy` to `StreamChat` and `StreamChatUI` binaries
- Add digital signature to `StreamChat` and `StreamChatUI` xcframeworks 
- Remove unrelated bundle identifiers from `match` fastlane lane
> Add PrivacyInfo and Digital Signatures

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/269
Fixes multiple issues related to user changes not being reflected in UI components.
- Fixes channel header view not updating when there are user changes
- Fixes user online presence UI not updated in the Channel Header View
- Fixes user online presence not updated in the Channel List items
Whenever there is a user update, now we not only trigger updates to the members but also to the channel to which that member belongs.
| Channel Header Updates | Online Presence Updates |
|  <video src="https://github.com/GetStream/stream-chat-swift/assets/12814114/33c7ba95-7312-49bf-9fe1-e26ff0431036"/>   |  <video src="https://github.com/GetStream/stream-chat-swift/assets/12814114/74e07f4a-fde5-4194-881f-cd49113e7642 …
> Fix channel header and user online presence not updated when user changes

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift
if the message composer’s parent view’s frame origin is not zero, there is a gap between the composer and the keyboard by that amount:
to fix this glitch
to find where the keyboard intersects the composer’s parent view, I think you need bounds, not frame. frame is in the coordinate space of composerParentView’s superview, and convertedKeyboardFrame is in the coordinate space of composerParentView.
changed frame to bounds
| <img width="608" alt="Screenshot 2023-08-21 at 3 53 20 PM" src="https://github.com/GetStream/stream-chat-swift/assets/8378384/5d9b5289-a96e-45d3-bb6f-cdfdb704438d"> | <img width="608" alt="Screenshot 2023-08-21 at 3 52 16 PM" src="https://github.com/GetStream/stream-chat-swift/assets/8378384/82c73b6d-4aa3-4cc0-aff1-a8d54474b57f"> |
> Fix gap between the composer and the keyboard when parent view’s frame origin is not zero

- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
None
Fix not being able to send messages when channel is empty. Also it should not be possible to send attachments initially, only after the channel is created.
|  <video src="https://github.com/GetStream/stream-chat-swift/assets/12814114/32531197-84bc-40ed-9e53-1ff41e13e77e"/>   |  <video src="https://github.com/GetStream/stream-chat-swift/assets/12814114/4cb25e7f-fb22-4e05-8df5-bba23b8ba9cc"/> |
Check the video
> Fix channel capabilities logic when channel is empty

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/1
Fixes scrolling to the bottom when tapping in the status bar.
1. Tap on the status bar
2. Should scroll to the top (In the current page)
> Fix tapping on status bar scrolling to bottom instead of top

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- Sources/StreamChatUI/Components.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/Controllers/ChatChannelController_Mock.swift
- Tests/StreamChatUITests/Mocks/ChatMessageList/ChatMessageListVC_Mock.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatThread/ChatThreadVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/533
Possibility to skip the animation when jumping to a message.
- Added a new `animated: Bool` to `jumpToMessage()`
- Added a new `Components.shouldAnimateJumpToMessageWhenOpeningChannel`
- Open DemoApp Configuration
- Disabled `shouldAnimateJumpToMessageWhenOpeningChannel`
- Enable Message Debugger
- Open a channel
- Long tap a message
- Tap on message debugger
- copy message id
- Leave the channel
- Swipe and tap on "..."
- Tap on "show channel with id"
- Should jump to the message without animation
> Add support for disabling jumping to message animation

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListLoadingView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListLoadingViewCell.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/CommonViews/SkeletonLoadable.swift
- Sources/StreamChatUI/Components.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/512
Resolves https://github.com/GetStream/ios-issues-tracking/issues/537
Make `ChannelListLoadingView` Customizable.
Fix a UI Glitch that sometimes would appear as dummy text for a split second.
- Add customization support for `ChannelListLoadingView`
- Fix dummy texts UI Glitch in `ChannelListLoadingView`
- Rename`Components.chatChannelListLoadingView` -> `Components.channelListLoadingView`
Currently, our Skeleton View is not very flexible, and ideally, we should have a generic Skeleton View, which would adapt independently of the Channel List Cell layout. Something similar to what we had in a previous WIP PR: https://github.com/GetStream/stream-chat-swift/blob/CIS-1010-Add_States_to_ChannelList/Sources/StreamChatUI/Utils/Lo …
> Make `ChannelListLoadingView` Customizable + Fix UI Glitch

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
None
Fix critical issues causing a query channel call for every new message.
Whenever we link a channel, we do a call to start watching that channel. This makes a request to the channels query endpoint. Because now we check for linking a channel on every new message, we need to first verify if this channel is already linked or not, otherwise, we will be making unnecessary requests. 
- Proxyman is needed to verify that the requests are not being sent anymore for every new message.
- Unit tests were added as well to cover these scenarios.
> Fix critical issue causing a query channel call for every new message

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelListSearchVC.swift
- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelSearchVC.swift
- Sources/StreamChatUI/ChatChannelList/Search/ChatMessageSearchVC.swift
None
Fix compilation issues introduced in the 4.37.0 release. 
Somehow for some customers that use Cocoapods, the `@available(iOSApplicationExtension, unavailable)` is required. 
N/A
> Fix compilation issues on NSEs when using Cocoapods

- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Do not mark unseen new messages as read. Wait until they are seen
When a user was in a chat, but scrolled up, new messages were being marked as read, even though those were not seen
Since 4.37.0, we have been using local flags to keep track of whether the first unread message and the newest message in the history were seen. For the latter, we need to make sure we reset the local flag to false after marking the channel as read, so that we don't mistakenly mark messages as read when they are not seen.
2. Make sure it is marked as read
3. Scroll up so the newest message is not visible on screen
4. Send a message from another device
- The new message should not be marked as …
> Release fix: Do not mark as read new unseen messages

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Fix issues around Mark as/Jump to unread for scenarios around truncation
There were some issues found when trying with truncated messages.
- When checking if the last message was seen, we are now checking if it was seen or it is currently on screen
- Truncation events now clear the state for current user's read
- When discarding messages using the unread messages pill, we are resetting the state that determines if the channel was marked as unread in the current session
** Truncation **
- Create a channel
- Add some messages with 2 users
- While in the channel, truncate it
- Receive new messages
- The unread message pill …
> Release fix: Truncation related fixes for mark as/jump to unread

- Sources/StreamChat/Utils/LazyCachedMapCollection.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC+DiffKit.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
Fixes the logic around skipping messages when receiving messages and scrolling at the top.
It also improves the efficiency of skipping messages by transforming the `LazyCachedMapCollection` to `Array` only when there are message list UI changes.
To be filled when merged to develop
Run the performance load script while scrolling the message list to the top. The message list should not jump + performance should be good.
To be filled when merged to develop
> Fix skipping messages logic + performance improvements

- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
Reverts updating every message whenever the user info changes since this causes a lot of performance issues.
> Revert message updates whenever user info changes

- CHANGELOG.md
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
N/A
Fix thread-safety issues when connection waiters time out.
Unit tests were added to proof it does not crash anymore.
> Fix thread-safety of connection waiter when timing out

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/520
Fix message list not updated when user name and image changes.
This one fixes the issue reverted here: https://github.com/GetStream/stream-chat-swift/pull/2810
The original fix caused big performance issues. The reason is that we did this change for every user update, even if there were no actual real user changes, and so this caused way too many message updates for no reason.
This new approach will only update the message when user names and images change. Since these rarely happen, it is safe to make this change. 
Perform a stress test in the Message List
1. Open a Channel
2. Update the user data of one of the members.
```bash
stream-cli chat upsert-user --properties "{\"id\":\"leia_organa\",\"name\":\"Leia\", …
```
> Fix messages not updated when user name and image changes

- CHANGELOG.md
- DemoShare/DemoShareViewModel.swift
- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/Controllers/ChatChannelListController_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/WebSocketEngine_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelReadPayload_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/CreateCallPayload_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Requests/ChannelTruncateRequestPayload_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Requests/MessageReactionRequestPayload_Tests.swift
- Tests/StreamChatTests/Query/ChannelListQuery_Tests.swift
- Tests/StreamChatTests/Query/ChannelMemberListQuery_Tests.swift
- Tests/StreamChatTests/Query/ChannelQuery_Tests.swift
- Tests/StreamChatTests/Query/PinnedMessages/PinnedMessagesQuery_Tests.swift
- Tests/StreamChatTests/StreamChatIntegrationTests/PinnedMessagesQuery_IntegrationTests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketConnectPayload_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/546
Resolves https://github.com/GetStream/ios-issues-tracking/issues/576
- Fix showing empty view when creating a new channel
- Fix showing loading view for cached channels
- Bonus: Fixed some swiftlint warnings
Both are bundled in this PR since they are related.
**Fix showing empty view when creating a new channel:**
This was happening because whenever the channels data was changed, we did not re-evaluate the state views. Now we also handle the state view changes whenever there are data changes.
**Fix showing loading view for cached channels:**
Because of the recent introduction of DIffKit in the Channel List, we had a race condition when determining if we should show the Loading View. The problem is that …
> Fix channel list states view when creating a channel and loading cached channels

- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
Fix deadlock introduced by: https://github.com/GetStream/stream-chat-swift/pull/2814
When timing out on `provideConnectionId`, a deadlock happens because of a `sync` dispatch to the same queue where we are already performing the work.
`connectionQueue` is a concurrent queue, and therefore multiple threads might be reading/writing `connectionIdWaiters`. This is not what we want. To fix that, we will dispatch writes using a `.barrier` flag, so that there are no race conditions there.
> Avoid deadlock when acessing connectionIdWaiters

- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
Closes https://github.com/GetStream/stream-chat-swift/issues/2840
When timing out on `provideConnectionId`, a deadlock can happen because of a `sync` dispatch to the same queue where we are already performing the work. If that ends up calling a property on the class that requires a `sync` dispatch, it would deadlock.
`tokenQueue` is a concurrent queue, and therefore multiple threads might be reading/writing `tokenWaiters`. This is not what we want. To fix that, we will dispatch writes using a `.barrier` flag, so that there are no race conditions there.
_Provide a funny gif …
> Avoid edge case deadlock in AuthenticationRepository

- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/Controllers/BackgroundListDatabaseObserver.swift
- Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/ListDatabaseObserverWrapper_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserTypingStateUpdaterMiddleware_Tests.swift
https://github.com/GetStream/ios-issues-tracking/issues/283
Make Background Mapping production ready
Background Mapping has been there for a while, but we never got the chance to ship it. This PR intends to make it production ready.
Things to test in both Channel List and Chat:
- Pagination
- Jump to messages
- Initial load
- Performance
> Background Mapping - Main implementation

- Sources/StreamChat/Controllers/BackgroundListDatabaseObserver.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/ListDatabaseObserver_Mock.swift
- Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/ListDatabaseObserverWrapper_Tests.swift
- Tests/StreamChatTests/Query/Sorting/ListDatabaseObserver+Sorting.swift
- Tests/StreamChatTests/Query/Sorting/ListDatabaseObserver+Sorting_Tests.swift
Continuation of https://github.com/GetStream/stream-chat-swift/pull/2831
The goal of this PR was to fix some deficiencies BG Mapping had when being Offline
There was an assumption that for the initial fetch we would not need to notify the listeners. This was not a problem when being online, given that any interaction with the network would trigger updates, and therefore the listeners would be notified.
This is, though, a big problem when in offline mode, where we depend on the initial data.
This PR makes sure the listener is always notified with the initial fetch
1. Open the app
2. Close the app
3. Disable internet
4. Open the app while offline (should have some content fetched in another session)
- The data in the channel list should be displayed
- Opening a channel …
> Background Mapping - Offline Fixes

- DemoApp/DemoAppConfiguration.swift
- Sources/StreamChat/Config/StreamRuntimeCheck.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/NSManagedObject+Validation.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/ChatMessage.swift
- Sources/StreamChat/Utils/CoreDataLazy.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
- Tests/StreamChatTests/StreamChatStressTests/CoreDataLazy_StressTests.swift
https://github.com/GetStream/ios-issues-tracking/issues/2
Allow fetching the needed relationships of models when mapping from DTO to Model without the performance degradation CoreDataLazy adds
When mapping the objects without `CoreDataLazy`, there was an infinite loop of fetches dues to circular relationships. This forced us to keep the laziness of `CoreDataLazy` for some mappings even when background mapping was enabled. Moreover, it was adding performance degradation due to its locking mechanisms.
- The logic around `CoreDataLazy` has been disabled for Background Mapping:
- Lazyness
- Locks
- Remove loops when fetching relationships
- When mapping relationships, a `depth` parameter is passed in order to stop fetching when a threshold is reached.
> Background Mapping - Disable CoreDataLazy

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/610
Some customers complained that it was difficult to override the `subtitleText: String` in the `ChatChannelListItemView`. There is quite a lot of logical branching inside this property which made it difficult to override the rendering of the subtitle without duplicating logic on the App side.
The following functions were added to make it easier to customize the channel item view without duplicating logic:
- Added `open func channelTitleTextForSearchedMessage()`
- Added `open func channelTitleText()`
- Added `open func previewMessageTextForEmptyMessage()`
- Added `open func previewMessageForAudioRecordingMessage()`
- Added `open func previewMessageTextForSystemMessage()`
- Added `open func …
> Allow easier customisation of the `ChatChannelListItemView`

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/619
Fix empty channel list when querying channels like so:
```swift
.or([
.equal(.hidden, to: true),
.equal(.hidden, to: false)
])
```
We were always adding a hidden filter by default. This filter assumed that the customer could only provide 1 filter for hidden, but that is actually not true. So this default hidden filter was overriding the logic provided by the customer. Now, we only add the hidden filter if the customer does not provide their own hidden filter.
N/A
N/A. 
Integration tests were added to prove it works.
> Fix empty channel list when querying both hidden or shown channels

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/597.
This is fixing the issue where you can fix pasting images from the browser, when isPastingImagesEnabled is false.
- Added a check when we perform the paste action
- Bonus: fixed changing this value to prevent files and images being in the composer at the same time (leftover)
- Disable isPastingImagesEnabled
- Go to the browser and copy an image
- Paste it in the composer - the link as a text should be pasted, instead of an image.
> Fixed pasting images from browser when isPastingImagesEnabled is false

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Models/Attachments/AnyAttachmentPayload.swift
- docusaurus/docs/iOS/uikit/guides/working-with-attachments.md
Resolves https://github.com/GetStream/ios-issues-tracking/issues/463
Adds support for editing custom attachments. 
A new API was added as part of the custom attachments flow. When creating the `ChatClient` it is now required to register the custom attachment payload through `ChatClient.registerAttachment(payloadType:)`.
Internally, we are currently using a static property because we can't afford having breaking changes. For StreamChat v5, we will most likely improve the attachments experience based on this WIP PR: https://github.com/GetStream/stream-chat-swift/pull/2879
N/A. We will eventually add a custom attachment in the Demo App out-of-the-box once we refresh the docs around custom attachments.
N/A
> Add support for editing custom attachments

- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
> Fix issue where text view is not scrollable when pasting a long text

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/JumpToUnreadMessagesButton.swift
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/Utils/Throttler.swift
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
- Tests/StreamChatUITests/Mocks/ChatMessageList/ChatMessageListVCDelegate_Mock.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/529
Enables the Jump to Unread button so that it jumps to the unread message when tapping it. 
- Adds support for jumping to unread messages through `ChatMessageListVC.jumpToUnreadMessage()`
- Adds a flag `Components.default.shouldJumpToUnreadWhenOpeningChannel` that if enabled the channel will open always in the unread message location
- Fixes a bug where "0 Unread Count" would show on the Jump To Unread Button
Because we don't yet get the `firstUnreadMessageId` from the backend, the current solution is to jump directly to the `firstUnreadMessageId` if it is already locally available. If not, we fetch the page where the `lastReadMessageId` is; since the `firstUnreadMessageId` will be located on that page, we then jump to …
> Add jump to unread interaction

- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/EventNotificationCenter_Mock.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
- Tests/StreamChatUITests/Mocks/ChatMessageList/ChatMessageListVC_Mock.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Regression found in 4.43.0
Fix broken jump to thread reply when opening channel.
> Fix jump to thread reply when opening channel

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
N/A
Fix marking channel read when `isJumpToUnread` is disabled.
The `shouldMarkChannelRead` logic did not account for the `isJumpToUnread` flag.
2. Mark a message unread on an old page
3. Go DemoApp configuration
4. Uncheck **isJumpToUnreadEnabled**
5. Open the same channel
6. Should mark the channel read when opening the channel
7. Go back to the channel list
8. Unread counts should be cleared
> Fix marking channel read when `isJumpToUnread` is disabled

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Repositories/ChannelRepository.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/ChannelRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Models/ChatChannel_Tests.swift
- Tests/StreamChatTests/Repositories/ChannelRepository_Tests.swift
- Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
Closes https://github.com/GetStream/ios-issues-tracking/issues/652
Fix Mark as unread when Background Mapping is enabled
We need to use the data that the API Request returns to us, instead of waiting for the delegate calls.
The most important thing here is that we cannot use the delegate calls because we cannot know if the update is from a “mark as unread” action or a different thing. If we just update the unread banner on the delegate call, we lose all the context as the channel will be marked as read, and the views would then disappear.
- The completion of `markUnread(from:completion:)` moves from just returning the `Error` to returning a `Result` object with the data.
- `ChannelController.getFirstUnreadMessageId(for:)` is now public
- `Channel` exposes now a convenience function to get …
> [Background Mapping] Fix Mark as unread

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
https://github.com/GetStream/ios-issues-tracking/issues/653
Stop marking channels as read for new members
Seems like we were marking the chat history as read for new channel members. This created a situation where on adding a member, all the messages in the history would increase their read count by one.
Stop marking as read for a new member in MemberEventMiddleware
1. Create a group
2. Send a message
3. Add a new member
- Read counts on messages should not increase
> Bugfix: Do not mark channel as read for new members

- CHANGELOG.md
- Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
- Sources/StreamChat/Audio/AudioRecorder/AudioRecording.swift
- Sources/StreamChat/Audio/AudioSessionConfiguring.swift
- Tests/StreamChatTests/Audio/StreamAudioPlayer_Tests.swift
- Tests/StreamChatTests/Audio/StreamAudioRecorder_Tests.swift
- Tests/StreamChatTests/Audio/StreamAudioSessionConfigurator_Tests.swift
- docusaurus/docs/iOS/client/audio-support/audio-playback.md
- docusaurus/docs/iOS/client/audio-support/audio-recording.md
Allow VoiceRecording feature to work aside with any other stack that also uses/manipulates the shared AVAudioSession instace.
In a WebRTC stack (which controls the AVAudioSession) if the user tries to send a VoiceRecording (chat during a voice/video call), once the message recording finishes, our AudioPlayer & AudioRecorder will try to mark the shared AVAudioSession as deactivated. That causes a conflict with the WebRTC stack which still requires the session to be activated.
The AudioSession handling as an implementation of our StreamAudioPlayer and StreamAudioRecorder (and not of them conforming protocols, AudioPlaying and AudioRecording). For this reason, we added a public method which can be used to update the underline `audioSessionConfigurator` on both classes. 
An example of usage …
> [Enhancement]Expose audioSessionConfiguration for the AudioPlayer

- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
N/A
Make sure `currentUser` data is available synchronously when accessing `client.currentUserController()`
Based on the usage of certain clients, we see that they expect that accessing `client.currentUserController().currentUser` should synchronously return the object. This was, though, not true when BackgroundMapping was enabled.
This PR reverts this so that we can still honor this usage
User `EntityDatabaseObserver` instead of `EntityDatabaseObserverWrapper` in `CurrentUserController`
> [Background Mapping] Do not use BG Mapping for CurrentUserController

- CHANGELOG.md
- StreamChat.xcodeproj/project.pbxproj
https://github.com/GetStream/stream-chat-swift/issues/2936
Fixes duplicated Runpath Search Paths. This was causing compilation warnings in Xcode 15, which has a new linker implementation, and it looks like it does not strip duplicated search paths. Either way, we can fix this on our side, and make sure we do not have duplicated search paths.
The reason we had duplicated search paths, was that we had both `@executable_path/Frameworks` and `@loader_path/Frameworks` defined in the Xcode project, and also in the `StreamChat` and `StreamChatUI` build settings. We had the search paths defined in the build settings of the frameworks plus the "$(inherited)" which basically copies what is defined in the Xcode project, hence the duplication. In our case, we can simply just use the `$(inherited)` …
> Fix duplicated Runpath Search Paths

- CHANGELOG.md
- Sources/StreamChat/Utils/Timers.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Utils/RepeatingTimer_Tests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketPingController_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/676
Fixes a crash in `RepeatingTimer`. The root cause is because of a double `resume()` call. Although we had protections against this, the reason this still happens very rarely is because this class is called from multiple threads, and so the way to fix it is to make sure the state is accessed in a serial queue.
N/A
> Fix `_dispatch_lane_resume` crash in RepeatingTimer

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
Messages with async voice attachment weren't edited properly - we treated the voice recording as video recording.
> Fix editing voice attachments

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/683
Fix quoted chat message view with wrong text.
The quoted chat message was using the `textView.text.isEmpty` to determine how to render text. Since this is used in a reusable cell, it would sometimes reproduce unexpected results.
This one was a bit hard to reproduce since it only happens when the cell is reused. 
Either way, we have plenty of snapshot testing covering the quoted messages. If the tests are green, it should not have any regressions.
> Fix quoted chat message view with wrong text

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/682
Fix the message list jumping to the bottom when loading new messages.
Before, whenever the newest message inserted was from the current user, we would scroll to the bottom. This is incorrect, since when loading new messages, if the last message author, is the current user, it will scroll to it. Now, it will only scroll if there is one insertion, which is what happens when the current user creates a new message. 
1. Jump to a mid-page
2. Load new pages (Scroll to the bottom)
3. When loading the newest page the newest message is by the current logged-in user
4. The message list should not scroll to the bottom automatically
**Note:** The difference is not very noticeable sometimes. This issue also fixes another case where …
> Fix jumping to bottom when loading new messages

- CHANGELOG.md
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
- Tests/StreamChatUITests/ChatMessage_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/691
Allow editing pending messages. Currently, while a message is being sent, it is not possible to edit it or cancel it. 
Throttle the network so that messages take more time to be sent
1. Send a message with and without attachments
2. While it is being sent, long press the message
3. Edit the text or attachments or delete it
4. Stop throttling the network
5. The message should be sent with the most updated data
> Allow editing pending messages

- CHANGELOG.md
- Sources/StreamChat/Query/UserListQuery.swift
None
Expose `UserListQuery.search(term:)` and `UserListQuery.user(withID:)`. This helper factory methods are useful to easily create and reuse these queries. They were internal, probably by mistake. 
N/A
> Expose `UserListQuery.search(term:)` and `UserListQuery.user(withID:)`

- .github/workflows/cron-checks.yml
- .github/workflows/smoke-checks.yml
- Cron checks take too much time during the release process (even longer if there is a queue), and so this PR shuts them down
- Cron checks are anyways executed every night on `develop`, and can be run on `release` PR manually via  `workflow_dispatch` if required
- Smoke checks are turned back on
> Do not run cron checks on releases

- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
Related to https://github.com/GetStream/stream-chat-swift/pull/2984
Follow-up task from https://github.com/GetStream/stream-chat-swift/pull/2984 to fix the composer link preview showing for multiple types of attachments. Whenever an attachment is inserted, we should discard the composer link preview.
**Case 1**
1. Type a link in the composer
2. The link preview should show
3. Insert an image
4. The link preview should be dismissed
**Case 2**
1. Insert an image in the composer
2. Type a link in the composer
3. The link preview should not show
**Case 3**
1. Edit a message that contains a link and an image
2. Should not show the link preview in the composer
> Do not show composer link preview with multiple attachment types

- Sources/StreamChat/Config/StreamRuntimeCheck.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
Provide a way to use stars scream instead of the url session WS.
> Added internal config for switching the WS implementation

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/645
When showing the ChannelListVC in a UINavigationController's stack, I noticed the swipe-to-go-back interaction wasn't working correctly. Upon investigation, I found the SwipeableView steals the gesture recognition from the navigation controller's interactivePoopGestureRecognizer
I've changed this view to ignore horizontal swipe gesture's when the action items are not expanded (i.e. view is not "open") _and_ the gesture is left-to-right. This SDK doesn't currently support action items on the left side, so this change should be safe.
- I've also made the delegate functions open. Making them public doesn't make sense because panGestureRecognizer is public and subclass or client of this view can override the delegate …
> Fix channel item actions gesture overriding native swipe go-back gesture

- CHANGELOG.md
- Scripts/updateDependency.sh
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatChannelList/Search/ChatMessageSearchVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
- Sources/StreamChatUI/Utils/Extensions/DifferenceKit+Stream.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatUITests/Utils/DifferenceKit+Stream_Tests.swift
Resolves [ios-issues-tracking/716](https://github.com/GetStream/ios-issues-tracking/issues/716)
Increase list performance and reduce UI glitches
- Avatars flash when opening the channel list
Avatars flash in the channel list when we apply `StagedChangeset.elementUpdated` changes. I observed that we call`reload(using:interrupt:setData:)` (applying data changes to the view) on the channel view 5 times after opening it (demo app) where one of the reload call contains 20 (in my case) `elementUpdated` changes. These, currently trigger cell reloads which cause the UI glitch (avatars flashing) and also reduces the performance since all the cells need to be created (it was the 4th reload call)
The proposed fix is to use Apple provided `UICollectionView.reconfigureItems(at:)` and …
> Reconfigure cells in the channel list when handling StagedChangeset.elementUpdated

- DemoShare/Info.plist
Fixes `warning: The CFBundleShortVersionString of an app extension ('1.0.0') must match that of its containing parent app ('1.0').` when building the demo app
> Demo app build warning about version mismatch

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Related to [PR 2984](https://github.com/GetStream/stream-chat-swift/pull/2984)
Clean up data detector types because since [PR 2984](https://github.com/GetStream/stream-chat-swift/pull/2984) we detect links manually in the text view.
> Clean up text view data detector types in the message cell

- .github/workflows/cron-checks.yml
The app could not be installed on older iOS devices if it was build on the latest Xcode/macOS
> Update xcode version for cron checks

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/Shared/Token+Development.swift
- Sources/StreamChat/Config/Token.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/719
Do not check token expiration client side. This is a bad practice since the user can change the device's time. 
- Stops checking expiration client side
- Fixes duplicated refresh tokens
- Fixes token refreshing not working when done server-side
- Adds the possibility to set refresh tokens in the Demo App
The main reason why server side refresh token was not working properly it was because `isGettingToken = false` should be set on `tokenReceived` as well, and not only when the waiting completion blocks are executed. The refresh token wouldn't be executed because `isGettingToken` was `true`, so it would ignore the refresh.
1. Open Demo App Configuration
2. Tap on "tokenRefreshDetails"
3. Input the app secret from the …
> Do not check token expiration client side

- docusaurus/docs/iOS/basics/logs.md
None
Adds documentation about how customers can intercept logs with the current logger implementation.
N/A
> Add documentation about intercepting logs

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift
None
Fix composer link preview overriding actual current link preview
- Increases the debouncer to 0.4s to be more aligned with how usually requests take to complete
- Fix composer link preview overriding actual current link preview
The proper way to do this is to cancel the previous request whenever we send a new request to enrich the url. The problem is that right now we do not have support for cancellable requests in our SDK, mostly because of tech debt issues. So right now, the best way to improve this is when we show the link preview we need to make sure that url is still the one in the composer input.
**Link preview should not show after sending the message**
1. Type a valid link in the composer
2. Very quickly after typing it, send the message
3. After the message was sent, it …
> Fix composer link preview overridden by previous enrichment

- CHANGELOG.md
- Sources/StreamChatUI/Utils/ImageLoading/NukeImageLoader.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatUITests/Utils/NukeImageLoader_Tests.swift
Related to [ios-issues-tracking/669](https://github.com/GetStream/ios-issues-tracking/issues/669)
Removed the flickering when opening channel list and merged avatars are loaded.
- Remove the non-determinism in the NukeImageLoader
NukeImageLoader sends multiple image loading requests to Nuke. It collects an array of results but the array is not sorted and depends on which request finished first. We currently just converted results into an array of images and proceeded with creating the merged avatars (individual images are also cached). When channel list updates cells, then the avatar generation is triggered again but this time, the order is different, because we already have images cached (in that case request order == response order). This change will make sure that returned images are …
> Images in merged avatars change their location when opening channel list

- Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
- Sources/StreamChatUI/Utils/Extensions/DifferenceKit+Stream.swift
Related to [PR:2996](https://github.com/GetStream/stream-chat-swift/pull/2996)
Make call sites nicer when we actually do not want to use reconfigure support (example: message list). Also optional closure allows skipping the partition call if we want to skip reconfigure.
This is a cleanup to the existing PR.
> Make reconfigure closure optional when reloading with staged changesets

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Relates to https://github.com/GetStream/stream-chat-swift/pull/3010
Fix native swipe-back gesture overridden by swipe to reply.
We use the `shouldRequireFailureOf` delegate method to check if the gesture should be overriden or not. If the active gesture is the one from swipe back, then we do not trigger the swipe-to-reply.
This issue was a problem with custom back buttons. So a custom back button was added to the Demo App to make sure we can test this.
2. Swipe back to go to the channel list
3. Open the channel again
4. Swipe to reply a message on the left
5. Both 2. and 3. should work
> Fix native swipe-back gesture overridden by swipe to reply

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/AvatarView/ChatChannelAvatarView.swift
- Sources/StreamChatUI/Utils/ImageLoading/ImageResultsMapper.swift
- Tests/StreamChatUITests/Mocks/ImageLoader_Mock.swift
- Tests/StreamChatUITests/Utils/ImageResultsMapper_Tests.swift
Resolves [ios-issues-tracking/725](https://github.com/GetStream/ios-issues-tracking/issues/725)
Fix CGBitmapContextInfoCreate warnings in console log when opening the channel list
- CGBitmapContextInfoCreate warning does not appear
CGBitmapContextInfoCreate warning appeared in console when creating merged/avatar collages for channel list. The warning was triggered when already resized image was passed again to the Nuke's image resizer. Seems to be an issue with creating a CGContext the Nuke uses for the same image which came from the same CGContext (e.g. double resize). Only triggered for images which have wide gamut/extended color space. Seems like it is something to do with bitmapInfo and color space mismatch (extended color spaces should use float data for the image store which is also …
> Fix CGBitmapContextInfoCreate warnings in console

- CHANGELOG.md
- Sources/StreamChatUI/Appearance+Formatters/MarkdownFormatter.swift
Related: [ios-issues-tracking/669](https://github.com/GetStream/ios-issues-tracking/issues/669)
Better performance by caching regular expression
Time profiler shows that recreating NSRegularExpression gets expensive. I was seeing ~0.6% of main thread time spent on just creating the NSRegularExpression again and again.
> Cache regular expression used for markdown which increases performance

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListVC_Tests.swift
Resolves [ios-issues-tracking/42](https://github.com/GetStream/ios-issues-tracking/issues/42)
Related [ios-issues-tracking/669](https://github.com/GetStream/ios-issues-tracking/issues/669)
Fix channel list update skip logic when we are displaying messages instead
Track channel list's visibility with `viewWillAppear` and `viewWillDisappear`
We have a logic in place which tries to skip channel updates when user is in the message list instead. Since we use navigation controller, then after pushing the message list to the stack, channel list stays in the view hierarchy. Therefore, we can't check if channel list's window is nil. Instead, we should track it with `viewWillAppear` and `viewWillDisappear`.
Did some extra testing:
- UINavigationController: skipping happens
- UISplitViewController: …
> Skipping channel updates did not work when displaying message list

- StreamChat.xcodeproj/xcshareddata/IDETemplateMacros.plist
The new file header template has a trailing space which SwiftLint is not happy about
> Remove a space from the first comment line

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelVC.swift
- Sources/StreamChat/Workers/Background/AttachmentQueueUploader.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/Workers/Background/AttachmentQueueUploader_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/701
Adds parallel attachment uploading
- Fix back button in Demo App's message list
- Add parallel attachment uploading
Before, we were uploading the next attachment only when the current attachment finished uploading. This is not needed at all. We can start all uploads at the same time. 
https://github.com/GetStream/stream-chat-swift/assets/12814114/fad1dc36-20ff-4627-a83f-94c5e62dddd8
**Scenario 1**
2. Add a message with multiple attachments
3. All attachments should start uploading at the same time
**Scenario 2**
2. Add a message with multiple attachments
3. Add another message with multiple attachments
4. Both messages's attachments should uploading at the same time
> Add parallel attachment uploading

- CHANGELOG.md
- Sources/StreamChatUI/Gallery/ZoomDismissalInteractionController.swift
Will fix https://github.com/GetStream/stream-chat-swift/issues/2975
Fix UI getting blocked after swiping up the gallery view.
The issue is that a cancellation and a regular dismissal were happening at the same time, causing a race condition. A cancel was getting called twice, and with `completeTransition(true)`, causing the transition to finish when it should not.
2. Open a image attachment
3. Swipe up multiple times very fast until the gallery is dismissed
4. The UI should not be blocked
> Fix race condition when dismissing the gallery causing the UI to be blocked

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
- Sources/StreamChat/Controllers/DatabaseObserver/BackgroundListDatabaseObserver.swift
- Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/675
Resolves https://github.com/GetStream/ios-issues-tracking/issues/626
- Fix search showing empty data with background mapping enabled
- Fix channel list showing empty data for a split second with background mapping enabled
The root cause of Search not working correctly with background mapping is that when we call `state = .remoteDataFetched` after the HTTP Request, at this time, the items from the background observer are not yet populated. They are only populated when the FRC Notifies of changes, which because it is in a background thread, is an async process.  So, the `controller.messages` has empty data when the delegate event `didChangeState` is called. 
After trying multiple solutions, I think this one is the one …
> Fix controllers having empty data when state changed to .remoteDataFetched with background mapping enabled

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/Shared/Token+Development.swift
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- DemoApp/StreamChat/DemoAppCoordinator+DemoApp.swift
- DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/FakeTimer/FakeTimer.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/AuthenticationRepository_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
Related to https://github.com/GetStream/stream-chat-swift/issues/3030
Resolves https://github.com/GetStream/ios-issues-tracking/issues/740
Fix token provider keeps retrying after calling disconnect.
- Changes the ChatClient to a singleton in the Demo App
- Add a way to disconnect the user in the Demo App, and not only logout
- Add a way to fake token refresh failures
- The token refresh details now accept a number of refreshes before it starts failing, so that we can fake token refresh failures.
- Fixes token provider retrying after calling disconnect
- Fixes connect user never completing when disconnecting in a middle of a retry
The reason this was happening was because whenever we disconnected, we didn't cancel the timers of the `AuthenticationRepository` so they kept running. 
1. Open …
> Fix token provider retrying after calling disconnect

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Errors/ErrorPayload.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/739
Related to https://github.com/GetStream/stream-chat-swift/issues/3032
Fix invalid token calling token refresh in an infinite loop
We were incorrectly triggering a token refresh whenever we received an invalid token. The token refresh should only be triggered when the token is expired. If a token is invalid, it is because of a programming error, so if we retry it, it will be in an infinite loop:
1. Get Token
2. Signature is Invalid
3. Refresh Token
4. Signature is Invalid
5. Go to 3.
With this change, if a token is invalid, we simply stop retrying, and a manual retry should be done. 
1. Open Demo App Configuration
2. Tap on tokenRefreshDetails
3. Add an invalid secret to the token
4. Open the app
5. The channel list fetch …
> Fix invalid token triggering token refresh in an infinite loop

- CHANGELOG.md
None
Forgot to add the new localisation key to the changelog. 
TODO: We need to add a danger warning in these cases.
> Add `message.edited` local key to CHANGELOG

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Errors/ClientError.swift
- Sources/StreamChat/Errors/ErrorPayload.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/754
Do not mark message as failed when server returns duplicated message error. This would cause an unrecoverable state, where the message would always be in failed state, even tho the message already exists on the server.
1. Setup Proxyman
2. Use Map Local to override sending a message:
```
Wildcard: `https://chat.stream-io-api.com/channels/messaging/*/message*`
Response:
HTTP/1.1 400 Bad Request
....
{"code":4,"message":"SendMessage failed with error: \"a message with ID b742eacb-be19-4cf5-91e2-0debd6ce72da already exists\"","StatusCode":400,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response","details":[]}
```
3. Send a message
4. It should not display the error icon 
5. Switch the error to …
> Do not mark message as failed when server returns duplicated message error

- .github/workflows/xcmetrics.yml
- fastlane/Fastfile
- Create a static benchmark
- Convert the number of hitches to float instead of int
- Fix an issue with zero division
- Bump timeout on GitHub Actions (sometimes there is a queue on Firebase)
> Add a static benchmark for xcmetrics

- Sources/StreamChat/StateLayer/ChatState+Observer.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- Sources/StreamChat/StateLayer/MessageState+Observer.swift
- Sources/StreamChat/StateLayer/MessageState.swift
- Sources/StreamChat/Utils/StreamCollection.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
Add `StreamCollection` which allows dynamically to change the internal base collection (to different types).
The new state layer uses `LazyCachedMapCollection` as the backing storage for items fetched from the database. Later, we would like to change it to a native Swift array. `StreamCollection` acts as the middle layer until this has happened allowing to change the base collection without requiring to make breaking changes to the public API layer. Ideally, the custom collection type is removed with one API breaking change, but this depends on when the new data flow lands.
> [ChatStateLayer] StreamCollection as opaque base collection wrapper

- StreamChatUITestsAppUITests/Tests/QuotedReply_Tests.swift
The scroll to bottom button does not appear because 20 messages are not enough for the screen size of an iPad.
> [CI] Quick fix for one E2E test on iPad

- Sources/StreamChat/Controllers/ChannelWatcherListController/ChatChannelWatcherListController.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatState+Observer.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
Support loading watchers for channels.
* Add `Chat.loadWatchers(with:)` (argument is `Pagination`, aligns with other platforms what support general pagination method)
* Add `Chat.loadNextWatchers(with:)` (convenience which uses pagination with an offset)
* Add `ChatState.watchers`
* Add `ChatState.hasLoadedAllWatchers` (`ChatChannelWatcherListController` does not have it but added it so that out pagination implementations have similar interfaces)
Follows along what we have in `ChatChannelWatcherListController` (pagination + watchers).
> [ChatStateLayer] Loading watchers for a channel

- Sources/StreamChat/ChatClient+Environment.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/Utils/StreamCollection.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
Add ChannelList and ChannelListState for actions and state when loading lists of channels with `ChannelListQuery`
* Adds actions and observable state support
* Does not include channel linking (will be a separate follow-up PR)
* Does not include tracking logic with SyncRepository (I have some ideas around it, will be a separate follow-up PR)
ChannelListUpdater makes the queries. ChatClient provides the factory method for creating the ChannelList objects. ChannelListState holds the state.
> [ChatStateLayer] ChannelList and ChannelListState

- Sources/StreamChat/ChatClient+Environment.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
*Merges to feature/chat-state-layer-channel-list-query*
Refetch channel list queries when syncing is triggered for the new chat state layer.
SyncRepository is keeping track of active ChannelListController objects (see [#1](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/ChatClient.swift#L45), [#2](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/Repositories/SyncRepository.swift#L129), [#3](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/Repositories/SyncOperations.swift#L103)). New ChannelList and ChannelListState objects should support the same functionality (resetting ends up fetching channels for the query and updating …
> [ChatStateLayer] Channel list query reset in SyncRepository

- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/Workers/EventObservers/EventObserver.swift
*Merges to feature/chat-state-layer-channel-list-query*
Add the linking and unlinking logic from ChannelListController to the new state layer.
* Listen to events and trigger the same linking and unlinking code paths
> [ChatStateLayer] Channel list linking and unlinking

- Sources/StreamChat/Extensions/Collection+Extensions.swift
- Sources/StreamChat/StateLayer/ChatState+Internal.swift
- Sources/StreamChat/StateLayer/ChatState+Observer.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- StreamChat.xcodeproj/project.pbxproj
Unread message and last read message lookup for ChatState
* Add `ChatState.lastReadMessage`
* Add `ChatState.firstUnreadMessage`
* Follows the rather complicated logic in [ChatChannelController](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/Controllers/ChannelController/ChannelController.swift#L1231)
* Added logic for taking account the message order
> [ChatStateLayer] Unread message and last read message

- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
Use fetch request for checking the changed channel is part of the channel list query
Fetch request avoids looping over the collection which is currently a `LazyCachedMapCollection` and looping would trigger loading each of the channel which can be expensive and wasteful.
> [ChatStateLayer] Use fetch request for channel list contains channel check

- DemoApp/StreamChat/Components/DemoChatMessageContentView.swift
Resolve https://github.com/GetStream/stream-chat-swift/issues/2983
Do not translate deleted messages in the DemoApp
2. Send a message
3. Translate it to Turkish
4. Soft-delete the translated message
- Message text is updated to "Message deleted"
- Message cell is disabled
> [DemoApp] Do not translate deleted messages

- Sources/StreamChat/Database/DataStore.swift
- Sources/StreamChat/StateLayer/ChatState.swift
Controllers conform to `DataStoreProvider` which requires that controller has `ChatClient` getter. New state layer does not capture `ChatClient` instances. Some of our UI code need these quick lookup methods the `DataStore` type defines.
Since the `DataStore` type itself if tied to `DatabaseContainer` and we are considering the possibility of not using CD as the only data source then it feels like it is better if the new layer does not expose `DataStore` directly. Maybe we just want to use in-memory array as a data source, then using this type makes it more complicated (I would need to inject data to it).
Therefore, proposing to just adding lookup methods on the new state …
> [ChatStateLayer] Local message lookup in chat

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/AppEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/EndpointPath+OfflineRequest.swift
- Sources/StreamChat/APIClient/Endpoints/EndpointPath.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/AppSettingsPayload.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Models/AppSettings.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Fixtures/JSONs/AppSettings.json
- Tests/StreamChatTests/APIClient/Endpoints/AppEndpoints_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/AppSettingsPayload_Tests.swift
Relates to https://github.com/GetStream/ios-issues-tracking/issues/757
Add a way to fetch the app settings. When connecting the user, it loads the app settings.
The app settings are useful to get file upload configurations, and we were missing it in the iOS SDK. This work is also going to be useful for implementing the new size limit in https://github.com/GetStream/ios-issues-tracking/issues/757.
Besides making the app settings request available to be called manually, we also load them whenever the user is connected, so that file upload limitations are available as soon as the user is connected.
It would be simpler if the backend just retrieved the app settings on the `connectUser` response since this would simplify the integration a lot. If the app settings call fails, we won't have the …
> Add `ChatClient.loadAppSettings` and `ChatClient.appSettings`

- DemoApp/Shared/StreamChatWrapper.swift
None
The goal is to fix the login logout flow in the DemoApp with the singleton approach. There were 2 issues:
1. We were logging out at the same time we removed the device. This would make the request for the removal of the device fail because the current user would not be available anymore. It would also cause a race condition, and we would have 2 current users at the same time, triggering an assertion in the StreamDevelopers scheme. 
2. When logging in to the user, we were connecting the user in a background thread, this would cause the channel list to be open before erasing the previous user, which would trigger an assertion in the StreamDevelopers scheme as well since we would also have 2 current users at the same time.
With this flow fixed, we also show customers how login/logout …
> Fix DemoApp's login-logout flow crashing in StreamDevelopers scheme

- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/UserList.swift
- Sources/StreamChat/StateLayer/UserListState.swift
- Sources/StreamChat/Workers/Background/NewUserQueryUpdater.swift
- Sources/StreamChat/Workers/UserListUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/UserListUpdater_Mock.swift
- Tests/StreamChatTests/Controllers/SearchControllers/UserListController/UserListController_Tests.swift
- Tests/StreamChatTests/Workers/UserListUpdater_Tests.swift
Add `UserList` and `UserListState` for representing `ChatUserListController` functionality in the new state layer
- Add `UserList`
- Add `UserListState`
- Add `ChatClient.makeUserList()`
Follows the same flow as we have for channel lists.
> [ChatStateLayer] UserList and UserListState

- Sources/StreamChat/StateLayer/ConnectedUser.swift
- Sources/StreamChat/Workers/UserUpdater.swift
*Merges to feature/chat-state-layer-current-user*
`ChatUserController` provides ways for muting and flagging users in all the channels. Add these functions to the `ConnectedUser` type.
> [ChatStateLayer] Add global user flagging and muting support

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Resolves https://github.com/GetStream/stream-chat-swift/issues/3099
Fix Message View not updated when new translations are added or removed.
N/A (At the moment we don't have a way to add multiple translations to a message in the DemoApp)
> Fix Message View not updated when new translations are added or removed

- Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/MessageSearch.swift
- Sources/StreamChat/StateLayer/MessageSearchState+Observer.swift
- Sources/StreamChat/StateLayer/MessageSearchState.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- Tests/StreamChatTests/Controllers/SearchControllers/MessageSearchController/MessageSearchController_Tests.swift
- Tests/StreamChatTests/Workers/ChannelMemberListUpdater_Tests.swift
Represent functionality in the `ChatMessageSearchController` in the new state layer. 
* Add `MessageSearch`
* Add `MessageSearchState`
Keep the internal setup the same where CoreData drives results although it is not ideal (ideally we want to drive it with API request only but we not currently ready for it)
> [ChatStateLayer] MessageSearch and MessageSearchState

- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/UserSearch.swift
- Sources/StreamChat/StateLayer/UserSearchState.swift
- Sources/StreamChat/Workers/UserListUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
Adds `UserSearchController` functionality to the new chat state layer.
- Add `UserSearch` and `UserSearchState` for representing the functionality in `ChatUserSearchController`
`ChatUserSearchController` does not really need CoreData support and it currently uses the store only for converting `UserPayload` > `ChatUser` (`UserPayload` is saved to CD as `UserDTO` and the DTO is converted to `ChatUser`). There is also complexity around `UserDTO` and `UserListQueryDTO`. Since we do not really need any CoreData storage here, there are no CoreDataLazy in `ChatUser`, it is possible map the `UserPayload` to `ChatUser` with one exception (`isFlaggedByCurrentUser`), I am proposing to …
> [ChatStateLayer] UserSearch and UserSearchState

- CHANGELOG.md
- DemoApp/Screens/MembersViewController.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MemberPayload.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Member.swift
- TestTools/StreamChatTestTools/Fixtures/JSONs/Member.json
- TestTools/StreamChatTestTools/Mocks/Models + Extensions/ChatChannelMember_Mock.swift
- TestTools/StreamChatTestTools/TestData/DummyData/ChatChannelMember.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/MemberPayload_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MemberModelDTO_Tests.swift
None
Expose `notificationsMuted` in `ChatChannelMember`. 
The value is true if the member has muted the channel. The property would probably be more clear if it was `hasMutedChannel`, but to keep it consistent with the backend and the other SDKs, we won't change it.
- Exposes `notificationsMuted` in `ChatChannelMember`
- Show Member Info when tapping on the channel member in the Demo App
https://github.com/GetStream/stream-chat-swift/assets/12814114/55f03b67-da7b-40f7-a7c8-1cc4f54e4bc8
1. Open the app with Han Solo
2. Mute a Channel
3. Open the app with Leia Organa
4. Open the same Channel
5. Tap on Debug icon
6. Tap on "Show Channel Member"
7. Tap on "Han Solo"
8. It should have `notificationsMuted` to `true`
> Expose `notificationsMuted` in `ChatChannelMember`

- Sources/StreamChat/ChatClient.swift
Add async variants to the `ChatClient` which return the new `ConnectedUser` instance.
> [ChatStateLayer] Async connect and disconnect in ChatClient

- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/StateLayer/Chat.swift
Remove capabilities checks as discussed during the tech meeting. We might revisit this in the future, currently it is really inconsistent.
> [ChatStateLayer] Skip capabilities

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
None
Invalid reaction scores are saved to the CoreData store.
- Seems like a type in `MessageDTO` when converting API response to `MessageDTO`
Add a test for reaction scores and counts and fix the reaction score saving.
> Invalid reaction scores were saved to CoreData store

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/Workers/EventNotificationCenter.swift
- Sources/StreamChat/Workers/EventSender.swift
Add functionality in `ChannelEventsController`, `EventsController`, and `ChatConnectionController ` to the new state layer.
* Add subscribe methods for channel events to `Chat`(related to `ChannelEventsController`)
* Add send custom event to `Chat` (related to `ChannelEventsController`)
* Add subscribe methods for client events to `ChatClient` (related to `EventsController`)
* Connection events use the same subscribe method in `ChatClient` (related to `ChatConnectionController`)
> [ChatStateLayer] Client, connection and channel events

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
Clean up the notification approach from the `SyncRepository`
> [ChatStateLayer] Sync repository channel list query tracking

- CHANGELOG.md
- DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
- Scripts/updateDependency.sh
- Sources/StreamChatUI/Appearance+Formatters/MarkdownFormatter.swift
- Tests/StreamChatUITests/Utils/DefaultMarkdownFormatter_Tests.swift
Resolves https://github.com/GetStream/stream-chat-swift/issues/2908
Fix markdown-formatter customization accessibility
Make the required stuff in `SwiftyMarkdown.swift` publically accessible
- Open any sample project (e.g.: `iMessage`)
- Create a custom markdown-formatter (e.g.: `CustomMarkdownFormatter()`)
- Inherit it from `DefaultMarkdownFormatter()`
- Update `format(_ string: String)` (e.g.: `markdownFormatter.bold.fontName = "CourierNewPSMT"`)
- Implement custom markdown-formatter: `appearance.formatters.markdownFormatter = CustomMarkdownFormatter()`
- Open the app
- Send a message (e.g.: `**test**`)
> Fix markdown-formatter customization accessibility

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/778
Fix pinning message that contains attachments stuck in `sending` state.
When we pin a message, we set it as `pendingSync`so that the `MessageEditor` can pick it up. The problem was that pinning a message with attachments did not trigger any change in `MessageEditor`. The reason is that it was observing only attachments that had `localState == uploaded`, but if `localState == nil`, it also means that the attachments are uploaded and are available on the server. 
1. Send a message with attachment
2. Pin the message
3. It should be pinned and not stuck in pending state
> Fix pinning messages with attachments stuck in sending state

- Sources/StreamChat/Controllers/DatabaseObserver/StateLayerListDatabaseObserver.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Extensions/Result+Extensions.swift
- TestTools/StreamChatTestTools/Extensions/XCTest+Helpers.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ChannelListUpdater_Spy.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
* Add basic test coverage to `ChannelList`, `ChannelListState`, and `ChannelListState.Observer`
- New CoreDate observer which does not lag (otherwise `loadChannel` finished, but `ChannelListState.channels` were not updated)
- Various tests covering main uses-cases
> [ChatStateLayer] ChannelList tests

- CHANGELOG.md
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Tests/StreamChatTests/Database/DTOs/MemberModelDTO_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/785
Fix the member list not updated after the moderator is demoted.
At the moment, the backend does not fire any event to notify that a moderator has been demoted or promoted. So, if we have a moderator in the local DB that was demoted, it won't be removed from the local DB, so it will never be deleted. 
Even if the backend does not fire any event, we should also make sure that when opening the member list for the first time, that we clear the cache, to make sure that removed members do not get included in the response.
Note: Make sure you have the latest update of `stream-cli` on your machine.
1. Add moderators to a channel through the CLI, example:
`stream-cli chat promote-moderators --type messaging --id 2884427A-E r2-d2 …
> Fix member list not updated after moderator is demoted

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Fix crash in channel list
We got a report that reconfigure cell triggered an assertion in Apple's code which led to a crash. After closer inspection the core issue is ChatChannelListVC.reloadChannels reentrancy.
Turn it off for now and enable it when we are properly handling reentrancy.
N/A
> Turn off cell reconfiguring in channel list

- Sources/StreamChat/Controllers/DatabaseObserver/StateLayerDatabaseObserver.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatState+Observer.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- Sources/StreamChat/StateLayer/ConnectedUserState+Observer.swift
- Sources/StreamChat/StateLayer/MemberListState+Observer.swift
- Sources/StreamChat/StateLayer/MemberListState.swift
- Sources/StreamChat/StateLayer/MessageSearchState+Observer.swift
- Sources/StreamChat/StateLayer/MessageState+Observer.swift
- Sources/StreamChat/StateLayer/MessageState.swift
- Sources/StreamChat/StateLayer/UserListState.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
Use the dedicated StateLayerDatabaseObserver in every state layer type
> [ChatStateLayer] Switch to StateLayerDatabaseObserver in the state layer

- Sources/StreamChat/Controllers/DatabaseObserver/ListDatabaseObserver.swift
- Sources/StreamChat/Controllers/DatabaseObserver/StateLayerDatabaseObserver.swift
- Sources/StreamChat/Utils/LazyCachedMapCollection.swift
Reduce copy paste code around LazyCachedMapCollection.
> [ChatStateLayer] Lazy cached convenience

- Sources/StreamChat/Controllers/DatabaseObserver/StateLayerDatabaseObserver.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Extensions/Task+Extensions.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/ConnectedUserState+Observer.swift
- Sources/StreamChat/StateLayer/MessageState+Observer.swift
- Sources/StreamChat/StateLayer/MessageState.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/TestData/DummyData/MessageReactionPayload.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StateLayer/MessageState_Tests.swift
- Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
- Basic test coverage for MessageState
- Tests for MessageState
- Changed database observer to react more quickly (I saw that it switched to global executor and then to main when it was not needed)
- Changed the DB read method to use the same state layer context
> [ChatStateLayer] DB observing improvements & tests for MessageState

- Sources/StreamChat/Query/Sorting/UserListSortingKey.swift
- Sources/StreamChat/StateLayer/UserSearch.swift
- Sources/StreamChat/StateLayer/UserSearchState.swift
- Tests/StreamChatTests/StateLayer/UserSearch_Tests.swift
User search did not work at all
> [ChatStateLayer] User search results were incorrect

- Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
Fix flaky DB-related unit tests on older iOS versions
> Bump timeout for DB tests on older iOS versions

- Sources/StreamChat/StateLayer/ConnectedUserState+Observer.swift
- Sources/StreamChat/StateLayer/ConnectedUserState.swift
- Sources/StreamChat/Workers/CurrentUserUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/CurrentUserUpdater_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/UserUpdater_Mock.swift
- Tests/StreamChatTests/StateLayer/ConnectedUser_Tests.swift
- Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
> [ChatStateLayer] Add test coverage for ConnectedUser

- .swiftformat
- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/ChannelListState.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- Sources/StreamChat/StateLayer/UserList.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/ChannelList_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/Chat_Mock.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StateLayer/UserList_Tests.swift
Make all the factory methods synchronous and add `get()` to `Chat` for triggering the server sync
- Factory methods are sync
- `Chat` has `get(watch:)` for triggering server sync which retrieves `cid` if required
- Chat does not have non-optional access to `cid`
- Requires changes how we set up dependencies and observing when `cid` changes
> [ChatStateLayer] Sync factory methods and get()

- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/MemberList.swift
- Sources/StreamChat/StateLayer/MessageSearch.swift
- Sources/StreamChat/StateLayer/UserList.swift
- Sources/StreamChat/StateLayer/UserSearch.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/ChannelList_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/Chat_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/MessageSearch_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/UserSearch_Mock.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StateLayer/MemberList_Tests.swift
- Tests/StreamChatTests/StateLayer/MessageSearch_Tests.swift
- Tests/StreamChatTests/StateLayer/UserList_Tests.swift
- Tests/StreamChatTests/StateLayer/UserSearch_Tests.swift
Rename pagination methods based on what we discussed:
- Use `more` instead of `next`
- Use `older` and `newer` instead of `previous` and `next` for messages
> [ChatStateLayer] Rename pagination methods and add new convenience methods

- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
After we added `get()` to Chat which resets `ChatState.messages` I realised that since we have `ChatState.members` and `ChatState.watchers` then it should also reset these as well. Otherwise users load 10000 members and there is no way to reset the whole state.
* `ChatState.members` is internally driven by `MemberList`, therefore I need to make sure we associate channel payload members with `ChannelMemberListQuery`. 
* Watchers needs to be reset before channel payload is saved
> [ChatState] Reset watchers and members in Chat when triggering get()

- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/Workers/Background/AttachmentQueueUploader.swift
- Sources/StreamChat/Workers/Background/MessageEditor.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatStressTestPlan.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
- Tests/StreamChatTests/Workers/Background/MessageEditor_Tests.swift
- Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Cover methods which use the waitForAPIRequest approach.
> [ChatStateLayer] Tests for waitForAPIRequest methods

- Sources/StreamChat/Workers/MessageUpdater.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
[Crash] Double completion handler: open giphy and cancel
> [ChatStateLayer] Send message action assertion on cancel

- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/Controllers/ChatChannelListController_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/AuthenticationRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/MessageRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/OfflineRequestsRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/SyncRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/VoiceRecording/MockAVURLAsset.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/VoiceRecording/MockAppStateObserver.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/VoiceRecording/MockAudioSessionConfigurator.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/AttachmentUploader_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/CDNClient_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ChannelListUpdater_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ChatChannelController_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ConnectionDetailsProviderDelegate_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/Logger_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/RequestDecoder_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/RequestEncoder_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/RetryStrategy_Spy.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/Spy.swift
- Tests/StreamChatTests/Audio/StreamAppStateObserver_Tests.swift
- Tests/StreamChatTests/Audio/StreamAudioRecorder_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
I keep seeing tests failing randomly and mostly seems to be related to reading the state from the `Spy` protocol.
> [ChatStateLayer ] Use thread-safe storage for Spy protocol

- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Depending on the message's localMessageState we need to wait in different workers
> [ChatStateLayer] Wait depends on the localMessageState

- CHANGELOG.md
- Sources/StreamChat/Database/DatabaseContainer.swift
Make sure that changed managed object contexts do not trigger adding new data in `removeAllData`
In the state layer branch we have a case where channel was not properly deleted on logout. That branch also has additional managed object context which is aggressively merging changes from other contexts (this seems to be related).
1. Log in with A
2. Open channel with A and B
3. Logout and log in with B
4. Open channel with A and B → issue happens (assert telling multiple ChannelDTOs for the same cid)
Reset contexts when we logout for making sure we discard any active changes and do not try to save them when later the code path calls `writableContext.save`.
From: `feature/chat-state-layer`
Follow the steps above.
> Discard any changes before we delete the persistent state

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/809
Make `ChatMessageContentView` open so that it can be overridable by customers.
N/A
> Make  `ChatMessageContentView.prepareForReuse()` open

- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/StateLayer/MemberList.swift
- Sources/StreamChat/StateLayer/MemberListState.swift
- Sources/StreamChat/StateLayer/ReactionList.swift
- Sources/StreamChat/StateLayer/ReactionListState+Observer.swift
- Sources/StreamChat/StateLayer/ReactionListState.swift
- Sources/StreamChat/Workers/ReactionListUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/TestData/DummyData/MessageReactionPayload.swift
- Tests/StreamChatTests/StateLayer/MemberList_Tests.swift
- Tests/StreamChatTests/StateLayer/ReactionList_Tests.swift
Add `ReactionList` for querying reactions using a filter.
> [ChatStateLayer] Add ReactionList

- CHANGELOG.md
- Sources/StreamChat/Utils/Cached.swift
- Tests/StreamChatTests/StreamChatStressTests/Cached_StressTests.swift
Resolves [ios-issues-tracking/805](https://github.com/GetStream/ios-issues-tracking/issues/805)
Fix issues related to `computeValue` callback in `@Cached`
* Do not call `computeValue` from the closure passed into `mutate` since it can trigger side-effects leading to crashes
* If multiple threads are accessing the property at the same time, and the cached value is nil, we might run `computeValue` multiple times. Old: `computeValue` was always called once, but in rare cases crashed.
* If cached value is nil, we now need to acquire a lock twice (first: reading the current value, second: setting a new value fetched from `computeValue`). Old: lock was acquired once, but in rare cases crashed.
The `computeValue` callback which is passed into mutate's closure (locked region) can trigger …
> Fix crash in @Cached property value when computeValue was called

- CHANGELOG.md
- Sources/StreamChat/APIClient/RequestDecoder.swift
- Tests/StreamChatTests/Errors/ClientError_Tests.swift
Relates to https://github.com/GetStream/ios-issues-tracking/issues/800
Do not retry rate-limited requests.
The requests will 100% fail, so it does not make sense to retry them. 
1. Open Proxyman
2. Use the rewrite tool
3. Select one of the requests to rewrite
4. Change the status code to: `HTTP/1.1 429 Too Many Requests`
5. Change the response to:
```
{
"StatusCode": 429,
"code": 0,
"details": [
0
],
"duration": "string",
"exception_fields": {
"additionalProp1": "string",
"additionalProp2": "string",
"additionalProp3": "string"
},
"message": "string",
"more_info": "string"
}
```
6. When the response fails, it should not retry.
> Do not retry rate-limited requests

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Utils/ThreadSafeWeakCollection.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/Utils/ThreadSafeWeakCollection_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/800
Fix having duplicated watching channel calls after reconnection logic.
Context: Whenever we reconnect, if the user is watching channels, we track these channels and re-watch them. 
This was because we were incorrectly adding a channel controller to `activeChannelControllers` whenever we created a controller. This is wrong; we should only add it when we call synchronize or start watching a channel. Only in this scenario do we need to track a channel. 
Besides this, we did not control whether we already had a channel in the `activeChannelControllers`. So, there were cases where we had duplicated active channel controllers, and whenever a reconnection happened, it would trigger duplicated watch calls.
Lastly, even if a …
> Fix duplicated watching channel calls when reconnecting

- CHANGELOG.md
- Sources/StreamChat/Repositories/SyncRepository.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/792
Fixes trying to sync more than 255 channels at the same time. (Backend limit)
Changes the limit to 250, and it should be more than enough. At most, customers will have about 100 active channels at the same time, and even then, it wouldn't be a big deal if all channels where not synced. Only the most recents are important, and eventually, they will be refetched anyways. 
The reason we could hit 255+ channels syncing is that we never erase the channels from the DB; we just unlink them from the queries. So, there could be a case where a user could have more than 255 channels in their local DB, with really old channels. 
N/A
> Only sync at most 250 channels at the same time

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Resolves [ios-issues-tracking/790](https://github.com/GetStream/ios-issues-tracking/issues/790)
Enable cell reconfiguring and guard against reentrancy which led to an assertion in Apple's code/
* Enable cell reconfiguring in channel list which makes it much faster
* Guard against reentrancy which can happen if reconfigure cells call ends up triggering Core Data store change which is then picked up by database observers (and leads to calling reloadChannels again)
Exploratory testing:
Open channel list and trigger channel list changes (e.g. new messages arriving)
> Improve channel list performance by enabling reconfigure cells

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/777
Related to https://github.com/GetStream/stream-chat-swift/issues/3089
Fix marking a channel read even after the user has left the channel view.
This could happen in a case where the user left the channel view, but the debouncer would still trigger a request to markRead.
Now, when the user leaves the channel view, we cancel the throttler.
Follow steps of https://github.com/GetStream/stream-chat-swift/issues/3089
> Fix marking channel read after leaving channel view

- .swiftlint.yml
We have SwiftLint's warning about function length going on for some time. We either bump the threshold or turn it off completely.
> Increase the function_body_length rule's warning from 120 to 150

- Sources/StreamChat/Database/DTOs/PollVoteDTO.swift
- Tests/StreamChatTests/Repositories/PollsRepository_Tests.swift
`Poll.latestAnswers` contained non-answer for a brief moment of time.
> Do not add non-answer to poll's latestAnswers

- Sources/StreamChat/Database/DatabaseContainer.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
Fix warnings like these in unit-tests:
```
Warning:  	 'UserListQueryDTO' (0x60000b5714a0) from NSManagedObjectModel (0x6000024e3a20) claims 'UserListQueryDTO'.
Error: -11 07:06:27.705004+0000 xctest[13294:90482] [error] warning:  	 'UserListQueryDTO' (0x60000b5718c0) from NSManagedObjectModel (0x6000024ada90) claims 'UserListQueryDTO'.
```
Allow creating the managed object context model only once
> Fix Core Data model warnings in unit-tests

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
Resolves [ios-issues-tracking/issues/855](https://github.com/GetStream/ios-issues-tracking/issues/855)
Channel membership can contain invalid notifications_muted value at the moment which was overriding correct data in channel members.
N/A
> Fix notifications muted state for the current user in channel members

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/862
Fixes `channel.pinnedMessages` not containing the whole data from the server.
The logic was incorrect. We were removing the pinned messages from `channel.pinnedMessages` if they already existed in the array. This is wrong. It should only be removed if they are not pinned anymore.
Not required. Covered by unit tests.
> Fix `channel.pinnedMessages` with missing messages

- DemoApp/Shared/DemoUsers.swift
- StreamChatUITestsApp/StreamChat/User.swift
- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
- StreamChatUITestsAppUITests/Tests/Performance/ChannelListScrollTime.swift
- TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
- Fix Performance tests that rely on a stable and filled-in channel list
- Added an option to switch API keys in the tests
> Add an option to switch API keys in the tests

- Sources/StreamChat/Database/DatabaseContainer.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
test_loadReplies_whenIsFirstPage_shouldClearCurrentMessagesExcludingLocalOnly sometimes fails on CI with 
```
XCTAssertEqual failed: ("1") is not equal to ("3")
[07:04:25]: ▸ Test Case '-[StreamChatTests.MessageUpdater_Tests 
```
I think it is related to timing in that test where we modify data using writableContext and then expect DTOs created using the view context to update immediately.
* Read data from DB every time when asserting
* Add convenience read methods
> [CI] Random test failure with test_loadReplies_whenIsFirstPage_shouldClearCurrentMessagesExcludingLocalOnly

- CHANGELOG.md
- DemoApp/Screens/UserProfileViewController.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/StateLayer/ConnectedUser.swift
- Sources/StreamChat/Workers/CurrentUserUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/CurrentUserUpdater_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/UserPayloads_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/UserEndpoints_Tests.swift
- Tests/StreamChatTests/StateLayer/ConnectedUser_Tests.swift
- Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
Resolves [ios-issues-tracking/issues/867](https://github.com/GetStream/ios-issues-tracking/issues/867)
Allow changing current user's role
* Add `role` argument to user update events
* Add `privacySettings` to `CurrentUser`'s user update method (state layer)
* Remove default values from `CurrentUserUpdater` for forcing to fix all call sites
1. Log in with user and open profile
2. Tap on the "Upgrade" button for changing the user role from `user` to `admin`
3. Logout and login with the same user
4. Observe that the profile shows update user role
> Add role argument to partial user updates

- CHANGELOG.md
- Sources/StreamChat/Config/StreamRuntimeCheck.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StreamChatStressTests/CoreDataLazy_StressTests.swift
- Tests/StreamChatTests/Utils/LazyCachedMapCollection_Tests.swift
Resolves [ios-issues-tracking/issues/863](https://github.com/GetStream/ios-issues-tracking/issues/863)
Set background mapping default to true.
> Turn on background mapping

- DemoAppPush/NotificationService.swift
Related [ios-issues-tracking/issues/872](https://github.com/GetStream/ios-issues-tracking/issues/872)
When notification extension downloads an image without path extension, UNNotificationAttachment creation fails. Just fallback to jpeg if not set.
Example is google maps and static links to maps.
> [Demo app] Fallback to jpeg path extension if the downloaded file does not specify it

- CHANGELOG.md
- Sources/StreamChat/Repositories/MessageRepository.swift
Resolves [ios-issues-tracking/issues/872](https://github.com/GetStream/ios-issues-tracking/issues/872)
Force load attachments in push notification extensions since discard changes would remove them.
N/A
> Fix message attachments returning nil sometimes in push notifications

- StreamChat.xcodeproj/project.pbxproj
Resolves https://stream-io.atlassian.net/browse/PBE-5021.
Our demo app didn't build on iOS 18 / Xcode 16 beta, because of an old Sentry dependency.
> Updated Sentry dependency

- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Extensions/FileManager+Extensions.swift
- TestTools/StreamChatTestTools/Extensions/Unique/URL+Unique.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/DatabaseContainer_Spy.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Tests/StreamChatTests/Controllers/PollsControllers/PollController_Tests.swift
- Tests/StreamChatTests/Controllers/PollsControllers/PollVoteListController_Tests.swift
- Tests/StreamChatTests/Controllers/SearchControllers/UserController/UserController_Tests.swift
- Tests/StreamChatTests/Controllers/SearchControllers/UserListController/UserListController_Tests.swift
Resolves [PBE-4302](https://stream-io.atlassian.net/browse/PBE-4302)
* Use in-memory database for tests except performance tests (faster, less errors with SQLite).
* Fix skipped channel list tests
* Fix unstable tests what appeared after background mapping is the default (we need to wait delegates since updates have a delay)
[PBE-4302]: https://stream-io.atlassian.net/browse/PBE-4302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Always use in-memory database in tests

- TestTools/StreamChatTestTools/TestData/DummyData/MessageReactionPayload.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Some tests failed randomly in last runs.
> Fix flakey tests due to using random reaction score and not waiting observers

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView+DiffKit.swift
ChatChannel and ChatMessage's equatable was changed for better SwiftUI SDK integration. DiffKit uses == for uniqueness by default. For reverting back to the old behaviour, we can override differenceIdentifier.
The case of opening the demo app avatars flashing and scroll target is incorrect.
> Use hash for differenceIdentifier after changing equatable

- DemoApp/Shared/DemoUsers.swift
- StreamChatUITestsApp/StreamChat/User.swift
- StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
- TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
Allow to easily switch API keys. Sometimes, the backend we are using for Development/Testing is busy, and we need to switch to another one.
1. Open the source code `DemoApp/Shared/DemoUsers.swift:8`
2. Set up the required API key. Currently there are three options: `frankfurt_c1` (UIKit Demo App), `francfurt_c2`, `us_east_c6` (SwiftUI Demo App)
3. Run the app
4. Login
> [DemoApp] Allow to switch API keys

- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Timing issues in typing indicator tests caused random CI failures.
> Typing indicator tests had timing issues

- Sources/StreamChatUI/ChatThreadList/ChatThreadListVC.swift
None. Spotted on QA Release.
Fix animation when opening the thread list. Because `hideBannerHeaderView` calls `layoufIfNeeded` on the table view, this causes the weird animation when opening the thread list. We don't need to call this on `setUp()`
Make sure white theme is enabled.
This should not happen:
https://github.com/GetStream/stream-chat-swift/assets/12814114/25aff309-5870-4542-b8e3-a0c14a479150
> Fix animation when opening thread list

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
- Sources/StreamChat/Controllers/DatabaseObserver/BackgroundListDatabaseObserver.swift
- Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
- Sources/StreamChat/Controllers/ThreadListController/ThreadListController.swift
- Sources/StreamChat/StateLayer/DatabaseObserver/StateLayerDatabaseObserver.swift
- Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
- Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
Related [PBE-4853](https://stream-io.atlassian.net/browse/PBE-4853)
Return items reflecting the current DB state when accessing observer's items while background mapping is still running.
- Synchronously fetch items (but reuse existing) if items are accessed while FRC's change is being processed.
- Remove `refreshItems` which was used a workaround for waiting background observer to finish processing
Background observers fetch initial items and process FRC changes using a queue. It is good for pushing the model mapping to a background thread but has a shortcoming if we need to access updated items before the queue has finished processing it.
Example is that I create a controller, call synchronize, and then in the completion want to access updated items. At that time the observer is …
>  Reliable access to database models while observer is processing database changes

- Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift
Support building and running tests with Xcode 16 beta.
> Xcode 16 fails to compile MessageDTO tests

- Tests/StreamChatTests/Controllers/PollsControllers/PollController_Tests.swift
- Tests/StreamChatTests/Controllers/PollsControllers/PollVoteListController_Tests.swift
DB observer supports for immediate DB reads now. Therefore, the more fragile path of waiting for delegate can be removed.
> Revert waiting for delegates in unstable polls tests

- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- DemoApp/Shared/Token+Development.swift
- DemoApp/StreamChat/Components/Banner/BannerShowingConnectionDelegate.swift
- DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
Related to https://stream-io.atlassian.net/browse/PBE-4780
Fixes the issues found in the Demo App from this [PR](https://github.com/GetStream/stream-chat-swift/pull/3303).
It is important to fix them in a separate PR, so that we can compare the new fixes vs the old implementation. Since showing the connection banner helps us understand the connecting state transitions.
N/A
> Fix Demo App Refresh Tokens + Connection Banner

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/Components.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5174
Add support for enabling message list animations as requested by some customers.
1. Login
2. Open a Channel
3. Send a message
4. Load more messages
5. No animations should be present
6. Logout
7. Go to configration screen
8. Enable animations
9. Repeat 2, 3, 4
10. Should have animations
> Add support for enabling message list view animations

- CHANGELOG.md
- DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift
- DemoApp/Shared/StreamChatWrapper.swift
- DemoApp/Shared/Token+Development.swift
- DemoApp/StreamChat/Components/Banner/BannerShowingConnectionDelegate.swift
- DemoApp/StreamChat/Components/DemoChatChannelListErrorView.swift
- DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
- Sources/StreamChat/APIClient/RequestDecoder.swift
- Sources/StreamChat/ChatClient+Environment.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Config/ChatClientConfig.swift
- Sources/StreamChat/Errors/ErrorPayload.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Sources/StreamChat/Utils/StreamTimer/ScheduledStreamTimer.swift
- Sources/StreamChat/WebSocketClient/ConnectionStatus.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatUITestsAppUITests/Robots/UserRobot.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/WebSocketClient_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/Background/ConnectionRecoveryHandler_Mock.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
- Tests/StreamChatTests/WebSocketClient/ConnectionStatus_Tests.swift
- Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
https://stream-io.atlassian.net/browse/PBE-4780
Add support for timing out reconnection.
SDK:
- Add an option to configure reconnection timeout
- Fix Channel List not hiding error view when data is available
- Fix not trying to connect if the network is not available (This can cause edge cases, according to Apple)
- Ignore network status since it is not reliable, even on the device sometimes network status is not returned correctly
- Fix invalid token errors considered as possible to reconnect
DemoApp:
- Fix the demo app not showing the connection bar
- Fixes fake token failures in the demo app not working
- Fix Demo App channel list error view animation
An alternative approach to https://github.com/GetStream/stream-chat-swift/pull/3302 uses a separate entity to control the timeout, …
> Add timeout support when connecting user

- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelListSearchVC.swift
Empty results view was shown for channel search (only the first time for search term X)
- Update view state when state and channel delegate is called.
Delegate call order changed in [PR:3305](https://github.com/GetStream/stream-chat-swift/pull/3305). Search view only updated empty view state when state delegate was called. ChatChannelListView on the other hand does this when channels and state change. The fix is to do the same in the search view.
1. Log out and log in (clears local state) (also set search to search for channels)
2. Search for "Re" > …
> Fix channel search view by refreshing the view state in both delegates

- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
* Fix test which had race between one instance deleting the local DB file and another instance reading it
> Unstable test_databaseContainer_removesAllData_whenShouldFlushOnStartIsTrue test

- CHANGELOG.md
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/ChatMessage.swift
Related to [PBE-5004](https://stream-io.atlassian.net/browse/PBE-5004)
* Reduce message and channel copies when calling `==`
Time profiler shows in the SwiftUI SDK that when doing `==` checks a lot of time is spent in making copies of messages and channels. Changing the `==` to use guard let takes away a lot of this overhead.
LazyCachedMapCollection's `==` is reduced from 118 ms > 11 ms  **>10** times improvement 
|  <img width="951" alt="Before" src="https://github.com/user-attachments/assets/68f65b42-04e3-48c8-a3de-c5e9fb48cdcd">   |  <img width="770" alt="After" src="https://github.com/user-attachments/assets/ad687756-a11a-46a0-a57d-bcf1c5a634ee">  |
None
[PBE-5004]: https://stream-io.atlassian.net/browse/PBE-5004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> Improve performance of ChatChannel and ChatMessage equality

- DemoApp/StreamChat/StreamChatWrapper+DemoApp.swift
- DemoApp/StreamRuntimeCheck+StreamInternal.swift
Quite often I would like to switch between logging levels and it is so much easier if I can use my development scheme for setting this value rather than making a code change which I can accidentally commit.
> Add environment value for injecting logging level for development 

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Database/DTOs/QueuedRequestDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Repositories/OfflineRequestsRepository.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/Workers/Background/MessageSender.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- Tests/StreamChatTests/Repositories/OfflineRequestsRepository_Tests.swift
- Tests/StreamChatTests/Workers/Background/MessageSender_Tests.swift
Resolves [PBE-4319](https://stream-io.atlassian.net/browse/PBE-4319)
Fix the issue of incorrect order of messages when multiple messages are in the pending send state and connection comes back.
- Forward queued messages to `OfflineRequestsRepository` for retrying on the next web-socket connect event (otherwise we have a race between it and `MessageSender`). Message statuses are set to `.sendingFailed`.
- When `MessageSender` is waiting for connection, it sends all the requests to the offline repository until it is notified connection status change (ensures that `MessageSender` and `OfflineRequestsRepository` are not sending messages for the came channel at the same time).
- `OfflineRequestsRepository` removes duplicate send message requests (in case or manual retries while offline) …
> Fix a rare issue with incorrect message order when sending messages offline

- .github/workflows/cron-checks.yml
- .github/workflows/sdk-performance-metrics.yml
- .github/workflows/sdk-size-metrics.yml
- .github/workflows/smoke-checks.yml
- fastlane/Fastfile
Resolve https://stream-io.atlassian.net/browse/PBE-4314
> [CI] Comment SDK size on every commit

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Filter.swift
- Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/Query/Sorting/ChannelListSortingKey_Tests.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5351
- Expose `.hasUnread` channel list filter option
- Fix sorting channel list by unread count
In order to support automatic filtering, I had to add a new property to `ChannelDTO.currentUserUnreadMessagesCount` which is computed from `ChannelDTO.reads`. Otherwise, it was not possible to create an NSPredicate out of `ChannelDTO.reads`.
By adding this property, we can now make the sorting of unreadCount work properly, which was not working before as well. 
Usage: `ChannelListQuery(filter: .hasUnread)`
Demo:
https://github.com/user-attachments/assets/23848a8b-781f-4f35-9eaa-64943388bd2a
**Requirements:** Use the SwiftUI API Keys. (The `hasUnread` is not working on the default keys)
1- Login
2- Tap on filters button (right top corner)
3- …
> Add Channel List `.hasUnread` filter

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelSearchVC.swift
- Sources/StreamChatUI/ChatChannelList/Search/ChatMessageSearchVC.swift
Message search results were empty after logging in and quickly typing a search term 
- Reload collection view on state change and update UI state on messages array change
1. Logout and login for clearing local DB
2. Quickly type a search term like "tes"
> Fix message search not showing results for new search terms

- CHANGELOG.md
- Sources/StreamChat/Database/DatabaseContainer.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Resolves [PBE-4309](https://stream-io.atlassian.net/browse/PBE-4309)
Fix crashes on logout related to local database access
- Notify `NSManagedObjectContext` that data was [deleted on the SQL level](https://developer.apple.com/documentation/coredata/nsbatchdeleterequest)
- Discard any `DatabaseContainer` write requests while clearing local data
Batch delete removes data on the SQL level and does not notify contexts. Contexts can be left into invalid state if we do not manually notify them.
Repeat
1. Log in
2. Do something
3. Log out
No crashes or any other odd things should appear.
[PBE-4309]: https://stream-io.atlassian.net/browse/PBE-4309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix rare crashes when deleting local database content on logout

- CHANGELOG.md
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- TestTools/StreamChatTestTools/SpyPattern/QueueAware/UserController_Delegate.swift
- Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Tests/StreamChatTests/Controllers/MemberListController/MemberListController_Tests.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
- Move last controller properties to background database observers which reduces main thread usage
User background observers for:
- `CurrentUserController.currentUser`
- `ChatChannelMemberListController.members`
- `ChatMessageController.message`
These controllers did not use background observers because at that time background observers did not support fetching its state immediately. This was added in [PR:3305](https://github.com/GetStream/stream-chat-swift/pull/3305).
Exploratory testing around mentioning users, interacting with messages using the context menu
> Use background database observers for remaining controller properties

- CHANGELOG.md
- Sources/StreamChat/Utils/MulticastDelegate.swift
- Tests/StreamChatTests/Utils/MulticastDelegate_Tests.swift
Resolves [PBE-5434](https://stream-io.atlassian.net/browse/PBE-5434)
Make `MulticastDelegate` thread-safe
We got a report of crashes in the MulticastDelegate what point at multi-threading issues..
```
Fatal Exception: NSGenericException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  CoreFoundation                 0x18220c -[__NSSingleObjectEnumerator init]
3  Foundation                     0x29284 -[NSConcreteHashTable countByEnumeratingWithState:objects:count:]
4  Foundation                     0x291f8 -[NSConcreteHashTable allObjects]
5  <Redacted>                      0x87dd44 specialized MulticastDelegate.mainDelegate.getter
6  <Redacted>                       0x87f570 specialized …
```
> Fix crash in MulticastDelegate caused by concurrent accesses

- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
Resolves [PBE-5422](https://stream-io.atlassian.net/browse/PBE-5422)
Fix issues around database read wrappers and context resets
- One DatabaseContainer read uses DatabaseSession, the async one NSManagedObjectContext > unify to use DatabaseSession
- Fix and issue where after logout contexts are not reset (keep referencing deleted objects)
- Change the read assert to trigger only based on counts (did not find a way how to fix the issue of it keeping tracking deleted objects)
Case 1:
Log in and log out
Case 2:
1. Open Demo Configuration Screen
2. Enable Hard Delete Message
3. Open a channel
4. Hard delete a message
5. Go to background
6. Wait 1min ( or as soon as web-socket's disconnect is logged)
7. Open the app again
8. :boom: 
[PBE-5422]: …
> Improve database container read and reset

- CHANGELOG.md
- Sources/StreamChat/ChatClient+Environment.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Config/StreamRuntimeCheck.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/StateLayer/ChannelList.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Controllers/ChatChannelListController_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/SyncRepository_Mock.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
- TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
- Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
Resolves [PBE-4293](https://stream-io.atlassian.net/browse/PBE-4293)
Resolves [stream-chat-swift/issues/2021](https://github.com/GetStream/stream-chat-swift/issues/2021)
Allow regular API calls to be made while offline sync is running which gives quicker UI updates when UI update requires API call to finish.
- Add a sync v2 implementation controllable with a `StreamRuntimeCheck._isSyncV2Enabled`
Adds a new version of the offline state sync which only pauses regular API requests when handling automatic retries. The sync is more lightweight and only syncs currently active channels (active = server state has been requested in this session aka calling synchronize). If sync is not possible (too many events), then data is fully refreshed for active channel lists (same as synchronize but not …
> Run offline state sync in the background

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Resolves [PBE-5497](https://stream-io.atlassian.net/browse/PBE-5497)
Reduce CPU usage caused by recreating `CurrentChatUserController` when sending typing events
* Add `ChatClient.UserSession` for reusing objects from connect to logout
* User the shared `CurrentChatUserController` for reading privacy settings 
We check if we should send typing events using an internal property in the `ChatChannelController` which created a new instance of the `CurrentChatUserController`. This is called often when typing to a channel. This led to high CPU usage because controller is created and the local database is read on every character change. If the current user has, for example, a lot of muted channels, then recreating `CurrentChatUser` gets really expensive.
```swift
internal var …
```
> High CPU usage while typing

- Sources/StreamChat/Models/ChannelType.swift
- docusaurus/docs/iOS/common-content/reference-docs/stream-chat/models/channel-type.md
N/A
Reduce onboarding friction by ensuring documentation reflects current code state
The in-code documentation for custom channel types stated that channel types should only have "small letters", which is incorrect: the code itself allowed both lowercased and uppercased letters. Since channel types are case-sensitive, customers who create a channel type with uppercase letters who follow the "small letters" requirement in their iOS code will receive errors because their spelling of the channel type is incorrect.
Updated documentation to reflect the current code requirements
> Update channel type documentation to reflect allowed characters

- CHANGELOG.md
- Sources/StreamChat/Controllers/DatabaseObserver/BackgroundDatabaseObserver.swift
- Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
- Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
- Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
Resolves [PBE-5519](https://stream-io.atlassian.net/browse/PBE-5519)
- Enable reading the local database state within `synchronize()`'s completion block when the initial DB state was empty
- Remove the additional `OperationQueue` from the `BackgroundDatabaseObserver` (less latency)
- Process DB changes immediately on the managed context queue (less latency)
- Fix an issue where the initial observer state was set to empty although data was just written to the DB
- Fix a timing issue with will change callback what returned changed data (timing related)
`BackgroundDatabaseObserver` tries to load the initial state as soon as observing starts using a background thread (less blocking of the main thread). Since it is an async operation, there is a data race between loading the initial state and …
> Fix reading the local database state just after the initial write

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- TestTools/StreamChatTestTools/Fixtures/JSONs/Channel.json
- TestTools/StreamChatTestTools/TestData/DummyData/ChannelPayload.swift
- TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
- Tests/StreamChatTests/APIClient/Endpoints/Payloads/IdentifiablePayload_Tests.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Resolves: [PBE-5482](https://stream-io.atlassian.net/browse/PBE-5482)
Support the [pending messages](https://getstream.io/chat/docs/ios-swift/pending_messages/) moderation feature
- Parse `pending_messages` field in the channel response and store these messages along with regular messages to the `ChannelDTO.messages` 
If the pending messages feature is enabled, all the messages the current user sends, goes to a pending list. Backend needs to "commit" these messages and after committing, these messages become queryable for everyone in the channel. Until then, pending messages are only visible for the current user. Because we did not parse these messages from the payload before, coming back to the channel cleared the local storage (server sync) and all the pending messages were removed from …
> Store pending message along with regular messages

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/Endpoints/UserEndpoints.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/StateLayer/ConnectedUser.swift
- Sources/StreamChat/Workers/CurrentUserUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/CurrentUserUpdater_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/UserEndpoints_Tests.swift
- Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
Resolves: [PBE-5848](https://stream-io.atlassian.net/browse/PBE-5848)
Add `unset` argument to `CurrentChatUserController.updateUserData` and `ConnectedUser.update` for clearing user data fields
1. Log in with an user who has an image set
2. Open a channel and its debug menu: Reset User Image
Result: User's image is reset in the channel list (image in the top left corner)
[PBE-5848]: https://stream-io.atlassian.net/browse/PBE-5848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add unset argument to update user data

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
[PBE-5686](https://stream-io.atlassian.net/browse/PBE-5686)
Clear NSManagedObjectContext state when saving fails (e.g. validation errors)
- Clear changes in the writableContext when save fails
- Add better documentation about using multiple `ChatClient` instances
- Remove the canWriteData check because it does not help (serial queue)
- Add an error message when multiple ChatClient instances is detected
```
[ERROR] [main] [ChatClient.swift:270] [validateIntegrity()] > There are multiple ChatClient instances using the same `ChatClientConfig.localStorageFolderURL` - this is disallowed.
Either create a shared instance or make sure the previous instance of `ChatClient` is deallocated.
```
Resetting the context helps to clear invalid save state. 
N/A
[PBE-5686]: …
> Local database integrity

- CHANGELOG.md
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ChatState.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/State/Chat_Mock.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
Resolves: [PBE-5899](https://stream-io.atlassian.net/browse/PBE-5899)
* When channel is watched and web-socket reconnection happens, we should keep watching the channel
N/A
[PBE-5899]: https://stream-io.atlassian.net/browse/PBE-5899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Channel watching did not resume on web-socket reconnection

- CHANGELOG.md
- Sources/StreamChat/Query/Filter.swift
Resolves: [PBE-5681](https://stream-io.atlassian.net/browse/PBE-5681)
Deprecate slow filter operators
`Filter.notEqual` and `Filter.notIn` cause performance issues and are considered to be removed in the future.
N/A
[PBE-5681]: https://stream-io.atlassian.net/browse/PBE-5681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Deprecate `Filter.notEqual` and `Filter.notIn`

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/ModerationEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/Requests/FlagRequestBody.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/UserController/UserController.swift
- Sources/StreamChat/StateLayer/Chat.swift
- Sources/StreamChat/StateLayer/ConnectedUser.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/UserUpdater.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/UserUpdater_Mock.swift
- Tests/StreamChatTests/APIClient/Endpoints/ModerationEndpoints_Tests.swift
- Tests/StreamChatTests/StateLayer/Chat_Tests.swift
- Tests/StreamChatTests/StateLayer/ConnectedUser_Tests.swift
- Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
- Tests/StreamChatTests/Workers/UserUpdater_Tests.swift
Resolves: [PBE-5887](https://stream-io.atlassian.net/browse/PBE-5887)
Add missing `reason` and `extraData` arguments to flagging methods
- Add `reason` and `extraData` arguments to `ChatUserController.flag(reason:extraData:completion:)` and `ConnectedUser.flag(_:reason:extraData:)`
- Add `extraData` argument to `ChatMessageController.flag(reason:extraData:completion:)` and `Chat.flagMessage(_:reason:extraData:)`
- Add an internal `FlagRequestBody`
N/A
[PBE-5887]: https://stream-io.atlassian.net/browse/PBE-5887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add reason and extraData to flag user and extraData to flag message methods

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
- Sources/StreamChat/Query/Sorting/ChannelMemberListSortingKey.swift
- Sources/StreamChat/Query/Sorting/SortValue.swift
- Sources/StreamChat/StateLayer/UserSearchState.swift
- Sources/StreamChat/Utils/Codable+Extensions.swift
- Sources/StreamChat/Utils/Database/DatabaseItemConverter.swift
- Sources/StreamChat/Utils/Sequence+CompactMapLoggingError.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/Extensions/String+Date.swift
- TestTools/StreamChatTestTools/TestData/DummyData/UserPayload.swift
- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
- Tests/StreamChatTests/Query/Sorting/ChannelMemberListSortingKey_Tests.swift
- Tests/StreamChatTests/Query/Sorting/SortingValue_Tests.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
- Tests/StreamChatTests/StateLayer/MemberList_Tests.swift
- Tests/StreamChatTests/Utils/JSONDecoder_Tests.swift
- Tests/StreamChatTests/Utils/StreamJSONDecoder_Tests.swift
Resolves: [PBE-5993](https://stream-io.atlassian.net/browse/PBE-5993)
When sorting by key(s) with equal values the sort order in SDK models is kept unchanged
> Recommendation: Always try to add sorting criteria what contains one sorting key with unique values.
- Fix an issue where microseconds in timestamps were ignored causing channel list sorting to have many channels with the same `lastMessageAt` timestamp (triggers active reordering)
- Fix an issue where just sorting by `unreadCount` or other Int or Bool keys led to unexpected reordering in the channel list (many channels with equal sorting value). Break this by adding `updatedAt` sorting key internally.
- Fix an issue of runtime sorting (post FRC sorting used when FRC does not support sorting key) returning incorrect order
- Add …
> Sorting order in lists with equal sorting criteria

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- TestTools/StreamChatTestTools/SpyPattern/Spy/ChatChannelController_Spy.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
- Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
Invalid error log message was logged because we are actually not in the recovery mode in sync v2
N/A
> An error message about recovery request mode was incorrectly logged after web-socket connect

- CHANGELOG.md
- Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/SwiftyLineProcessor.swift
- Tests/StreamChatUITests/Utils/DefaultMarkdownFormatter_Tests.swift
Resolves [PBE-6131](https://stream-io.atlassian.net/browse/PBE-6131)
Crash when `---` is used in markdown
SwiftyMarkdown does not handle `---` correctly and caused a crash.
Send a message like
```
---
hi!
```
Result: no crash, `hi!` is rendered (not fully correct because SwiftyMarkdown removes `---`)
[PBE-6131]: https://stream-io.atlassian.net/browse/PBE-6131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix a crash with thematic breaks in markdown

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
- Sources/StreamChat/Workers/ChannelListLinker.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/SpyPattern/Spy/ChannelListUpdater_Spy.swift
- Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
- Tests/StreamChatTests/Workers/ChannelListLinker_Tests.swift
Resolves: [PBE-6097](https://stream-io.atlassian.net/browse/PBE-6097)
- Fix issues with linking a channel when dynamic filter is used
- Fix issues where web-socket event updates the channel and it was not linked to the current query (extra data changes in a way that it matches with the current query now, think about the custom pinning feature in the demo app)
- Revisit the whole web-socket event handling for linking and make sure we link only when after sorting, the changed channel would be part of the currently loaded channel list (makes sure we do not insert it when it is from unloaded pages and therefore would disturb pagination)
1. Launch two clients A and B
2. On the client B, A's user is added to a channel
Result: The channel appears in the A's channel list
1. Launch two clients A …
> Linking and unlinking channels based on the loaded list of channels

- CHANGELOG.md
- Sources/StreamChat/Database/DatabaseContainer.swift
Resolves: [PBE-6035](https://stream-io.atlassian.net/browse/PBE-6035)
Try fixing rare crash on managed object context save
I learned that the rare crash we have seen on context save is related to Core Data failing to resolve constraint conflict (although I can't see how this could happen). NSManagedObjectContext has [refresh(_:mergeChanges:)](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506224-refresh) for forcing the context to fetch the persistent state and applying local changes. I would like to see if this resolves these rare cases.
> Merging the local values into object always succeeds, and never results in a merge conflict.
> You typically use this method to ensure data freshness if multiple managed object contexts share a single persistent store. You …
> Avoid rare optimistic locking failure by refreshing the object before saving

- TestTools/StreamChatTestTools/Extensions/String+Date.swift
Change `toDate()` not to use the shared ISO8601DateFormatter because it makes unit-tests to crash on iOS 13 and 14.
ISO8601DateFormatter is not marked as Sendable, therefore it does not seem to be thread-safe (at least on iOS 13 and 14). Maybe on iOS 15 and later it is because it did not crash there, not sure. But this change fixes crashes.
> Unit-tests were crashing on iOS 13 and 14 when toDate() was used

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
Resolves: [PBE-5549](https://stream-io.atlassian.net/browse/PBE-5549)
Fix an issue where unread messages divider did not appear on mark as unread
- Invalid unread message id was returned because of incorrect get message before implementation
We need to find a previous message from the message we are marking as unread. API requires the last read message, not the first unread message id. The sorting logic and limiting the fetch to 1 ended up returning the oldest loaded message instead (filter matches, let's say 25 messages before limiting to 1, but we picked the id from the wrong end of results). Due to that reason, MessageListVC tried to reload cell for an older message instead (reloading is needed for making the cell to show the unread messages divider).
| ------ | …
> Unread messages divider did not appear in the message list when marking unread

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCell.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5999
Fix an issue where the thread parent message would shrink after sending a thread reply and quickly scroll to the parent message.
The reason for the issue is that the decorator's views rely on showing and hiding the top and bottom stack views in `ChatMessageCell`, but when quickly scrolling, the message cell, since it has the same identifier as the regular reply, is reused and the decorators are not shown instantly and it requires a cell reload to re-calculate its size. 
Using our custom `ContainerStackView` fixes the problem since it relies on manually disabling and enabling constraints, which will re-calculate the cell's size.
Follow to the steps in https://stream-io.atlassian.net/browse/PBE-5999
> Fix UI glitch in thread parent message when sending a message and scrolling

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/EphemeralValuesContainer.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Extensions/KeyPath+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- TestTools/StreamChatTestTools/DatabaseModels/TestDataModel.xcdatamodeld/TestDataModel.xcdatamodel/contents
- TestTools/StreamChatTestTools/TestData/DummyData/UserPayload.swift
- TestTools/StreamChatTestTools/TestData/TestManagedObject.swift
- Tests/StreamChatTests/Database/DTOs/UserDTO_Tests.swift
- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Resolves: [PBE-6125](https://stream-io.atlassian.net/browse/PBE-6125)
Improve reliability and performance of resetting ephemeral values by using batch updates and skipping loading DTOs for **every** single object in the DB. There has been reports of crashes when loading all the DTOs in `resetEphemeralValues`.
- Use fetch request for resetting relationship properties (but fetch only what needed)
- Use batch update for resetting non-relationship properties
- Skip fetching every single DTO
Remove the convenience protocol for resetting values because it is not efficient and causes fetching all the objects just for resetting values (even when the type does not conform to the protocol). New approach is less flexible but better for performance and reliability.
Example from demo app after opening …
> Improve reliability and  performance of resetting ephemeral values

- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Fix an unstable test what has race between another write call and reading the database state.
> [CI] Unstable data container test

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
Fix warnings:
```
ChatClient.swift:584:54: Converting a value of type '(__shared sending Result<AppSettings, any Error>) -> ()' to type '(Result<AppSettings, any Error>) -> Void' risks causing data races; this is an error in the Swift 6 language mode
```
> [Swift6] Fix converting value causes data races warnings in Xcode 16

- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Utils/Codable+Extensions.swift
- Sources/StreamChat/Utils/Operations/AsyncOperation.swift
- Sources/StreamChat/Workers/EventNotificationCenter.swift
- Sources/StreamChatUI/StreamNuke/Internal/Operation.swift
Reduce warnings when building with Xcode 16:
- Class `XYZ` must restate inherited `@unchecked Sendable` conformance
> [Swift6] Fix unchecked sendable warnings in Xcode 16

- CHANGELOG.md
- Scripts/updateDependency.sh
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/StreamSwiftyMarkdown/SwiftyMarkdown/PerfomanceLog.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
Resolves: [PBE-6192](https://stream-io.atlassian.net/browse/PBE-6192)
Present `ChatChannelVC` quicker
- Reduce cell reloads after applying message list changes
- Skip duplicate `updateContent` call when creating the `ChatMessageContentCell`
`ChatMessageContentView` parses markdown and links which can get expensive. Reloading a cell repeats the parsing. This PR aims to reduce cell reloads. 
Measured with iPhone 12 Pro Max and 3 different channels using a separate sample app what just presents the `ChatChannelVC` in a sheet. Time spent by the main thread.
Channel with 25 simple messages with text. Negligible change here. **5-10%** faster.
| Criteria | Before | After |
| ----- | ------ | ----- |
| Main thread |  269 ms  |  251 ms  |
| Hang time | 297 ms  | 291 ms  |
Channel with complex …
> Improve performance of presenting ChatChannelVC

- CHANGELOG.md
- Sources/StreamChat/Repositories/SyncOperations.swift
- Sources/StreamChat/Repositories/SyncRepository.swift
- Tests/StreamChatTests/Repositories/SyncOperations_Tests.swift
- Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
Resolves: [PBE-6191](https://stream-io.atlassian.net/browse/PBE-6191)
Reduce channel list updates when opening a channel list while syncing is in progress
- Run channel list refresh before syncing events (`/sync`)
- Do not (again) fetch events for channels in the channel list (because these were just refreshed)
- Replace `Array` with `Set` in the context
Currently the sequence has been (historically), call the `/sync` endpoint first and then refresh channel lists. This can trigger an issue where events applied from the `/sync` endpoint trigger local database change (channels can reorder) and then a moment later the whole channel list is refreshed which might cause another reordering. This PR changes things around by first refreshing channel list and then calling /sync only for active …
> Reduce channel list updates when syncing

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/Search/ChatChannelSearchVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/Search/ChatChannelSearchVC_Tests.swift
None
Fixes watching channels when performing channel search.
N/A
> Do not watch channels when searching by channels

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatChannelList/ChatChannelListVC_Tests.swift
None. Found the issue when investigating https://stream-io.atlassian.net/browse/PBE-6291 for SwiftUI.
Fixes a rare case where the channel list won't update the state views if the view is not on the screen. (Example, creating a channel)
The issue was that when skipping the channel list rendering while the view is off-screen, we were not calling the update on the channel list state views, which caused the empty view to not disappear.
1- Open the Demo App
2- Login with Guest User
3- Create a DM Channel
4- Go back to the Channel List
5- The channel list should have the new channel and not the empty view.
> Fix channel list state views not updating when the view is not visible

- Sources/StreamChat/Query/Filter+ChatChannel.swift
None. The issue is easy to reproduce. 
Filter is mainly used in two cases:
1. Construct the payload of the request sent to Stream backend API.
2. Construct the predicate of the request sent to CoreData Database.
After creating a ChatChannelListController, the controller owns a query inside which is a filter. The filter is mix-used in the above two cases. 
On one hand, stream API supprt filtering extraData of channel. So user can defined their custom field via extension: 
```swift
extension FilterKey where Scope: AnyChannelListFilterScope {
static var customField1: FilterKey<Scope, Bool> { "customField1" }
static var customField2: FilterKey<Scope, String> { "customField2" }
}
```
and use it in this way:
```swift
extension ChannelListQuery {
static func custom(id: UserModel.ID) -> Self { …
```
> fix: avoid FALSEPREDICATE for user-defined FilterKey

- CHANGELOG.md
- Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Follow-up to [3482](https://github.com/GetStream/stream-chat-swift/pull/3482)
* Add tests and changelog entry to an external contribution
> Add tests and changelog entry for false predicate PR:3482

- StreamChat.xcodeproj/project.pbxproj
Leftover from my previous PR, we had docusaurus folder reference in the Xcode project.
> Remove docusaurus xcodeproj reference

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Tests/StreamChatTests/Database/DTOs/CurrentUserDTO_Tests.swift
Resolves [IOS-21](https://linear.app/stream/issue/IOS-21)
Cache `NSManagedObjectID` instead of the full `CurrentUserDTO` for increased reliability. 
- Cache `NSManagedObjectID` which is less susceptible to possible threading issues (although I haven't found out that his is actually the case, but something seems to have corrupted the DTO in rare cases)
We have seen a crash when NSManagedObjectContext's currentUser property is accessed which leads to a crash when the `user.id` is called. This PR tries to fix this issue by not keeping the DTO alive all the time and instead asking context to retrieve it instead of (which is not slow).
I measured the time taken for accessing the `currentUser` property and when all the call sites are combined, it was 1 ms.
Quick testing round of logging in and …
> Cache NSManagedObjectID instead of the CurrentUserDTO

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Workers/TypingEventsSender.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/TypingEventsSender_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Part of [IOS-558](https://linear.app/stream/issue/IOS-558)
Remove current user controller since it takes unnecessary CPU time when reacting to DB changes
- Replace internal current user controller with just reading the data directly
We had a perf issue some time ago where we used to create the `ChatCurrentUserController` every single time when checking for typing state (on each key press). Then we started to use a shared instance for that. Solved the issue, but there is one downside, reacting to current user changes can get expensive (e.g. current user has many muted channels which triggers recreating channel objects when updating the immutable `CurrentChatUser` type). Instead all of this, we should just read the data we need and skip controllers.
Try typing events, if disabled, should …
> Replace shared current user observer used for reading privacy settings

- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
Fix unstable test: test_loadPreviousReplies_whenMessagesAreEmpty_callDelegateWithEmptyChanges
Unstable because it is checking delegate call counts, but did not properly wait for the initial background observer callback. This caused a race between initial fetch and the second load replies call. Failure was reproducible when running the unit-test locally with the repeat option.
> Fix sometimes failing test_loadPreviousReplies_whenMessagesAreEmpty_callDelegateWithEmptyChanges

- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
`CurrentUserDTO.mutedUsers`'s deletion rule was changed from cascade to nullify. This in turn requires that relationships have the optional check enabled in the model, which we did not have the deletion rule change. This triggered the error. 
`
[ChatClient.swift:496] [logout(completion:)] > Logging out current user failed with error Error Domain=NSCocoaErrorDomain Code=134050 "Constraint trigger violation: Batch delete failed due to mandatory MTM nullify inverse on CurrentUserDTO/mutedUsers" UserInfo={NSExceptionOmitCallstacks=true, NSLocalizedFailureReason=Constraint trigger violation: Batch delete failed due to mandatory MTM nullify inverse on CurrentUserDTO/mutedUsers, _NSCoreDataOptimisticLockingFailureConflictsKey=(
)}
`
_Add relevant …
> Fix batch deleting current user while it has muted users attached to it

- CHANGELOG.md
- Sources/StreamChat/Controllers/DatabaseObserver/ListChange.swift
Resolves [IOS-569](https://linear.app/stream/issue/IOS-569)
Fix a crash caused by infinite loop in Core Data when converting models
- Delay converting models to the point of time when `NSFetchedRequestController` has finished reporting changes
We had an internal crash report which showed that Core Data change came in, triggered `NSFetchedRequestController` delegate, then we converted the DTO to a model type, but since the model type did another fetch request, this triggered the whole cycle again. Therefore, let's avoid it by delaying the model conversion to the point of time where `NSFetchedRequestController` has finished reporting changes.
Retrying the flow in IOS-569 which triggered it.
> Convert to models after NSFetchedResultsController finishes reporting changes

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Fixes https://linear.app/stream/issue/IOS-582
Fix Channel List search bar disappearing in rare cases. If the number of items was about 10, the channel list would be scrollable initially with the Search Bar shown. After scrolling to the bottom, the search bar would disappear, losing the scrollability.
The `alwaysBounceVertical` should be set to `true` so that the scrollability is never lost and the Search Bar reappears again. 
- Open the channel list with "General Grievous"
- It should have exactly 10 channels only in the Channel List
- Scroll to the bottom and up again
- Search bar should always be visible
> Fix Channel List search bar disappearing

- Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
These tests were not updated to include the waiting part ([PR:3502](https://github.com/GetStream/stream-chat-swift/pull/3502) made typing check asynchronous which now started triggering test failures)
> Fix unstable typing related tests in ChatChannelController_Tests

- CHANGELOG.md
- Sources/StreamChat/ChatClient+Environment.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Repositories/AuthenticationRepository.swift
- Sources/StreamChat/Repositories/ConnectionRepository.swift
- Sources/StreamChat/WebSocketClient/ConnectionStatus.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryHandler.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/AuthenticationRepository_Mock.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/WebSocketClient_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
- Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
- Tests/StreamChatTests/WebSocketClient/WebSocketClient_Tests.swift
- Tests/StreamChatTests/Workers/Background/ConnectionRecoveryHandler_Tests.swift
Fixes https://linear.app/stream/issue/IOS-78
Fixes the reconnection timeout handler not working in the token provider phase.
The main change is that the `reconnectionTimeoutHandler` was moved from the `ConnectionRecoveryHandler` to the `ChatClient` so that it can handle the token provider phase. For this to work, a couple of things required some changes. There are comments in the PR explaining each change.
Flow diagram to explain why we need to set the state to `.initialize` again whenever we call connect in `ChatClient`:
```mermaid
stateDiagram-v2
[*] --> ChatClient.init
ChatClient.init--> ChatClient.Connect
ChatClient.Connect --> TokenProvider
TokenProvider --> ReconnectionTimeout: Fails
TokenProvider --> WebSocket.Connect: Success
ReconnectionTimeout --> disconnected
disconnected --> …
```
> Fix reconnection timeout handler not working in the token provider phase

- fastlane/Fastfile
Removing `!` ensures that if there is no `-SNAPSHOT` postfix it won’t clean up the file.
> [CI] Fix release script

- Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
Fix unstable `AuthenticationRepository_Tests.test_reset()` where the reset internally uses `tokenQueue.async` call to set the `resetConsecutiveFailures` state, checking for `isGettingToken` just schedules `tokenQueue.sync` internally and therefore fixes the timing issue
> Fix unstable AuthenticationRepository_Tests.test_reset()

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/BackgroundTaskScheduler.swift
- Tests/StreamChatTests/WebSocketClient/BackgroundTaskScheduler_Tests.swift
Resolves: [IOS-43](https://linear.app/stream/issue/IOS-43/)
Make sure previous task is ended when begin task is called immediately.
There have been cases where background tasks are not ended correctly. Although I haven't been able to reproduce this with the demo app, I did find one way to reproduce it. Involves calling begin task twice. Could it be that in some configurations this can happen, not sure.
> End previous background task as soon as begin task is called

- CHANGELOG.md
- Sources/StreamChat/Models/Member.swift
- Sources/StreamChat/Query/ChannelMemberListQuery.swift
- Sources/StreamChat/Query/Filter.swift
- Sources/StreamChat/Query/Sorting/ChannelMemberListSortingKey.swift
- Tests/StreamChatTests/Query/MemberListFilterScope_Tests.swift
- Tests/StreamChatTests/Query/Sorting/ChannelMemberListSortingKey_Tests.swift
Resolves: [IOS-605](https://linear.app/stream/issue/IOS-605/)
No way for filtering by `channel_role` and sorting by `channel_role` in member list queries.
- Add member list filtering keys: `FilterKey.channelRole` and `FilterKey.email`
- Add member list sorting key: `ChannelMemberListSortingKey.channelRole`
- Encode `MemberRole.member` as `channel_member` and `MemberRole.moderator` as `channel_moderator`
Example snippet for testing filtering and sorting (`chewbacca`)
```swift
let query = ChannelMemberListQuery(
cid: ChannelId(type: .messaging, id: "83100323-A"),
filter: .equal(.channelRole, to: .member),
sort: [.init(key: .channelRole)]
)
let memberList = self.makeMemberList(with: query)
do {
try await memberList.get()
let members = await memberList.state.members
print(members.count)
for …
```
> Add additional sorting filter keys for member list query

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListVC.swift
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Filter+ChatChannel.swift
- Sources/StreamChat/Query/Filter.swift
- Tests/StreamChatTests/Query/Filter_Tests.swift
Resolves [IOS-609](https://linear.app/stream/issue/IOS-609)
Enable filtering channel list with `$eq` and an array of channel member ids
- Add `FilterKey.members`
- Add support for `$eq` to match an array of values
Filtering by `members` supports `$in` and `$eq` operators. We did not expose the latter. For supporting it, some changes were required for enabling Core Data to match channels with `$eq` and an array of values.
1. Log in with `chewbacca`
2. Try different channel queries (R2-D2 Channels uses the new members equals query and returns all the channels where members equal to `current user` and `r2-d2`)
Example snippet
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(5)) {
Task {
let query = ChannelListQuery(filter: .equal(.members, values: ["chewbacca", …
```
> Add FilterKey.members and support for equal operator to match an array

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageReactionDTO.swift
- Sources/StreamChat/Database/DTOs/PollDTO.swift
- Sources/StreamChat/Database/DTOs/PollOptionDTO.swift
- Sources/StreamChat/Database/DTOs/ThreadDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Utils/Codable+Extensions.swift
- Tests/StreamChatTests/Utils/JSONDecoder_Tests.swift
Resolves: [IOS-610](https://linear.app/stream/issue/IOS-610)
- Improve performance of model conversion with more extreme use-cases (e.g. extra data is used a lot)
- Cache extra data because it can be large and makes JSONDecoder way too busy when DB changes occur
- Remove reading the model state from the persistent storage in DatabaseContainer.write because it degrades performance a lot (other managed object contexts need to refetch everything, affects row cache)
Demo user `Chewbacca` has 19 muted channels and has a channel named "Performance Testing" with 12 members where each of the member has extra data filled with 162 fields (nested data).
```swift
var myData = [String: RawJSON]()
for index in 0..<40 {
myData["extra_data_key_\(index)"] = .dictionary([
"timestamp": …
```
> Improve database model conversion performance by caching extra data and keeping row cache

- CHANGELOG.md
- Sources/StreamChat/Database/DataStore.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Tests/StreamChatTests/Database/DataStore_Tests.swift
Resolves [IOS-626](https://linear.app/stream/issue/IOS-626)
`DataStore` is public and therefore we should not have the main thread requirement which can be misused easily
* Force all thread data reads to the background context's queue
> Read data using a background context in the DataStore

- README.md
_Provide all Linear and/or Github issues related to this PR, if applicable._
> Updated the tutorial link for UIKit

- fastlane/Fastfile
Resolve https://linear.app/stream/issue/IOS-630
Resolve SwiftUI XCFramework compilation issue
Get rid of `SwiftUICore` in all `StreamChatUI`-related swiftinterfaces (inside xcframework)
- https://github.com/GetStream/apple-internal-testing-pipeline/actions/runs/12631550370/job/35193503476
> [CI] Resolve SwiftUI XCFramework compilation issue

- Sources/StreamChat/Models/AppSettings.swift
_Provide all Linear and/or Github issues related to this PR, if applicable._
> CocoaPods linting error

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
- Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/ChatMessageActionsVC_Tests.swift
Resolves IOS-187
Fix thread reply action shown when inside a Thread.
We need context in the Message Actions where the view is being presented. This was previously requested by other customers since this can be useful for other things. So now, whenever we present the message actions, we have a new boolean property that tells if the actions are being presented inside a thread or not.
1. Open a Thread
2. Long press the Parent Message
3. Should not show "Thread Reply Action"
> Fix thread reply action shown when inside a Thread

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/StateLayer/ChatClient+Factory.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/ConnectionRepository_Mock.swift
- Tests/StreamChatTests/ChatClient_Tests.swift
Resolves [IOS-655](https://linear.app/stream/issue/IOS-655)
Wait for current user data to be synced before accessing current user data in async connect methods.
Current user data comes with web-socket event. Therefore, it caused a data race between accessing the current user data and receiving the event. `CurrentChatUserController.synchronize()` uses the same mechanism of calling `provideConnectionId`. Most of the time this issue does not happen, but it can.
N/A
> Wait for current user data to be synced when connectUser() is called

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatThreadVC.swift
- Sources/StreamChat/Repositories/MessageRepository.swift
- Sources/StreamChat/WebSocketClient/Events/Event.swift
- Sources/StreamChat/WebSocketClient/Events/MessageEvents.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
- Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
- Tests/StreamChatTests/WebSocketClient/Events/MessageEvents_Tests.swift
Resolves https://linear.app/stream/issue/IOS-282/hard-delete-on-a-root-message-from-a-thread-is-broken
Fix the Thread not dismissing when the root message is hard deleted.
I've decided to implement this on the Demo App since hard deleting is an action that only exists on the Demo App. Usually, we do not advertise the feature much since it is not recommended.
Besides that, the logic will most likely differ depending on the app. So this is mostly app logic and not SDK logic.
Either way, while doing this, I spotted some bugs:
- The `ChatThreadVC.didReceiveEvent` delegate was always being called twice. This was due to the fact that we had `channelEventsController` and `eventsController` assigning both delegates to the `ChatThreadVC`
- The `MessageDeletedEvent` was not being surfaced to the …
> Dismiss thread when hard deleting root message

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/ListCollectionViewLayout/ListCollectionViewLayout.swift
Resolves [IOS-667](https://linear.app/stream/issue/IOS-667)
Fix exception of missing final attributes for supplementary view in the `ListCollectionViewLayout`
* Provide `layoutAttributesForSupplementaryView(ofKind:at:)` implementation
While looking at the exception the only idea I have is that could implementing `layoutAttributesForSupplementaryView(ofKind:at:)` help to resolve it. 
[layoutAttributesForSupplementaryView(ofKind:at:)](https://developer.apple.com/documentation/uikit/uicollectionviewlayout/layoutattributesforsupplementaryview(ofkind:at:)) documentation:
> If your layout object defines any supplementary views, you must override this method and use it to return layout information for those views.
I have not been able to reproduce this and therefore hard to know exactly why this …
> Fix missing final attributes for supplementary views exception

- Sources/StreamChatUI/CommonViews/ListCollectionViewLayout/ListCollectionViewLayout.swift
Caused by changes in #3570 
Fix an exception on logout
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b910c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180092da8 objc_exception_throw + 72
2   CoreFoundation                      0x000000018039e37c -[__NSArrayM getObjects:range:] + 0
3   UIKitCore                           0x000000018528e598 -[_UIFlowLayoutSection frameForItemAtIndexPath:] + 248
4   UIKitCore                           0x000000018527b3dc -[UICollectionViewFlowLayout _frameForItem:inSection:usingData:] + 100
5   UIKitCore …
```
> Exception when trying to access layout attributes for non-existent item

- TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
[IOS-682](https://linear.app/stream/issue/IOS-682/pass-bundle-into-databasecontainer-spy-in-streamchattesttools)
Allow passing in bundle when creating mocked ChatClient
* Other modules need to pass in different bundles for loading the Core Data model
> Do not ignore bundle when creating ChatClient mock

- CHANGELOG.md
- Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
https://getstream.zendesk.com/agent/tickets/61293
Expands `StreamAudioPlayer` to allow passing `AVURLAsset` options during initialisation.
> [Enhancement]Allow passing options on AVURLAsset init

- CHANGELOG.md
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
IOS-709
Fix the message transformer not being applied when editing a message.
N/A. Covered by unit tests.
> Fix message transformer not being applied when editing a message

- CHANGELOG.md
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
- Tests/StreamChatTests/Database/DTOs/ChannelDTO_Tests.swift
- Tests/StreamChatTests/Query/ChannelListFilterScope_Tests.swift
- Tests/StreamChatTests/Query/Sorting/ChannelListSortingKey_Tests.swift
Resolves: [IOS-687](https://linear.app/stream/issue/IOS-687)
Fix the issue where reordering happens when paginating with `ChannelListSortingKey.default`
* Turns out that we use incorrect remote key
The default sorting key backend uses is [last_updated](https://getstream.io/chat/docs/ios-swift/query_channels/), not `updated_at`. This caused reordering issues because channel list backend returns has different order.
Note how channels reorder when pagination happens.
|  ![img](https://github.com/user-attachments/assets/de4010da-45cf-43e6-81c7-c5858a460222)   |  ![img](https://github.com/user-attachments/assets/08d9e2e0-f111-4b13-9993-1ca8215799be)  |
Demo app sorts by pinned state and then uses default sorting (last message at or created at).
1. Create a …
> Fix default channel list sorting by replacing updated_at with last_updated

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/BackgroundTaskScheduler.swift
https://linear.app/stream/issue/IOS-653/
* Revert UIApplication accessor to use lazy var
We got a report that `IOSBackgroundTaskScheduler` has app property nil sometimes. It was changed in 4.74.0 from lazy var to let. I'll revert that change (can't reproduce this myself)
> Access UIApplication on demand in IOSBackgroundTaskScheduler

- CHANGELOG.md
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/StreamChatTests/Models/ChatChannel_Tests.swift
https://linear.app/stream/issue/IOS-728/polls-capability-handling
Expose the `channel.canSendPoll` capability and don't show Poll Creation in the composer.
Bonus: Also exposed `channel.canCastPollVote`. No UI was changed for this capability since there is no Official UI for this at the moment.
Next Step: SwiftUI
1. Open the Stream Dashboard
2. Disable poll ability in a channel
3. When opening the attachments, actions
4. Should not show poll creation
> Expose canSendPoll capability and handle it in the Composer

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
https://linear.app/stream/issue/IOS-699/[uikit]-image-uploading-fails-if-copy-pasted-from-the-app
Fix not able to send images with floating point numbers in the original size.
When pasting images with sizes that are not integers, the backend fails to accept them. 
Ideally, the backend should support this, but until then, we can round down the images that have floating-point numbers.
1. Open a Channel
2. Send a random image
3. Tap on the image
4. Tap on the left bottom icon (Share Icon)
5. Tap on Copy
6. Go to the composer
7. Paste the Photo
8. Publish the message
9. Should not error
> Fix not able to send images with floating point numbers in the original size

- CHANGELOG.md
- DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/StateLayer/ConnectedUser.swift
- Sources/StreamChat/Workers/CurrentUserUpdater.swift
- TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/CurrentUserUpdater_Mock.swift
- Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Tests/StreamChatTests/Workers/CurrentUserUpdater_Tests.swift
https://linear.app/stream/issue/IOS-803/unsetproperties-does-not-do-anything-in-current-user-controller
Fix `unsetProperties` not having any effect in `CurrentUserController.updateUserData()`.
- Fixes `unsetProperties` not doing anything in`CurrentUserController.updateUserData()`.
- Makes sure the current user updater does not have default values.
- Changes teamsRole parameter to use existing types.
1. Log in with a user who has an image set
2. Open a channel and its debug menu: Reset User Image
Result: User's image is reset in the channel list (image in the top left corner)
> Fix `unsetProperties` not having any effect in `CurrentUserController.updateUserData()`

- .github/workflows/testflight.yml
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
Align the workflow with StreamVideo ([related PR](https://github.com/GetStream/stream-video-swift/pull/787))
> [CI] Update TestFlight app version on manual uploading

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Tests/StreamChatUITests/SnapshotTests/ChatMessageList/ChatMessageListVC_Tests.swift
https://linear.app/stream/issue/IOS-809/swipe-to-reply-does-not-work-if-threads-are-disabled-in-the-dashboard
Fix swipe to reply enabled when quoting a message is disabled
1. Go to Stream Dashboard of UIKit Demo App
2. Go to Channel Types
3. Go to Messaging
4. Disable Quotes
5. Go to the Demo App
6. Swipe to reply in a message should not work
> Fix swipe to reply enabled when quoting a message is disabled

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Tests/StreamChatTests/Database/DatabaseSession_Tests.swift
Resolves bug found in https://linear.app/stream/issue/IOS-857
Fix message not marked as published on `message.new` event if it was previously intercepted.
In the `message.new` event, we do not mark the message as published, because we usually do it after the request is finished. In the interceptor use case, the request is not finished when it completes; it should rely on the `message.new` event instead. So, the goal of this PR is to mark the message as published whenever we receive `message.new` event in case it is not yet marked as published.
N/A. Covered by unit tests.
> Fix message not marked as published if it was previously intercepted
