GetStream/stream-chat-swift

Example/Sources/CustomChatViewController.swift
Example/Sources/DarkChannelsViewController.swift
Example/Sources/LoginViewController.swift
Example/Sources/Main.storyboard
Sources/Core/Client/BaseURL.swift
Sources/Core/Client/Client+Request.swift
Sources/Core/Client/Endpoint.swift
Sources/Core/Model/Channel+Requests.swift
Sources/Core/Model/Channel.swift
Sources/Core/Model/Event.swift
Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Request.swift
Sources/Core/Presenter/ChannelsPresenter.swift
Sources/UI/User Story/Chat/Cells/MessageTableViewCell.swift

- Hide channel with a clearing messages history parameter.
- Added the connection lost error to the logs.
- Example project updated.

Hide a channel with clearing messages history and `channel.hidden` event

---

CHANGELOG.md

Refactors styling to put more emphasis on Breaking Changes
Sorry for the bad branch name, I was trying to _not_ create another branch for this

Refactor CHANGELOG.md

---

.github/workflows/ci.yml

We'll gain ~10minutes with this

Add caching Carthage dependencies to CI

---

Sources/UI/Chat/Attachments/AttachmentPreview.swift

It took me whole yesterday & today to figure this out... But I've learned a lot about message attachments along the way :)

Fix video attachment actions are not recognized

---

StreamChatCoreTests/Unit Tests/ClientLoggerTests.swift

CI fails sometimes and we need more info to debug it.

Fixes ClientLogger unit tests and adds more info so debugging is easier

---

Sources/UI/Web View/WebViewController.swift

See https://stackoverflow.com/questions/58164583/wkwebview-with-the-new-ios13-modal-crash-when-a-file-picker-is-invoked
Fixes #66

Fixes WebView crashing when file picker is presented in a website

---

Sources/Core/Presenter/Channel Presenter/ChannelPresenter+EphemeralMessages.swift
Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Events.swift
Sources/Core/Presenter/ChannelsPresenter.swift
Sources/Core/Presenter/ViewChanges.swift
Sources/UI/Channels/ChannelsViewController.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift

Fixes message grouping issue for new messages

---

CHANGELOG.md
Sources/Core/Client/Uploader.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Sources/UI/Chat/Composer/ComposerView+Files.swift
Sources/UI/Chat/Composer/ComposerView+Images.swift
Sources/UI/ViewController+ImagePicker.swift
Sources/UI/ViewController.swift
StreamChat.xcodeproj/project.pbxproj

Fix allowing uploading files bigger than limit

---

CHANGELOG.md
Sources/UI/Web View/WebViewController.swift

Fix video previews crashing on iOS12

---

Sources/UI/Chat/Attachments/AttachmentFilePreview.swift
Sources/UI/Chat/Attachments/AttachmentPreview.swift
Sources/UI/Chat/Attachments/AttachmentPreviewProtocol.swift

Fix some typos
`s/Competion/Completion/`
#no_changelog

Fix some typos in attachment preview

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Extensions/Keyboard.swift

This (new) behavior is closer to mainstream chat apps (whatsapp, telegram)

Fix pan gestures on composerview affect tableview scroll

---

Sources/Core/Client/Client+Request.swift
Sources/Core/Client/Client.swift

.. so we let the users know of new versions
#no_changelog

Add pod version check after Client initialization

---

CHANGELOG.md
Sources/Core/Client/InternetConnection.swift
Sources/Core/Client/WebSocket/WebSocket.swift

Fixed connection issue

---

StreamChatClient.podspec

Add podspec for Client and refactor dependencies

---

Sources/Core/Notifications/Notifications.swift

Now `askForPermission` (and `askForPermissionIfNeeded`) are not required, since there's no state in Notifications singleton. Also refactored some names so meanings are clearer

Refactor Notifications singleton

---

Sources/Client/Model/Channel/Channel.swift
Sources/Client/Model/Channel/ChannelQuery.swift
Sources/Client/Model/Channel/ChannelResponse.swift
Sources/Client/Model/Channel/ChannelsQuery.swift
Sources/Client/Model/Pagination.swift
Sources/Core/Client/Channel/Channel+RxRequests.swift
Sources/Core/Client/Client+RxChannel.swift
Sources/Core/Presenter/Messages/ChannelPresenter+RxRequests.swift

- added members and watchers paginators in QueryChannel,
- added watchers to the Channel,
- improved ChannelPresenter and ChannelsPresenter.

Added watchers to the Channel

---

Sources/UI/Channels/ChannelTableViewCell.swift
Sources/UI/Channels/ChannelsViewController.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Chat/Composer/ComposerView.swift
Sources/UI/Extensions/UIKit/TableView.swift
Sources/UI/Style/AvatarViewStyle.swift
Sources/UI/Style/ChannelViewStyle.swift
Sources/UI/Style/ChatViewStyle.swift
Sources/UI/Style/ComposerViewStyle.swift
Sources/UI/Style/SeparatorStyle.swift
Sources/UI/Style/Spacing.swift
Sources/UI/Style/VerticalAlignment.swift
StreamChat.xcodeproj/project.pbxproj

- Add vertical alignment option for channel cell avatar image
- Make ChannelTableViewCell subclasses more usable (without losing super behavior) in ChannelsViewController
- Convert let's to var's in multiple style files to support chained assignments
- Create `configureChatViewController` function in ChannelsViewController for easier overriding
- Add placeholderText style option in ComposerViewStyle

iMessage clone: customization additions and fixes

---

CHANGELOG.md
Example/Sources/LoginViewController.swift
Sources/Core/Client/Client+Config.swift
Sources/Core/Client/Client.swift
Sources/Core/Client/ClientError.swift
Sources/Core/Client/Endpoint.swift
Sources/Core/Model/Channel+Requests.swift
Sources/Core/Model/Event.swift
Sources/Core/Model/ExtraData.swift
Sources/Core/Model/Message+Requests.swift
Sources/Core/Model/Message.swift
Sources/Core/Model/Reaction.swift
Sources/Core/Model/ReactionCounts.swift
Sources/Core/Model/ReactionScores.swift
Sources/Core/Model/ReactionType.swift
Sources/Core/Presenter/Channel Presenter/ChannelPresenter+Events.swift
Sources/Core/Presenter/Channel Presenter/ChannelPresenter.swift
Sources/Database/Realm/Model/Message.swift
Sources/Database/Realm/Model/Reaction.swift
Sources/UI/Chat/Cells/MessageTableViewCell+Updates.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift
Sources/UI/Views/ReactionsView.swift
StreamChat.xcodeproj/project.pbxproj
StreamChatCoreTests/Integration Tests/ChannelTests.swift
StreamChatCoreTests/Unit Tests/ClientLoggerTests.swift

**Changes:**
- custom reactions
- custom fields in reactions.

Custom Reactions

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift

Show message actions with the context menu from iOS 13 instead of ActionSheet.

Context menu (iOS 13)

---

Example/Sources/CustomChatViewController.swift
Example/Sources/DarkChannelsViewController.swift
Sources/Core/Presenter/Channels/ChannelsPresenter.swift
Sources/UI/Channels/ChannelsViewController.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+TableFooterView.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift

Clean up presenter property names in view controllers.

Renaming presenters

---

Sources/Client/Client/Client+Request.swift
Sources/Client/Client/Client+Setup.swift
Sources/Client/Client/Client.swift
Sources/Client/Utils/RepeatingTimer.swift
Sources/Client/WebSocket/WebSocket.swift
Sources/Core/Notifications/Notifications.swift

1. Fixed the background workflow.
2. Fixed the local notifications warning.

Background Work

---

Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Chat/Composer/ComposerView.swift

Sometimes ComposerView stays disabled when the client is connected.

Fixed ComposerView style state

---

Example/Sources/LoginViewController.swift
Example/Sources/Main.storyboard
Sources/Client/Client/Client+Setup.swift

Added a default completion block for set user.

Improved set user

---

Sources/Client/Extensions/Array+Extensions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift
StreamChat.xcodeproj/project.pbxproj

Came across this crash while playing around with the example & tapping messages randomly. I couldn't reproduce a second time, but haven't tried much.

Fix possible crash on showing message actions

---

Sources/Client/Client/Client+Channel.swift
Sources/Client/Model/Channel/Channel+Requests.swift
Sources/Core/Client/Channel/Channel+RxRequests.swift
Sources/Core/Client/Client+RxChannel.swift
Tests/Client/Integration Tests/ClientTests01+Channels.swift
Tests/Client/TestCase.swift

Added managing with channel members as users

Users as members

---

Sources/Client/Client/Client+User.swift
Sources/Client/Model/User/User.swift
Tests/Client/Integration Tests/ClientTests02+Users.swift

Update current user after updateUser is called

---

CHANGELOG.md
Sources/Client/Model/Channel/ChannelExtraData.swift
Sources/Client/Utils/Application.swift
Sources/Core/Presenter/Channel/ChannelPresenter.swift
Sources/Core/Presenter/Channels/ChannelsPresenter.swift
Sources/UI/Channels/ChannelsViewController.swift

If the app state is active after the Internet connection is ready.

Small fixes for 2.0

---

CHANGELOG.md
Package.resolved
Package.swift
README.md
Sources/Core/Client/Client+RxRequest.swift
Sources/Core/Extensions/InternetConnection+Rx.swift

...also added SPM support for Client, and minor changes in README/CHANGELOG

Fixed SPM support for 2.0

---

Example/Cocoapods/Podfile.lock

It just works via `pod install --repo-update`

Fix Podfile.lock for Cocoapods example

---

Sources/Client/Client/Client+Request.swift
Sources/Client/Client/Client+Setup.swift
Sources/Client/Client/Client.swift
Sources/Client/Utils/Application.swift

Fixed a bug in observing app state on the working thread (producing the main queue)

Checking connection issues

---

CHANGELOG.md
Cartfile
Cartfile.resolved
Package.resolved
Package.swift
Sources/Client/Extensions/Codable+Extensions.swift
Sources/Client/Extensions/Data+Gzip.swift
StreamChat.xcodeproj/project.pbxproj
StreamChatClient.podspec

- The wrapper function from `Gzip` we use is included directly.
- `Gzip` dependency is removed.

Remove Gzip dependency

---

CHANGELOG.md
Sources/Client/Model/UserConnection.swift

Added unread count for `UserConnection`.

UserConnection updated

---

CHANGELOG.md
Cartfile
Cartfile.resolved
Package.resolved
Package.swift
Sources/Client/Utils/InternetConnection.swift
Sources/Client/Utils/Reachability.swift
StreamChat.xcodeproj/project.pbxproj
StreamChatClient.podspec

- Reachability code embedded directly.
- `Reachability` framework removed from dependencies

Remove unnecessary Reachability dependency

---

CHANGELOG.md
Sources/Client/Client/Client+Message.swift
Sources/Client/Client/Client+User.swift
Sources/Client/Client/Client+WebSocket.swift
Sources/Client/WebSocket/WebSocket.swift

- The flagging message/user wasn't working #176
- Discard messages from muted users.

Fixed flag message/user

---

CHANGELOG.md
Sources/UI/Channels/ChannelTableViewCell.swift
Sources/UI/Chat/Cells/MessageTableViewCell.swift

Open `prepareForReuse()` in
- `ChannelTableViewCell`
- `MessageTableViewCell`

Fixed prepareForReuse

---

Sources/Client/Client/Client+Channels.swift
Sources/Client/Model/Channel/ChannelsQuery.swift
Sources/Client/Model/Filter.swift
Sources/Core/Client/Client+RxChannels.swift
Sources/Core/Presenter/Channels/ChannelsPresenter.swift
Sources/UI/Channels/ChannelsViewController.swift
Tests/Client/Integration Tests/ClientTests00.swift
Tests/Client/Integration Tests/ClientTests01+Channels.swift

Remove an empty filter by default.

Removed empty filter

---

Sources/UI/Channels/ChannelsViewController.swift

Fixed `ChannelsViewController` view controller subscription setup when it's invisible.

Invisible ChannelsViewController

---

.github/workflows/beta.yml
.github/workflows/ci.yml
Example/SPM/ChatExample.xcodeproj/project.pbxproj
Example/SPM/ChatExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Example/SPM/ChatExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Example/SPM/ChatExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/SPM/ChatExample/ChatExample-Bridging-Header.h
Example/SPM/ChatExample/Info.plist
fastlane/Fastfile
fastlane/README.md
fastlane/Scanfile

Also refactors our beta and CI workflows to use fastlane more efficently.
Redundant `carthage bootstrap` commands are not an issue since it takes 10 seconds when it finds valid cache.

CIS-94 Add SPM Example project and integration tests

---

CHANGELOG.md
Sources/UI/Channels/ChannelTableViewCell.swift
Sources/UI/Channels/ChannelsViewController.swift
Sources/UI/Chat/Cells/MessageTableViewCell.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+TableFooterView.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Chat/ChatFooterView.swift
Sources/UI/Style/AvatarViewStyle.swift
Sources/UI/Views/AvatarView.swift
Sources/UI/Views/ReactionsView.swift
Sources/UI/Views/ReadUsersView.swift

- added open methods for `AvatarView` customization:
- in `ChannelsViewController`:
```swift
open func updateChannelCellAvatarView(in cell: ChannelTableViewCell, channel: Channel)
```
- in `ChatViewController`:
```swift
open func updateMessageCellAvatarView(in cell: MessageTableViewCell, message: Message, messageStyle: MessageViewStyle)
open func updateFooterTypingUserAvatarView(footerView: ChatFooterView, user: User)
```
- updated `AvatarViewStyle`: addad new properties:
- `placeholderTextColor: UIColor?`
- `placeholderBackgroundColor: UIColor?`

Customization for AvatarView

---

CHANGELOG.md
Example/Sources/RootViewController.swift
Sources/Client/Client/Client+Channel.swift
Sources/Client/Client/Client+Events.swift
Sources/Client/Client/Client+WebSocket.swift
Sources/Client/Client/Client.swift
Sources/Client/Extensions/Array+Extensions.swift
Sources/Client/Model/Channel/Channel+Requests.swift
Sources/Client/Model/Channel/Channel+UnreadCount.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Utils/Atomic.swift
Sources/Client/Utils/InternetConnection.swift
Sources/Client/Utils/WeakRef.swift
Sources/Client/WebSocket/ConnectionState.swift
Sources/Client/WebSocket/WebSocket.swift
Sources/Core/Presenter/Channel/ChannelPresenter.swift

Added restoring watching channels.
When calling `channel.watch()` for a channel, it will be restored when the connection returns.

Re-watch watching channels.

---

.github/stale.yml

https://github.com/apps/stale
To mark issues older than 20 days as stale and close them automatically in 27 days

Add Stale bot to repo

---

CHANGELOG.md
Example/Sources/CustomChatViewController.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift

Made this based on how ChannelsViewController allows customizing the ChatViewController.
Closes #136

Allow customizing ChatViewController used in Threads

---

README.md

Small changes. Just gave it a pass in Grammarly.

Improve wording and spelling in README

---

CHANGELOG.md
Sources/Client/Client/Client+UnreadCount.swift
Sources/Client/Model/Channel/Channel+UnreadCount.swift
Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift
Sources/UI/Channels/ChannelTableViewCell.swift
Sources/UI/Channels/ChannelsViewController.swift

Fixed UI and unread count handling for deleted messages.

CIS-24 Fixed unread count for deleted messages

---

CHANGELOG.md
Sources/Core/Notifications/Notifications.swift

Fixed local notifications for muted users.

Suppress local notifications for muted users.

---

.github/workflows/rebase-release.yml

Add Github Actions workflow to rebase release/* branches

---

CHANGELOG.md
Sources/Client/URL Session Task/Uploader.swift
Sources/Core/Presenter/Channel/ChannelPresenter.swift

Public access to set `ChannelPresenter.uploadManager` to use custom `Uploader`.

Fixed ChannelPresenter.uploadManager property access

---

Sources/Client/Utils/InternetConnection.swift
Sources/Client/Utils/Reachability.swift

Removed `Reachability.init` with our site URL (impossible case).

CIS-88 Updated `Reachability.init` in InternetConnection

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Style/ChatViewStyle.swift

for customizing Navigation Right Bar Button Item in Chat screen
As per customer request

Add ChatViewStyle.avatarViewStyle option

---

CHANGELOG.md
Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift

Fix last message not set on sending message to empty channel

---

CHANGELOG.md
Example/Sources/AppDelegate.swift
Sources/Client/Client/Client+Request.swift
Sources/Client/Client/Client+Setup.swift
Sources/Client/Client/Client.swift
Sources/Client/Client/ClientLogger.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Model/User/User.swift
Sources/Client/URL Session Task/ClientURLSessionTaskDelegate.swift
Sources/Client/Utils/InternetConnection.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Tests/Client/Integration Tests/TestCase.swift
Tests/Client/Unit Tests/ClientLoggerTests.swift

Also adds options to disable emoji in logs
Our Logger is still suboptimal and it's known, we'll overhaul it shortly so I tried to keep this PR short

[CIS-104] Add log level to log outputs

---

CHANGELOG.md
Sources/Client/Client/Client+Channel.swift
Sources/Client/Model/Channel/ChannelNamingStrategy.swift
Sources/Client/Model/User/User.swift
StreamChat.xcodeproj/project.pbxproj
Tests/Client/Unit Tests/Channel+Setup.swift
Tests/Client/Unit Tests/Channel+SetupTests.swift
Tests/Client/Unit Tests/ChannelNamingStrategyTests.swift

Example:
```swift
let anotherUser = User("second")
anotherUser.name = "John"
anotherUser.avatarURL = URL(string: "http://example.com/john")
let channel = client.channel(members: [client.user, anotherUser])
print(channel.name) // will print "John"
print(channel.imageURL) // will print "http://example.com/john"
```

Use user names and avatars for the channel name and image without id.

---

Sources/UI/Chat/Cells/MessageTableViewCell.swift

Fixed lint warning with body length

---

CHANGELOG.md
Sources/Client/Model/Channel/ChannelsQuery.swift
Sources/Client/Model/Filter.swift
Sources/Client/Model/SearchQuery.swift
Tests/Client/Unit Tests/FilterTests.swift

Adds back none filter with console warnings, adds new filter operators as discussed, and also adds custom filter operator to future-proof

Add contains filter

---

CHANGELOG.md
Sources/Client/Client/Client+Channel.swift
Sources/Client/Extensions/Functions.swift
Sources/Client/Model/Channel/Channel+Requests.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Utils/Timers.swift
Sources/Core/Client/Channel/Channel+RxRequests.swift
Sources/Core/Client/Client+RxRequest.swift
Sources/Core/Extensions/RxFunctions.swift
Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift
Sources/Core/Presenter/Channel/ChannelPresenter+RxRequests.swift
Sources/Core/Presenter/Channel/ChannelPresenter.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+TableFooterView.swift
Sources/UI/Chat/ChatFooterView.swift
StreamChat.xcodeproj/project.pbxproj
Tests/Client/Custom Assertions/AssertNetworkRequest.swift
Tests/Client/Unit Tests/Channel+KeystrokeTests.swift
Tests/Client/Unit Tests/Channel+SilentMessageTests.swift
Tests/Client/Unit Tests/Client+DevicesTests.swift
Tests/Client/Unit Tests/Client+SilentMessageTests.swift
Tests/Client/Unit Tests/ClientTestCase.swift
Tests/Virtual Time/VirtualTime.swift
Tests/Virtual Time/VirtualTimers.swift

Implementation of `keystroke` and `stopTyping` on LLC.

CIS-69 keystroke

---

CHANGELOG.md
Sources/Client/BaseURL.swift

Two new regions added for Singapore and Sydney.

Added support for new regions

---

CHANGELOG.md
Sources/Client/Client/Client+Channel.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Model/User/User.swift

Docs: https://getstream.io/chat/docs/multi_tenant_chat/?language=swift

[CIS-167] Add support for multi tenancy

---

.github/workflows/ci.yml
StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/WebSocketClient/Engine/StarscreamWebSocketEngine.swift
StreamChatClient_v3/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
StreamChatClient_v3/WebSocketClient/Engine/WebSocketEngine.swift
StreamChatClient_v3/WebSocketClient/WebSocketClient.swift

- Deployment target of v3 set to iOS 11
- `StarscreamWebSocketEngine` migrated to v3
#no_changelog

[CIS-175] Make v3 compile for iOS11 deployment target

---

CHANGELOG.md
Sources/Client/Client/ClientLogger.swift

[CIS-182] Add showConnectionErrorAlert flag to ClientLogger

---

CHANGELOG.md
Example/Carthage/ChatExample.xcodeproj/project.pbxproj
Example/Carthage/ChatExample/FakeChatViewController.swift
Example/Sources/CustomChatViewController.swift
Example/Sources/Main.storyboard
Sources/Core/Presenter/Channel/ChannelPresenter+Request.swift
Sources/UI/Chat/Attachments/ImageAttachmentPreview.swift
Sources/UI/Chat/Cells/MessageTableViewCell.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Extensions/UIKit/CGFloat+Extensions.swift
Sources/UI/Extensions/UIKit/TableView.swift
Sources/UI/Extensions/UIKit/UIImage/UIImage+Render.swift

- Fixed an error with the UI when adding new messages.
- Fixed background color for an empty image.
- Fixed height rendering for a message.
- Fixed rendering of a message bubble curve.
- Fixed scrolling to the current message when you go to the last page.

CIS-146 Fixed unexpected scrolling

---

CHANGELOG.md
Sources/Client/BaseURL.swift
Sources/Client/Client/Client+Config.swift
Sources/Client/Client/Client.swift

[CIS-177] Change configureShared fatalError to warning for same config

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/ChatClient.swift
StreamChatClient_v3/Database/DatabaseContainer.swift
StreamChatClient_v3/Utils/Codable+Extensions.swift
StreamChatClient_v3/Utils/Logger/BaseLogDestination.swift
StreamChatClient_v3/Utils/Logger/ConsoleLogDestination.swift
StreamChatClient_v3/Utils/Logger/LogDestination.swift
StreamChatClient_v3/Utils/Logger/LogFormatter.swift
StreamChatClient_v3/Utils/Logger/Logger.swift
StreamChatClient_v3/Utils/Logger/PrefixLogFormatter.swift
StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
StreamChatClient_v3/Workers/Worker.swift
V3SampleApp/AppDelegate.swift

I still cannot decide how we're going to pass the logger around:
1. A global variable (not constant) that every new client will assign?
2. Dependency injecting it into every component?

[CIS-166] Add Logger and related components

---

StreamChatClient_v3/Utils/Atomic_tests.swift

- `Atomic` tests shouldn't randomly crash anymore.
The problem was that reading from `Atomic` sometimes took too long and the `Atomic` instance was already gone. 
We saw a similar issue with the v2 tests here https://github.com/GetStream/stream-chat-swift/pull/254/files#r422086666 . I thought it wouldn't be needed now when `Atomic` is a struct 🤷‍♂️

[CIS-188] Fix bad access crash in `Atomic` tests

---

CHANGELOG.md
Sources/Client/Client/Client+WebSocket.swift
Sources/Client/Model/Event.swift
Sources/Client/Model/EventType.swift
Tests/Client/Unit Tests/EventTests.swift

[CIS-189] Add userUnbanned ws event

---

Sources/Client/Model/Message/Message+Requests.swift
Sources/Client/Model/Message/Message.swift
Sources/Client/Model/MessageTranslations.swift
StreamChat.xcodeproj/project.pbxproj

[CIS-179] Refine Message translation endpoint

---

CHANGELOG.md
Sources/Client/Client/Client+User.swift
Sources/Client/Model/User/UsersQuery.swift
Sources/Core/Client/Client+RxUser.swift
Tests/Client/Unit Tests/QueryEncodingTests.swift

Fix queryUsers not encoding sorting

---

StreamChatClient_v3/Database/DTOs/ChannelDTO.swift
StreamChatClient_v3/Database/DTOs/ChannelDTO_Tests.swift
StreamChatClient_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
StreamChatClient_v3/Query/ChannelListQuery.swift
StreamChatClient_v3/Query/Sorting.swift
TestResources_v3/TemporaryData.swift

- added `ChannelDTO.defaultSortingDate`
- added indexes for: 
- `ChannelDTO`: `defaultSortingDate`, `cid`, `lastMessageDate`, `createdDate`
- `ChannelListQueryDTO`: `filterHash`
- `MemberDTO`: `id`
- `MessageDTO`: `id`
- `TeamDTO`: `id`
- `UserDTO`: `id`
- Added a sorting for fetching data from db.

[CIS-192] Channel list respects sorting from the query

---

.swiftformat
bootstrap.sh
hooks/git-format-staged
hooks/pre-commit.sh

Add pre-commit hook.

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/Models/ChannelId.swift
StreamChatClient_v3/Models/ChannelId_Tests.swift
StreamChatClient_v3/Models/ChannelType.swift

Surprisedly I had to fix `ChannelId` and `ChannelType` to pass tests.

[CIS-215] Tests for ChannelId

---

CHANGELOG.md
Sources/Client/Client/Client+Channel.swift
Sources/Client/Client/Endpoint.swift
Sources/Client/Model/Channel/Channel+Requests.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Model/User/User.swift
Sources/Core/Client/Channel/Channel+RxRequests.swift
Sources/Core/Client/Client+RxChannel.swift
Sources/UI/Chat/Chat View Controller/ChatViewController+MessageActions.swift

- `client.unban(user:User in channel: Channel, _ completion:)`
- `client.rx.unban(user:User in channel: Channel)`
- `channel.unban(user:User, _ completion:)`
- `channel.rx.unban(user:User)`

CIS-216 Add user unban request

---

CHANGELOG.md
Sources/Client/Model/Device.swift

Make Device.created optional

---

CHANGELOG.md
Sources/UI/Extensions/UIKit/UITapGestureRecognizer+Extensions.swift

Take label font into account for link tap detection in messages

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
StreamChatClient_v3/Controllers/ChannelListController.swift
StreamChatClient_v3/Controllers/ChannelListController_Tests.swift

- Add setup for `ChannelListController` and `ChannelEndpoints` tests

[CIS255-256] Add setup for `ChannelListController` and `ChannelEndpoints` tests

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints.swift
StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
StreamChatClient_v3/APIClient/Endpoints/Requests/HideChannelRequest.swift
StreamChatClient_v3/APIClient/RequestEncoder.swift
StreamChatClient_v3/Controllers/ChannelListController.swift
StreamChatClient_v3/Controllers/ChannelListController_Tests.swift
StreamChatClient_v3/Workers/ChannelUpdater.swift
V3SampleApp/MasterViewController.swift

- Add `delete`, `hide`, `show` channel endpoints.
- Add usage of `delete`, `hide`, `show` channel endpoints to `ChannelListController`
- Adjust `encodeGETRequestBody` to `encodeGETorDELETERequestBody` in `RequestEncoder`

[CIS 255] Implement deleting & hiding of a channel

---

CHANGELOG.md
Sources/Client/Client/Client+Events.swift
Sources/Client/Client/Client+UnreadCount.swift
Sources/Client/Client/Client+WebSocket.swift
Sources/Client/Model/Channel/Channel+UnreadCount.swift
Sources/Client/Model/Channel/Channel+WatcherCount.swift
Sources/Client/Model/Event.swift
Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift
Tests/Client/Unit Tests/Channel+SilentMessageTests.swift
Tests/Client/Unit Tests/Client+SilentMessageTests.swift
Tests/Client/Unit Tests/EventTests.swift

1. Use unread count from message.new event
2. Don't use message.deleted for unread count

Fix global unread count

---

CHANGELOG.md
Sources/Client/Client/Client+UnreadCount.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Client/Model/Channel/ChannelResponse.swift
Sources/Client/Model/User/Member.swift
Tests/Client/Unit Tests/Channel+SilentMessageTests.swift

- Don't update unread count for zero values
- Add membership for Channel
- Fix unread count calculation

CIS-271 Fix unread count for mark read

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/ChannelCodingKeys.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/ChannelEditDetailPayload.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/ChannelEditDetailPayload_Tests.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/ChannelListPayload.swift
StreamChatClient_v3/Controllers/ChannelController.swift
StreamChatClient_v3/Controllers/ChannelController_Tests.swift
StreamChatClient_v3/Query/ChannelQuery.swift
StreamChatClient_v3/Query/ChannelQuery_Tests.swift
StreamChatClient_v3/Workers/ChannelUpdater_Tests.swift
V3SampleApp/MasterViewController.swift

- Add possibility to create new channel
- Clean and adjust `ChannelQuery`
- Make use of channel creation feature in `V3SampleApp`

[CIS-248] Add channel creation

---

CHANGELOG.md
Sources/Client/Client/Client+Request.swift

- changed pipelining and request timeout for `URLSessionConfiguration`
- update our custom header

Add pipelining to URLSessionConfiguration

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/Utils/Result+Extensions.swift
StreamChatClient_v3/Workers/ChannelUpdater.swift

- Added `error` `Result` property
- Replaced `switch-cases`in `ChannelUpdater` with this property

Follow-up for [CIS-255-256] with added `error` `Result` property

---

StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints.swift
StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
StreamChatClient_v3/Controllers/ChannelController.swift
StreamChatClient_v3/Controllers/ChannelController_Tests.swift
StreamChatClient_v3/Workers/ChannelUpdater.swift
StreamChatClient_v3/Workers/ChannelUpdater_Mock.swift
StreamChatClient_v3/Workers/ChannelUpdater_Tests.swift
V3SampleApp/MasterViewController.swift

- Add `updateChannel` endpoint
- Add `updateChannel` functionality to `ChannelUpdater`
- Expose `updateChannel` functionality to `ChannelController`
- Make it possible to change channel name in `V3SampleApp`

[CIS-251] Channel update

---

CHANGELOG.md
Example/Sources/RootViewController.swift
Sources/Client/Client/Client+Events.swift
Sources/Client/Client/Client+UnreadCount.swift

- Fixed CHANGELOG for #369 
- Updated examples and docs for unread count usage

CIS-277 Update examples for unread count

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/APIClient/Endpoints/GuestEndpoints.swift
StreamChatClient_v3/APIClient/Endpoints/GuestEndpoints_Tests.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/GuestUserTokenPayload.swift
StreamChatClient_v3/APIClient/Endpoints/Payloads/GuestUserTokenPayload_Tests.swift
StreamChatClient_v3/APIClient/Endpoints/Requests/GuestUserTokenRequestPayload.swift
StreamChatClient_v3/APIClient/Endpoints/Requests/GuestUserTokenRequestPayload_Tests.swift
StreamChatClient_v3/ChatClient.swift
StreamChatClient_v3/ChatClient_Tests.swift
TestResources_v3/Dummy data/CurrentUserPayload.swift
TestResources_v3/MockEnpointResponses/GuestUser/GuestUser+CustomExtraData.json
TestResources_v3/MockEnpointResponses/GuestUser/GuestUser+DefaultExtraData.json
TestResources_v3/MockEnpointResponses/GuestUser/GuestUser+NoExtraData.json

(on behalf of @evsaev )
**This PR:** 
- Provides implementation for `ChatClient.setGuestUser`;
- Introduces `guestUserToken` endpoint;
- Introduces `GuestUserTokenRequestPayload` for `guestUserToken` request;
- Introduces `GuestUserTokenPayload` for `guestUserToken` response;
- Adds generic dummy method to `CurrentUserPayload`.

[CIS-234] Implement guest users

---

StreamChat.xcodeproj/project.pbxproj
StreamChatClient_v3/Controllers/ChannelController.swift
StreamChatClient_v3/Controllers/ChannelController_Tests.swift
StreamChatClient_v3/Controllers/ChannelListController.swift
StreamChatClient_v3/Controllers/ChannelListController_Tests.swift
StreamChatClient_v3/Controllers/Controller.swift
StreamChatClient_v3/Controllers/Controller_Tests.swift
V3SampleApp/MasterViewController.swift

- Introduce `ControllerStateDelegate` and more states

Preparation PR for [CIS-253]

---

Tests_v3/Await.swift
Tests_v3/Custom Assertions/AssertAsync+Events.swift
Tests_v3/Custom Assertions/AssertAsync.swift
Tests_v3/Custom Assertions/AssertResult.swift
Tests_v3/Mock Network/AssertNetworkRequest.swift
Tests_v3/StressTestCase.swift
Tests_v3/TemporaryData.swift
Tests_v3/Virtual Time/VirtualTime.swift
Tests_v3/Virtual Time/VirtualTimer.swift
Tests_v3/XCTAssertEqual+Difference.swift
bootstrap.sh

Format code for Test v3

---

Sources_v3/Controllers/ChannelController.swift
Sources_v3/Controllers/ChannelController_Tests.swift

- Add possibility to create 1-1 channels
- Add error handling for failed DB fetch on `ChannelQuery`reset

[CIS-253] Create 1-1 channels

---

Sample_v3/Extensions/UIView+InstantiateFromNib.swift
Sample_v3/Samples/SimpleChat/DetailViewController.swift
Sample_v3/Samples/SimpleChat/Views/ComposerView.swift
Sample_v3/Samples/SimpleChat/Views/ComposerView.xib
StreamChat_v3.xcodeproj/project.pbxproj

Replaced the alert with a simple composer similar to iMessage
#no_changelog

Add composer to v3 simple chat sample

---

CHANGELOG.md
Sources/Client/Client/Client+WebSocket.swift
Sources/Client/WebSocket/WebSocket.swift
Tests/Client/Unit Tests/WebSocket/WebSocketTests.swift

[CIS-302] Fix Websocket not handling expired token

---

Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Controllers/ListDatabaseObserver.swift
Sources_v3/Database/DTOs/ChannelDTO.swift
Sources_v3/Database/DTOs/ChannelListQueryDTO.swift
Sources_v3/Database/DatabaseContainerMock.swift
Sources_v3/Query/Filter.swift
Sources_v3/Query/Filter_Tests.swift
Sources_v3/Workers/Background/NewChannelQueryUpdater.swift
Sources_v3/Workers/Background/NewChannelQueryUpdater_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

After creating new channel it's not observed cause it's not linked to any ChannelListQuery. 
So we need some `Worker` to do the job.
- Introduce `NewChannelQueryUpdater`

[CIS-200] New channel observation

---

Sample_v3/Samples/SimpleChat/DetailViewController.swift
Sources_v3/Controllers/ChannelController.swift
Sources_v3/Controllers/ChannelController_Tests.swift
Sources_v3/Query/ChannelQuery.swift

- Implement message pagination in `ChannelController`
- Make use of message pagination in `SampleApp`

[CIS-250] Message pagination in `ChannelController`

---

Sources_v3/APIClient/APIClient_Tests.swift
Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Controllers/ChannelController.swift
Sources_v3/Controllers/ChannelController_Tests.swift
Sources_v3/WebSocketClient/EventMiddlewares/EventMiddleware_Mock.swift
Sources_v3/WebSocketClient/HealthCheckMiddleware_Tests.swift
Sources_v3/WebSocketClient/WebSocketClient.swift
Sources_v3/WebSocketClient/WebSocketClient_Tests.swift
Sources_v3/Workers/EventNotificationCenter.swift
Sources_v3/Workers/EventNotificationCenter_Tests.swift
Sources_v3/Workers/Worker.swift
StreamChat_v3.xcodeproj/project.pbxproj
Tests_v3/EventLogger.swift

**This PR:**
- Introduces `EventNotificationCenter` that pre-process incoming events before being published
- Uses `EventNotificationCenter` in `WebSocketClient`

[CIS-289] Extract event-posting logic

---

CHANGELOG.md
Sources/Core/Presenter/Channel/ChannelPresenter+Events.swift

[CIS-306] Fix date separators not appearing after a new message

---

.gitignore
CHANGELOG.md
Package.swift
StreamChat.podspec
StreamChatClient.podspec
StreamChatCore.podspec

[CIS-304] Bump swift version to 5.2

---

Sample_v3/Base.lproj/Main.storyboard
Sample_v3/LoginViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
StreamChat_v3.xcodeproj/project.pbxproj

No Stream Chat logic in it yet. Just some basic UI elements to start.
#no_changelog

Add SwiftUI sample stub

---

CHANGELOG.md
Sources/Client/Model/Device.swift

[CIS-307] Fix Device object failing to decode due to backend issue

---

Sample_v3/Samples/SimpleChat/DetailViewController.swift
Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Config/ChatClientConfig.swift
Sources_v3/Controllers/ChannelController.swift
Sources_v3/Controllers/ChannelController_Tests.swift
Sources_v3/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware.swift
Sources_v3/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware_Tests.swift
Sources_v3/WebSocketClient/Events/EventType.swift
Sources_v3/WebSocketClient/Events/TypingEvent.swift
Sources_v3/WebSocketClient/Events/TypingEvent_Tests.swift
Sources_v3/Workers/EventObservers/TypingEventObserver.swift
Sources_v3/Workers/EventObservers/TypingEventObserver_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Introduce `TypingEventObserver`
- Make prefix renaming `UserTyping` -> `Typing`

[CIS-246] Implement observer for typing events

---

CHANGELOG.md
Sample/Sources/CustomChatViewController.swift
Sample/Sources/LoginViewController.swift
Sources/Client/Client/Client+Devices.swift
Sources/Client/Client/Client+User.swift
Sources/Client/Model/User/User.swift

This seems like the only solution to prevent the Atomic crashes, proved by our customer's reports

Change `User` from struct to class

---

CHANGELOG.md
Sources/Client/Model/EventType.swift

Fix `user.unbanned` event cannot be listened for via channel

---

Sources_v3/Controllers/ChannelController_Tests.swift
Sources_v3/Controllers/ChannelListController_Tests.swift
Sources_v3/Database/DatabaseContainer_Tests.swift

Another edition of your favorite weekly PR!

Fix stress tests, vol.5

---

Sample_v3/Extensions/UIColor+ForUsername.swift
Sample_v3/Extensions/UITableViewController+KeyboardAvoidance.swift
Sample_v3/Samples/SimpleChat/MasterViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/Views/ComposerView.swift
Sample_v3/Samples/SplitViewController.swift
Sample_v3/SceneDelegate.swift
StreamChat_v3.xcodeproj/project.pbxproj

This some improvements to the UIKit sample
- Inverts the UITableView
- Adds keyboard avoidance behavior
- IRC styled message cell
- Start on Channels Screen
Preview:

Improve v3 UIKit sample chat UI

---

Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
Sample_v3/SceneDelegate.swift

This is mainly an effort to start organizing and commenting the sample code itself, but also added some features.
1. Added comments (still evolving in style and usefulness, but it's a start)
2. Separated some of the UI logic to highlight the Stream Chat code
3. Moved code which interacts with `ChannelController` to the top and moved most UI code to the bottom.
4. Added member count and online count to top of chat screen
5. Added typing indicator to top of chat screen
6. Added delete channel option in menu (it's crashing for now, same as in channel list screen)

Add comments and more features to v3 sample chat UI

---

Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Introduce `ChannelWatchStateUpdater `

[CIS-315] Re-watch existing channels after the WSConnection is established

---

Sources_v3/Controllers/ChannelController/ChannelController+Combine.swift
Sources_v3/Controllers/ChannelController/ChannelController+Combine_Tests.swift
Sources_v3/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources_v3/Controllers/ChannelController/ChannelController.swift
Sources_v3/Controllers/ChannelListController/ChannelListController+Combine.swift
Sources_v3/Controllers/CurrentUserController/CurrentUserController+Combine.swift
Sources_v3/Controllers/CurrentUserController/CurrentUserController+Combine_Tests.swift
Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
Sources_v3/Utils/Publisher+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Add `Combine` wrapper to `ChannelController`
- Add `Combine` wrapper to `CurrentUserController`

[CIS-327] Combine wrappers for `ChannelController` and `CurrrentUserController`

---

Sources_v3/Controllers/MessageController/MessageController+Combine.swift
Sources_v3/Controllers/MessageController/MessageController+Combine_Tests.swift
Sources_v3/Controllers/MessageController/MessageController+SwiftUI.swift
Sources_v3/Controllers/MessageController/MessageController+SwiftUI_Tests.swift
Sources_v3/Controllers/MessageController/MessageController.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Add SwiftUI wrapper for `MessageController`
- Add Combine wrapper for `MessageController`

[CIS-322] [CIS-328] SwiftUI and Combine wrappers for MessageController

---

Sample_v3/LoginViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChat.storyboard

Also fixed a mistake on authentication (development token was guest)

Add unread indication, count and last message to channel cell

---

Sample_v3/AppDelegate.swift
Sample_v3/LoginViewController.swift
Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift

- fixed a bug where we wiped out the local cache every time the current user is set
- Sample app doesn't wait for the connection and show the channel list immediately

Offline support for Sample app

---

Sample/Carthage/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExample.xcscheme

I think after fixes for Carthage the scheme for Sample app v2 was missed

Add Sample app v2 missed scheme

---

Sources_v3/Controllers/ConnectionController/ConnectionController+Combine.swift
Sources_v3/Controllers/ConnectionController/ConnectionController+Combine_Tests.swift
Sources_v3/Controllers/ConnectionController/ConnectionController+SwiftUI.swift
Sources_v3/Controllers/ConnectionController/ConnectionController+SwiftUI_Tests.swift
Sources_v3/Controllers/ConnectionController/ConnectionController.swift
Sources_v3/Controllers/ConnectionController/ConnectionController_Tests.swift
Sources_v3/WebSocketClient/Events/ConnectionEvents.swift
StreamChat_v3.xcodeproj/project.pbxproj

- added `ConnectionControllerGeneric` and `ConnectionControllerDelegate`
- added `ConnectionEventObserver` for observing `ConnectionStatusUpdated`

[CIS-308] Add ConnectionController

---

Sample_v3/Samples/SettingsViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift

[CIS-343] Implement `ChannelListView` in `SwiftUI` example

---

Sample_v3/Base.lproj/Main.storyboard
Sample_v3/LoginViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChat.storyboard
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/SplitViewController.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Add Combine example for `SimpleChatChannelsViewController`
- Add Combine example for `SimpleChatViewController`

[CIS-330] UIKit+Combine example

---

Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Controllers/ConnectionController/ConnectionController.swift
Sources_v3/Database/DatabaseContainer.swift
Sources_v3/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
Sources_v3/Workers/Background/MessageEditor.swift
Sources_v3/Workers/Background/MessageSender.swift
Sources_v3/Workers/Background/MissingEventsPublisher.swift
Sources_v3/Workers/Background/MissingEventsPublisher_Tests.swift
Sources_v3/Workers/Background/NewChannelQueryUpdater.swift
Sources_v3/Workers/EventObservers/EventObserver.swift
Sources_v3/Workers/EventObservers/EventObserver_Tests.swift
Sources_v3/Workers/EventObservers/MemberEventObserver.swift
Sources_v3/Workers/EventObservers/TypingEventObserver.swift

..Also adds the middleware to be used in the client, which I forgot in #482 
Let's see how the CI reacts

[CIS-333] Fix accessing DTOs without `backgroundReadOnlyContext.perform`

---

Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/SettingsViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift

Settings screen was crashing on SwiftUI and combine samples.

Sample v3: fix settings screen crash

---

Sample_v3/Base.lproj/Main.storyboard
Sample_v3/Extensions/UIColor+ForUsername.swift
Sample_v3/LoginViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift

~Base is #485 for now.~ moved to master
Added most features present in the UIKit sample.
Additionally:
- Added random user button to the login screen - this helps testing :)

[CIS-343] Improve v3 SwiftUI sample's ChatView

---

Sample_v3/Extensions/Channel+MembersInfo.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR** updates `SimpleChat`, `SimpleChat+Combine`, `SimpleChat+SwiftUI` samples to show a list of typing members for each channel in a channel list.

[CIS-340] Typing indicator in channel list

---

Sample_v3/Extensions/UITableViewController+Cells.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
StreamChat_v3.xcodeproj/project.pbxproj

- move some of the cell UI code to an extension
- commented and organized `CombineSimpleChannelsViewController`

Sample v3: code organization and comment combine channels screen

---

Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift

UIKit+Combine example is in pretty good shape after https://github.com/GetStream/stream-chat-swift/pull/496.
So, **in this PR** some minor changes and comments to `CombineSimpleChannelsViewController` and `CombineSimpleChatViewController`.

[CIS-351] Audit the UIKit + Combine implementation

---

Sources_v3/ChatClient.swift
Sources_v3/ChatClient_Mock.swift
Sources_v3/ChatClient_Tests.swift
Sources_v3/Config/ChatClientConfig.swift
Sources_v3/Database/DatabaseContainer.swift
Sources_v3/Database/DatabaseContainer_Mock.swift
Sources_v3/Database/DatabaseContainer_Tests.swift

- Add flushing on model conflicts
- Add option to flush DB on start for SDK users
_Not implemented (details will be in JIRA ticket):  DB flush on ExtraData changes._

[CIS-211] Database flushing adjustments

---

Sources_v3/Database/DTOs/ChannelDTO.swift
Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/Models/ChannelModel.swift

- Fix `memberCount` and `watcherCount` for `ChatChannel`

[CIS-361] Fix memberCount and watcherCount for ChatChannel

---

CHANGELOG.md
Sources/Client/Model/Channel/MutedChannel.swift

Channel mute response was incorrect

Fix Channel mute response not parsed correctly

---

CHANGELOG.md
Sources/Client/Client/Client+Request.swift

Fix update warning displayed for 3.x versions

---

README.md
Sources_v3/CHANGELOG.md

Just a couple of things from `master_v3` that should actually live in `master`

v3 Beta Pre-release cleanup

---

CHANGELOG.md
Sources/Client/Client/Client+Channel.swift
Sources/Client/Client/Endpoint.swift
Sources/Client/Model/Channel/Channel+Requests.swift
Sources/Client/Model/Channel/Channel.swift
Sources/Core/Client/Channel/Channel+RxRequests.swift
Sources/Core/Client/Client+RxChannel.swift

Add slowMode client-side implementation

---

Sample_v3/Extensions/Channel+MembersInfo.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift

Minor adjustments of `SwiftUI` sample.

[CIS-352] Audit `SwiftUI` sample

---

Sample_v3/Base.lproj/Main.storyboard
Sample_v3/LoginViewController.swift
Sources_v3/Database/DatabaseContainer.swift
Sources_v3/Database/DatabaseContainer_Mock.swift
Sources_v3/Database/DatabaseContainer_Tests.swift

- Added configuration section with storage and region options
- Improve layout (separate low-level samples from high-level samples placeholders)
- Fix login being called when pressing cells other than samples
- Fix crash on login error
Also small change in SDK:
- Don't do anything when flush is enabled but local storage is not (flushing without local storage causes crash)
#no_changelog

Sample v3: Improve login experience

---

Sample_v3/README.md
sample-bootstrap.sh

Sample v3: Create README.md

---

Sources_v3/APIClient/Endpoints/Payloads/UserListPayload.swift
Sources_v3/APIClient/Endpoints/Payloads/UserListPayload_Tests.swift
Sources_v3/APIClient/Endpoints/UserEndpoints.swift
Sources_v3/APIClient/Endpoints/UserEndpoints_Tests.swift
Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
Sources_v3/Controllers/ChannelListController/ChannelListController_Tests.swift
Sources_v3/Controllers/MessageController/MessageController_Tests.swift
Sources_v3/Controllers/UserListController/UserListController+Tests.swift
Sources_v3/Controllers/UserListController/UserListController.swift
Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
Sources_v3/Database/DTOs/UserDTO.swift
Sources_v3/Database/DTOs/UserDTO_Tests.swift
Sources_v3/Database/DTOs/UserListQueryDTO.swift
Sources_v3/Database/DatabaseSession.swift
Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/Models/ChannelId_Tests.swift
Sources_v3/Query/ChannelListQuery.swift
Sources_v3/Query/ChannelQuery_Tests.swift
Sources_v3/Query/Pagination.swift
Sources_v3/Query/Sorting.swift
Sources_v3/Query/UserListQuery.swift
Sources_v3/Query/UserListQuery_Tests.swift
Sources_v3/Workers/ChannelListUpdater_Tests.swift
Sources_v3/Workers/UserListUpdater.swift
Sources_v3/Workers/UserListUpdater_Mock.swift
Sources_v3/Workers/UserListUpdater_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj
Tests_v3/JSONEncoder+Extensions.swift
Tests_v3/MockEnpointResponses/UsersQuery.json

- Introduce `users` endpoint, `UserListPayload`, `UserListQuery`
- Introduce `UserListQueryDTO`
- Introduce `UserListUpdater`
- Introduce `UserListController`

[CIS-372] UserListController base implementation

---

Sources_v3/Controllers/UserController/UserController+Combine.swift
Sources_v3/Controllers/UserController/UserController+Combine_Tests.swift
Sources_v3/Controllers/UserController/UserController+SwiftUI.swift
Sources_v3/Controllers/UserController/UserController+SwiftUI_Tests.swift
Sources_v3/Controllers/UserController/UserController.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR** provides `Combine` and `SwiftUI` wrappers for `ChatUserController`

[CIS-377] Implement `Combine/SwiftUI` wrappers for user-controller

---

.github/workflows/ci.yml
Sample/Carthage/ChatExample/Info.plist
Sample_v3/Info.plist

Update app display name and disable codecov for iOS12.4 tests

---

Sample_v3/Extensions/UIStoryboard+Definitions.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChat.storyboard
Sample_v3/Samples/CombineSimpleChat/CombineSimpleUsersViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
Sample_v3/Samples/SimpleChat/SimpleUsersViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/UserListView.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Expose `UserListController` in `UIKit+Delegates` sample
- Expose `UserListController` in `UIKit+Combine` sample
- Expose `UserListController` in `SwiftUI` sample
- Fix comments in `SimpleChannelsViewController`

[CIS-374] Expose UserListController in Sample app

---

Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sources_v3/Controllers/ChannelListController/ChannelListController+SwiftUI_Tests.swift
Sources_v3/Controllers/UserListController/UserListController_Tests.swift
Sources_v3/Database/DTOs/ChannelListQueryDTO.swift
Sources_v3/Database/DTOs/ChannelMemberListQueryDTO.swift
Sources_v3/Database/DTOs/ChannelMemberListQueryDTO_Tests.swift
Sources_v3/Database/DTOs/UserDTO.swift
Sources_v3/Database/DTOs/UserListQueryDTO.swift
Sources_v3/Database/DatabaseContainer_Mock.swift
Sources_v3/Database/DatabaseSession.swift
Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/Query/ChannelListQuery.swift
Sources_v3/Query/ChannelMemberListQuery.swift
Sources_v3/Query/ChannelMemberListQuery_Tests.swift
Sources_v3/Query/Filter.swift
Sources_v3/Query/UserListQuery.swift
Sources_v3/Workers/Background/NewUserQueryUpdater.swift
Sources_v3/Workers/Background/NewUserQueryUpdater_Tests.swift

- Remove `.none` `Filter` option
- Adjust `NewUserQueryUpdater` to handle `nil` filter
- Adjust `Sample` app after introducing `nil` `Filter`

[CIS-383] Remove .none Filter option

---

Sources_v3/Controllers/MemberController/MemberController+Combine.swift
Sources_v3/Controllers/MemberController/MemberController+Combine_Tests.swift
Sources_v3/Controllers/MemberController/MemberController+SwiftUI.swift
Sources_v3/Controllers/MemberController/MemberController+SwiftUI_Tests.swift
Sources_v3/Controllers/MemberController/MemberController.swift
Sources_v3/Controllers/MemberController/MemberController_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR:**
- adds `SwiftUI` wrapper for `ChatChannelMemberController`
- adds `Combine` wrapper for `ChatChannelMemberController`
- fixes the delegate types naming

[CIS-381] Member controller wrappers

---

Sources_v3/Query/ChannelMemberListQuery_Tests.swift
Sources_v3/Query/Sorting.swift
Sources_v3/Query/Sorting_Tests.swift
Sources_v3/Query/UserListQuery_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Fix `Sorting` encoding
_Note: Backend was not returning any errors but sorting was not applied._

[CIS-389] Fix Sorting encoding

---

Sources_v3/APIClient/APIClient_Tests.swift
Sources_v3/APIClient/Endpoints/DeviceEndpoints.swift
Sources_v3/APIClient/Endpoints/DeviceEndpoints_Tests.swift
Sources_v3/APIClient/Endpoints/Payloads/CurrentUserPayloads.swift
Sources_v3/APIClient/Endpoints/Payloads/DevicePayloads.swift
Sources_v3/APIClient/Endpoints/Payloads/DevicePayloads_Tests.swift
Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
Sources_v3/Database/DTOs/CurrentUserDTO.swift
Sources_v3/Database/DTOs/CurrentUserDTO_Tests.swift
Sources_v3/Database/DTOs/DeviceDTO.swift
Sources_v3/Database/DTOs/DeviceDTO_Tests.swift
Sources_v3/Database/DatabaseSession.swift
Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/Models/Device.swift
Sources_v3/Utils/Codable+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj
Tests_v3/Custom Assertions/AssertJSONEqual.swift
Tests_v3/Dummy data/CurrentUserPayload.swift
Tests_v3/Dummy data/DevicePayloads.swift
Tests_v3/MockEnpointResponses/Devices.json

[CIS-366] Device endpoints

---

Sample_v3/Samples/SettingsViewController.swift

**This PR**:
- fixes the compilation error in Sample app

[CIS-391] Fix compilation error in Sample

---

Sources_v3/Controllers/MemberListController/MemberListController+Combine.swift
Sources_v3/Controllers/MemberListController/MemberListController+Combine_Tests.swift
Sources_v3/Controllers/MemberListController/MemberListController+SwiftUI.swift
Sources_v3/Controllers/MemberListController/MemberListController+SwiftUI_Tests.swift
Sources_v3/Controllers/MemberListController/MemberListController.swift
Sources_v3/Controllers/MemberListController/MemberListController_Mock.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR:**
- adds `SwiftUI` wrapper for `ChatChannelMemberListController`
- adds `Combine` wrapper for `ChatChannelMemberListController`

[CIS-387] SwiftUI and Combine wrappers for MemberListController

---

Sample_v3/LoginViewController.swift
Sources_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
Sources_v3/APIClient/Endpoints/MemberEndpoints_Tests.swift
Sources_v3/APIClient/Endpoints/UserEndpoints_Tests.swift
Sources_v3/Controllers/ChannelController/ChannelController.swift
Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
Sources_v3/Controllers/ChannelListController/ChannelListController.swift
Sources_v3/Controllers/ChannelListController/ChannelListController_Tests.swift
Sources_v3/Controllers/MemberListController/MemberListController.swift
Sources_v3/Controllers/MemberListController/MemberListController_Tests.swift
Sources_v3/Controllers/UserListController/UserListController.swift
Sources_v3/Controllers/UserListController/UserListController_Tests.swift
Sources_v3/Query/ChannelListQuery.swift
Sources_v3/Query/ChannelMemberListQuery.swift
Sources_v3/Query/ChannelMemberListQuery_Tests.swift
Sources_v3/Query/ChannelQuery.swift
Sources_v3/Query/ChannelQuery_Tests.swift
Sources_v3/Query/Pagination.swift
Sources_v3/Query/Pagination_Tests.swift
Sources_v3/Query/QueryOptions.swift
Sources_v3/Query/UserListQuery.swift
Sources_v3/Query/UserListQuery_Tests.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater.swift
Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Make `QueryOptions` internal
- Simplify `Pagination` usage

[CIS-376] Make query types more user-friendly

---

Sample_v3/Extensions/Channel+Extensions.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Sources_v3/Models/Channel.swift

- Adds context menu to the messages in the three samples
- If own message, actions are: edit and delete
- If message from other user, actions are: ban or unban user

[CIS-382] Implement member actions in samples

---

Sample_v3/Extensions/ChannelMember+Extensions.swift
Sample_v3/Extensions/Date+Extensions.swift
Sample_v3/Extensions/UITableViewController+Cells.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelMembersViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChat.storyboard
Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
Sample_v3/Samples/CombineSimpleChat/CombineSimpleUsersViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelMembersViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
Sample_v3/Samples/SimpleChat/SimpleUsersViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
Sample_v3/Samples/SwiftUISimpleChat/MemberListView.swift
Sample_v3/Samples/SwiftUISimpleChat/UserListView.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR**:
- adds channel-member-list screen to `UIKit + Delegate` sample
- adds channel-member-list screen to `UIKit + Combine` sample
- adds channel-member-list screen to `SwiftUI` sample

[CIS-388] Expose channel-member-list in SampleApp

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Style/AvatarViewStyle.swift
Sources/UI/Style/ReactionViewStyle.swift
Sources/UI/Views/AvatarView.swift
Sources/UI/Views/ReactionsView.swift

Due to customer requests, commits are atomic

Add extra customization options to UI elements

---

Sources_v3/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources_v3/Controllers/ChannelController/ChannelController.swift
Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
Sources_v3/Controllers/MessageController/MessageController+Combine.swift
Sources_v3/Controllers/MessageController/MessageController+Combine_Tests.swift
Sources_v3/Controllers/MessageController/MessageController+SwiftUI.swift
Sources_v3/Controllers/MessageController/MessageController+SwiftUI_Tests.swift
Sources_v3/Controllers/MessageController/MessageController.swift
Sources_v3/Controllers/MessageController/MessageController_Tests.swift
Sources_v3/Database/DTOs/MessageDTO.swift
Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/Models/Message.swift

- Expose `latestReplies` on `ChatMessage`
- Expose `replies` on `MessageController`

[CIS-404] Expose message replies on MessageController

---

Tests_v3/StreamChatTests/StreamChatStressTestPlan.xctestplan

I decided to try a different approach - every day I'll disable the failing stress tests, hoping that we will be able to isolate the problem better.

[CIS-359] Fix stress tests, vol.6

---

Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewDataSource.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewDelegate.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelNavigationBar.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelViewController.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewDataSource.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewDelegate.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListNavigationBar.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListViewController.swift
StreamChat_v3.xcodeproj/project.pbxproj

...so we can start building these!

Add basic files for UI SDK

---

Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift

Sample v3: Fix crash on SwiftUI empty channels

---

Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift

Show an alert with textfield after pressing add channel button
#no_changelog

Sample v3: Ask for channel name when creating channel

---

Sample_v3/AppDelegate.swift
Sample_v3/Base.lproj/Main.storyboard
Sample_v3/LoginViewController.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListViewController.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelView.swift
Sources_v3/StreamChatUI/Common Views/AvatarView.swift
Sources_v3/StreamChatUI/Common Views/ContainerStackView.swift
Sources_v3/StreamChatUI/NameAndImageProviding.swift
Sources_v3/StreamChatUI/UIConfig.swift
Sources_v3/StreamChatUI/UIExtraData.swift
Sources_v3/StreamChatUI/Utils/UIImageView+Extensions.swift
Sources_v3/StreamChatUI/Utils/UIView+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR**:
- introduces `UIConfig` concept for overriding UI types
- introduces UI components generic over extra-data for channel list 
- introduces `ContainerStackView` for flexible layout
- showcases `StreamChatUI` usage in sample app

[CIS-410] Backbone UI

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Sources/UI/Web View/WebViewController.swift

..so link tap behavior can be overridden
Due to customer request

Open `showWebView` function

---

Sample_v3/AppDelegate.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelView.swift
Sources_v3/StreamChatUI/UIConfig.swift
Sources_v3/StreamChatUI/Utils/UIView+Extensions.swift

**This PR**:
- makes `ChatChannelListCollectionViewCell` self-sizing
- updates `ChatChannelListCollectionViewLayout` to incapsulate spacing and estimated item size
- adds dynamic font and layout margins support to channel list
- updates the way `ChatChannelListVC` loads next channels and updates the list
- fixes layout helpers

[CIS-421] Layout for channel-list

---

Sources_v3/StreamChatUI/Utils/UIImageView+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj
StreamChat_v3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

We'll be using it for gif loading in the future, too

[CIS-415] Introduce and use Nuke for image loading

---

DemoApp/AppDelegate.swift
DemoApp/Assets.xcassets/AccentColor.colorset/Contents.json
DemoApp/Assets.xcassets/AppIcon.appiconset/Contents.json
DemoApp/Assets.xcassets/Contents.json
DemoApp/Base.lproj/LaunchScreen.storyboard
DemoApp/Base.lproj/Main.storyboard
DemoApp/Info.plist
DemoApp/SceneDelegate.swift
DemoApp/ViewController.swift
StreamChat_v3.xcodeproj/project.pbxproj
hooks/pre-commit.sh

Demo -> app as shown in figma designs. We're using a target instead of a separate project to make development easier

Adds Demo app target

---

bootstrap.sh

Fix bootstrap script

---

Sources_v3/StreamChatUI/UIConfig.swift

**This PR** removes init from `UIConfig` and nested types.

[CIS-495] `UIConfig` clean-up

---

Sources_v3/StreamChatUI/Common Views/BaseViews.swift

- A new lifecycle method added - `setUp()`. It's meant to be used for the general setup of the view (setting delegates, adding subviews, etc.)
- A new helper method `updateContentIfNeeded()` which calls `updateContent()` only if it's safe.

Improve view life cycle methods

---

Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageImageGallery.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageMetadataView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageReactionsView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatReadStatusCheckmarkView.swift
Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView+ActionButton.swift
Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView.swift
Sources_v3/StreamChatUI/UIConfig.swift
Sources_v3/StreamChatUI/Utils/UIColor+Extensions.swift

Move most of colors into `UIConfig`
Introduce way to calculate highlighted/disabled/unselected colors
Introduce designers color pallet for future use

Introduce color palette into UIConfig

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController.swift

Fallback on inconsistent table view update (fix crash)

---

Sample_v3/LoginViewController.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelRouter.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageContentView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListRouter.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageReactionsView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageThreadInfoView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatThreadVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListRouter.swift
Sources_v3/StreamChatUI/UIConfig.swift
StreamChat_v3.xcodeproj/project.pbxproj

In this PR I:
- reduce amount of layout warnings within message view
- extract message list in separate view controller
- create thread view controller

[CIS-463] Reuse Chat channel controller for threads

---

Sample_v3/Configuration.swift

- Introduces new users and new API Key to Sample applications.
- You can go to any sample app and try out if there are new users.

Add new api key and sample users

---

Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposerCommandCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
Sources_v3/StreamChatUI/ChatChannel/MessageInputSlashCommandView.swift
Sources_v3/StreamChatUI/UIConfig.swift
Sources_v3/StreamChatUI/Utils/String+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj

- Implement slash command UI logic
- Update `MessageInputSlashCommandView` with base view inheritance
_Note: LLC attachment decoding issue will be fixed separately._

[CIS-512] Slash commands UI composer logic

---

Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController.swift
Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
Sources_v3/StreamChat/Query/Sorting/UserListSortingKey.swift
Sources_v3/StreamChat/Workers/UserListUpdater.swift
Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift

The improvements arose when I've tried to use ChatUserSearchController in the demo app.
Please check commit descriptions.

Improve ChatUserSearchController

---

Sources_v3/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
Sources_v3/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
Sources_v3/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
Sources_v3/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
Sources_v3/StreamChat/Workers/Background/MessageSender.swift
Sources_v3/StreamChat/Workers/Background/MessageSender_Tests.swift
StreamChat_v3.xcodeproj/project.pbxproj
Tests_v3/StreamChatTests/MockEnpointResponses/WrappedMessage.json

- Implement `MessagePayload` saving after successful message sending

[CIS-531] Message response payload saving

---

Sources_v3/StreamChat/Database/DTOs/ChannelMemberListQueryDTO.swift
Sources_v3/StreamChat/Database/DTOs/MessageReactionDTO.swift

Fix initialization of DTOs

---

Sources_v3/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources_v3/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources_v3/StreamChat/Controllers/ChannelListController/ChannelListController.swift
Sources_v3/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
Sources_v3/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
Sources_v3/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
Sources_v3/StreamChat/Controllers/MemberController/MemberController.swift
Sources_v3/StreamChat/Controllers/MemberController/MemberController_Tests.swift
Sources_v3/StreamChat/Controllers/MemberListController/MemberListController.swift
Sources_v3/StreamChat/Controllers/MemberListController/MemberListController_Tests.swift
Sources_v3/StreamChat/Controllers/MessageController/MessageController.swift
Sources_v3/StreamChat/Controllers/MessageController/MessageController_Tests.swift
Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController.swift
Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
Sources_v3/StreamChat/Controllers/UserController/UserController.swift
Sources_v3/StreamChat/Controllers/UserController/UserController_Tests.swift
Sources_v3/StreamChat/Controllers/UserListController/UserListController.swift
Sources_v3/StreamChat/Controllers/UserListController/UserListController_Tests.swift
Sources_v3/StreamChat/Workers/ChannelListUpdater_Mock.swift
Sources_v3/StreamChat/Workers/ChannelMemberListUpdater_Mock.swift
Sources_v3/StreamChat/Workers/ChannelMemberUpdater_Mock.swift
Sources_v3/StreamChat/Workers/ChannelUpdater_Mock.swift
Sources_v3/StreamChat/Workers/UserListUpdater_Mock.swift

Only `ChannelController` as POC, rest incoming

[CIS-529] Unify Controller lifetime

---

DemoApp/Base.lproj/Main.storyboard
DemoApp/ChatPresenter.swift
DemoApp/CreateChatViewController.swift
DemoApp/CreateGroupViewController.swift
DemoApp/LoginViewController.swift
DemoApp/NameGroupViewController.swift
StreamChat_v3.xcodeproj/project.pbxproj

This PR includes:
- DM Channel creation screen
- Group channel creation screen
- Group overview/naming screen
Which should've been 3 separate PRs.\
Prototypes will be polished in an upcoming PR

[CIS-488] [Demo] Prototype Channel creation screens

---

CHANGELOG.md
Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift

V2: disable reactions when connection is down

---

DemoApp/ChatPresenter.swift

**This PR** fixes build errors in `Demo` app caused by [message actions follow-up PR](https://github.com/GetStream/stream-chat-swift/pull/680)

Fix `Demo` app

---

Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
Sources_v3/StreamChatUI/UIConfig.swift

- Implement image and document attachments sending

[CIS-543] Document picker and attachment sending

---

Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionView.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListRouter.swift

- Creates DataSources for SuggestionsViewController both mentions and commands, also deletes SuggestionsViewControllerPresenter and handles the presentation of this a bit better ;) 
- Go to chat and try commands and mentions, expect mentions not to fill the name yet, this will be handled in diff coming soon.

[CIS-513] Presenting Suggestion and creating DataSource

---

Sources_v3/StreamChat/APIClient/Endpoints/Payloads/AttachmentPayload.swift
Sources_v3/StreamChat/APIClient/Endpoints/Payloads/AttachmentPayload_Tests.swift
Sources_v3/StreamChat/Models/Attachment.swift
Sources_v3/StreamChat/Models/Attachment_Tests.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageLinkPreviewView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageContentView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListRouter.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Sources_v3/StreamChatUI/UIConfig.swift
StreamChat_v3.xcodeproj/project.pbxproj
Tests_v3/StreamChatTests/MockEnpointResponses/Attachment/AttachmentPayload+Giphy.json
Tests_v3/StreamChatTests/MockEnpointResponses/Attachment/AttachmentPayload+LinkImage.json

- `AttachmentPayload.swift`: `link` is our custom attachment type, backend mark attachments that were created from link by populating `og_scrape_url` field

[CIS-453] Add links preview

---

Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift

This test was failing because `newUser { database.viewContext.user(...) }` was accessed inside a `database.writeSync` closure. `viewContext` should always be accessed in main queue.

Fix flaky userlistupdater test

---

Sources_v3/StreamChat/Database/DTOs/MessageDTO.swift
Sources_v3/StreamChat/Workers/MessageUpdater.swift
Sources_v3/StreamChat/Workers/MessageUpdater_Tests.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/AttachmentListViewData.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatFileAttachmentListView.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageAttachmentsView.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView.swift
Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageLinkPreviewView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageGroupPart.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatRepliedMessageContentView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Sources_v3/StreamChatUI/UIConfig.swift
Sources_v3/StreamChatUI/Utils/ChatMessage+Extensions.swift
Sources_v3/StreamChatUI/Utils/ChatMessageAttachment+Extensions.swift
StreamChat_v3.xcodeproj/project.pbxproj

**This PR**:
- shows `ephemeral` messages with actions in message list
- invokes LLC methods when message action is tapped
- disables message actions for `ephemeral` messages
Screenshots:

[CIS-521] Attachment actions (UI)

---

Sources_v3/StreamChatUI/ChatChannel/Reactions/ChatMessageReactionsBubbleView+Default.swift
Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift

**This PR** improves message actions pop-up UX:
- fixes jumps of partially visible messages
- updates layout to respect safe-area insets
- autoscrolls to make all content + actions visible
https://user-images.githubusercontent.com/12818985/103361309-394b0880-4aca-11eb-9553-e8cc1209cb02.mov

[CIS-524] Message actions UX

---

DemoApp/Base.lproj/Main.storyboard
DemoApp/CreateChatViewController.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift

Adds state management and actual chat creation (with the help of composer!)
Missing: Displaying chat when the user(s) are selected
Checkout and test is recommended!
https://user-images.githubusercontent.com/770464/103410677-af07b080-4b6c-11eb-875a-386a1e957eab.mov

Polish Chat creation screen

---

Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
Sources_v3/StreamChatUI/Generated/L10n.swift

- Implements tapping on user suggestions, so it fills the user id to the composer textView
https://user-images.githubusercontent.com/17381941/103372861-82538a80-4ad3-11eb-9a70-41c37da4f92d.mov

[CIS-465] Add reaction on tapping user mention

---

Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
Sources_v3/StreamChatUI/ChatChannel/ChatChannelRouter.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatThreadVC.swift
Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift

What have been changed:
- Improved scrolling experience when reaching the top by disabling "infinite scroll" hack
- Scroll to bottom on message send
- Add spacing between last message and composer
- Add keyboard hide on swipe down

Improve message list UX

---

Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatFileAttachmentListView+ItemView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
Sources_v3/StreamChatUI/Common Views/BaseViews.swift
Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
Sources_v3/StreamChatUI/UIConfig.swift

Interesting points:
- `mode` naming could be better
- on traits changes we need to call `updateContent` because some UI change depends on data. But it should happen only twice a day, only for views on screen, so I would say it's fine
_Cauz of upload limits, video can be found in slack_

Improve dark mode experience

---

Sources_v3/StreamChatUI/ChatChannel/ChatChannelRouter.swift
Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageMetadataView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
Sources_v3/StreamChatUI/ChatChannelList/ChatSwipeableListItemView.swift
Sources_v3/StreamChatUI/Common Views/OnlineIndicatorView.swift
Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift
Sources_v3/StreamChatUI/UIConfig.swift

This PR Introduces:
- Fixing of user experience on deleting
- Not scrolling on message reactions
- Fix of almost-invisible border on `OnlineIndicatorView`
- Smaller font for label which shows timestamp of message

UX and UI Fixes of the application

---

Sources_v3/StreamChatUI/UIConfig.swift

Update reaction constants to use same across all frontends

Use reactions from RN

---

Sources_v3/StreamChatUI/MessageActionsPopup/ChatMessagePopupViewController.swift

**This PR** updates actions pop-up to apply initial content offset only once elimination content jumps when layout is changed (reaction is added/removed OR gif is loaded)

[CIS-554] Fix content jumps on message actions pop-up

---

.github/workflows/ci.yml
Sources_v3/StreamChat/APIClient/APIClient_Tests.swift

Add Slack bot on failed tests

---

CHANGELOG.md
Sources/UI/Chat/Composer/ComposerView.swift

Fix ComposerView layout overlap when multiple types are uploaded

---

Sources_v3/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
Sources_v3/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
Sources_v3/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources_v3/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources_v3/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources_v3/StreamChat/Controllers/MessageController/MessageController.swift
Sources_v3/StreamChat/Controllers/MessageController/MessageController_Tests.swift
Sources_v3/StreamChat/Database/DTOs/MessageDTO.swift
Sources_v3/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources_v3/StreamChat/Database/DatabaseSession.swift
Sources_v3/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources_v3/StreamChat/Models/Message.swift
Sources_v3/StreamChat/Workers/Background/MessageSender_Tests.swift
Sources_v3/StreamChat/Workers/ChannelUpdater.swift
Sources_v3/StreamChat/Workers/ChannelUpdater_Mock.swift
Sources_v3/StreamChat/Workers/ChannelUpdater_Tests.swift
Sources_v3/StreamChat/Workers/MessageUpdater.swift
Sources_v3/StreamChat/Workers/MessageUpdater_Mock.swift
Sources_v3/StreamChat/Workers/MessageUpdater_Tests.swift
Tests_v3/StreamChatTests/Dummy data/MessagePayload.swift
Tests_v3/StreamChatTests/MockEnpointResponses/Message.json

In this PR:
- Add LLC support for quoted messages sending and receiving
UI part will be done in `CIS-575`.

[CIS-505] Quoted messages

---

Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageLinkPreviewView.swift
Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift

Updated:
- forgotten constraint priority on link preview
- contentOffset calculation for keyboard appearance

Message list small fixes

---

Sources/Client/Client/Client+Request.swift
Sources_v3/StreamChat/ChatClient.swift
Sources_v3/StreamChat/ChatClient_Tests.swift

#skip_changelog since this change is internal only

Remove session metadata from both versions

---

DemoApp/Base.lproj/Main.storyboard
DemoApp/CreateChatViewController.swift
DemoApp/CreateGroupViewController.swift

All High and most of Mid issues resolved, with a sprinkle of Lows here and there

[CIS-583] Resolve design issues in chat creation

---

Sources/StreamChat/CHANGELOG.md
Sources/StreamChat/Config/Token.swift
Sources/StreamChat/Config/TokenProvider_Tests.swift

Fix development token

---

Sources/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
Sources/StreamChatUI/Common Views/ChatAvatarView.swift
Sources/StreamChatUI/UIConfig.swift
StreamChat.xcodeproj/project.pbxproj

**This PR** fixes `ChatUserAvatart` type name
#no_changelog

Fix cyrillic letter in `ChatAvatarView` type name

---

Sources/StreamChatUI/UIConfig.swift
Sources/StreamChatUI/Utils/UIFont+Extensions.swift

- Remove `.medium` weight from `body` font

[CIS-600] Remove `.medium` weight from `body` font

---

Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
Sources/StreamChat/Controllers/ListDatabaseObserver_Tests.swift
Sources/StreamChat/Database/DTOs/ChannelDTO.swift
Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChat/Database/DTOs/UserDTO.swift
Sources/StreamChat/Database/DTOs/UserDTO_Tests.swift
Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources/StreamChat/Utils/AssignIfDifferent.swift
Sources/StreamChat/Utils/AssignIfDifferent_Tests.swift
Sources/StreamChat/Utils/ChangeHashable.swift
StreamChat.xcodeproj/project.pbxproj

Since User, Channel and Message composes of nearly all updated entities, this PR focuses on these 3.

[CIS-582] Prevent unnecessary DB updates

---

Sources/StreamChatUI/Utils/Bundle+Extensions.swift
StreamChatUI.podspec

Resolves #774
I don't know a way to resolve this issue without the compiler check, suggestions welcome
Tested and works for both direct import (DemoApp) and Cocoapods

[CIS-617] Use resource_bundles for StreamChatUI

---

README.md

Users are now encouraged to start using v3 for their new projects.

[CIS-616] Update README with more info about 3.x

---

Dangerfile

Disable changelog warning for StreamChatUI in DangerFile, hopefully this works on first try 😅

[CIS-631] Disable changelog warning for StreamChatUI

---

Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatChannelVC.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift

Changes the Routers setter to the public, in order to change the routing with multiple instances.
#no_changelog

[CIS-639] Change Routers setter to public

---

Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageBubbleView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/UIConfig+MessageList.swift

[CIS-625] Separate text and attachment cells

---

DemoApp/CreateChatViewController.swift
Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift

Just a couple of small improvements

Improve public API for custom attachments

---

.github/workflows/ci.yml
.swiftformat-snippets
.swiftlint.yml
DocsSnippets/00-Introduction/00-ChatClient.swift
DocsSnippets/00-Introduction/01-Channels.swift
DocsSnippets/00-Introduction/02-Messages.swift
DocsSnippets/00-Introduction/03-Events.swift
DocsSnippets/01-UX/00-Quick-Start/00-Client-Setup.swift
DocsSnippets/01-UX/00-Quick-Start/01-Channels-Storyboard.swift
DocsSnippets/01-UX/00-Quick-Start/02-Channels-Code.swift
DocsSnippets/01-UX/00-Quick-Start/03-Messages-Storyboard.swift
DocsSnippets/01-UX/00-Quick-Start/04-Messages-Storyboard.swift
DocsSnippets/DocsSnippets.h
DocsSnippets/Info.plist
DocsSnippets/Objects.swift
StreamChat.xcodeproj/project.pbxproj
StreamChat.xcodeproj/xcshareddata/xcschemes/DocsSnippets.xcscheme
fastlane/Fastfile
fastlane/README.md
hooks/pre-commit.sh

Each snippet has its own file. I tried to mimick the docs structure with the folders as well.

Add DocsSnippets target

---

CHANGELOG.md
Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
Sources/StreamChat/Workers/CurrentUserUpdater.swift
Sources/StreamChat/Workers/CurrentUserUpdater_Mock.swift
Sources/StreamChat/Workers/CurrentUserUpdater_Tests.swift
Tests/StreamChatTests/Dummy data/CurrentUserPayload.swift

The implementation was incorrect and the test wasn't structured properly enough to capture it.

Fix failing devices test

---

Sources/StreamChatUI/Common Views/BaseViews.swift

- Fix view lifecycle methods called multiple times

[CIS-668] Fix view lifecycle methods called multiple times

---

Documentation/Installation.MD
README.md
Sample/README.md
Sources/StreamChat/README.md

Update information about project

---

.github/workflows/beta.yml
.github/workflows/ci.yml
.github/workflows/nightly-tests.yml
CHANGELOG.md
Integration/CocoaPods/.gitignore
Integration/CocoaPods/CocoaPods.xcodeproj/project.pbxproj
Integration/CocoaPods/CocoaPods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Integration/CocoaPods/CocoaPods.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Integration/CocoaPods/CocoaPods.xcworkspace/contents.xcworkspacedata
Integration/CocoaPods/CocoaPods.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Integration/CocoaPods/CocoaPods/AppDelegate.swift
Integration/CocoaPods/CocoaPods/Assets.xcassets/AccentColor.colorset/Contents.json
Integration/CocoaPods/CocoaPods/Assets.xcassets/AppIcon.appiconset/Contents.json
Integration/CocoaPods/CocoaPods/Assets.xcassets/Contents.json
Integration/CocoaPods/CocoaPods/Base.lproj/LaunchScreen.storyboard
Integration/CocoaPods/CocoaPods/Base.lproj/Main.storyboard
Integration/CocoaPods/CocoaPods/Info.plist
Integration/CocoaPods/CocoaPods/SceneDelegate.swift
Integration/CocoaPods/CocoaPods/ViewController.swift
Integration/CocoaPods/podfile
Sources/StreamChatUI/.swiftgen.yml
Sources/StreamChatUI/Generated/L10n.swift
Sources/StreamChatUI/Generated/L10n_template.stencil
fastlane/Fastfile
fastlane/README.md

The generated strings file didn't use the correct resources bundle for CocoaPods.
I also added an integration test for CocoaPods which will be run on CI for every PR.
---
Closes #839

Fix incorrect bundle for strings with CocoaPods integration

---

CHANGELOG.md
Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelCodingKeys.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources/StreamChat/Database/DTOs/ChannelDTO.swift
Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources/StreamChat/Models/Channel.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Sources/StreamChat/Workers/ChannelUpdater.swift
Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
Tests/StreamChatTests/DummyData/ChannelPayload.swift
Tests/StreamChatTests/MockEnpointResponses/Channel.json

Not doing:
- Not introducing check for sending a new message

[CIS-691] Add support for cooldown/throttling

---

Sources/StreamChat/Models/ChannelType.swift
Sources/StreamChat/Query/ChannelQuery.swift
Sources/StreamChat/Query/ChannelQuery_Tests.swift
Tests/Shared/ChannelId.swift

Add tests and fix custom channel path parameters

[CIS-706] Fix custom channel path parameters

---

.github/workflows/full-checks.yml

- Add iOS 13 to building sample apps
- Adds latest iOS to Stress tests
- Runs Stress tests only in Release

Cleanup CI Full Checks Tests

---

DemoApp/Info.plist

This reverts commit a738e656024df565bc5bba33a0a9c738277ea6fd.
#skip-changelog
#skip-ci

Revert "Allow arbitrary loads in Demo app"

---

.github/workflows/cancel.yml

Add cancel workflow action

---

DocsSnippets/01-UX/06-Customizing-Views/07-Injecting-Custom-Subclass-2.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageBubbleView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift
Sources/StreamChatUI/UIConfig+MessageList.swift

Simplifies the way we create cells. All cell subviews are instantiated lazily which speeds up the initial setup time.
This is not production ready yet. The implementation has to cleaned-up and properly tested.

[CIS-650] Create flexible mother cell

---

Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView_Tests.swift

Text properties of `ChatChannelListItemView` exposed.
Use case: user will be able to directly change/override the properties when wrapped in SwiftUI custom view.

[CIS-732] Expose properties of ChatChannelListItemView

---

DemoApp/AdvancedOptionsViewController.swift
DemoApp/Base.lproj/Main.storyboard
DemoApp/LoginViewController.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsBubbleView.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift
Sources/StreamChatUI/Utils/Animation.swift

Improves overal experience of Demo App:
1. Adds loading indicator to channel loading
2. Adds Haptic feedback on longpress of message and improves animation
3. New chat screen add button now supports dark mode
4. Advanced options menu is now presented modally 
5. TableView on user selection is now bouncing

[CIS-736] Improve Demo App experience 🤔

---

fastlane/Fastfile

The options were missing from some release test lanes.

Add missing options argument to fastlane lanes

---

Sources/StreamChat/ChatClient_Tests.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources/StreamChat/Controllers/ChannelListController/ChannelListController+SwiftUI_Tests.swift
Sources/StreamChat/Controllers/ConnectionController/ConnectionController+SwiftUI_Tests.swift
Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController+SwiftUI_Tests.swift
Sources/StreamChat/Controllers/MessageController/MessageController+SwiftUI_Tests.swift
Sources/StreamChat/Controllers/UserListController/UserListController+SwiftUI_Tests.swift
Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
Sources/StreamChat/Database/DataStore_Tests.swift
Tests/Shared/Await.swift

Another PR with missing explicit DB release calls.

Make database release explicit

---

bootstrap.sh

Just a couple of small improvements based on the issues reported by @skorepak:
- the script now prints an explicit error message when something fails:
- the script creates the `.git/hooks` directory if needed

Improve bootstrap experience

---

.github/workflows/docusaurus.yml
stream-chat-swift-docs/connection-status.md
stream-chat-swift-docs/debugging.md
stream-chat-swift-docs/docs/ui-cheat-sheet.md
stream-chat-swift-docs/events.md
stream-chat-swift-docs/src/css/custom.css
stream-chat-swift-docs/working-with-user.md

This is for @DominikBucher12 :)
I will check if the workflow works now

Update tint color and fix docusaurus workflow

---

CHANGELOG.md
Dangerfile

and include missing changelog entry for #945

Convert danger CHANGELOG check to message level

---

Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift

Yet another try to fix the issue with incorrect collection view update...

Don't update collection view unless it's fully laid out

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift

Fixes #800 
I found that "Thread Reply" feature is not working for all sample apps ( iMessageClone, SlackClone, DemoApp )
I fixed the bug by following the comment of @cjmconie

Fix "thread reply" on StreamChatUI

---

Sources/StreamChat/WebSocketClient/Events/MessageEvents.swift
Sources/StreamChat/WebSocketClient/Events/MessageEvents_Tests.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatTests/MockEnpointResponses/Events/Message/MessageRead+MissingUnreadCount.json

This is a follow up to #969 based on the discussion with @b-onc

Add optional `unreadCount` to `MessageReadEvent`

---

Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift
Sources/StreamChatUI/Utils/DateFormatter+Extensions.swift

* Added list update based on the changes from `ChatChannelController`
* Integrate message composer
* Implement scrolling to the latest message

Message list composer

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatVC.swift

All work was done in #969, this is just the final piece 🍒 🍰

[CIS-778] Call `markRead` on `ChatVC.viewDidAppear`

---

Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift

Implement correct long press on message cell using long press recognizer.

Implement correct long press on message cell

---

Sources/StreamChatUI/ChatMessageList/RETHINK/MessageContentView.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsView.swift
Sources/StreamChatUI/Utils/CGPoint+Extensions.swift
Sources/StreamChatUI/Utils/CGRect+Extensions.swift
Sources/StreamChatUI/Utils/UIImage+Extensions.swift
StreamChat.xcodeproj/project.pbxproj

**This PR**:
- introduces new bubble for reactions view
- masks `MessageCell` to have space around reactions bubble
- introduces some `CGRect/CGPoint` helpers
- introduces `UIImage` helper to make a mask

Message reactions bubble

---

DemoApp/DemoUsers.swift

Where we use Star Wars themed people

Switch DemoApp users to SampleApp users

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift
Sources/StreamChatUI/ChatMessageList/RETHINK/MessageThreadVC.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift

* Fixes crash when presenting popup actions vc
* Disables tap gesture when hitting actions
* with that it fixes delete message alert not presenting itself
* Implementation is done also in the thread vc but that currently doesn't support the popup

Fix messages popup

---

Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift

Fixes 2 flaky tests on `CurrentUserController.synchronize()`

Fix `CurrentUserController.synchronize()` flaky Tests

---

DemoApp/ChatPresenter.swift

Fix DemoApp not compiling due to leftover optional

---

.github/workflows/DemoAppTestFlight.yml
fastlane/Fastfile
fastlane/README.md

This PR includes a fastlane lane for publishing as well as GitHub actions workflow.
Also added APPSTORE_API_KEY secret so now GitHub actions can authorise in appstoreconnect if necessary

[CIS-708] Implement DemoApp publishing to TestFlight

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListScrollOverlayView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/Components+MessageList.swift
StreamChat.xcodeproj/project.pbxproj

Add static label that changes its text based on message that is displayed below.
Currently it looks like this, I expect some changes there.
When doing this I noticed that dynamic type doesn't work correctly on message list so I also fixed that.

Add date label to message list

---

DemoApp/CreateChatViewController.swift
DemoApp/CreateGroupViewController.swift
DemoApp/DemoAppCoordinator.swift
DemoApp/NameGroupViewController.swift

Implemented this while debugging the ChannelRead issues

Add group chat creation to DemoApp

---

Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
Sources/StreamChat/Models/Message.swift
Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
Sources/StreamChat/Workers/MessageUpdater_Tests.swift
Sources/StreamChatTestTools/Models/ChatMessage_Mock.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift

**This PR**:
- exposes attachment counts on `ChatMessage`
- hides type-erased attachments on `ChatMessage`

[CIS-844] Expose attachment counts on `ChatMessage`

---

Sources/StreamChat/Models/Attachments/AnyAttachmentPayload.swift
Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageFileAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageLinkAttachment.swift
Sources/StreamChatTestTools/Models/Attachments/ChatMessageLinkAttachment_Mock.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageLinkPreviewView_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift

**This PR** adds missing documentation to updated attachment types

Attachments documentation

---

Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC_Tests.swift

Fixes potential crashes when there are collection view changes. Checks if there are any conflicting changes, if there is, reloads the collection data, instead of performing batch updates.

Add safer updates to collection view changes

---

stream-chat-swift-docs/docs/guides/ui-customization.md

Add basic draft for UI customization guide

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift

Add Channel Avatar View to MessageList header

---

Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift

Fixes threads and delete relates issues.

Polish UI for beta release 4.0 (vol.4)

---

Package.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
StreamChat.xcodeproj/project.pbxproj

**This PR**:
- exposes `isMessageLastInSequence` on `ChatMessageLayoutOptionsResolver`
- adds missing tests to `ChatMessageLayoutOptionsResolver` type

Audit `ChatMessageLayoutOptionsResolver`

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListKeyboardObserver.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift

**This PR** fixes message list layout issues when actions pop-up is requested when the keyboard is shown
https://user-images.githubusercontent.com/12818985/120458248-cbb84680-c39f-11eb-940b-9e1544c08146.mov
https://user-images.githubusercontent.com/12818985/120458303-d70b7200-c39f-11eb-85e3-bbbe0d00b523.mov

Fix message list layout glitches

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/Composer/ComposerVC.swift

- Opens missing APIs of ComposerVC
- Fixes composer layout on Landscape
- Fix message list animation glitches when keyboard appears.

Fix Composer + Keyboard layout issues

---

Sources/StreamChatUI/CommonViews/ContainerStackView.swift

This was causing occasional layout feedback loops...

Don't force re-layout in `ContainerStackView`

---

Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift

Make `InputTextView` listen only to its own changes

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/Components.swift
Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift

Just a couple of forgotten hardcoded types...

Fix hardcorded view controller types

---

CHANGELOG.md
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/WebSocketClient/WebSocketClient.swift
Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
Sources/StreamChat/Workers/EventNotificationCenter.swift

Fix `CurrentUserDTO` not saved after completion of `reloadUserIfNeeded`

---

Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift

The C was the Russian "C" and was not recognized by swift-doc

Fix invalid letter in ChatMessageCollectionViewCell

---

Sources/StreamChatUI/CommonViews/Suggestions/ChatSuggestionsViewController.swift
Sources/StreamChatUI/Composer/ComposerVC.swift

The way we present suggestions was not compatible with SwiftUI. I updated the logic to use autolayout rather than manual frame calculation.

Composer SwiftUI compatibility fixes

---

Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputTextView.swift
Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsView+ItemView.swift

Rename flagged funcs (3.x beta)

---

CHANGELOG.md
Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsView+ItemView.swift
Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
Sources/StreamChatUI/ImageGallery/ImageGalleryVC.swift
Sources/StreamChatUI/ImageGallery/ZoomDismissalInteractionController.swift
Sources/StreamChatUI/ImageGallery/ZoomTransitionController.swift

Rename flagged function names (4.x)

---

Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputTextView.swift
Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsView+ItemView.swift

Rename flagged func names (3.x)

---

docusaurus/docs/iOS/guides/working-with-channel-list.md

Reordered the doc and some headers, and fixed the image for docusaurus. Still needs content review though

Update Working with Channel List guide

---

Sources/StreamChatUI/Composer/ComposerVC.swift

Adds support for limiting the length of the composer message input.

Add support for composer message input max length

---

docusaurus/docs/iOS/guides/push-notifications.md
docusaurus/docs/iOS/guides/working-with-messages.md

* subj
* Fix a broken link in Working with messages guide

Add a guide on push notifications

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactions+Types.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsVC.swift

So a slack-like reactions view is possible

[CIS-915] Introduce `score` to `ChatMessageReactionData`

---

CHANGELOG.md
Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChat/Models/ChatMessage_Tests.swift
Sources/StreamChat/Models/Message.swift
Sources/StreamChatTestTools/Models/ChatMessage_Mock.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC+SwiftUI_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC_Tests.swift
Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView+SwiftUI_Tests.swift
Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView_Tests.swift
Sources/StreamChatUI/ImageGallery/ImageGalleryVC_Tests.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC_Tests.swift
Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC_Tests.swift
Tests/StreamChatUITests/ChatChannel.swift
Tests/StreamChatUITests/ChatMessage_Tests.swift

[CIS-935] Expose `cid` on `Message`

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListKeyboardObserver.swift

**This PR** puts back undocked keyboard support

Undocked keyboard support

---

docusaurus/docs/iOS/common-content/components-note.md
docusaurus/docs/iOS/common-content/theming-note.md
docusaurus/docs/iOS/guides/working-with-custom-attachments.md

- Fixes grammar of `<ComponentsNote/>`
- Adds `<ThemingNote/>` doc component

Add <ThemingNote/> doc component

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift

**This PR**:
- fixes weird scroll to bottom animation (we go to the first message and then show the most recent one with animation)
- fixes scrolling to bottom when someone is typing if the last message was not fully visible (when the last message is huge the automatic scrolling would be unwanted)
https://user-images.githubusercontent.com/12818985/123972038-31a9e500-d9c3-11eb-8185-1aea049fa99c.mp4

[CIS-976] Scroll to bottom animation

---

CHANGELOG.md
Sources/StreamChat/Controllers/SearchControllers/UserSearchController.swift
Sources/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
Sources/StreamChat/Query/Filter.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/Composer/ComposerVC.swift

With this PR, customizing mentions to work with multi-tenancy is possible. This also opens possibility of using UserSearchController is a variety of custom manners

[CIS-929] UserSearch with given Query

---

DemoApp/ChatPresenter.swift
DemoApp/CreateChatViewController.swift
DemoApp/DemoAppCoordinator.swift

I think this will make everyone's lives much easier
https://user-images.githubusercontent.com/770464/124301263-dc570a80-db5f-11eb-9e86-8df46a2e05cb.mp4

Add debug options to demo app

---

.github/workflows/distribute-test-build.yml
.github/workflows/docusaurus.yml
.github/workflows/full-checks.yml
.github/workflows/macos-checks.yml
.github/workflows/smoke-checks.yml
.github/workflows/testflight.yml

Improvement for github actions. Now we'll be aware then TestFlight deployment fails, too

Fix GH Actions Slack reporting action and add it to more workflows

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift

**This PR** fixes the crash on message list by checking that the row we wanna scroll to exists.

[CIS-999] Check row is within bounds before scroll

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/Attachments/AttachmentViewInjector.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageGalleryView.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageGiphyView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/Utils/UIView+Extensions.swift

**This PR** fixes messages changing their size/position when channel is opened
https://user-images.githubusercontent.com/12818985/124967778-7968e600-e02d-11eb-9239-eacbdf788a29.mp4
https://user-images.githubusercontent.com/12818985/124967807-84bc1180-e02d-11eb-8522-e8fc041d83f8.mp4

[CIS-985] Fix messages changing their sizes when channel is opened

---

CHANGELOG.md
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents

- This  PR fixes the issue where multiple messages in a channel could not quote a single same message.

[CIS-1003] Fix multiple messages in a channel cannot quote a single message

---

Sources/StreamChat/Workers/Background/MessageSender.swift

A crash was reproducing for me in this place because we read `MessageDTO`'s property on `sendingDispatchQueue`.

[CIS-1006] Fix a crash in MessageSender

---

CHANGELOG.md
Package.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
Sources/StreamChatUI/Utils/CollectionUpdatesMapper.swift
Sources/StreamChatUI/Utils/CollectionUpdatesMapper_Tests.swift
StreamChat.xcodeproj/project.pbxproj

https://github.com/GetStream/stream-chat-swift/issues/1283
@evsaev suggested that we experience the same thing we have for channel list, hence here goes the same fix

[CIS-1029] Fix message list crashing on updates

---

Sources/StreamChatUI/ChatMessageList/TypingIndicatorView.swift

**This PR** makes `TypingIndicatorView.content` open

[CIS-1032] Make `TypingIndicatorView.content` open

---

CHANGELOG.md

**This PR** moves CHANGELOG entry to the upcoming section

Move `EventsController` stuff to upcoming section in CHANGELOG

---

SlackClone/SlackMessageOptionsResolver.swift
YouTubeClone/MessageOptionsResolver/YTMessageLayoutOptionsResolver.swift
iMessageClone/iMessageChatMessageContentView.swift

- This PR fixes the overrides for the method `optionsForMessage(...)` in the sample apps.

[CIS-1041] Fix sample apps to handle `ChatMessageLayoutOptionsResolver` deprecations

---

CHANGELOG.md
Sources/StreamChat/Models/Attachments/ChatMessageAudioAttachment.swift
Sources/StreamChat/Models/ChatMessage.swift
StreamChat.xcodeproj/project.pbxproj

We don't provide UI support as of now, only LLC support is there. Users need to build their own UI components handling this attachment type.
Thanks @felyfely for the help!

[CIS-1068] Introduce AudioAttachments

---

Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware_Tests.swift

This middleware should be able to see un-saved data from EventDataProcessorMiddleware so it can edit that data.
Check Jira ticket for more info.

[CIS-1077] Add ChannelVisibilityEventMiddleware pendingChanges test

---

CHANGELOG.md
Sources/StreamChat/Query/Sorting/ChannelListSortingKey.swift
Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsVC.swift

Also, some functions in `ChatMessageReactionsVC` needed to be `open`

[CIS-1091] Introduce `ChannelListSortingKey`s

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift

[CIS-1078] Remove print statements

---

docusaurus/docs/iOS/guides/migrating-from-3-to-4.md

[CIS-1052] Update v3 migration guide

---

Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/RawJSON_Tests.swift
Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
Tests/StreamChatTests/MockEnpointResponses/MessageWithBrokenAttachments.json

Some more tests we did not have around custom data and RawJSON, I wrote this while trying to reproduce some bugs. Nothing broke I figured its good to keep them :)

Add more test around extra data and RawJSON

---

CHANGELOG.md
Sources/StreamChatUI/Gallery/ZoomAnimator.swift
Sources/StreamChatUI/Gallery/ZoomDismissalInteractionController.swift
Sources/StreamChatUI/Gallery/ZoomTransitionController.swift
Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift

Removes all the force unwraps on weak refs to avoid potential crashes.

[CIS-1134] Fix crash when dismissing gallery images

---

Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift

Fixes a crash caused by the fix of removing forced weak refs.

Fix crash when reacting a message

---

CHANGELOG.md
Package.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads_Tests.swift
Sources/StreamChat/APIClient/Endpoints/Requests/MissingEventsRequestBody_Tests.swift
Sources/StreamChat/Utils/Codable+Extensions.swift
Sources/StreamChat/Utils/JSONDecoder_Tests.swift
Sources/StreamChat/Utils/JSONEncoder_Tests.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
StreamChat.xcodeproj/project.pbxproj

[-] Added check that dateString is non-empty before removing last element

[CIS-1145] Decode RemoveLast Crash

---

CHANGELOG.md
Sources/StreamChatUI/Composer/ComposerVC.swift
Sources/StreamChatUI/Composer/ComposerVC_Tests.swift

- Support `options.minimumRequiredCharacters = 0` so that suggestions are presented after the @
- Improve search result ordering, matches with same distance from search are not sorted consistently (by id)

CIS-1160 Better autocomplete for mentions

---

DemoApp/AppDelegate.swift
DemoApp/DemoAppCoordinator.swift
DemoAppPush/NotificationService.swift

Fix push for demo app
- Replace `UserDefaults.standard` with `UserDefaults(suiteName: applicationGroupIdentifier)`
- Call notification handler when something does not work

Fix demo app push extension

---

CHANGELOG.md
DemoApp/DemoAppCoordinator.swift
DemoAppPush/NotificationService.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift

Fixes an issue where message cells are not updating correctly their size

Fix message edits

---

DemoApp/DemoAppCoordinator.swift
Sources/StreamChat/APIClient/RequestDecoder.swift
Sources/StreamChat/Workers/ChatClientUpdater.swift

- Set sample app log level to .warning
- Log error responses from API with .warning level]
- Skip useless warning message when connecting

CIS-1166 Improve logging

---

Sources/StreamChat/Workers/ChannelListUpdater.swift

Disable trumping

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
Sources/StreamChatUI/Components.swift

[-] Added chatReactionsBubbleView to Components
[-] Added components injection to ChatMessageContentView
[-] Added corresponding test to test injection

[CIS-1173] ChatReactionsBubbleView Inject To Components

---

CHANGELOG.md
Sources/StreamChat/ChatClient.swift
Sources/StreamChat/ChatClient_Tests.swift
Sources/StreamChat/Utils/InternetConnection/InternetConnection_Tests.swift

This PR updates `ChatClient` to disconnect immediately when the Internet connection disappears

[CIS-1082] Internet connection handling

---

CHANGELOG.md
Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/CommonViews/AvatarView/ChatAvatarView.swift

Co-authored-by: kennic <namkennic@me.com>
Closes #1442

Add delegate func for tap on user avatar for a message

---

CHANGELOG.md
Sources/StreamChat/Models/ChannelType.swift

Fix hypens are not allowed in custom channel types

---

CHANGELOG.md
Sources/StreamChat/Utils/Atomic_Tests.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Sources/StreamChatTestTools/DummyData/MessagePayload.swift

Local unread count logic was not the same as the one used by server-side

Fix unread count logic

---

CHANGELOG.md
Sources/StreamChat/APIClient/CDNClient.swift
Sources/StreamChat/APIClient/Endpoints/AttachmentEndpoints.swift
Sources/StreamChat/APIClient/Endpoints/AttachmentEndpoints_Tests.swift
Sources/StreamChat/APIClient/StreamCDNClient_Tests.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources/StreamChat/Models/Attachments/AnyAttachmentPayload.swift
Sources/StreamChat/Models/Attachments/ChatMessageAttachment_Tests.swift
Sources/StreamChat/Models/Attachments/ChatMessageAudioAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageFileAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
Sources/StreamChat/Models/Attachments/ChatMessageVideoAttachment.swift
Sources/StreamChat/Workers/ChannelUpdater.swift
Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
Sources/StreamChatTestTools/Models/Attachments/ChatMessageFileAttachment_Mock.swift
Sources/StreamChatTestTools/Models/Attachments/ChatMessageImageAttachment_Mock.swift

It'll allow uploading a file to CDN without having to upload an attachment to a message

[CIS-1181] Implement uploadFile API

---

Sources/StreamChatUI/CommonViews/Attachments/AttachmentsPreviewVC.swift

The #1480 fix broken the vertical attachment previews. This PR fixes that and makes sure there horizontal and vertical attachment previews on the composer have dynamic sizes.

Fix hidden vertical attachment previews in the Composer

---

Sources/StreamChatUI/CommonViews/Attachments/AttachmentsPreviewVC.swift

This fixes a UI glitch when adding a horizontal attachment preview in the composer after adding a vertical attachment.
Steps to reproduce:
1. Add a vertical attachment (file)
2. Remove vertical attachment (file)
3. Add a horizontal attachment (image or video)
This PR also refactors the way horizontal and vertical attachments are layout in a manner that it will be easier to support multiple attachments at once in the future.

Fix composer horizontal attachment after adding vertical attachment

---

README.md

Update README.md with v4 official release version

---

CHANGELOG.md
Sources/StreamChat/Controllers/ChannelListController/ChannelListController+Combine.swift
Sources/StreamChat/Controllers/ChannelListController/ChannelListController+SwiftUI.swift
Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
StreamChat.xcodeproj/xcshareddata/xcschemes/Messenger.xcscheme
StreamChat.xcodeproj/xcshareddata/xcschemes/Slack.xcscheme
StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChatSample.xcscheme
StreamChat.xcodeproj/xcshareddata/xcschemes/YouTube.xcscheme
StreamChat.xcodeproj/xcshareddata/xcschemes/iMessage.xcscheme
StreamChatSample/Samples/SimpleChat/SimpleChannelsViewController.swift

....in ChannelListVC subclasses
Fixes #1484

Fix ChannelListController delegate funcs are not overridable

---

StreamChat.xcodeproj/project.pbxproj
fastlane/Fastfile

...which blocked running app in our registered devices.
Also changes testflight workflow so it automatically submits for external review testing

Fix incorrect provisioning profiles in project

---

CHANGELOG.md

Fixing the changelog, some wrong logs were introduced after some merge conflicts

Fix CHANGELOG.md 

---

Makefile
Scripts/updateDependency.sh
Sources/StreamSwiftyGif/UIImage+SwiftyGif.swift

https://stream-io.atlassian.net/browse/CIS-1301
This PR ads a simple script to update the dependencies to a particular version.

[CIS-1301] Automate update of 3rd party dependencies

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Add default code owners to this repo.
- @GetStream/ios-developers

[BW] Default Code owners added to this repo

---

.github/workflows/smoke-checks.yml
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DatabaseSession.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
Sources/StreamChat/Workers/MessageUpdater.swift
Sources/StreamChat/Workers/MessageUpdater_Tests.swift
fastlane/Fastfile

Add Xcode 12.5.1 + Fix XCode compatibility issues

---

.github/workflows/smoke-checks.yml
fastlane/Fastfile

Properly set up the CI to build the project for Xcode 12.
The Previous PR (https://github.com/GetStream/stream-chat-swift/pull/1632) did not handle running the UI SDK, and the names of the job didn't make sense.

Build LLC and UI SDK on Xcode 12 CI Workflow

---

Makefile
Scripts/buildStaticLibraries.sh
Scripts/removeUnneededSymbols.sh
Scripts/updateDependency.sh
Sources/StreamChat/Utils/Bundle+Extensions.swift
Sources/StreamChatUI/Utils/Bundle+Extensions.swift
StreamChat.xcodeproj/project.pbxproj

https://stream-io.atlassian.net/browse/CIS-1354
Be able to distribute our code as static libraries
This PR adds a script that will create static libraries wrapped in xcframeworks.
It also creates 2 bundle files that contain the needed resources for each library.
Detailed explanation here: https://www.notion.so/stream-chat-fe-sdk/Static-Libraries-4c5c4220b1fa45a1bbd7d52f5ce3f585

[CIS-1354] Pipeline to distribute Static Libraries

---

CHANGELOG.md

CIS-1325
CIS-1332
Update changelog to mention that SwiftyGif crash is now solved.
Nothing. We already depend always on major versions only of SwiftyGif, so the fixes will be automatically updated.
N/A
N/A

[CIS-1325, CIS-1332] Update CHANGELOG with SwiftyGif crash fix

---

Cartfile
Package.resolved
Package.swift
StreamChat.xcodeproj/project.pbxproj
StreamChat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatUI.podspec

https://stream-io.atlassian.net/browse/CIS-1370
Point towards latest [stable version](https://github.com/kirualex/SwiftyGif/releases/tag/5.4.1) of SwiftyGif
Points podspec towards v5.4 and above, up to the next major
Points SPM towards v5.4.1 and above, up to the next major
Points Carthage towards v5.4.1 and above, up to the next major

[CIS-1370] Update version of SwiftyGif to >= 5.4.1

---

Scripts/updateDependency.sh
Sources/StreamChatUI/StreamSwiftyGif/NSImageView+SwiftyGif.swift
Sources/StreamChatUI/StreamSwiftyGif/UIImage+SwiftyGif.swift
Sources/StreamChatUI/StreamSwiftyGif/UIImageView+SwiftyGif.swift

Use the latest stable version of SwiftyGif.
* Ensure the changeset reflects changes in SwiftyGif release 4.5.1
* `make update_swiftygif version=5.4.1`
* Replaced `git co` call with `git checkout`

[BW] Update embedded SwiftyGif to 4.5.1

---

CHANGELOG.md

Add disclaimer about hidden dependencies in Changelog

---

.github/workflows/distribute-test-build.yml
.github/workflows/docusaurus-staging.yml
.github/workflows/emerge.yml
.github/workflows/macos-checks.yml
.github/workflows/smoke-checks.yml
fastlane/Fastfile

We're moving to `develop` to be one step closer to Git-Flow 🚀

Update references to use develop instead of main whenever needed

---

.github/workflows/publish-release.yml
fastlane/Fastfile

This PR is to update the publish-release and fastfile to fix our automated release pipeline.

Updating workflow scripts along with fastfile

---

CHANGELOG.md
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift

https://stream-io.atlassian.net/browse/CIS-1445
This PR adds test coverage for #1707

[CIS-1445] Add test coverage for CIS-1339 / #1707

---

Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChatTestTools/DummyData/MessagePayload.swift

Fixes a regression from the deleted replies fix, the PR adds better tests and cleans up the conditions for showing messages in channels.

CIS-1451 Fix channel message visiblity

---

docusaurus/docs/iOS/swiftui/components/composer-commands.md
docusaurus/docs/iOS/swiftui/getting-started.md
docusaurus/sidebars-ios.json

[JIRA](https://stream-io.atlassian.net/jira/software/projects/SWUI/boards/109?selectedIssue=SWUI-42)
Add docs for composer commands implemented in the SwiftUI SDK.
Run the docs locally to see the changes.

Added docs for composer commands

---

docusaurus/docs/iOS/swiftui/components/composer-commands.md
docusaurus/docs/iOS/swiftui/components/helper-views.md
docusaurus/docs/iOS/swiftui/getting-started.md
docusaurus/sidebars-ios.json

[JIRA](https://stream-io.atlassian.net/browse/SWUI-84?atlOrigin=eyJpIjoiYjVkOGZkYWU2OTk0NGFiZjljNmU0ZDQ4NjhmYjY5OTgiLCJwIjoiaiJ9)
Updating the docs to reflect changes in the SwiftUI SDK.
Docusaurus files in the SwiftUI folder are changed.
Run the docs locally to see the changes.

Updated the docs for composer commands and channel list items

---

README.md

...and remove the versions sections as discussed internally

Fix shields on README

---

README.md
docusaurus/docs/iOS/swiftui/components/helper-views.md
docusaurus/docs/iOS/swiftui/components/message-list.md
docusaurus/docs/iOS/swiftui/components/message-reactions.md
docusaurus/docs/iOS/swiftui/components/typing-indicators.md
docusaurus/sidebars-ios.json

- Update the SwiftUI docs, based on the new features.
- Link the SwiftUI SDK from this repo.
Updated docusaurus files and README/
Only docs changes.
Run docusaurus locally and see the changes.

Updated SwiftUI docs and README file

---

docusaurus/docs/iOS/swiftui/components/custom-avatar.md
docusaurus/docs/iOS/swiftui/components/helper-views.md
docusaurus/docs/iOS/swiftui/components/list-tap-events.md
docusaurus/docs/iOS/swiftui/components/message-list.md

[JIRA](https://stream-io.atlassian.net/browse/SWUI-110?atlOrigin=eyJpIjoiN2U4MjE1MmJlYzY4NDg0Yzg4MWEyZDYyMDc1YmVhMzYiLCJwIjoiaiJ9)
Docs changes in the SwiftUI SDK.
Nothing visible.
N/A
Run the docs locally and see the changes.
https://media.giphy.com/media/l4pTqyJ8XMhLZ3ScE/giphy.gif

Updated the SwiftUI docs for customizing backgrounds and deep-linking

---

docusaurus/docs/iOS/uikit/data-formatting.md

CIS-1648
Update the formatter customization docs:
- Fix typo with wrong title in one of the examples
- Add one example to reuse a default formatter.

[CIS-1648] [Docs] Improve formatter customization examples

---

Sources/StreamChat/APIClient/APIClient.swift
Sources/StreamChat/APIClient/APIClient_Tests.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/MissingEventsPayload.swift
Sources/StreamChat/Database/DTOs/MessageDTO.swift
Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
Sources/StreamChat/Database/DTOs/UserListQueryDTO.swift
Sources/StreamChat/Repositories/MessageRepository_Tests.swift
Sources/StreamChat/Utils/KeyedDecodingContainer+Array.swift
Sources/StreamChat/Utils/Logger/Logger_Mock.swift
Sources/StreamChat/Workers/Background/NewUserQueryUpdater.swift
Sources/StreamChat/Workers/Background/NewUserQueryUpdater_Tests.swift
Sources/StreamChat/Workers/ChannelListUpdater.swift
Sources/StreamChat/Workers/ChannelListUpdater_Tests.swift
Sources/StreamChat/Workers/MessageUpdater.swift
Sources/StreamChat/Workers/MessageUpdater_Tests.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatUITests/ChatMessage_Tests.swift

https://stream-io.atlassian.net/browse/CIS-1608
https://stream-io.atlassian.net/browse/CIS-1636
https://stream-io.atlassian.net/browse/CIS-1637
https://stream-io.atlassian.net/browse/CIS-1638
https://stream-io.atlassian.net/browse/CIS-1639
https://stream-io.atlassian.net/browse/CIS-1640
https://stream-io.atlassian.net/browse/CIS-1642
Polish missing details for Offline Support's release
_Explain how this change can be tested (or why it can't be tested)_

Offline Support - Test session bugs

---

CHANGELOG.md
Sources/StreamChat/Config/ChatClientConfig.swift
docusaurus/docs/iOS/guides/offline-support.md
docusaurus/sidebars-ios.json

We think now is the right time to make it the default.

Enable Offline Support by default

---

DemoAppPush/NotificationService.swift
Sources/StreamChatUI/ChatChannelList/ChatChannelListVC+SwiftUI.swift
StreamChatUITestsApp/AppDelegate.swift
StreamChatUITestsApp/StreamChat/StreamChatWrapper.swift

Removing use of orphan documentation, we should use /// for code docs and // for inline comments.
I have made them all inline comments because I think they're worthy of staying put.
CMB + B ;]

[SwiftLint] Removing Orphan Documentation

---

StreamChatUITestsAppUITests/MockServer/EventResponses.swift
StreamChatUITestsAppUITests/MockServer/MessageDetails.swift
StreamChatUITestsAppUITests/MockServer/MessagingResponses.swift
StreamChatUITestsAppUITests/MockServer/ReactionResponses.swift
StreamChatUITestsAppUITests/MockServer/StreamMockServer.swift
StreamChatUITestsAppUITests/Robots/ParticipantRobot.swift

This is fixing all shorthand syntax violations, to make it more "Swifty"!
The changes are mainly in the new Mock Server implementation @alteral @bielikb to check please
CMD + B ;]

[SwiftLint] Fixing Shorthand Violations

---

docusaurus/docs/iOS/guides/push-notifications.md

None
Fix broken link in push notifications guide.

[Docs] Fix broken link in push notifications guide

---

.swiftlint.yml
DemoApp/AppConfigViewController/AppConfigViewController.swift

- Removing constraints rule
- Fixing closure params on same line violations
CMD + B (Violations fixed)

[SwiftLint] Disable the constraints rule and changing closure params on same line

---

Examples/iMessageClone/iMessageChatChannelListViewController.swift
Sources/StreamChat/Database/DatabaseSession.swift
Sources/StreamChatUI/ChatMessageList/Attachments/LinkAttachmentViewInjector.swift
Sources/StreamChatUI/ChatMessageList/ChatMessageListScrollOverlayView.swift
Sources/StreamChatUI/Gallery/Cells/GalleryCollectionViewCell.swift
Sources/StreamChatUI/Gallery/GalleryVC.swift
StreamChatSample/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
StreamChatSample/Samples/LogsViewController.swift
StreamChatSample/Samples/SettingsViewController.swift

Fixing attribute violations on SwiftLint
CMD + B

[SwiftLint] Attribute Violations

---

Sources/StreamChat/APIClient/APIClient.swift
Sources/StreamChat/WebSocketClient/Engine/URLSessionWebSocketEngine.swift

Adds missing log for websocket upgrade URL request.
* HTTP headers are logged too
1. ```LogConfig.level = .debug```
2. Observe console logs

Logs WebSocket URL request

---

docusaurus/docs/iOS/swiftui/view-customizations.md

n/a
Update the docs for improving build times for our SwiftU `ViewFactory`.
Small docusaurus update.
Run the docs locally.

Updated the docs for view customizations

---

Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
Sources/StreamChat/Controllers/ListDatabaseObserver.swift

As discussed in slack and around
Reproduce:
2. Send a message
Interestingly, `computeValue` closure was not called when a `self` reference was kept in it.

Fix crashes when sending a message

---

docusaurus/docs/iOS/swiftui/components/swipe-actions-channels.md

n/a
Updated old method signature in the SwiftUI docs.
Docusaurus files update.
Run the docs locally.

Updated old method signature for more channel actions

---

.github/workflows/smoke-checks.yml
.gitignore
Scripts/bootstrap.sh
Scripts/installAllureDependencies.sh
fastlane/Fastfile
fastlane/README.md

- https://stream-io.atlassian.net/browse/CIS-1795
The goal is to upload E2E test results to Allure TestOps after each execution.
- Added a new fastlane lane to upload test results to Allure
- Added a new bash script to install Allure dependencies

[CIS-1795] Upload test results to Allure TestOps

---

Mintfile

We are adding SwiftLint to the Mint file so it's preinstalled when onboarding new engineers.

[SwiftLint] Adding to Mint File

---

fastlane/Fastfile
fastlane/Sonarfile

- https://stream-io.atlassian.net/browse/CIS-1770
- Publish Sonar updates on push to `main` and `develop` branches
- Move sonar lanes to a separate file
- Move the execution to another lane
- Add switch/case by branch name
- Create Sonarfile for sonar related lanes

[CIS-1770] Publish Sonar report to Slack straight after analysis

---

Gemfile.lock

We received a Git dependency warning and this updates the gem.lockfile

[Hotfix] Updating Git gem as security threat

---

docusaurus/docs/iOS/uikit/components/channel-list.md
docusaurus/docs/iOS/uikit/controllers/channels.md

Improve the documentation for both LLC/UI channel-list controllers.
- Update documentation for `ChatChannelListController`, bring special attention to `filter` closure 
- Explain how to show `ChatChannelListVC` modally/in the navigation controller/in tab bar/as a child

[Docs] Improve channel-list components documentation

---

fastlane/Fastfile

As we're now making our Demo App available on the website, we should update the app automatically based on our current automatic deployments. This will fix the build being added to the right group.

[FastLane] Updating Group Name for Automatic Deployment

---

.swiftlint.yml

None
Fix swiftlint linting external dependencies.

[SwiftLint] Fix swiftlint linting external dependencies

---

docusaurus/docs/iOS/swiftui/components/channel-header.md
docusaurus/docs/iOS/swiftui/components/message-list.md

[Issues](https://stream-io.atlassian.net/jira/software/projects/SWUI/boards/109)
Update the SwiftUI docs before the new release.
Updated the docusarus files.
Run docusaurus locally.

Updated the SwiftUI docs for sprint 17

---

.github/workflows/smoke-checks.yml
StreamChatUITestsAppUITests/MockServer/MessageResponses.swift
StreamChatUITestsAppUITests/MockServer/ReactionResponses.swift
StreamChatUITestsAppUITests/Robots/ParticipantRobot.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
fastlane/Allurefile

- Avoid flakiness on CI
- Update UI tests and Allurefile

Update UI tests and Allurefile to avoid flakiness on CI

---

Sources/StreamChat/Database/DTOs/MessageDTO.swift
Tests/StreamChatTests/Database/DTOs/MessageDTO_Tests.swift

CIS-1857
Fix showing errors & ephemeral messages in channel preview as they are not persisted on the backend and disappear when the channel is reopened. This was leading to weird behavior when the message that no longer shown in the channel was still visible in the channel preview.
Reload channel preview when the current preview is updated.
**Before**
https://user-images.githubusercontent.com/12818985/168063328-919364c2-e527-4bf4-978d-43abae2c2e66.mp4
**After**
https://user-images.githubusercontent.com/12818985/168063383-46e9a091-b13a-4724-9a2a-610d6241f4b9.mp4
**GIVEN** I'm in the channel 
**AND** I send a message with invalid command
**AND** The message is updated to be an `error`
**WHEN** I go back to the channel list
**THEN** The error message is not shown in preview
**GIVEN** I'm in …

[CIS-1857] Fix showing errors and ephemeral messages in channel preview

---

Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift

Automate UI scenarios
[Cheers](https://media.giphy.com/media/12qq4Em3MVuwJW/giphy.gif)

UI test scenarios

---

docusaurus/docs/iOS/guides/message-composer-custom-attachments.md
docusaurus/docs/iOS/uikit/components/message-composer.md

No ticket.
Fix broken links.
Fixed and tested locally.
Up up two dirs, up up two dirs, and another up up two dirs and down another... That's it.
No impact.

Fix a couple broken links.

---

StreamChat.xcodeproj/project.pbxproj
StreamChatUITestsAppUITests/MockServer/MessageResponses.swift
StreamChatUITestsAppUITests/MockServer/MockServerAttributes.swift
StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift

More automated UI test scenarios for fixed bugs.

More UI test scenarios

---

StreamChatUITestsAppUITests/Robots/Robot+CustomAssertions.swift
StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift

Few more automated UI scenarios

---

.github/actions/bootstrap/action.yml
.github/actions/set-build-image-var/action.yml
.github/workflows/distribute-test-build.yml
.github/workflows/emerge.yml
.github/workflows/publish-release.yml
.github/workflows/smoke-checks.yml
.github/workflows/testflight.yml

- Fix image version environment variable on CI

Fix image version environment variable on CI

---

CHANGELOG.md

The goal of this PR is to run the CI and publish `4.15.0` release when merged.
Removes dots from CHANGELOG.md

4.15.0 Release

---

.github/workflows/smoke-checks.yml
.github/workflows/testflight.yml
Scripts/bootstrap.sh
fastlane/Fastfile

- https://stream-io.atlassian.net/browse/CIS-1822
- Publish release build on Testflight for regression testing
- Update a condition when to publish Testflight build
- Fix Allure job when no tests were executed
- Fix `testing_required?` fastlane method on `push`

[CIS-1822] Publish release build on Testflight for regression testing

---

docusaurus/docs/iOS/guides/working-with-attachments.md

CIS-1918
Add documentation on how to add interaction to custom attachments + cleanup old documentation.
N/A

[CIS-1918] Add documentation on how to add interaction to custom attachments

---

.github/workflows/smoke-checks.yml

- https://stream-io.atlassian.net/browse/CIS-1911
- Reduce the number of queues on CI
- Do not run tests on the same code twice (on `PR` and on `push`)

[CIS-1911] Remove smoke checks on push

---

docusaurus/docs/iOS/swiftui/components/message-list.md

[Issues](https://stream-io.atlassian.net/jira/software/projects/SWUI/boards/109)
Updated the docs with the latest changes in the SwiftUI SDK.
Updated docs around the message list.
Docusaurus files updates.
Run docusaurus locally to see the changes.

Updated the SwiftUI docs

---

docusaurus/docs/iOS/guides/video-100ms.md
docusaurus/docs/iOS/guides/video-agora.md

Add sample movies to video guides

---

docusaurus/docs/iOS/swiftui/components/typing-indicators.md

Update the docs for the latest SwiftUI changes.

SwiftUI docs update for typing indicators

---

docusaurus/docs/iOS/swiftui/components/message-list.md

[JIRA](https://stream-io.atlassian.net/browse/SWUI-166?atlOrigin=eyJpIjoiYmI4NjMxNjhkN2ZiNDg3MDg5NzU4ZDM3OTMwODliZDkiLCJwIjoiaiJ9)
Update the SwiftUI docs for a new feature.

Added docs for swipe gesture sensitivity

---

Package.swift
StreamChat.xcodeproj/project.pbxproj
StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift

- https://stream-io.atlassian.net/browse/SWUI-180
- Make mock server and robots stable on SwiftUI

[SWUI-180] Make mock server and robots stable on SwiftUI

---

docusaurus/docs/iOS/swiftui/components/channel-header.md

Small docs update, reported by a customer.

Fixed a code snippet in SwiftUI's docs

---

StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
TestTools/StreamChatTestMockServer/MockServer/StreamMockServer.swift

- N/A
- To fix flaky UI tests
|  [Failed cron checks](https://github.com/GetStream/stream-chat-swift/actions/runs/2653966011)   |  [Passed cron checks](https://github.com/GetStream/stream-chat-swift/actions/runs/2655373549)  |

[BW] Fix flaky UI tests

---

StreamChat.xcodeproj/project.pbxproj
StreamChatUITestsAppUITests/Pages/MessageListPage.swift
StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_unsplash_link.json
TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_youtube_link.json
TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift

- https://stream-io.atlassian.net/browse/CIS-2012
- Support link previews in Mock Server
- Link previews are supported in Mock Server
- Related scenarios are automated
- Added error messages for some existed scenarios

[CIS-2012] Support link previews in Mock Server

---

fastlane/Appfile
fastlane/Matchfile

- N/A
- Remove username from fastlane files
- Make sure fastlane `gym` and `match` work fine on CI
- [Passed TestFlight job](https://github.com/GetStream/stream-chat-swift/runs/7539624810?check_suite_focus=true)

[BW] Remove username from fastlane files

---

.github/workflows/smoke-checks.yml
DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift
StreamChat.xcodeproj/project.pbxproj
StreamChatUITestsApp/DebugMenu.swift
StreamChatUITestsAppUITests/Pages/MessageListPage.swift
StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/StreamChatUITestsApp.xctestplan
StreamChatUITestsAppUITests/Tests/Attachments_Tests.swift
StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
TestTools/StreamChatTestMockServer/Fixtures/JSONs/http_truncate.json
TestTools/StreamChatTestMockServer/MockServer/ChannelResponses.swift
TestTools/StreamChatTestMockServer/MockServer/EventResponses.swift
TestTools/StreamChatTestMockServer/MockServer/MessageList.swift
TestTools/StreamChatTestMockServer/MockServer/MessageResponses.swift
TestTools/StreamChatTestMockServer/MockServer/MockServerAttributes.swift
TestTools/StreamChatTestMockServer/MockServer/ReactionResponses.swift
TestTools/StreamChatTestMockServer/MockServer/StreamMockServer.swift
TestTools/StreamChatTestMockServer/MockServer/User.swift
TestTools/StreamChatTestMockServer/MockServer/WebsocketResponses.swift
TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift

- https://stream-io.atlassian.net/browse/CIS-2013
- Support channel truncation in Mock Server
- Automate related scenarios
- Mock server supports truncate channel feature
- Related scenarios are automated
- Some additional scenarios were automated for the company
- Truncate with & w/o buttons were added to DebugMenu in the TestApp
- Some refactoring of the mock server and the tests has been done

[CIS-2013] Support channel truncation in Mock Server

---

fastlane/Fastfile

N/A
- Fix the release workflow
- Add a default value for the `Package.swift` formatted line

[BW] Add a default value for package.swift formatted line

---

fastlane/Fastfile

- Support for message moderation (NNBB) [#2103](https://github.com/GetStream/stream-chat-swift/pull/2103/files)
- Fix crash in ListDatabaseObserver.startObserving() [#2177](https://github.com/GetStream/stream-chat-swift/pull/2177)
- Make BaseOperation thread safe [#2198](https://github.com/GetStream/stream-chat-swift/pull/2198)
- Fix build issues in Xcode 14 beta [#2202](https://github.com/GetStream/stream-chat-swift/pull/2202)
- Improve consistency when retrieving Message after Push Notification [#2200](https://github.com/GetStream/stream-chat-swift/pull/2200)
- Make sure ChannelDTO is still valid when accessing Lazy blocks [#2204](https://github.com/GetStream/stream-chat-swift/pull/2204)
- Add channel list states; empty, error and loading views …

Initiate release v4.20.0

---

docusaurus/docs/iOS/swiftui/chat-channel-components/message-list.md

Small docs update for SwiftUI.

Updated docs about group avatars

---

Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
Tests/StreamChatTests/StreamChatTestPlan.xctestplan

- N/A
- Update flaky test suite

[BW] Update flaky test suite

---

StreamChat.xcodeproj/project.pbxproj
sonar-project.properties

- https://stream-io.atlassian.net/browse/CIS-1821
- Add SwiftLint report to Sonar analysis
- Create a report file after every execution of swiftlint
- Provide a new report file path in Sonar config

[CIS-1821] Cooperate SwiftLint and SonarCloud

---

README.md

Updated the README for Xcode 14 beta compatibility.

Updated the README for Xcode 14 beta compatibility

---

docusaurus/docs/iOS/swiftui/message-components/message-threads.md

[GH](https://github.com/GetStream/stream-chat-swiftui/issues/177)
Update the docs because of a SwiftUI SDK change.

Updated the docs for message replies view in SwiftUI

---

Sources/StreamChat/Controllers/ChannelController/ChannelController.swift

Fix slow mode showing incorrectly on slower devices, as spotted on our QA session.

Fixed issue with slow mode shown on slower devices

---

Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift

CIS-2159
Fix keyboard handling when the chat is embedded in a Tab Bar

[CIS-2159] Fix keyboard handler in tab bars

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift

CIS-2159
Fixed message list not reloading skipped messages.

[CIS-2159] Fix message list not reloading skipped messages

---

StreamChatUITestsAppUITests/Robots/UserRobot.swift

- Somehow relates to https://stream-io.atlassian.net/browse/CIS-1737
- Make `test_userLogsInAfterLoggingOut` UI test stable

[BW] Workaround for the flakey UI test

---

README.md

Updated README to remove Xcode beta references.

Updated README for iOS 16 support

---

CHANGELOG.md
Sources/StreamChat/APIClient/APIClient.swift
Sources/StreamChat/ChatClient.swift
Sources/StreamChat/Config/ChatClientConfig.swift
Tests/StreamChatTests/Errors/ClientError_Tests.swift

Minor changes to improve APIClient
- Decrease timeout from 60 to 30
- Fix broken logic to detect connectivity errors

[Internal] Improve APIClient in Low Connectivity

---

StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
TestTools/StreamChatTestMockServer/Robots/ParticipantRobot.swift

[BW] Fix flakiness in the message delivery status tests

---

docusaurus/docs/iOS/swiftui/view-customizations.md

https://github.com/GetStream/stream-chat-swiftui/issues/218
Improve the docs that are not clear to customers.

Updated the docs for using typealias for improving build times

---

docusaurus/docs/iOS/guides/offline-support.md

[JIRA](https://stream-io.atlassian.net/browse/CIS-2186)
Update the docs about reconnection logic not working reliably on iOS simulators.

Updated the docs about reconnection on iOS simulators

---

Scripts/bootstrap.sh

- N/A
- To fix Allure's failed test report, which was broken after migrating to Xcode 14

[BW] Bump Allure version

---

TestTools/StreamChatTestTools/SpyPattern/Spy/AttachmentUploader_Spy.swift

Fixed missing import in AttachmentUploader_Spy.swift

---

.github/workflows/cron-checks.yml
.github/workflows/docusaurus-prod.yml
.github/workflows/docusaurus-staging.yml
.github/workflows/emerge.yml
.github/workflows/publish-release.yml
.github/workflows/smoke-checks.yml
.github/workflows/testflight.yml

[BW] Bump Github Actions version

---

Sources/StreamChat/Repositories/SyncRepository.swift
Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift

https://stream-io.atlassian.net/browse/CIS-2204

[CIS-2204] Clear lastSyncAt when resetting DB content

---

Sources/StreamChat/ChatClient.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/EventDTOConverterMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/EventMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/UserChannelBanEventsMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/UserTypingStateUpdaterMiddleware.swift
Sources/StreamChat/WebSocketClient/EventMiddlewares/UserWatchingEventMiddleware.swift
Sources/StreamChat/Workers/EventNotificationCenter.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/WebSocketClient/EventMiddlewares/EventMiddleware_Mock.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/ChannelVisibilityEventMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/EventDTOConverterMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/EventMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserChannelBanEventsMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserTypingStateUpdaterMiddleware_Tests.swift
Tests/StreamChatTests/WebSocketClient/EventMiddlewares/UserWatchingEventMiddleware_Tests.swift

[internal] Middlewares Changes

---

docusaurus/docs/iOS/swiftui/message-components/message-reactions.md

Add docs for sorting reactions in SwiftUI.
Run docusaurus locally.

Added docs for sorting reactions in SwiftUI

---

Tests/StreamChatTests/APIClient/APIClient_Tests.swift
Tests/StreamChatTests/APIClient/StreamAttachmentUploader_Tests.swift
Tests/StreamChatTests/BackgroundListDatabaseObserver_Tests.swift
Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Tests/StreamChatTests/Controllers/ChannelListController/ChannelListController_Tests.swift
Tests/StreamChatTests/Controllers/ConnectionController/ConnectionController_Tests.swift
Tests/StreamChatTests/Controllers/CurrentUserController/CurrentUserController_Tests.swift
Tests/StreamChatTests/Controllers/MessageController/MessageController_Tests.swift
Tests/StreamChatTests/Controllers/SearchControllers/UserSearchController/UserSearchController_Tests.swift
Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift
Tests/StreamChatTests/Models/Attachments/AnyAttachmentUpdater_Tests.swift
Tests/StreamChatTests/Repositories/AuthenticationRepository_Tests.swift
Tests/StreamChatTests/Repositories/ConnectionRepository_Tests.swift
Tests/StreamChatTests/Repositories/MessageRepository_Tests.swift
Tests/StreamChatTests/Repositories/OfflineRequestsRepository_Tests.swift
Tests/StreamChatTests/Repositories/SyncRepository_Tests.swift
Tests/StreamChatTests/StreamChat/ChatClient_Tests.swift
Tests/StreamChatTests/Utils/CooldownTracker_Tests.swift
Tests/StreamChatTests/Utils/MulticastDelegate_Tests.swift
Tests/StreamChatTests/Utils/Operations/AsyncOperation_Tests.swift
Tests/StreamChatTests/Workers/ChannelListUpdater_Tests.swift
Tests/StreamChatTests/Workers/ChannelUpdater_Tests.swift
Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift
Tests/StreamChatTests/Workers/UserListUpdater_Tests.swift

https://github.com/GetStream/ios-issues-tracking/issues/258
Improve the flakiness of some tests.

[Internal] Update test timeouts to improve flakiness

---

README.md

Update the readme about Objective-C usage.

Updated the README about Objective-C usage

---

docusaurus/docs/iOS/swiftui/chat-channel-components/message-list.md

Add docs for the new messages separator in SwiftUI.

Added docs for new messages separator in SwiftUI

---

docusaurus/docs/iOS/guides/video-100ms.md

[Fix] Resolved issues in 100ms video guide

---

.github/workflows/docusaurus-prod.yml
.github/workflows/docusaurus-staging.yml

- https://github.com/GetStream/stream-chat-swift/actions/runs/4224564856/jobs/7335681344

[BW] Lock node version for docusaurus

---

fastlane/Fastfile

- ✅ https://github.com/GetStream/stream-chat-swift/actions/runs/4232428662

[BW] Fix simulator issue on older iOS versions

---

Sources/StreamChatUI/CommonViews/GradientView/GradientView.swift
Sources/StreamChatUI/CommonViews/PlayerView.swift

Prevent name collisions in Objective-C based projects.

Update names for some views in Objective-C

---

Sources/StreamChatUI/Appearance+Formatters/Appearance+Formatters.swift
Sources/StreamChatUI/Appearance+Formatters/AudioPlaybackRateFormatter.swift
Sources/StreamChatUI/Appearance+Formatters/AudioRecordingNameFormatter.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatUITests/Utils/DefaultAudioPlaybackRateFormatter_Tests.swift
Tests/StreamChatUITests/Utils/DefaultAudioRecordingNameFormatter_Tests.swift

Implement the formatters required by Async Messages.

[Async Messages]Audio Formatters

---

Sources/StreamChat/WebSocketClient/WebSocketClient.swift

Resolve a `empty_enum_arguments` rule violation.
https://realm.github.io/SwiftLint/empty_enum_arguments.html
As the title says.

Remove an unused enum argument

---

Sources/StreamChat/Audio/AudioRecorder/AudioRecording.swift
Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
Sources/StreamChat/Utils/Array+Sampling.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatTests/Audio/StreamAudioRecorder_Tests.swift
Tests/StreamChatTests/Utils/ArraySampling_Tests.swift

Make a few additional changes on LLC that are required by UI components

[Async Messages] Up/Down sampling util implementation

---

Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatUITests/SnapshotTests/MessageActionsPopup/MessageActionsTransitionController_Tests.swift

commit-id:718a087e
---
**Stack**:
- #2623
- #2622
- #2621
- #2620
- #2619
- #2618
- #2617
- #2616 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

[Async Messages]MessageActionsTransitionController fix

---

Tests/StreamChatUITests/Localization_Tests.swift

commit-id:79bcdc89
---
**Stack**:
- #2623
- #2622
- #2621
- #2620
- #2619
- #2618
- #2617
- #2625 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

[Fix]Localization Test affecting all testCases

---

Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
Tests/StreamChatTests/Models/Attachments/AttachmentFileType_Tests.swift

[Async Messsages]Fix is audio by removing `.mp4`

---

Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
Sources/StreamChat/Audio/AudioPlayer/AudioQueuePlayer.swift
Sources/StreamChat/Audio/AudioRecorder/AudioRecording.swift
Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
Sources/StreamChatUI/Components.swift
StreamChat.xcodeproj/project.pbxproj
TestTools/StreamChatTestTools/Mocks/StreamChat/VoiceRecording/MockAudioPlayer.swift
Tests/StreamChatTests/Audio/StreamAudioPlayer_Tests.swift
Tests/StreamChatTests/Audio/StreamAudioQueuePlayer_Tests.swift
Tests/StreamChatUITests/SnapshotTests/ChatChannel/ChatChannelVC_Tests.swift
Tests/StreamChatUITests/SnapshotTests/ChatThread/ChatThreadVC_Tests.swift
Tests/StreamChatUITests/SnapshotTests/CommonViews/Attachments/AttachmentsPreviewVC_Tests.swift
Tests/StreamChatUITests/SnapshotTests/Composer/ComposerVC_Tests.swift

- Refactors StreamRemoteAudioPlayer -> StreamAudioPlayer
- Refactors StreamRemoteAudioQueuePlayer  -> StreamAudioQueuePlayer
- Remove unused error from StreamAudioRecorder 
- Remove unused method from StreamAudioPlayer

[Async Messages]Refactor and cleanup

---

Sources/StreamChat/Audio/Analysis/AudioAnalysisEngine.swift
Sources/StreamChat/Audio/AudioPlayer/AudioPlaying.swift
Sources/StreamChatUI/VoiceRecording/VoiceRecordingVC.swift
docusaurus/docs/iOS/client/audio-support/audio-analysis.md
docusaurus/docs/iOS/client/audio-support/audio-playback.md
docusaurus/docs/iOS/client/audio-support/audio-recording-and-playback-overview.md
docusaurus/docs/iOS/client/audio-support/audio-recording.md
docusaurus/docs/iOS/common-content/reference-docs/stream-chat-ui/composer/composer-vc-properties.md
docusaurus/docs/iOS/uikit/components/voice-recording.md
docusaurus/docs/iOS/uikit/guides/working-with-attachments.md
docusaurus/sidebars-ios.json

Add documentation about the Async Messages feature and its main components.
Pages added:
`/chat/docs/sdk/ios/client/audio-support/audio-recording-and-playback-overview/`
`/chat/docs/sdk/ios/client/audio-support/audio-recording/`
`/chat/docs/sdk/ios/client/audio-support/audio-analysis/`
`/chat/docs/sdk/ios/client/audio-support/audio-playback/`
`/chat/docs/sdk/ios/uikit/components/voice-recording/`

[Async Messages]Add feature documentation

---

StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/Tests/QuotedReply_Tests.swift

Resolve https://github.com/GetStream/ios-issues-tracking/issues/469

[BW] Update quoted reply tests

---

docusaurus/docs/iOS/swiftui/chat-channel-components/message-list.md

We had a TODO in the SwiftUI docs.
Just a doc update.

Fixed a TODO for missing link in the SwiftUI docs

---

docusaurus/docs/iOS/swiftui/chat-channel-components/message-composer.md

Fix outdated docs for custom attachments in SwiftUI

---

Package.swift

Increase the version of the ChatTestHelpers dependency.

Increase TestHelpers version

---

.swiftlint.yml
Mintfile
Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
Sources/StreamChat/Utils/MulticastDelegate.swift
Sources/StreamChatUI/ChatChannelList/Search/ChatChannelListSearchVC.swift
Sources/StreamChatUI/ChatMessageList/Attachments/AttachmentViewCatalog.swift
Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageVoiceRecordingAttachmentListView+ItemView.swift
Sources/StreamChatUI/CommonViews/ContainerStackView.swift
Sources/StreamChatUI/Deprecations.swift
Sources/StreamChatUI/Utils/Extensions/NSLayoutConstraint+Extensions.swift
StreamChatUITestsAppUITests/Pages/MessageListPage.swift

```
🌱 Encountered error during "swift build -c release --product swiftlint -Xswiftc -target -Xswiftc arm64-apple-macosx13.5". 
🌱  Failed to build SwiftLint with SPM
```

[BW] Resolve SwiftLint CI issues

---

docusaurus/docs/iOS/uikit/getting-started.md

Docs update about logout and disconnect.

Updated the docs for logout and disconnect

---

DemoApp/Screens/AppConfigViewController/AppConfigViewController.swift

Add debug flag to toggle jumpToUnread feature

---

Sources/StreamChat/Controllers/ChannelController/ChannelController.swift

A customer pointed this out, the docs are wrong.

Fixed Swift docs for members methods in ChannelController

---

DemoShare/Info.plist
StreamChat.xcodeproj/project.pbxproj
fastlane/Fastfile
fastlane/testflight_export_options.plist

Test: https://github.com/GetStream/stream-chat-swift/actions/runs/6420318119

Add DemoShare to Testflight build

---

.gitignore

Solving this issue on CI:
```
ln: /Users/runner/work/stream-chat-swift/stream-chat-swift/buildcache/bin/clang: File exists
Error: buildcache: failure during restore: Error: The process '/bin/ln' failed with exit code 1
Error: Error: The process '/bin/ln' failed with exit code 1
```

[CI] Fix buildcache issue

---

docusaurus/docs/iOS/uikit/components/channel.md

Fixed broken link in docs

---

docusaurus/docs/iOS/uikit/components/message.md
docusaurus/docs/iOS/uikit/guides/customize-message-composer.md
docusaurus/docs/iOS/uikit/guides/message-composer-custom-attachments.md
docusaurus/docs/iOS/uikit/guides/working-with-attachments.md

Fixed docs typos

---

Sources/StreamChat/Workers/Background/AttachmentQueueUploader.swift
Sources/StreamChat/Workers/Background/MessageEditor.swift
Sources/StreamChat/Workers/Background/MessageSender.swift

https://getstream.slack.com/archives/CRB9P6L03/p1701077563014689
Avoid threading issues when using DatabaseObservers that report back DTOs
There are some places in which we listen to the Database and we don't map to a model, but instead we get the DTO. Because those DTOs are only accessible from the same thread where they were created, we cannot use background mapping as it would be unsafe.
The current implementation is not safe either, but because everything happens on the main thread, no issues are created out of it. It is important that this gets fixed at some point to not rely on DTO spread around the code.
Brings back main-thread-only access to the DTOs mentioned above
2. Pin a messsage
Nothing crashes, and the message is pinned

[Background Mapping] Do not use Background Mapping when mapping from DTO to DTO

---

docusaurus/docs/iOS/basics/overview.md
docusaurus/docs/iOS/client/controllers/channels.md
docusaurus/docs/iOS/client/controllers/connection.md
docusaurus/docs/iOS/client/controllers/events.md
docusaurus/docs/iOS/client/controllers/messages.md
docusaurus/docs/iOS/client/controllers/users.md
docusaurus/docs/iOS/client/llc-client-overview.md
docusaurus/docs/iOS/swiftui/channel-list-components/helper-views.md
docusaurus/docs/iOS/swiftui/chat-channel-components/overview.md
docusaurus/docs/iOS/swiftui/getting-started.md
docusaurus/docs/iOS/swiftui/view-customizations.md
docusaurus/docs/iOS/uikit/components/voice-recording.md
docusaurus/docs/iOS/uikit/getting-started.md
docusaurus/docs/iOS/uikit/guides/message-composer-custom-attachments.md
docusaurus/docs/iOS/uikit/views/channel-header-view.md
docusaurus/sidebars-ios.json

- Another doc restructure
- Remove duplicated content from the LLC docs
- Content improvements
- https://www.notion.so/stream-wiki/Docs-iOS-Review-December-4th-c47c6cc4e30246709008024500511975
Docusaurus updates.

Docs structure updates

---

DemoApp/StreamChat/Components/DemoChatChannelListRouter.swift

N/A
This was causing some confusion when doing QA, so update the system message here as well.

Add system message when adding a member in the DemoApp

---

docusaurus/docs/iOS/client/custom-cdn.md

Resolves https://github.com/GetStream/ios-issues-tracking/issues/678.
Link a Firebase Storage implementation for our custom CDN.

Added docs for custom Firebase Storage CDN

---

docusaurus/docs/iOS/client/push-notifications.md
docusaurus/docs/iOS/uikit/components/message-composer.md

- https://getstream.io/chat/docs/sdk/ios/uikit/uikit/custom-components/#setuplayout
- https://getstream.io/chat/docs/sdk/ios/uikit/custom-components/#setuplayout
PS:
- Also updated links to apple dev

Fix broken link in the UIKit docs

---

Gemfile
Gemfile.lock
TestTools/StreamChatTestMockServer/MockServer/DeviceRemoteControl.swift

- Fix issues related to Sinatra server
- Gemfile refactoring

Fix issues related to Sinatra server

---

Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
Sources/StreamChatUI/Resources/en.lproj/Localizable.strings

Resolves https://github.com/GetStream/ios-issues-tracking/issues/717.
Provide explanations for the localizable keys. Makes it easier for customers to customize the texts.
Updated the localizable file.
Just text changes.
No need for testing, just check the texts for typos.

Added comments for the localization texts

---

Gemfile

Hard-code fastplane pluginfile path

---

StreamChatUITestsAppUITests/StreamChatUITestsApp.xctestplan

More details: https://github.com/eroshenkoam/xcresults/issues/67

Enable screenshots in Allure Report on iOS 17 / Xcode 15

---

StreamChat.xcodeproj/xcshareddata/IDETemplateMacros.plist

Use the same file header format we have everywhere when creating new files.
The template will generate file header like this:
```
//
// Copyright © 2024 Stream.io Inc. All rights reserved.
//
```

Add a custom file header template

---

.github/workflows/cron-checks.yml

[CI] Solve brew issue on macos-13

---

fastlane/Fastfile

- https://github.com/GetStream/stream-chat-swift/actions/runs/8476614092/job/23226392077

Fix XCMetrics PR detection on scheduled runs

---

Sources/StreamChat/Controllers/DatabaseObserver/StateLayerListDatabaseObserver.swift
Sources/StreamChat/StateLayer/ChannelListState+Observer.swift
Sources/StreamChat/StateLayer/Chat.swift
Sources/StreamChat/StateLayer/ChatState+Observer.swift
Sources/StreamChat/StateLayer/ChatState.swift
Sources/StreamChat/Workers/ChannelUpdater.swift
Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift

Add tests for message pagination (basic tests)

[ChatStateLayer] Chat message pagination tests

---

Sources/StreamChat/Controllers/DatabaseObserver/StateLayerListDatabaseObserver.swift
Sources/StreamChat/StateLayer/MessageSearch.swift
Sources/StreamChat/StateLayer/MessageSearchState+Observer.swift
Sources/StreamChat/StateLayer/MessageSearchState.swift
StreamChat.xcodeproj/project.pbxproj
TestTools/StreamChatTestTools/Extensions/XCTest+Helpers.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
Tests/StreamChatTests/StateLayer/MessageSearch_Tests.swift

Basic test coverage for MessageSearch (more tests later).

[ChatStateLayer] Message search tests

---

TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelMemberUpdater_Mock.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/MessageUpdater_Mock.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift

Add more ChatLayer Unit Tests
- Some of the tests are commented due to complexity of realisation and should be fixed in further PRs

[ChatStateLayer] Chat unit tests

---

Sources/StreamChat/StateLayer/UserListState+Observer.swift
Sources/StreamChat/StateLayer/UserListState.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatTests/StateLayer/UserList_Tests.swift

Basic test coverage for UserList

[ChatStateLayer] Basic tests for UserList

---

Sources/StreamChat/StateLayer/UserSearch.swift
Sources/StreamChat/StateLayer/UserSearchState.swift
Sources/StreamChat/Workers/UserListUpdater.swift
StreamChat.xcodeproj/project.pbxproj
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/UserListUpdater_Mock.swift
Tests/StreamChatTests/StateLayer/UserSearch_Tests.swift

[ChatStateLayer] Basic tests for UserSearch

---

StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatTests/StateLayer/MemberList_Tests.swift

Basic test coverage for member list

[ChatStateLayer] Basic tests for member list

---

Sources/StreamChat/StateLayer/ChatClient+Factory.swift

[ChatStateLayer] Add synchronous makeConnectedUser

---

Sources/StreamChat/APIClient/Endpoints/Payloads/IdentifiableModel.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/IdentifiablePayload.swift
Sources/StreamChat/APIClient/Endpoints/Payloads/ThreadListPayload.swift
Sources/StreamChat/Database/DTOs/ThreadDTO.swift
Sources/StreamChat/Database/DTOs/ThreadParticipantDTO.swift
Sources/StreamChat/Database/DTOs/ThreadReadDTO.swift
Sources/StreamChat/Database/DatabaseSession.swift
Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
Sources/StreamChat/Models/Thread.swift
Sources/StreamChat/Models/ThreadParticipant.swift
Sources/StreamChat/Models/ThreadRead.swift
StreamChat.xcodeproj/project.pbxproj
TestTools/StreamChatTestTools/Mocks/StreamChat/Database/DatabaseSession_Mock.swift
TestTools/StreamChatTestTools/TestData/DummyData/XCTestCase+Dummy.swift
Tests/StreamChatTests/APIClient/Endpoints/Payloads/ThreadListPayload_Tests.swift
Tests/StreamChatTests/Database/DTOs/ThreadDTO_Tests.swift
Tests/StreamChatTests/Database/DTOs/ThreadParticipantDTO_Tests.swift
Tests/StreamChatTests/Database/DTOs/ThreadReadDTO_Tests.swift
Tests/StreamChatTests/Database/DatabaseContainer_Tests.swift

Relates to https://github.com/GetStream/ios-issues-tracking/issues/752
Part 2 of the Threads V2 Implementation. This adds all domain models and DTOs. For now, all are internal.
**UPDATE:** 
N/A

[Threads v2] Add Thread Domain Models and DTOs

---

Sources/StreamChat/Repositories/MessageRepository.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/ChatClient_Mock.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/TypingEventsSender_Mock.swift
TestTools/StreamChatTestTools/SpyPattern/Spy/APIClient_Spy.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift

[ChatStateLayer] Tests for Chat

---

Sources/StreamChat/Database/DTOs/MessageReactionDTO.swift
Sources/StreamChat/StateLayer/Chat.swift
Sources/StreamChat/StateLayer/ChatState.swift
Sources/StreamChat/StateLayer/MessageState+Observer.swift
Sources/StreamChat/StateLayer/MessageState.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Workers/ChannelUpdater_Mock.swift
Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift
Tests/StreamChatTests/Workers/MessageUpdater_Tests.swift

More tests! Mostly used for validating tests on CI.

[ChatStateLayer] Add tests uncovered parts in Chat

---

TestTools/StreamChatTestTools/SpyPattern/Spy/Logger_Spy.swift

…se iteration count
Fix instability in cached tests.

Test instability in cached tests

---

Sources/StreamChat/Repositories/SyncRepository.swift

Updates the channel limit updated here: https://github.com/GetStream/stream-chat-swift/pull/3188

Change sync channels limit to 100

---

Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources/StreamChat/Repositories/MessageRepository.swift
Sources/StreamChat/StateLayer/Chat.swift
Sources/StreamChat/StateLayer/ChatState.swift
Sources/StreamChat/Workers/ChannelUpdater.swift
Sources/StreamChat/Workers/ReadStateHandler.swift
Sources/StreamChat/Workers/ReadStateSender.swift
StreamChat.xcodeproj/project.pbxproj
Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift

Share the logic used for marking channel read.

[ChatStateLayer] Share mark and mark unread message

---

.github/workflows/cron-checks.yml
.github/workflows/smoke-checks.yml

Resolve https://github.com/GetStream/ios-issues-tracking/issues/821
Archive LLC and E2E test logs

Archive test logs

---

.github/workflows/start-new-release.yml
Gemfile.lock
fastlane/Fastfile
fastlane/Pluginfile

Example: https://github.com/GetStream/stream-chat-swift/pull/3210

Update release lane

---

Sources/StreamChat/Workers/ChannelUpdater.swift
Tests/StreamChatTests/StateLayer/ChannelList_Tests.swift
Tests/StreamChatTests/StateLayer/Chat_Tests.swift
Tests/StreamChatTests/StateLayer/StateLayerDatabaseObserver_Tests.swift
Tests/StreamChatTests/StateLayer/UserSearch_Tests.swift
Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
Tests/StreamChatTests/StreamChatStressTestPlan.xctestplan
Tests/StreamChatTests/StreamChatTestPlan.xctestplan

Fix issues when running cron checks.

Unit-test instability on older Xcode versions

---

Sources/StreamChat/Controllers/PollController/PollVoteListController.swift
Sources/StreamChat/Repositories/PollsRepository.swift
TestTools/StreamChatTestTools/Mocks/StreamChat/Repositories/PollsRepository_Mock.swift
Tests/StreamChatTests/Controllers/PollsControllers/PollController_Tests.swift
Tests/StreamChatTests/Controllers/PollsControllers/PollVoteListController_Tests.swift

Vote list endpoint only supports cursors.

Use cursor when fetching more votes

---

docusaurus/docs/iOS/swiftui/polls.md

Fixed vale warnings for polls docs

---

Sources/StreamChat/Controllers/PollController/PollController.swift
Sources/StreamChat/Controllers/PollController/PollVoteListController.swift
Sources/StreamChat/Database/DTOs/PollVoteDTO.swift
Sources/StreamChat/Database/DatabaseSession.swift

Updated handling for anonymous answers in polls

---

Tests/StreamChatTests/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift

https://github.com/GetStream/ios-issues-tracking/issues/848

[CI] Skip flaky unit test until further investigation

---

docusaurus/sidebars-ios.json

Bring back listening events to the sidebar.

Updated the docs section with events listening

---

.github/workflows/cron-checks.yml
.github/workflows/smoke-checks.yml
.github/workflows/xcmetrics.yml
Scripts/bootstrap.sh
StreamChatUITestsAppUITests/Pages/MessageListPage.swift
StreamChatUITestsAppUITests/Pages/SpringBoard.swift
StreamChatUITestsAppUITests/Robots/UserRobot+Asserts.swift
StreamChatUITestsAppUITests/Robots/UserRobot.swift
StreamChatUITestsAppUITests/Tests/Attachments_Tests.swift
StreamChatUITestsAppUITests/Tests/Base TestCase/StreamTestCase.swift
StreamChatUITestsAppUITests/Tests/ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Ephemeral_Messages_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus+ChannelList_Tests.swift
StreamChatUITestsAppUITests/Tests/Message Delivery Status/MessageDeliveryStatus_Tests.swift
StreamChatUITestsAppUITests/Tests/MessageList_Tests.swift
StreamChatUITestsAppUITests/Tests/PushNotification_Tests.swift
StreamChatUITestsAppUITests/Tests/QuotedReply_Tests.swift
StreamChatUITestsAppUITests/Tests/Reactions_Tests.swift
StreamChatUITestsAppUITests/Tests/SlowMode_Tests.swift
StreamChatUITestsAppUITests/Tests/UserDetails_Tests.swift
TestTools/StreamChatTestMockServer/Utilities/LaunchArgument.swift
fastlane/Fastfile

✅ https://github.com/GetStream/stream-chat-swift/actions/runs/9593133817/job/26453131991

[CI] Make CI green again

---

.github/PULL_REQUEST_TEMPLATE.md

- Updates PR Template to include new Localization Keys step in the CheckList
- Removes unnecessary warning from CheckList

Update PR Template to include new Localization Keys step

---

CHANGELOG.md
Sources/StreamChat/APIClient/RequestEncoder.swift
Tests/StreamChatTests/APIClient/RequestEncoder_Tests.swift

https://stream-io.atlassian.net/browse/PBE-5067
Fix an edge case with a semicolon in user name

Fix an edge case with a semicolon in user name

---

.github/workflows/smoke-checks.yml

- Build Test App and Frameworks
- Automated Code Review
- Build LLC + UI (Xcode 14)
- Test LLC
- Test UI
- E2E tests
- Build Demo App + Example Apps
- Test Integration

[CI] Update the order of smoke checks

---

CHANGELOG.md

Announce that we will drop iOS 12 soon.

Updated the CHANGELOG about the increase of the deployment target

---

Tests/StreamChatTests/Controllers/ChannelController/ChannelController_Tests.swift
Tests/StreamChatTests/StreamChatFlakyTests.xctestplan
Tests/StreamChatTests/StreamChatTestPlan.xctestplan

Do not access DTOs from different threads in tests

---

CHANGELOG.md
Sources/StreamChat/Utils/Debouncer.swift
Sources/StreamChatUI/Utils/Throttler.swift

`Throttler` and `Debouncer` should have higher QoS because background might never get any priority.
Apple's QoS [descriptions](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html)
```
Background
Work that operates in the background and isn’t visible to the user, such as indexing, synchronizing, and backups. Focuses on energy efficiency.
Work takes significant time, such as minutes or hours.
```
vs
```
Utility
Work that may take some time to complete and doesn’t require an immediate result, such as downloading or importing data. Utility tasks typically have a progress bar that is visible to the user. Focuses on providing a balance between responsiveness, performance, and energy efficiency.
Work takes a few seconds to a …
```

Increase QoS for Throttler and Debouncer to utility

---

docusaurus/docs/iOS/swiftui/getting-started.md

Realized we don't have a section of connect call in the getting started guide for SwiftUI.
Just a docusuarus update.
The content is the same as UIKit.

Added connectUser setup in the SwiftUI getting started guide

---

Sources/StreamChat/Models/Channel.swift
Sources/StreamChat/Utils/Codable+Extensions.swift
Sources/StreamChat/Utils/MessagesPaginationStateHandling/MessagesPaginationState.swift
Sources/StreamChat/Utils/TranslationLanguage.swift

Helps with https://stream-io.atlassian.net/browse/PBE-4993?atlOrigin=eyJpIjoiMDI5NDFhMTIxNDRiNDJlNDhkOTQxY2RkYWFjZDQ5NjgiLCJwIjoiaiJ9.
Change some static var to constants.

[Swift6 migration] Make static properties immutable where possible

---

Package.swift

N/A
Fix package warnings
Fixes the following SPM warnings when resolving the package
```
warning: 'stream-chat-swift': /package/.build/checkouts/stream-chat-swift/Package.swift:62:6: warning: 'package(name:url:_:)' is deprecated: use specific requirement APIs instead (e.g. use 'branch:' instead of '.branch')
60 | #if swift(>=5.6)
61 | package.dependencies.append(
62 |     .package(name: "SwiftDocCPlugin", url: "https://github.com/apple/swift-docc-plugin", .exact("1.0.0"))
|      `- warning: 'package(name:url:_:)' is deprecated: use specific requirement APIs instead (e.g. use 'branch:' instead of '.branch')
63 | )
64 | #endif
/package/.build/checkouts/stream-chat-swift/Package.swift:62:91: warning: 'exact' is deprecated
60 | #if swift(>=5.6)
61 | package.dependencies.append(
62 | …
```

Fix SPM deprecation warning

---

fastlane/Fastfile

Relates to:
- https://github.com/GetStream/stream-video-swift/pull/467
- https://github.com/GetStream/stream-chat-swiftui/pull/555

[CI] Automate merge to develop on release

---

StreamChat.xcodeproj/project.pbxproj
fastlane/Fastfile

- https://www.notion.so/stream-wiki/Renewing-expired-provision-profiles-and-certificates-841d148dd48e40f1a5de55f8db48f0ea?pvs=4#fccb1e373d5e4fcb9461e8b334ea9ade
- https://github.com/GetStream/stream-chat-swift/actions/runs/10083698731

Resolve test cert issue

---

Gemfile.lock
fastlane/Pluginfile

[CI] Set up a default base branch when automatically creating PRs

---

Sources/StreamChat/APIClient/APIClient.swift
Sources/StreamChat/Extensions/URLRequest+cURL.swift
StreamChat.xcodeproj/project.pbxproj

Resolves [PBE-4316](https://stream-io.atlassian.net/browse/PBE-4316)
Better support for debugging API requests as now I can easily share the cURL command.
[PBE-4316]: https://stream-io.atlassian.net/browse/PBE-4316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Log cURL representation of the URLRequest to the debug log

---

docusaurus/docs/iOS/swiftui/swiftui-cookbook/creating-channels.md

Removed some unused leftover code that was confusing to customer that the cookbook is about groups.

Update the cookbook for creating channels

---

README.md
Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
Sources/StreamChat/Controllers/MessageController/MessageController.swift
Sources/StreamChat/Controllers/ReactionListController/ReactionListController.swift
Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
Sources/StreamChat/Controllers/SearchControllers/UserSearchController/UserSearchController.swift
Sources/StreamChat/Controllers/UserListController/UserListController.swift
docusaurus/docs/iOS/basics/integration.md
docusaurus/docs/iOS/basics/overview.md
docusaurus/docs/iOS/client/state-layer/state-layer-overview.md
docusaurus/docs/iOS/uikit/getting-started.md
docusaurus/docs/iOS/uikit/theming.md

Resolves: [PBE-5540](https://stream-io.atlassian.net/browse/PBE-5540)
Update outdated content and add more examples
[PBE-5540]: https://stream-io.atlassian.net/browse/PBE-5540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update outdated documentation and add examples

---

Sources/StreamChat/Models/ChannelId.swift

Make ChannelId Sendable

---

Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Sources/StreamChatUI/Composer/ComposerVC.swift

None. Issues found while doing Release QA.
- Fix memory leaks in alert actions in the Poll views.
- Fix Poll Creation action shown inside threads.

Fix Polls Memory Leak in Alerts + Creation Poll Action shown inside Threads

---

StreamChatUITestsAppUITests/Performance.xctestplan
fastlane/Fastfile

Revert this PR as soon as https://stream-io.atlassian.net/browse/PBE-5666 is solved.

[CI] Channel list performance

---

docusaurus/docs/iOS/client/controllers/controllers-overview.md
docusaurus/docs/iOS/guides/attachments-migration.md
docusaurus/docs/iOS/guides/migrating-from-1.x-and-2.x.md
docusaurus/docs/iOS/guides/migrating-from-3-to-4.md
docusaurus/docs/iOS/swiftui/getting-started.md
docusaurus/docs/iOS/uikit/components/channel-list.md
docusaurus/docs/iOS/uikit/custom-components.md
docusaurus/docs/iOS/uikit/theming.md

Our new docs will not support docs that are not part of the navigation tree. Therefore, we need to change those links with ones directly from GitHub.

Updated reference links in the docs

---

CHANGELOG.md
Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
Sources/StreamChatUI/ChatThread/ChatThreadVC.swift

https://github.com/GetStream/stream-chat-swift/issues/3461
Opens both properties so that additional logic can be added by the customer.
N/A

Open `shouldMarkThreadRead` and `shouldMarkChannelRead`

---

docusaurus/docs/iOS/swiftui/channel-list-components/channel-list-search.md

Related to https://stream-io.atlassian.net/browse/PBE-6220
Add Channel Search documentation to SwiftUI.
Requires https://github.com/GetStream/stream-chat-swiftui/pull/628 to be merged first.

Add Channel Search documentation to SwiftUI

---

.github/workflows/release-publish.yml

Example: https://getstream.slack.com/archives/CRML30N0H/p1731669961930409

[CI] Add reminder about last release step

---

CHANGELOG.md

Fix PR links in the changelog

---

.github/workflows/record-snapshots.yml
.github/workflows/smoke-checks.yml
fastlane/Fastfile

Avoid re-recording all the snapshots on CI
- [Soft-recording](https://github.com/GetStream/stream-chat-swift/actions/runs/13262103938/job/37020948565)
- [Hard-recording](https://github.com/GetStream/stream-chat-swift/actions/runs/13262560489/job/37022450912)

[CI] Snapshots recording improvement

---

.github/workflows/cron-checks.yml

https://github.com/GetStream/stream-chat-swift/actions/runs/13675114836

[CI] Replace simulator on cron checks

---

README.md

Resolves https://linear.app/stream/issue/IOS-875/readme-updates.
Increase visibility of the Video SDK.

Added reference to the video SDK

---

.github/workflows/cron-checks.yml
.github/workflows/smoke-checks.yml

Test: https://github.com/GetStream/stream-chat-swift/actions/runs/15440883835

[CI] Switch macos version to keep the support of Xcode 15.4

---

DemoApp/Screens/Livestream/DemoLivestreamChatChannelVC.swift

Quickly add missing debug icon to the demo app

Add debug icon to livestream demo app screen
