GetStream/stream-chat-swift

- Sources/Core/Client/ClientError.swift
- Sources/Core/Model/Attachment.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChatCoreTests/Unit Tests/AttachmentTypeTests.swift
There was no information in the application what was the type of the attachment if it wasn't on the list of recognized types. I added parameter to `.unknown` type
> Added raw type to unknown AttachmentType

- Sources/Core/Client/Client+Setup.swift
- Sources/Core/Client/Token.swift
Change `Token`'s `payload` variable to be a [String: Any] dictionary.
The JWT token on our chat decodes to:
```
{"exp": 00000000, "user_id": "xxxxx"}
```
where `exp` is an Int and `user_id` is a String. Currently, `Token`'s `payload` variable tries to cast the serialized JSON  object as a [String: String] dictionary, which returns a `tokenInvalid` error and a request will never be made. The Stream getting started tutorial only contains the `user_id` key in the JSON, so it succeeds.
> Bugfix: tokenInvalid error.

- StreamChat.xcodeproj/project.pbxproj
Signing my app using Xcode 11 was failing because of error:
```
Assertion failed: Duplicate symbols for [Nuke's id]
```
`carthage copy-frameworks` has to be added only to the application's target, not libraries.
> Removed carthage phase from libraries

- Sources/Core/Model/Channel.swift
- Not sure that tests are needed here
Use member avatar as channel image in one-on-one convenience initializer.
Because the `imageURL` property of a `Channel` object is currently not configurable after initialization, it’s impossible to get the user’s avatar set up using the one-on-one convenience initializer. Using this avatar feels like the correct default to me.
> Use member avatar as channel image in one-on-one convenience initializer

- README.md
I don't know when was it broken, but just drag & dropping libraries selects "Embed & Sign" option which gives "Multiple commands produce framework" error during build time. Our setup instructions are exactly the same as the official one but it does not work. The updated instructions are tested and working.
> Fixes Carthage setup instructions

- StreamChatRealm.podspec
Typo for database folder.
The StreamChatRealm podspec had a typo in the source files path which was not allowing the pod to install any files.
> [Minor]: Typo in Source files Path

- CHANGELOG.md
- Sources/UI/Chat/Cells/MessageTextEnrichment.swift
Since `.markdown` CharacterSet did not include "~~" character (and could not include - since it's 2 characters) `addMarkdown` was returning false for strings such as `~~str~~`
> Fix strikethrough markdown with ~~

- CHANGELOG.md
- Sources/Core/Client/Client+Request.swift
- Sources/Core/Client/ClientError.swift
- Sources/Core/Model/Attachment.swift
- Sources/UI/Banners/Banners.swift
That's another take on issue #104 .
I modified errors so they conform to `CustomDebugStringConvertible`. This way `print(error.localizedDescription)` will always produce human-readable error and `print(error)` will produce more detailed debug information. 
`localizedDescription` is suitable for displaying error to the user while `String(describing: error)` or `\(error)` should be used when displaying error in the logs.
> Add debugDescription to all errors

- Sources/Client/Client/Client.swift
I needed this while writing the Push notification test application. I've used this closure:
```swift
Client.shared.onConnect = { connection in
if connection.isConnected {
DispatchQueue.main.async {
self.viewController?.askForNotificationPermissionIfNeeded()
}
Client.shared.onConnect = { _ in }
}
}
Client.shared.connect()
```
but a completion closure (which automatically handles this) would be more clear.
> Add completion closure to connect function

- Example/Sources/LoginViewController.swift
- Sources/Client/BaseURL.swift
- Sources/Client/Client/Client.swift
... and adds Config initializer for baseURL param
So users can do:
```swift
if let config = Client.Config(apiKey: apiKey, baseURL: "https://your-awesome-chat-server.com/") {
Client.config = config
}
```
or
```swift
if let url = URL("https://your-awesome-chat-server.com/") {
Client.config = .init(apiKey: apiKey, baseURL: url)
}
```
and
```swift
Client.config = .init(apiKey: apiKey, baseURL: .usEast)
```
more!
```swift
Client.config = .init(apiKey: apiKey, baseURL: .dublin)
```
without losing the current functionality
> Removes proxy and staging servers

- Sources/Client/Client/Client+Config.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/ExtraData.swift
- Sources/Client/Model/Message/Attachment/Attachment.swift
- Sources/Client/Model/Message/Message.swift
- Sources/Client/Model/Message/Reaction.swift
- Sources/Client/Model/User/User.swift
- Sources/Core/Client/Subscription.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Integration Tests/ClientTests01+Channels.swift
- Tests/Client/Integration Tests/ClientTests10+ClientLogger.swift
- Tests/Client/TestCase.swift
Create a custom extra data type with any complexity, but `Codable`:
```swift
struct ProductChannel: Codable {
let info: String
let product: Product
}
```
Set this custom type at any time (this is good for tutorials) to the related our model type:
```swift
Channel.extraDataType = ProductChannel.self
```
Use extra data in place:
```swift
if let productChannel = channelPresenter.channel.extraData?.object as? ProductChannel {
cell.nameLabel.text = productChannel.product.name
cell.detailTextLabel.text = productChannel.info
}
```
> Setup ExtraData types

- CHANGELOG.md
- Sources/Core/Client/Client+Request.swift
- Sources/Core/Presenter/Channel Presenter/ChannelPresenter.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Here's a video showing it working: 
https://www.dropbox.com/s/ibrmgcyjwesuu1f/Screen%20Recording%202020-03-18%20at%2011.35.35.mov?dl=0
The idea is:
1. When the user starts typing, send `typingStarted` event, only once.
2. If the user doesn't type for 3 seconds, send `typingStopped` event, only once.
I've tried to simplify as much as possible for this scenario. `bufffer` helps me fire periodical events, which `debounce` does not do. Also, `debounce` and sending `typingStopped` event relied on server response of `typingStarted` event, which didn't work as expected.
> Fix typing events are not reliably sent in UI components

- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Fixes #118
Steps to reproduce this bug can be found in #118
After investigating a couple of messajing apps (Whatsapp, Slack, Twitter) I've realized that when those apps are sent to bg when keyboard is visible, they don't `resignFirstResponder` so when reopened, keyboard is correctly visible. I believe the best solution is to follow other messaging apps so our SDK behaves like users expect.
The issue arises from keyboard notification not sent when we `resignFirstResponder` after apps is reopened. Our state machine breaks and calculations are not correct anymore.
One other solution could be to `resignFirstResponder` in `viewWillDisappear`.
> Fix composerView disappearing after sending the bg

- Example/Cocoapods/Podfile
- Example/Cocoapods/Podfile.lock
Example depends on 'StreamChatClient', which was missing from the Podfile.
> Update CocoaPods example

- Sources/UI/Chat/Cells/MessageTextEnrichment.swift
Ranges of links were being decided before markdown was parsed, so they were shifted right by the number of characters removed in the markdown parsing.
I just moved the link parsing to after the markdown parsing & made sure the attributedString.string (without markdown symbols) is used instead of the plain text.
|-|-|
|![2020-04-02 01 46 38](https://user-images.githubusercontent.com/5606812/78212440-1f6e8d80-7486-11ea-9f56-3d588e06566c.gif)|![2020-04-02 02 05 59](https://user-images.githubusercontent.com/5606812/78212697-dff47100-7486-11ea-928d-fd1c8ef9879d.gif)|
Test strings: 
```
Google: https://google.com
Discord: https://discord.com
**Google**: https://google.com
**Discord**: https://discord.com
```
> Fix link detection accuracy in messages with markdown

- Sources/Client/Model/Channel/ChannelExtraData.swift
- Sources/Client/Model/User/UserExtraData.swift
...otherwise they're not usable from outside
> Add memberwise inits for extra data structs

- CHANGELOG.md
- Sources/Client/Client/Client+Request.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Client/ClientError.swift
- Sources/Client/Client/Endpoint.swift
I don't think printing the callStack on error is good/expected by developers, so I replaced it with instructions to print callstack (like RxSwift does)
I've followed our REST docs to see which endpoints require connection id, but I'd appreciate a second pair of eyes: https://getstream.io/chat/docs_rest/
> CIS-65 Add verbose error for endpoints requiring connection id

- CHANGELOG.md
- Sources/Client/Client/Client+Events.swift
Removes the API call side-effect and instead it now relies on events that include watcher_count.
@buh do you include CHANGELOG changes in each PR or do you make that at release time?
> CIS-72 Change channel.subscribeToWatcherCount to only rely on channel events

- Sources/Client/Model/Pagination.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Unit Tests/QueryEncodingTests.swift
Fixes #165
Fixes the block in `ChannelQuery`:
```swift
if !messagesPagination.isEmpty {
try container.encode(messagesPagination, forKey: .messages)
}
if !membersPagination.isEmpty {
try container.encode(membersPagination, forKey: .members)
}
if !watchersPagination.isEmpty {
try container.encode(watchersPagination, forKey: .watchers)
}
```
encoding an array instead of an object.
Also closes CIS-38
> CIS-38 Fix container.encode for Pagination encoding array

- Example/Sources/LoginViewController.swift
- Example/Sources/Main.storyboard
- Example/Sources/RootViewController.swift
- Sources/Client/Client/Client+Events.swift
- Sources/Client/Client/Client+Request.swift
- Sources/Client/Client/Client+Setup.swift
- Sources/Client/Client/Client+WebSocket.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Client/ClientError.swift
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/Event.swift
- Sources/Client/Model/EventType.swift
- Sources/Client/Model/UserConnection.swift
- Sources/Client/WebSocket/ConnectionState.swift
- Sources/Client/WebSocket/WebSocket.swift
- Sources/Core/Client/Client+RxEvents.swift
- Sources/Core/Client/Client+RxUnreadCount.swift
- Sources/Core/Extensions/RxFunctions.swift
- Sources/Core/Presenter/Channel/ChannelPresenter+RxRequests.swift
- Sources/Core/Presenter/Channels/ChannelsPresenter+Rx.swift
- Sources/Core/Presenter/Presenter+Rx.swift
- Sources/Core/Presenter/ViewChanges.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Integration Tests/ClientTests00.swift
- Tests/Client/TestCase.swift
- Tests/Client/Unit Tests/QueryEncodingTests.swift
- releasing.md
- added `set(user:)` with a completion block with a result of `UserConnection`.
- `WebSocket` connection now is publishing as events.
- `Token` event observing was removed because connection management moved to LLC.
- check if channel subscription for channel events only (show a warning in logs)
- Example app UI was simplified
- added a priority to the client for WebSocket events to avoid late update for the user and watching channels.
> WebSocket connection as event

- CHANGELOG.md
- StreamChat.xcodeproj/project.pbxproj
`RxBlocking` was referenced as a linked framework in `StreamChatCore`. The dependency is never used and can be removed.
> Remove unused RxBlocking import

- Sources/Client/Utils/Reachability.swift
- Sources/Core/Extensions/InternetConnection+Rx.swift
- Builds were failing because of a forgotten `import Reachability`
- I have to make parts of the `Reachability` class public so we can access them from the `Core` framework.
> Remove forgotten `Reachability` import

- Example/Carthage/ChatExample.xcodeproj/project.pbxproj
- Example/Cocoapods/Podfile.lock
- Our Example apps we still using removed dependencies.
- Both Carthage and CocoaPods integration are fixed
> Update Example apps to not used removed dependencies

- .github/workflows/ci.yml
- Cartfile.resolved
- We shouldn't be using `carthage update` for installing the dependencies. This can result in dependencies updating to without us knowing about it.
- `carthage bootstrap` resolves the dependency tree based on the info from `Cartfile.resolved` and never updates the dependencies.
> Improve Carthage setup

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Originally #124 should've resolved this, but seems like it didn't. Issue is caused from VC calling `willTransitionTo(traitCollection)` when going into bg. Keyboard is visible at this stage so `initialSafeAreaBottom` is wrongly calculated taking into account the keyboard's size.
Fixes #188
> Fix composerView hiding behind keyboard after sending bg

- Example/Carthage/ChatExample.xcodeproj/project.pbxproj
- Example/Carthage/ChatExample/Info.plist
- Sources/Info.plist
- StreamChat.xcodeproj/project.pbxproj
- fastlane/Fastfile
- fastlane/README.md
- fastlane/actions/touch_changelog.rb
For now, we can only run it locally with a correct GITHUB_TOKEN (it asks for one in CLI if it can't find it in ENV)
I've left the `pod_push` actions to the last step since they can fail unnecessarily, in that case we should only run `pod trunk push <podpsec>` in our CLI, all other stuff will be taken care of by fastlane
And yes, I've wrote a custom `touch_changelog` action just for our CHANGELOG format and learnt a lot of ruby from the process......
Closes #77 
> Add release lane to fastlane

- .github/workflows/beta.yml
- .github/workflows/ci.yml
- Tests/Client/TestCase.swift
- fastlane/Fastfile
- fastlane/README.md
- fastlane/Scanfile
Refactor Carthage caching to rebuild deps when cache misses, and makes sure it runs when cache hits too (it'll take a couple of seconds since we use `--cache-builds`. Also renames nightly to Beta since it doesn't run Nightly, and introduces fastlane lane for testing (goodbye xcodebuild)
> Refactor CI/Beta workflows

- .github/workflows/ci.yml
- fastlane/Fastfile
- fastlane/README.md
- fastlane/Scanfile
- Some of the existing tests are flaky and it doesn't make sense to run them on the CI. Let's just make sure we can build.
- I added a new `build` lane to Fastfile for building only.
> Temporarily disable tests on the CI

- Dangerfile
Doesn't make sense to include changelog entry for meta PRs
> Update Dangerfile to not warn for CHANGELOG when meta tag is used

- CHANGELOG.md
- Sources/UI/Web View/WebViewController.swift
- This is a part of the work for CIS-89.
- I added additional links with more info about the bug the code causing the warning fixes.
- I used the good old Obj-C style to remove the deprecation warning from the compiler.
> Remove deprecation warning for UIDocumentMenuViewController

- .github/workflows/ci.yml
- Dangerfile
- Temporarily disable code coverage reports on PRs.
- Remove Danger's warning that tests were not updated: 
- This warning is not relevant. For many (all?) internal changes we don't want tests to be updated! As long as tests compile and are green we should be good.
> Improve CI experience

- Sources/UI/Views/AvatarView.swift
A small bug if the flow for AvatarView updating is a little bit different there is a case where the placeholder label is not hidden.
> Fixed AvatarView update

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Extensions/UIKit/ViewController+ImagePicker.swift
Also fixes image picker not asking for permission for available source types
Fixes #199
I wish I could use
```swift
do {
let val = try result.get()
} catch {
// ...
}
```
for result types, but unfortunately `catch` block will always receive an `Error` although it's only possible for 1 type of error to be thrown.
> Fix ImagePicker shows errors when no image is picked

- fastlane/Fastfile
... and skip pod_push validation since our CI is awesome
> Refactor release lane with git checks

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
We don't need to disable composer after every message, messages are sent via WS and this is very fast.
> Fix keyboard disappearing after every message

- StreamChat.podspec
- StreamChatCore.podspec
- StreamChatRealm.podspec
- This PR fixes podspec files to always fetch dependencies with the same version number.
> Change podspecs to lock all frameworks to same version

- CHANGELOG.md
- Example/Sources/LoginViewController.swift
- Sources/.swiftlint.yml
- Sources/Client/Client/Client+Config.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Client/ClientLogger.swift
- Tests/Client/Integration Tests/ClientTests01+Channels.swift
- Tests/Client/Integration Tests/TestCase.swift
- Tests/Client/Unit Tests/QueryEncodingTests.swift
- **No breaking changes!**
- Using the static `Client.config` variable is deprecated.
- Configuring the shared `Client` has to be done explicitly by calling `Client.configure(_:)`.
```swift
// Deprecated:
Client.config = .init(apiKey: apiKey, logOptions: .info)
// Preferred:
var config = Client.Config(apiKey: apiKey)
config.logOptions = .info
Client.configure(config)
```
- Using `Client.shared` without configuring it triggers an assertion failure in the DEBUG configuration (silently fails in RELEASE):
- Trying to change the configuration of an existing singleton triggers an assertion failure in the DEBUG configuration (silently fails in RELEASE):
- Using an empty string as the API key triggers an assertion failure in the DEBUG configuration (silently fails in RELEASE):
---
Happy to hear …
> CIS-114 Make shared Client config more robust

- fastlane/Fastfile
- fastlane/README.md
As we're adding issue numbers in our CHANGELOG, this lane can help us determine the next issue number, preventing unnecessary commits
> Add lane for getting next issue number

- Sources/Client/Client/Client+Request.swift
- Sources/Client/Client/Client.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Custom Assertions/AssertNetworkRequest.swift
- Tests/Client/RequestRecorderURLProtocol.swift
- Tests/Client/Unit Tests/Client+DevicesTests.swift
- I made the default `URLSessionConfiguration` the client uses configurable. I had to do it to make it possible to register a custom `URLProtocol` on `Client`'s `URLSession`.
- I created `RequestRecorderURLProtocol`, a `URLProtocol` implementation which listens to all network requests and stores the last one made. You can call `getLatestRequestSynchronously()` on it to synchronously wait for a future request. This is quite cool but it makes asynchronous tests as simple to write as synchronous.
- To showcase how this can be used I added tests for `Client+Device` API calls.
Please note that this is just the first step. As we will use this more and more we can add more functionality and smooth all rough edges.
#no_changelog
---
@buh @b-onc Since this PR is big, I prepared the commit history …
> CIS 120 Add possibility to assert a network request was made

- CHANGELOG.md
- Sources/Core/Presenter/UploadingItem.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Chat/Composer/UploaderItem+UIImagePickerController.swift
Since images coming from camera have no local fileURL, our uploads were failing. I've moved the size check logic into UploadingItem, now size check is being done on uploadingItem.data
Moreover, we've broken video uploads some time in the past and this PR fixes them too. Tested and working.
Fixes #236
> Fix image & video uploads from camera

- CHANGELOG.md
- Sources/Client/Extensions/URL+Extensions.swift
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/User/User.swift
- Sources/Client/Model/User/UserExtraData.swift
- StreamChat.xcodeproj/project.pbxproj
If ExtraData fails on decoding for some property it will fail all properties.
This PR will add 2 things:
1. Show a decoding error in logs
2. Try to decode as a default extra data type.
The story:
We have a customer who has `imageURL` as an empty string and it fails to decode. Users, in this case, will be shown as ids instead of names.
> CIS-138 Recover the default extra data for User and Channel types

- .github/workflows/beta.yml
- .github/workflows/ci.yml
- .github/workflows/test-old-ios-versions.yml
- Gemfile
- Gemfile.lock
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Unit Tests/ClientLoggerTests.swift
- fastlane/Fastfile
- fastlane/README.md
- fastlane/Scanfile
Test run here: https://github.com/GetStream/stream-chat-swift/runs/649869791?check_suite_focus=true
We're able to test iOS 11.4 and 12.4 (in parallel!), and we're using (we have to) backend integration test. The reported iOS12 crash was related to network request part, so I thought this makes sense to have!
Oh, also moved ClientLogger tests to Unit tests target since it was a unit test.
> CIS-115 Test old iOS SDKs nightly

- CHANGELOG.md
- Sources/Client/Utils/Atomic.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Custom Assertions/AssertEventually.swift
- Tests/Client/Unit Tests/AtomicTests.swift
- I created two new async assertions `AssertEqualEventually` and `AssertNilEventually`. They are inspired by [Nimble](https://github.com/Quick/Nimble) and they allow us to write async assertions as they were synchronous.
- I added a test suite for `Atomic` and changed its implementation from using `DispatchQueue` to `NSRecursiveLock`.
---
[Closes #252]
> [CIS 122] Add test coverage for `Atomic`

- CHANGELOG.md
- Sources/Core/Client/Channel/Channel+RxEvents.swift
Fixed crashes on `channel.rx.events` and `channel.rx.unreadCount`.
> Fixed rx crashes

- CHANGELOG.md
- Sources/Client/Client/Client.swift
- Sources/Client/WebSocket/WebSocket.swift
- Sources/Core/Client/Client+RxEvents.swift
- Sources/Core/Presenter/Presenter+Rx.swift
For rx subscriptions important to start with an initial connection state.
I made `WebSocket.connectionState` as Atomic and shared it on `Client`.
Also, I added current values for Client unread count and user on subscribe.
> Fixed rx observing for the connection state.

- CHANGELOG.md
- Sources/Client/Client/Client+UnreadCount.swift
- Sources/Client/Client/Client+WebSocket.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Utils/Atomic.swift
- Sources/Client/WebSocket/WebSocket.swift
- Sources/Core/Presenter/Channel/ChannelPresenter.swift
- Tests/Client/Unit Tests/AtomicTests.swift
- `value` in `Atomic` is no longer treated as `Optional` by default
- `Atomic` stress tests random crash (hopefully) fixed 🤞 
---
@buh  @b-onc Please review and test this **extremely** carefully. I touched a lot of different parts of the app and could easily introduce some copy-paste/typo kind of bug 🙏
> Removed forced optional type used in `Atomic`

- CHANGELOG.md
- Sources/Core/Client/AutoCancellingSubscription.swift
RxSwift Event type can have unknown values in updates, better to not use switch on it
> Fix RxSwift warning

- CHANGELOG.md
- Sources/Client/Client/Client.swift
- Sources/Client/Client/Endpoint.swift
Backend has informed me that it's not actually required unless presence or state is requested
Also fixed CHANGELOG since it was broken
> Fix clientId is required for queries

- Sources/Client/Client/Client+Request.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Custom Assertions/AssertJSONEqual.swift
- Tests/Client/RequestRecorderURLProtocol.swift
- Tests/Client/Unit Tests/Channel_SilentMessageTests.swift
- Tests/Client/Unit Tests/Client+DevicesTests.swift
- Tests/Client/Unit Tests/Client_SilentMessageTests.swift
- Tests/Client/Unit Tests/QueryEncodingTests.swift
- Tests/Client/Unit Tests/WebSocket/WebSocketTests.swift
- Make`RequestRecorderURLProtocol` record only selected requests if needed
#no_changelog
> Improve test stability

- Sources/Client/Client/Client+Request.swift
Fixes 85690141eb3b48dd58663a9bbdaecacee1638221
```swift
config.httpAdditionalHeaders?.merge(headers, uniquingKeysWith: { (_, new) in new })
```
did not work when `config.httpAdditionalHeaders` is `nil`, which is when it's first setup
#no_changelog
> Fix URLSession headers not being assigned

- CHANGELOG.md
- Sources/Client/Client/ClientLogger.swift
Users using old logger will see compiler warning but their logic won't work - this PR fixes it
> Fix deprecated logger overrides logic

- CHANGELOG.md
- Sources/Client/WebSocket/Provider/URLSessionWebSocketProvider.swift
- The original implementation didn't behave correctly when the WS connection fails and ended up in the infinite loop and crashed.
- We do not want to call `doRead()` again when the connection fails.
> Fix infinite loop when `URLSessionWebSocketTask` fails

- .swiftformat
- bootstrap.sh
- hooks/pre-commit.sh
Please run `./bootstrap.sh` after merging this PR to install pre-commit hook!
The hook only runs on /StreamChatClient_v3 folder for now, we'll continue to use swiftlint until v3 is released.
Swiftformat rule documentation: https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md
Rules are inferred from: https://github.com/apple/swift/tree/master/stdlib/public/core
> [CIS-117] Add pre-commit hook

- CHANGELOG.md
- Sources/Client/Client/Client+WebSocket.swift
- Sources/Client/Model/User/User.swift
- Sources/Client/WebSocket/WebSocket.swift
- Tests/Client/Custom Assertions/AssertAsync.swift
- Tests/Client/Unit Tests/WebSocket/WebSocketTests.swift
Stop showing a user typing if a user doesn't send a stop typing event after 30 sec.
**Note:** I moved a logic related to the current user from WebSocket to the Client to make tests work.
> [CIS-68] Automatically send `typingStop` event after a timeout

- Sources/Client/Client/Client+Channel.swift
- Sources/Client/Client/Client.swift
- Sources/Client/Model/Channel/Channel+Requests.swift
- Sources/Client/Model/Channel/Channel.swift
- Tests/Client/Unit Tests/Channel+KeystrokeTests.swift
- The tests for keystroke events now run synchronously
#no_changelog
> Improve keystroke tests

- Sources/Client/Utils/Atomic.swift
New Atomic implementation doesn't need an extension for Collection. It works with regular `subscript`.
> New Atomic implementation doesn't need extension for Collection.

- .github/workflows/ci.yml
- fastlane/Fastfile
- fastlane/README.md
Danger and codecov obviously disabled for v3 targets for now. Carthage is not needed for v3 tests since it has no dependencies.
> [CIS-152] Add testing lane for v3 and run on CI

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/Utils/Atomic.swift
- StreamChatClient_v3/Utils/Atomic_tests.swift
- TestResources_v3/Custom Assertions/AssertAsync.swift
- `AssertAsync.willBeEqual` no longer takes `@escaping` closures (we don't need to use `self` on the caller site)
- The basic functionality of `Atomic` is migrated to v3
- Added option to use it as a property wrapper
#no_changelog
> [CIS-176] Migrate `Atomic` to v3

- StreamChat.xcodeproj/project.pbxproj
- TestResources_v3/Await.swift
- TestResources_v3/Custom Assertions/AssertAsync.swift
- TestResources_v3/Custom Assertions/AssertJSONEqual.swift
- TestResources_v3/Custom Assertions/AssertResult.swift
- TestResources_v3/TemporaryURLs.swift
- TestResources_v3/TestError.swift
- hooks/pre-commit.sh
- The formatter is ran for `/TestResources_v3` folder, too
- Existing code is reformatted
#no_changelog
> [CIS-174] Format Swift code in `/TestResources_v3` folder, too

- CHANGELOG.md
- Sources/Core/Presenter/Channel/ChannelPresenter+RxRequests.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
1. Initialize ChatViewController
2. Make queryChannels without queryOptions eg: `Client.shared.queryChannels(filter: .equal("id", to: "general2")) { ... }`
3. Use the ChannelResponse to initialize a ChannelPresenter with queryOptions .all, eg: `ChannelPresenter(response: response, queryOptions: .all)`
4. Set the ChatViewController presenter to it and display the view controller
5. Sending a message won't show up and no other updates are given
Logs without bug: http://dontpad.com/working_logs_jqwelqkwej1
Logs with bug: http://dontpad.com/bug_logs_lqwenqkwej12
The .watch (or .all) query option given to ChannelPresenter does not seem to take effect.
If a ChannelPresenter is initialized with a ChannelResponse and it already contains items, it won't run `presenter.reload()` in …
> Fix new messages/updates not given for ChannelPresenter initialized with ChannelResponse

- CHANGELOG.md
- Sources/Core/Presenter/Channels/ChannelsPresenter+Rx.swift
- Sources/Core/Presenter/Channels/ChannelsPresenter.swift
Let's say we create our channel with filter:```channelsVC.presenter = .init(filter: .currentUserInMembers & .equal("id", to: "general")```and it initially shows a single channel (as expected).When our user is added to a new channel, websocket sends `notification_added_to_new_channel` event and ChannelsPresenter parses this and adds the new channel into list. Neither backend nor presenter does not check for the filters, so filters are disregarded for newly created channels.
> [CIS-145] Fix ChannelsPresenter not respecting filter for new channels

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/WebSocketClient/WebSocketReconnectionStrategy.swift
- StreamChatClient_v3/WebSocketClient/WebSocketReconnectionStrategy_tests.swift
The work on [CIS-168] turned out to be so massive I decided to split it the PR into multiple parts.
This part contains the web socket reconnection logic which is now extracted into a separate object.
#no_changelog
[CIS-168]: https://stream-io.atlassian.net/browse/CIS-168
> [CIS-168] Finish WebSocketClient implementation Part 2: Reconnection strategy

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/WebSocketClient/ConnectionState.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/EventMiddleware.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/EventMiddleware_tests.swift
- StreamChatClient_v3/WebSocketClient/Events/ConnectionEvents.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient_tests.swift
- StreamChatClient_v3/Workers/Background/ChannelEventsHandler_tests.swift
The work on [CIS-168] turned out to be so massive I decided to split it the PR into multiple parts.
This part contains the actual migration of `WebSocketClient` to v3. Important bits:
- It's not 1-to-1 conversion, I tried to clean up, simplify, and formalize the patterns we use
- Missing pieces:
- logging [CIS-184]
- reacting to internet connection changes [CIS-185]
#no_changelog
[CIS-168]: https://stream-io.atlassian.net/browse/CIS-168
[CIS-184]: https://stream-io.atlassian.net/browse/CIS-184
[CIS-185]: https://stream-io.atlassian.net/browse/CIS-185
> [CIS-168] Finish WebSocketClient implementation Part 3: Implementation

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/HealthCheckFilterMiddleware.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/HealthCheckFilterMiddleware_tests.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware_tests.swift
- StreamChatClient_v3/WebSocketClient/Events/TypingEvents.swift
The work on [CIS-168] turned out to be so massive I decided to split it the PR into multiple parts.
This part contains example implementations of 2 event middlewares:
- `HealthCheckFilter`
- `TypingStartCleanupMiddleware`
#no_changelog
[CIS-168]: https://stream-io.atlassian.net/browse/CIS-168
> [CIS-168] Finish WebSocketClient implementation Part 4: Middlewares

- CHANGELOG.md
- Sources/Client/Client/Client+Message.swift
- Sources/Client/Client/Endpoint.swift
- Sources/Client/Model/LocalizedMessage.swift
- Sources/Client/Model/Message/Message+Requests.swift
- Sources/Client/Model/Message/Message.swift
- Sources/Client/Utils/Language.swift
- StreamChat.xcodeproj/project.pbxproj
```swift
message.translate(to: .german) { result in
let germanText = result.value!.message.i18n?.translated[.german]
}
```
API looks very close to other SDKs
> [CIS-179] Add Message translation endpoint

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
- Sources/UI/Style/ComposerViewStyle.swift
`PinStyle` for `ComposerViewStyle` with options:
- `.floating` - shows `ComposerView` over messages (by default).
- `.solid` - shows messages above `ComposerView` with a `ComposerViewStyle` top edge inset.
> Add `PinStyle` for `ComposerViewStyle`

- Dangerfile
- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/APIClient/APIClient.swift
- StreamChatClient_v3/APIClient/APIClient_Tests.swift
- StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints.swift
- StreamChatClient_v3/APIClient/Endpoints/Endpoint.swift
- StreamChatClient_v3/APIClient/RequestDecoder.swift
- StreamChatClient_v3/APIClient/RequestDecoder_Tests.swift
- StreamChatClient_v3/APIClient/RequestEncoder.swift
- StreamChatClient_v3/APIClient/RequestEncoder_Tests.swift
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/ChatClient_Tests.swift
- StreamChatClient_v3/Config/ChatClientConfig.swift
- StreamChatClient_v3/Errors/ClientError.swift
- StreamChatClient_v3/Errors/ErrorPayload.swift
- StreamChatClient_v3/Utils/Codable+Extensions.swift
- StreamChatClient_v3/Utils/Logger/Logger.swift
- StreamChatClient_v3/Utils/OptionSet+Extensions.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketReconnectionStrategy.swift
- StreamChatClient_v3/WebSocketClient/WebSocketReconnectionStrategy_Tests.swift
- StreamChatClient_v3/Workers/Background/ChannelEventsHandler_Tests.swift
- TestResources_v3/Await.swift
- TestResources_v3/Mock Network/AssertNetworkRequest.swift
- TestResources_v3/Mock Network/MockNetworkURLProtocol.swift
- TestResources_v3/Mock Network/RequestRecorderURLProtocol.swift
- TestResources_v3/TemporaryData.swift
- V3SampleApp/AppDelegate.swift
- Danger changelog warning is skipped for `v3` PRs. Having a changelog is not necessary until `v3` is released.
- `v2` test helpers were updated, improved, and migrated to `v3`. It would be good to backport them to `v2`, too, since they are more reliable now (CIS-195).
- `APIKey` is now a custom struct. This was done mainly to avoid the unnecessary `isEmpty` checks down the road.
- The fields of `Endpoint` are simplified and we use `Encodable?` for both, the query items and the body.
- `v2` `APIClient` is split into 3 separate objects:
- `RequestEncoder` -> converts `Endpoint` to `URLRequest` and takes care of encoding all the requierd and endpoint-specific values.
- `RequestDecoder` -> used to handle the response from the network and decode it.
- `APIClient` -> Orchestrates everything …
> [CIS-169] APIClient implementation

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints.swift
- StreamChatClient_v3/APIClient/Endpoints/MemberEndpoints.swift
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/Database/DTOs/ChannelDTO.swift
- StreamChatClient_v3/Database/DTOs/ChannelDTO_Tests.swift
- StreamChatClient_v3/Database/DTOs/MemberModelDTO.swift
- StreamChatClient_v3/Database/DTOs/TeamDTO.swift
- StreamChatClient_v3/Database/DatabaseContainer.swift
- StreamChatClient_v3/Database/DatabaseContainer_Tests.swift
- StreamChatClient_v3/Database/DatabaseSession.swift
- StreamChatClient_v3/Database/DatabaseSession_Tests.swift
- StreamChatClient_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- StreamChatClient_v3/Models/ChannelId.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
- StreamChatClient_v3/WebSocketClient/EventMiddlewares/HealthCheckFilterMiddleware_Tests.swift
- StreamChatClient_v3/WebSocketClient/Events/ChannelEvents.swift
- StreamChatClient_v3/WebSocketClient/Events/ConnectionEvents.swift
- StreamChatClient_v3/WebSocketClient/Events/Event.swift
- StreamChatClient_v3/WebSocketClient/Events/EventDecoder.swift
- StreamChatClient_v3/WebSocketClient/Events/Event_Tests.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- TestResources_v3/MockEnpointResponses/Event.json
- V3SampleApp/AppDelegate.swift
The main goal of this PR is to prepare the basic infrastructure for Event handling and saving the incoming data to DB. 
In v2, the data of the event are simply part of the event object itself. This is no longer possible because all data live in the DB. The desired behavior, when an event comes, is to parse the JSON data, save then to DB, and **then** publish the event to listeners.
However, we can't simply attach the `EventPayload` to `Event` for two reasons:
- `EventPayload` is internal and we don't want to leak this information to users
- `EventPayload` is generic over `ExtraData` and we don't want to introduce associated type to `Event` protocol
I created a new internal protocol `EventWithPayload` to which events, where it is desirable to save the additional data, conform. The payload …
> [CIS-196] Handle incoming Event data

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Reactions.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
- Sources/UI/Views/ReactionsView.swift
I had to make it a little more complex than just sorting with < since that yields:
And that's a weird order to have. It makes more sense to have this which is in line with most social platforms:
Ideally, the dictionary would be an array of `(type: String, (emoji: String, maxScore: String))`, but this would break API for `defaultEmojiReactionTypes`.
Closes #332
> Fix emojis in reaction view displayed in inconsistent order

- CHANGELOG.md
- Sources/UI/Chat/Cells/MessageTableViewCell.swift
> Fix increasing username label font size in message cell causing cut off

- StreamChatClient_v3/APIClient/RequestDecoder.swift
- StreamChatClient_v3/APIClient/RequestEncoder.swift
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/Errors/ClientError.swift
- StreamChatClient_v3/Models/ChannelId.swift
- StreamChatClient_v3/WebSocketClient/Events/ChannelEvents.swift
- StreamChatClient_v3/WebSocketClient/Events/ConnectionEvents.swift
- StreamChatClient_v3/WebSocketClient/Events/EventDecoder.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient_Tests.swift
I went through existing cases for ClientError's. The idea to make ClientError more friendly on printing to confirm to `CustomStringConvertible` protocol. On the same time an error usually described by `localizedDescription` that used a lot in error subclasses, but we can't override variable in easier usage. So I made it as read only variable and now you can override it.
For example:
```swift
extension ClientError {
class ImageURL: ClientError {
override public var localizedDescription: String { "The image url is not valid." }
}
}
let imageURLError = ClientError.ImageURL()
print(imageURLError)
// Error ImageURL in PrintError.playground:45 -> The image url is not valid.
// ClientError with some external error.
print(ClientError(with: imageURLError))
// Error ClientError in …
```
> CIS-193 Improve ClientError printing

- StreamChat.xcodeproj/project.pbxproj
- StreamChat.xcodeproj/xcshareddata/xcschemes/V3SampleApp.xcscheme
- StreamChatClient_v3/APIClient/APIClient_Tests.swift
- StreamChatClient_v3/APIClient/Endpoints/Endpoint.swift
- StreamChatClient_v3/APIClient/RequestEncoder.swift
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/ChatClient_Tests.swift
- StreamChatClient_v3/Config/BaseURL.swift
- StreamChatClient_v3/WebSocketClient/Engine/StarscreamWebSocketEngine.swift
- StreamChatClient_v3/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
- StreamChatClient_v3/WebSocketClient/Engine/WebSocketEngine.swift
- StreamChatClient_v3/WebSocketClient/Engine/WebSocketEngine_Tests.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient_Tests.swift
- StreamChatClient_v3/Workers/Background/ChannelEventsHandler_Tests.swift
- V3SampleApp/AppDelegate.swift
- V3SampleApp/SceneDelegate.swift
- We use the same `URLSessionConfigruation` for both `APIClient` and `WebSocketClient`
- We use the existing `RequestEncoder` to encode the initial request for `WebSockectClient`, too
- The implementation of `Client` is cleaned-up
- I added missing tests and documentation.
---
*Note 1:* Since `Client` in v3 acts like a controller, the tests are a little bit messy becase we need to mock everything and basically just check `Client` calls the mocks correctly.
*Note 2:* Setting the user + logging in/out is not handled in this PR and will be part of CIS-164
> [CIS-170] Clean up the implementation of `Client` and add missing tests

- CHANGELOG.md
- Sources/Client/Client/Client+Channels.swift
- Sources/Client/Model/Filter.swift
- Sources/Client/Model/SearchQuery.swift
- Tests/Client/Unit Tests/QueryEncodingTests.swift
Changes
- Added `Client.search(filter: Filter, messageFilter: Filter, ...)`
- Added `SearchQuery.init(filter: Filter, messageFilter: Filter, ...)`
- Added `Filter.exists(Key, Bool)`
API doesn't accept SearchQuery with `query` and `messageFilter` at the same time, that's why it has two initializers now.
Sample usage:
```swift
Client.shared.search(filter: .equal("id", to: "general"), messageFilter: .exists("attachments", true)) { result in
switch result {
case let .success(messages):
print(messages)
case let .failure(error):
print(error)
}
}
```
> CIS-219 Implement search with message_filter_conditions

- .github/workflows/ci.yml
- StreamChat.xcodeproj/project.pbxproj
- fastlane/Fastfile
- fastlane/README.md
CI now has a new job that builds and tests the v3 target in the Release configuration, too. I added a new configuration named `ReleaseTests`. This one inherits from `Release` but it has `enableTestability` set to `true`.
> [CIS-171] Extend v3 CI builds to Release config

- CHANGELOG.md
- Sources/Client/Client/Client+Channel.swift
- Sources/Core/Client/Channel/Channel+RxRequests.swift
- Sources/Core/Client/Client+RxChannel.swift
- Sources/Core/Presenter/Channel/ChannelPresenter+RxRequests.swift
- Sources/Core/Presenter/Channel/ChannelPresenter.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
I opted to add parseMentionedUsers parameter with default true to avoid a breaking change
Closes #338
> Add parseMentionedUsers parameter to Client.send(message: ...)

- .github/workflows/ci.yml
- .github/workflows/nightly-tests.yml
- Dangerfile
- Example/Carthage/ChatExample.xcodeproj/project.pbxproj
- Gemfile
- Gemfile.lock
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChatClient_v3.xcscheme
- StreamChatClientStress_v3.xctestplan
- StreamChatClient_v3.xctestplan
- fastlane/Fastfile
- fastlane/README.md
- Danger now runs in a separate job to ensure it's always reported, even though the tests fail.
- CodeCov is reported for LLC v3
- I added a restore key to Carthage cache, which should help us with getting faster builds.
- Danger now lints commit messages and emits an error, if the commit message doesn't follow the standards (starts with a capitalized letter, doesn't end with `.`)
- I converted the existing v3 tests to a test plan. This allowed me to introduce a new "stress" test plan with random test ordering.
- This stress test is ran every nigh at 1am.
> [CIS-181][CIS-223] CI Improvements

- Dangerfile
- fastlane/Fastfile
It's too aggressive (50 chars - GitHub has 80) and it can't be easily configured.
> Disable Danger commit length rule

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/Database/DTOs/ChannelDTO_Tests.swift
- StreamChatClient_v3/Database/DTOs/MessageDTO.swift
- StreamChatClient_v3/Database/DTOs/MessageDTO_Tests.swift
- StreamChatClient_v3/Database/DatabaseSession.swift
- StreamChatClient_v3/Database/DatabaseSession_Tests.swift
- StreamChatClient_v3/Models/Message.swift
- Added missing tests for `MessagePayload`
- Some polishing of `MessageModel`: Unread count is `Int`, extra data are non-optional. 
- Incoming message data are saved to the DB. The rest is happening automatically :magic:
> [CIS-159] Implement message receiving

- .github/workflows/nightly-tests.yml
- Gemfile
- Gemfile.lock
- StreamChat.xcodeproj/project.pbxproj
- TestResources_v3/TestRunnerEnvironment.swift
- TestResources_v3/XCTAssertEqual+Difference.swift
- codecov.yml
- fastlane/Fastfile
- fastlane/README.md
This is just some preliminary work for improving test stability. The logs from the CI currently doesn't say much because the `Difference` library output is not visible thanks to `xcpretty` formatter.
- This PR adds a `CI=TRUE` env variable for tests when we run on the CI. When this is set, we don't use the `Difference` library.
- I also added a stress test suite for release configuration, since we see different behavior for debug and release configurations.
- Codecov coverage now properly ignores the test files. This causes the code coverage to drop for this PR.
> [CIS-229] Improve test stability (part 1)

- CHANGELOG.md
- Sources/Client/Client/Client+Message.swift
> [CIS-231] Fix flagging current user's messages are not allowed

- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/Channel/ChannelResponse.swift
- Sources/Client/Model/Message/Attachment/Attachment.swift
- Sources/Client/Model/Message/Attachment/AttachmentFile.swift
- Sources/Client/Model/Message/Attachment/AttachmentType.swift
- Sources/Client/Model/Message/Message.swift
- Sources/Client/Model/Message/MessageRead.swift
- Sources/Core/Presenter/Channel/ChannelPresenter+TypingUsers.swift
- Sources/UI/Style/ChannelViewStyle.swift
- Sources/UI/Style/ChatViewStyle.swift
- Sources/UI/Style/ComposerViewStyle.swift
- Sources/UI/Style/SeparatorStyle.swift
Reintroducing all hashable conformances removed here:
https://github.com/GetStream/stream-chat-swift/compare/2.2.0...2.2.1
Some of them are now auto-generated
#no_changelog
> Reintroduce Hashable conformances removed in 2.2.1

- CHANGELOG.md
- Sources/Client/Client/Client+Channel.swift
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/Channel/ChannelNamingStrategy.swift
- Sources/Core/Presenter/Channel/ChannelPresenter.swift
- Tests/Client/Unit Tests/Channel+SetupTests.swift
- Tests/Client/Unit Tests/ChannelNamingStrategyTests.swift
`ChannelNamingStrategy` was generating names correctly for a single user and was sending this name/image to backend. So if user1 created a DM with user2, user1 would correctly see the chat name as "user2" but user2 would also see "user2", since the name was sent to backend.
This PR fixes this: generated name/images are not send to backend or stored anywhere. This way, all users participating in a channel created without id (so backend generates the id, starting with `!member`) will get correct, legible name/images.
Also, there's no breaking change, API is compatible with old versions.
> [CIS-222] Make ChannelNamingStrategy per user

- StreamChatClient_v3/APIClient/APIClient_Tests.swift
- StreamChatClient_v3/Controllers/ChannelListController_Tests.swift
- StreamChatClient_v3/Database/DatabaseContainer.swift
- TestResources_v3/Await.swift
- TestResources_v3/Mock Network/AssertNetworkRequest.swift
- TestResources_v3/Mock Network/RequestRecorderURLProtocol.swift
- TestResources_v3/StressTestCase.swift
- TestResources_v3/Virtual Time/VirtualTime.swift
- TestResources_v3/XCTAssertEqual+Difference.swift
- fastlane/Fastfile
This is the last PR of the series. I'm reluctant to say our stress tests are stable, but they are definitely **more** stable than before. I hope we won't see many regressions, at least for existing tests.
- I made some small changes to our test infrastructure. I made a couple of timeouts bigger when running stress tests, and in general, made our setup more CI-friendly.
- There was a race condition in the way we asserted network requests. It's fixed.
- There was a race condition in `ChannelListController` tests, it should be fixed now.
> [CIS-229] Improve test stability (part 3)

- StreamChat.xcodeproj/project.pbxproj
- StreamChatClient_v3/ChatClient.swift
- StreamChatClient_v3/Utils/Logger/Formatter/PingPongEmojiFormatter.swift
- StreamChatClient_v3/Utils/Logger/Formatter/PrefixLogFormatter.swift
- StreamChatClient_v3/WebSocketClient/ConnectionState.swift
- StreamChatClient_v3/WebSocketClient/Engine/WebSocketEngine_Mock.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient_Tests.swift
- StreamChatClient_v3/WebSocketClient/WebSocketPingController.swift
- StreamChatClient_v3/WebSocketClient/WebSocketPingController_Tests.swift
- V3SampleApp/AppDelegate.swift
- Added `WebSocketPingController`:
- ping by repeating timer
- checks if pong was received otherwise call force disconnect
- resume/suspend ping timer when connection state did change.
- Added tests for `WebSocketPingController`.
- Integrated `WebSocketPingController` to `WebSocketClient` and removed internal ping timer.
- Updated `WebSocketClient` tests.
> CIS-198 Reconnect Web Socket if no pong is received

- CHANGELOG.md
- Sources/Client/Client/Client+Channel.swift
This is a possible performance-related breaking change for people using the low-level SDK. Something to consider in review: maybe it's better to add a parameter with default value (skipReadEventsEnabledCheck: Bool = false) and allow the check to be skipped explicitly to avoid the breaking change.
This shouldn't impact usage in Core and UI, since the check is already done in ChannelPresenter:
https://github.com/GetStream/stream-chat-swift/blob/93341063a9e52cfd42617416081f5948a4a3449b/Sources/Core/Presenter/Channel/ChannelPresenter%2BRxRequests.swift#L123-L126
Closes #280
> [CIS-263] Remove unneeded readEventsEnabled check in Channel.markRead function

- StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints.swift
- StreamChatClient_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- StreamChatClient_v3/Controllers/ChannelListController.swift
- StreamChatClient_v3/Controllers/ChannelListController_Tests.swift
- StreamChatClient_v3/Workers/ChannelUpdater.swift
- V3SampleApp/MasterViewController.swift
**This PR:**
- adds `muteChannel` endpoint;
- exposes muting channel functionality via `ChannelListController`;
- adds channel mute/unmute functionality to `V3SampleApp`.
> [CIS 256] Implement mute/unmute channel functionality

- StreamChatClient_v3/WebSocketClient/Engine/WebSocketEngine_Mock.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient.swift
- StreamChatClient_v3/WebSocketClient/WebSocketClient_Tests.swift
- StreamChatClient_v3/WebSocketClient/WebSocketPingController.swift
- StreamChatClient_v3/WebSocketClient/WebSocketPingController_Tests.swift
- TestResources_v3/Custom Assertions/AssertAsync.swift
The `WebSocketTests` should (hopefully 🤞) be stable again. I must admit I'm not really sure what was happening and why.
The problem was caused by the fact, that we use a special queue to communicate with the engine, to ensure the engine commands are executed in the correct order when calling from different threads. This created some issues when we needed to re-create the engine because of the connection endpoint change.
The good thing is, that the original implementation where we did:
```swift
engineQueue.async {  self.engine.connect() }
```
was incorrect, so the tests correctly failed on this. We now capture the engine reference when we dispatch the call, so we're sure the "correct" engine receives the call.
```swift
engineQueue.async { [engine] in engine.connect() }
```
However, I'm not …
> [CIS-270] WebSocketTests improvements

- CHANGELOG.md
- Sources/Client/Client/Client.swift
- Sources/Client/Client/Endpoint.swift
- Tests/Client/Unit Tests/Client+DevicesTests.swift
To improve request latency, we use the time while the WS connection is establishing to open a new TCP connection, which can then later be reused by other requests. With the backend increasing the `keep:alive` timeout, this should improve the request latency significantly.
> [CIS-279] Open a TCP connection while WS is connecting

- Sources_v3/Controllers/ChannelController.swift
- Sources_v3/Controllers/ChannelController_Tests.swift
- Sources_v3/WebSocketClient/Events/MemberEvents.swift
- Sources_v3/WebSocketClient/Events/MemberEvents_Tests.swift
- Sources_v3/Workers/EventObservers/EventObserver.swift
- Sources_v3/Workers/EventObservers/EventObserver_Tests.swift
- Sources_v3/Workers/EventObservers/MemberEventObserver.swift
- Sources_v3/Workers/EventObservers/MemberEventObserver_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
**This PR:**
- introduces `MemberEvent`
- introduces `EventObserver` and `MemberEventObserver` for event-listening
- updates member events to be non-generic and have only generic `init`
- updates `ChannelController` to listen for and deliver `MemberEvent` from it's channel
> [CIS-245] Event observing

- Sources_v3/Controllers/ChannelController_Tests.swift
- Sources_v3/Controllers/ChannelListController_Tests.swift
Stress tests were crashing because of simultaneous access to test delegate properties. Using `@Atomic` for them should fix the issue.
> Fix failing stress tests

- Sources_v3/Controllers/ChannelController.swift
- Sources_v3/Controllers/ChannelController_Tests.swift
- Sources_v3/Query/ChannelQuery.swift
- Sources_v3/Workers/ChannelUpdater.swift
- Sources_v3/Workers/ChannelUpdater_Mock.swift
- Sources_v3/Workers/ChannelUpdater_Tests.swift
- Add possibility to reset DB observers on receiving channel id from backend
**Q:** If we will stick to this changes, should we also perform them to `ChannelListController` for unification even though they are not needed from technical perspective at the moment?
> Preparation for 1-1 channel creation

- bootstrap.sh
Fixed bootstrap to use our version of `swiftformat` if it already installed.
> Fix bootstrap

- Sources_v3/APIClient/APIClient_Mock.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Workers/Background/MessageSender.swift
- Sources_v3/Workers/Background/MessageSender_Tests.swift
- Sources_v3/Workers/ChannelListQueryUpdater_Tests.swift
- Sources_v3/Workers/ChannelUpdater_Mock.swift
- Sources_v3/Workers/ChannelUpdater_Tests.swift
- Add `Atomic` wrapper to mock classes
- Fix bug in `MessageSender` background init
- `APIClientMock` records all completion blocks so we have to explicitly call `cleanUp()` on it to release them.
> [CIS-299] Make test mocks thread safe

- Sample_v3/Samples/SettingsViewController.swift
- Sources_v3/APIClient/Endpoints/Payloads/CurrentUserPayloads.swift
- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Controllers/ChannelController.swift
- Sources_v3/Controllers/CurrentUserController.swift
- Sources_v3/Controllers/CurrentUserController_Tests.swift
- Sources_v3/Controllers/EntityDatabaseObserver.swift
- Sources_v3/Controllers/EntityDatabaseObserver_Tests.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources_v3/Database/DatabaseSession.swift
- Sources_v3/Database/DatabaseSession_Tests.swift
- Sources_v3/Models/CurrentUser.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Dummy data/CurrentUserPayload.swift
- Tests_v3/Dummy data/UnreadCount.swift
**This PR:**
- Introduces `CurrentUserController`
- Removes `currentUser` from `ChatClient`
- Updates `EntityDatabaseObserver` to have multiple listeners
- Adds `unreadCount` to `CurrentUserPayload`
- Updates `CurrentUserDatabaseSession` to manage unread-count
> [CIS-258] User unread count

- Sources_v3/APIClient/APIClient_Tests.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Controllers/ChannelController_Tests.swift
- Sources_v3/Controllers/ChannelListController_Tests.swift
- Sources_v3/Controllers/CurrentUserController_Tests.swift
- Sources_v3/Controllers/EntityDatabaseObserver_Tests.swift
- Sources_v3/Database/DatabaseContainerMock.swift
- Sources_v3/WebSocketClient/WebSocketClient_Tests.swift
- Sources_v3/Workers/Background/MessageSender.swift
- Sources_v3/Workers/Background/MessageSender_Tests.swift
- Sources_v3/Workers/Background/NewChannelQueryUpdater.swift
- Sources_v3/Workers/Background/NewChannelQueryUpdater_Tests.swift
- Tests/Client/Unit Tests/Client+DevicesTests.swift
- Tests_v3/Custom Assertions/AssertAsync.swift
We can still see some test instability and stress tests failing. This PR should improve that.
- I added a new `canBeReleased` assertion to `AssertAsync` which remove the boilerplate we use for checking the object has no retain cycles, or we just need to wait for it to be released.
- I added a couple of missing `Atomic` wrappers to mocks
> Tests improvement

- Sample_v3/Samples/SimpleChat/MasterViewController.swift
- Sources_v3/Controllers/ChannelListController.swift
- Sources_v3/Controllers/ChannelListController_Tests.swift
- Sources_v3/Query/ChannelListQuery.swift
- Implement channels pagination in `ChannelListController`
- Make use of pagination in `SampleApp`
_**Q**: I’m not doing any checks for empty `channels` in `loadNextChannels` function cause it’s not an issue to have 0 offset. But there is a possibility that this function will be called successfully before `startUpdating` call. (`channels` has empty array as fallback value) If we want to restrict this we can check for controller `state` but I’m not sure if we should do that._
> [CIS-259] Channels pagination

- CHANGELOG.md
- Sample/Sources/DarkChannelsViewController.swift
- Sources/Client/Client/Client+Channel.swift
- Sources/Client/Client/Client+WebSocket.swift
- Sources/Client/Client/Endpoint.swift
- Sources/Client/Model/Channel/Channel+Requests.swift
- Sources/Client/Model/Channel/MutedChannel.swift
- Sources/Client/Model/Event.swift
- Sources/Client/Model/EventType.swift
- Sources/Client/Model/User/User.swift
- Sources/Core/Client/Channel/Channel+RxRequests.swift
- Sources/Core/Client/Client+RxChannel.swift
- Sources/Core/Presenter/Channels/ChannelsPresenter+Rx.swift
- Sources/Core/Presenter/Channels/ChannelsPresenter.swift
- Sources/UI/Channels/ChannelsViewController.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Client/Unit Tests/EventTests.swift
- added mute/unmute a channel
- `Client.shared.mute(channel: channel) {}` or `channel.mute {}`
- `Client.shared.rx.mute(channel: channel)` or `channel.rx.mute()`
- added `.notificationChannelMutesUpdated` event type to get the current user updated when a channel was muted or unmuted
> [CIS-61] Mute/unmute a channel

- .swiftformat
- Sources_v3/.swiftlint.yml
- Sources_v3/ChatClient.swift
- Sources_v3/Utils/Internet Connection/InternetConnection.swift
- Sources_v3/Utils/Internet Connection/InternetConnection_Tests.swift
- Sources_v3/Utils/Internet Connection/Reachability_Vendor.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- codecov.yml
Added `InternetConnection` to monitor the Internet connection.
Basically, it's a wrapper over legacy monitor based on `Reachability` (iOS 11 only) and default monitor based on `Network`.`NWPathMonitor` (iOS 12+).
> [CIS-301] Internet Connection

- Sample_v3/LoginViewController.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sources_v3/ChatClient_Mock.swift
- Sources_v3/Controllers/ChannelController.swift
- Sources_v3/Controllers/ChannelListController+SwiftUI.swift
- Sources_v3/Controllers/ChannelListController+SwiftUI_Tests.swift
- Sources_v3/Controllers/ChannelListController.swift
- Sources_v3/Controllers/Controller.swift
- Sources_v3/Controllers/Controller_Tests.swift
- Sources_v3/Controllers/CurrentUserController.swift
- Sources_v3/Models/ChannelModel.swift
- Sources_v3/Utils/MulticastDelegate.swift
- Sources_v3/Utils/MulticastDelegateTests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR adds and `ObservableObject` wrapper for `ChannelListController` to be used in SwiftUI.
- We use `MulticastDelegate` to make it possible to attach additional delegates for the wrappers, while keeping the underlying controller fully functional. This is a much better experience than originally designed in #356 , where the wrapped controller wasn't accessible. 
_Note_: Refactoring this was a piece of cake thanks to our existing test coverage 😎 
- The `ObservableObject` wrapper is just a simple object that aggregates the changes reported by the delegate.
- Notice the simplicity of the tests. We don't need to test the actual functionality. We just test that the wrapper listens to the delegate callbacks.
> [CIS-291] ObservableObject for controllers (part 1: `ChannelListController`)

- Sample_v3/Samples/SimpleChat/MasterViewController.swift
- Sources_v3/Controllers/ChannelListController+Combine.swift
- Sources_v3/Controllers/ChannelListController+Combine_Tests.swift
- Sources_v3/Controllers/ChannelListController.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Custom Assertions/AssertAsync.swift
This PR follows the same pattern we use for the **SwiftUI** wrapper.
Two interesting bits:
- We use the internal `BasePublishers` object which is shared for all exposed publishers. It simplifies the implementation a lot because we don't need to implement custom `Publisher` types, and we just expose them as `AnyPublisher`.
- We have a `keepAlive(_: AnyObject)` helper on the `Publisher` type. It allows "attaching" any object's lifetime to the lifetime of the publisher chain. Without this helper, the following construct won't work, because the result of the `client.channelListController()`call - the actual controller - would get deallocated and wouldn't listen for database updates:
```swift
client.channelListController(query: ...)
.channelsChangesPublisher
.map { ... } 
.assign(to: ...) …
```
> [CIS-202] Combine wrapper for `ChannelListController`

- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sources_v3/Controllers/ChannelController.swift
- Sources_v3/Controllers/ChannelListController.swift
- Sources_v3/Controllers/CurrentUserController.swift
- Sources_v3/Database/DataStore.swift
- Sources_v3/Database/DataStore_Tests.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- StreamChat_v3.xcodeproj/project.pbxproj
We should allow users to load any arbitrary object from the DB based on its id.
I solved this by introducing a `DataStoreProvider` protocol. Every object conforming to this protocol automatically exposes a `dataStore` variable, that acts like a proxy to the db.
Currently, only controllers expose `dataStore`, but any other object having access to `Client` (like the client itself) can adopt this protocol, too.
---
@cardoso This should fix the issue you have with not having access to the user model from typing events.
> [CIS-317] Give users access to any object by its id

- Sources_v3/APIClient/APIClient_Tests.swift
- Sources_v3/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources_v3/Controllers/ChannelListController/ChannelListController+Combine_Tests.swift
- Sources_v3/Controllers/ChannelListController/ChannelListController+SwiftUI_Tests.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController+SwiftUI_Tests.swift
- Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
- Sources_v3/Database/DatabaseContainer.swift
- Sources_v3/Models/ChannelId_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/iOS13TestCase.swift
The failing tests were caused by 3 different bugs in Xcode and/or Swift.
**`JSONEncoder`/`Decoder` don't support JSON framents on iOS11&12**
Prior iOS13, trying to encode a JSON fragment fails with an error. I worked around this by always boxing the value into a JSON object.
**`NSInMemoryStore` doesn't work properly on iOS13**
**`NSSQLiteStoreType` with `/dev/null` URL doesn't work correctly on iOS 11&12**
So it means, we have to use `NSInMemoryStore` for older versions, and `NSSQLiteStoreType` for iOS13.
**Xcode ignores `@available()` directives on `XCTestCase` classes and run them anyway.**
I created a custom `XCTestCase` subclass that skips test invocations when running on iOS 13. It's ugly but it works.
> [CIS-318] Fix failing tests on iOS11&12

- Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
- Fix failing `ChannelWatchStateUpdater` test
_The test fails because we are comparing endpoints and in `==` method of `AnyEndpoint` 2 arrays with different elements order are treated as not equal. It's hard to make any sorting cause we are dealing with String(describing: `Encodable`) comparing. I decided that test modification doesn't affect test goal so it's the best way to fix error rather than modifying client code for test._
> Failing `ChannelWatchStateUpdater` test

- CHANGELOG.md
- Sources/.swiftlint.yml
- Sources/UI/Chat/Cells/MessageTableViewCell+Attachments.swift
- Sources/UI/Chat/Cells/MessageTableViewCell.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Added a new method for `ChatViewController` to customize behaviour for a tap on an attachment:
```swift
open func tapOnAttachment(_ attachment: Attachment,
at index: Int,
in cell: MessageTableViewCell,
message: Message) {
```
> [CIS-325] Tap on attachments

- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sources_v3/APIClient/Endpoints/MessageEndpoints.swift
- Sources_v3/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Sources_v3/ChatClient.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources_v3/Controllers/EntityDatabaseObserver_Mock.swift
- Sources_v3/Controllers/MessageController/MessageController.swift
- Sources_v3/Controllers/MessageController/MessageController_Tests.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Database/DatabaseSession.swift
- Sources_v3/Database/DatabaseSession_Tests.swift
- Sources_v3/Models/Message.swift
- Sources_v3/Workers/Background/MessageEditor.swift
- Sources_v3/Workers/Background/MessageEditor_Tests.swift
- Sources_v3/Workers/MessageUpdater.swift
- Sources_v3/Workers/MessageUpdater_Mock.swift
- Sources_v3/Workers/MessageUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Dummy data/MessagePayload.swift
**This PR:**
- introduces `MessageController` that can be used to take **edit/delete** actions a specific message
- introduces `MessageEditor` - background worker that listens for messages in a `pendingSync` state and syncs them with the backend
- introduces `MessageUpdater` that acts as an API wrapper for message related endpoints
- adds new `pendingSync/syncing/syncingFailed` local message states that allows `MessageEditor` to do it's job
> [CIS-238] Message actions

- Sample_v3/LogStore.swift
- Sources_v3/APIClient/APIClient_Tests.swift
- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Mock.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Utils/Internet Connection/Error+InternetNotAvailable.swift
- Sources_v3/Utils/Internet Connection/InternetConnection.swift
- Sources_v3/Utils/Internet Connection/InternetConnection_Tests.swift
- Sources_v3/WebSocketClient/Engine/StarscreamWebSocketEngine.swift
- Sources_v3/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
- Sources_v3/WebSocketClient/Engine/WebSocketEngine.swift
- Sources_v3/WebSocketClient/Engine/WebSocketEngine_Mock.swift
- Sources_v3/WebSocketClient/WebSocketClient.swift
- Sources_v3/WebSocketClient/WebSocketClient_Tests.swift
- Sources_v3/WebSocketClient/WebSocketReconnectionStrategy.swift
- Sources_v3/WebSocketClient/WebSocketReconnectionStrategy_Tests.swift
- Sources_v3/Workers/Background/MessageEditor.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This is an alternative approach to #457. I tried to come up with a different and more straightforward solution that relies more on the existing infrastructure.
- The engine returns "no internet" error
- `ReconnectionStrategy` returns `nil` and no reconnection is scheduled
- An `InternetConnection` waiter is scheduled
- Once the connection is back online, WS tries to reconnect
It seems we don't need any special handling for the foreground/background app state. As far as I understand, the existing implementation covers that situation properly.
---
@buh Please take a look and let me know if I missed something. It seems to me this is all we need to do.
> [CIS-185] Connect the web socket when connection restored

- Sources_v3/APIClient/Endpoints/Payloads/MissingEventsPayload.swift
- Sources_v3/APIClient/Endpoints/Payloads/MissingEventsPayload_Tests.swift
- Sources_v3/APIClient/Endpoints/Requests/MissingEventsRequestBody.swift
- Sources_v3/APIClient/Endpoints/Requests/MissingEventsRequestBody_Tests.swift
- Sources_v3/APIClient/Endpoints/SyncEndpoint.swift
- Sources_v3/APIClient/Endpoints/SyncEndpoint_Tests.swift
- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Database/DTOs/ChannelDTO.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DatabaseSession.swift
- Sources_v3/Database/DatabaseSession_Tests.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/WebSocketClient/Events/MessageEvents.swift
- Sources_v3/WebSocketClient/Events/MessageEvents_Tests.swift
- Sources_v3/Workers/Background/MissingEventsPublisher.swift
- Sources_v3/Workers/Background/MissingEventsPublisher_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/MockEnpointResponses/Events/Message/MessageNew+MissingFields.json
- Tests_v3/MockEnpointResponses/Sync/MissingEventsPayload.json
**This PR:**
- introduces `MissingEventsPublisher` that replays missing events that happened when the user was not connected to a web-socket, sets`MissingEventsPublisher` as a background worker;
- introduces `/sync` endpoint and types for incoming/outgoing JSONs;
- adjusts `MessageNewEvent` so it can be parsed from `/sync` endpoint response.
> [CIS-249] Replay missing events

- Sample_v3/AppDelegate.swift
- Sample_v3/Extensions/UITableViewController+KeyboardAvoidance.swift
- Sample_v3/Extensions/UIViewController+Alert.swift
- Sample_v3/LoginViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Decided to do these two tasks in one PR because both could use the alert extension. The alert for the login error is pretty much never called since, for now, the setUser method keeps retrying forever.
Also fixes:
- a glitch when the member actions alert shows up the tableview offset can go wrong
- chatClient not receiving the API key specified in the login screen
> [CIS-341] [CIS-342] V3 Sample: allow specifying id in member actions & show alert on login error

- Sources_v3/Controllers/ChannelController/ChannelController.swift
- Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
- Sources_v3/Controllers/Controller.swift
As it is, ChannelController.startUpdating passes its completion param to multiple places:
- to setupDatabaseObservers
- to channelCreatedCallback
so, if an error occurs in multiple places, it'll be reported in multiple places. If this is what we want, then it's correct.
Another issue is that `startDatabaseObservers` should not be called before channel is actually created (so `isChannelAlreadyCreated` should be true) but it's not checked. I've also refactored it so `startDatabaseObservers` and `setupEventObservers` are called once, in the correct place: if channel exists, called in `startUpdating` otherwise called in `channelCreatedCallback` (hence in set(channelQuery:))
> Fixes ChannelController.startUpdating completion called multiple times

- Sample_v3/AppDelegate.swift
- Sample_v3/LoginViewController.swift
- Sample_v3/Samples/SettingsViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sources_v3/APIClient/Endpoints/ChannelEndpoints.swift
- Sources_v3/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Sources_v3/Workers/EventSender.swift
- Sources_v3/Workers/EventSender_Tests.swift
List of changes:
- SimpleChatViewController.swift: Send keystroke events
- Multiple files: Remove global reference to chat client (it's now passed down via the controllers)
- SimpleChannelsViewController.swift: Comment & refactor to focus on `ChannelListController` usage.
> [CIS-339] V3 Sample: Send keystroke events

- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Tests.swift
For quite some time, I've been thinking about test cases for this... But I'm not able to!
This PR aims to prevent the case, where if there's an ongoing API request during a user change, the result of API request shouldn't affect the new user's DB instance. [1]
But it shouldn't be possible anyway!
When a new user is set, we flush the database. The workers only update the DTO's based on their id/cid. If we flushed the DB, the entity won't exist anymore, therefore it won't get updated.
I've checked the workers but none of them seem to insert new entities to the DB, in which [1] would cause an inconsistency.
But this should be tested regardless, so I'm opening the PR as draft for discussions.
> [CIS-347] Re-create background workers on `prepareEnvironmentForNewUser`

- Sources_v3/Workers/Background/ChannelWatchStateUpdater.swift
- Sources_v3/Workers/Background/ChannelWatchStateUpdater_Tests.swift
- Sources_v3/Workers/Background/MessageEditor.swift
- Sources_v3/Workers/Background/MessageEditor_Tests.swift
- Sources_v3/Workers/Background/MessageSender.swift
- Sources_v3/Workers/Background/MessageSender_Tests.swift
- Sources_v3/Workers/Background/MissingEventsPublisher_Tests.swift
- Sources_v3/Workers/Background/NewChannelQueryUpdater_Tests.swift
**This PR:**
- updates each background worker **not to retain** itself via database/api-client completion;
- adds tests that check workers can be released if completions haven't called yet;
> [CIS-346] Background workers ownership

- Sources_v3/Database/DTOs/ChannelDTO.swift
- Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
- Sources_v3/Database/DTOs/ChannelReadDTO.swift
- Sources_v3/Database/DatabaseSession.swift
- Sources_v3/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- Sources_v3/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
- Sources_v3/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
The missing piece is, parsing `messageRead` events and updating DB's `ChannelRead` objects accordingly. I believe an event observer will be used for this purpose. Should it be done in this PR?
> [CIS-288] Calculate channel unread count based on latest channel read

- Sources_v3/Database/DTOs/ChannelDTO.swift
- Sources_v3/Database/DTOs/ChannelListQueryDTO.swift
- Sources_v3/Database/DTOs/ChannelReadDTO.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/MemberModelDTO.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Utils/Database/NSManagedObject+Extensions.swift
- Sources_v3/Utils/Database/NSManagedObject_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
**This PR:** moves `entityName` to extension and reduces the boilerplate code we have to write when we declare a new DTO.
> [CIS-350] Move `entityName` to extension

- Sample_v3/AppDelegate.swift
- Sources_v3/APIClient/RequestDecoder.swift
- Sources_v3/ChatClient.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Utils/Logger/Destination/BaseLogDestination.swift
- Sources_v3/Utils/Logger/Destination/LogDestination.swift
- Sources_v3/Utils/Logger/Logger.swift
- Sources_v3/Utils/Logger/StringInterpolation+Extenstions.swift
- Sources_v3/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Add `assertationFailure` to `Logger`
- Revise log leves in `Logger`
- Pretty print JSON responses
- Move logging to custom queue
- Introduce `PrettyPrintable` protocol
`struct EventPayload<ExtraData: ExtraDataTypes>: Decodable {`: 
`struct EventPayload<ExtraData: ExtraDataTypes>: Decodable, PrettyPrintable {`:
> [CIS-194] Logger improvements

- Sample_v3/Extensions/View+AlertTextField.swift
- Sample_v3/LoginViewController.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Additional changes:
- Chat and composer will now adjust for keyboard (iOS 14 does this by default)
- Composer is now multiline and autoexpands (using TextEditor + Text ZStack workaround)
- Can now specify user id to add / remove in a channel (wrapping the existing UIKit alert extension)
> Sample v3: Upgrade SwiftUI sample to iOS 14

- Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
- Sources_v3/Controllers/EntityDatabaseObserver.swift
- Sources_v3/Controllers/EntityDatabaseObserver_Tests.swift
- Sources_v3/Controllers/ListDatabaseObserver.swift
- Sources_v3/Controllers/ListDatabaseObserver_Tests.swift
- Sources_v3/Database/DTOs/ChannelReadDTO.swift
- Sources_v3/Workers/Background/MissingEventsPublisher.swift
- Sources_v3/Workers/Background/MissingEventsPublisher_Tests.swift
**This PR**:
- fixes `setGuestUser` to have **extraData = .defaultValue**;
- fixes `MissingEventsPublisher` not to call `/sync` if there are no channels;
- fixes `unreadMessageCount` in `ChannelReadDTO` to match database model;
- provides `description` for `EntityChange` and `ListChange` types.
> [CIS-356] Fix bugs in alpha version

- Sample_v3/Samples/SettingsViewController.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController+Combine.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController+Combine_Tests.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController+SwiftUI.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController+SwiftUI_Tests.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Tests_v3/Await.swift
**This PR**:
- removes `startUpdating` from `CurrentChatUserController`
- updates `CurrentChatUserController` not to be `DataController`
- updates swift-ui & combine wrappers
> [CIS-357] Update current-user controller

- Cartfile
- Cartfile.resolved
- Package.resolved
- Package.swift
- Sources/Client/WebSocket/Provider/StarscreamWebSocketProvider.swift
- Sources_v3/WebSocketClient/Engine/StarscreamWebSocketEngine.swift
- StreamChatClient.podspec
**This PR:** 
- bumps `Startscream` dependency from `~> 3.1` to `~> 4.0` for both **v2** and **v3** SDK versions for all dependency managers (Carthage/CocoaPods/SPM)
- updates **v2** and **v3** SDK versions to meet the new API
> [CIS-209] Bump `Startscream` dependency

- Sources_v3/Database/DTOs/ChannelDTO.swift
- Sources_v3/Database/DTOs/ChannelDTO_Tests.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources_v3/Database/DTOs/MemberModelDTO.swift
- Sources_v3/Database/DTOs/MemberModelDTO_Tests.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/DTOs/MessageDTO_Tests.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Database/DTOs/UserDTO_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR changes the extra decoding logic to be more robust and nicely recover by using `defaultValue` if extra data decoding fails.
> [CIS-364] Use `defaultValue` when extra decoding fails

- Tests_v3/StreamChatClientStressTestPlan.xctestplan
This PR changes tests execution order Random -> Alphabetical for stress plan. The goal is to apply this change and see if it helps because debugging stress tests locally takes much time.
> [CIS-359] Change execution order for stress tests

- Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
- Sources_v3/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources_v3/Controllers/DataController_Tests.swift
- Sources_v3/Controllers/MessageController/MessageController_Tests.swift
- Tests_v3/QueueAwareDelegate.swift
This PR is another iteration of eliminating the failing stress tests issue. It updates `QueueAwareDelegate` to receive `expectedQueueId` via init other than having it as a mutable optional property. This ensures the `expectedQueueId` to always exist when any of the delegate method is called.
> [CIS-359] Ensure delegates always have expected-queue-id set in tests

- Sample_v3/Extensions/UIViewController+Alert.swift
- Sample_v3/LoginViewController.swift
- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
- Sources_v3/Errors/ErrorPayload.swift
- Sources_v3/WebSocketClient/WebSocketReconnectionStrategy.swift
- Sources_v3/WebSocketClient/WebSocketReconnectionStrategy_Tests.swift
The original implementation tried to reconnect the web socket when the connection failed with a 400...499 status code.
The new implementation doesn't try to reconnect in those cases, and the completion of `set(Guest/Anonymous)User` is called with an error instead.
---
@cardoso It seems the sample app doesn't handle this case properly in `setUserCompletion`. Would you mind taking a look and fixing it, please? Feel free to push more commits to this PR directly.
> [CIS-370] Call `setUser` completion with error when WS connection fails

- Sources_v3/APIClient/Endpoints/ModerationEndpoints.swift
- Sources_v3/APIClient/Endpoints/ModerationEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/Payloads/CurrentUserPayloads.swift
- Sources_v3/Controllers/UserController/UserController.swift
- Sources_v3/Controllers/UserController/UserController_Tests.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Query/UserListQuery.swift
- Sources_v3/Query/UserListQuery_Tests.swift
- Sources_v3/Workers/UserUpdater.swift
- Sources_v3/Workers/UserUpdater_Mock.swift
- Sources_v3/Workers/UserUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Dummy data/CurrentUserPayload.swift
- Tests_v3/Dummy data/ExtraData.swift
- Tests_v3/Dummy data/MutedUser.swift
- Tests_v3/Dummy data/MutedUserPayload.swift
- Tests_v3/Dummy data/UserPayload.swift
**This PR:**
- introduces `ChatUserController` that provided the API for performing user-related actions;
- updates `CurrentUserDatabaseSession` to take `mutedUsers` into account;
- introduces `UserUpdater` that sends API requests representing user-related actions;
> [CIS-261] User muting

- Sources_v3/ChatClient.swift
- Sources_v3/ChatClient_Tests.swift
- Sources_v3/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources_v3/Controllers/UserListController/UserListController+Tests.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/Workers/Background/NewChannelQueryUpdater_Tests.swift
- Sources_v3/Workers/Background/NewUserQueryUpdater.swift
- Sources_v3/Workers/Background/NewUserQueryUpdater_Tests.swift
- Sources_v3/Workers/ChannelListUpdater_Mock.swift
- Sources_v3/Workers/UserListUpdater_Mock.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Introduce `NewUserQueryUpdater`
_I’ve tried unifying it by creating generic NewDTOQueryUpdater, but it will lead to creating a lot of protocols, and methods of modifying filters will still be different so I decided we don’t need it at this point._
> [CIS-375] NewUserQueryUpdater

- Sources_v3/Controllers/CurrentUserController/CurrentUserController.swift
- Sources_v3/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources_v3/Controllers/EntityDatabaseObserver.swift
- Sources_v3/Controllers/EntityDatabaseObserver_Tests.swift
- Sources_v3/Controllers/ListDatabaseObserver.swift
- Sources_v3/Controllers/ListDatabaseObserver_Tests.swift
- Sources_v3/Database/DatabaseContainer.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Database/DatabaseContainer_Tests.swift
- Sources_v3/Models/CurrentUser.swift
- Sources_v3/Utils/MainQueue+Synchronous.swift
- Sources_v3/Workers/MessageUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR fixed the problem specified in CIS-300.
**Solution:**
- `DatabaseContainer.removeAllData` is changed such that it sends `WillRemoveAllData` and `DidRemoveAllData` notifications for every context is owns. It also uses a different (and simplified) way of deleting all data by destroying the underlying persistent store.
- Because we never use `NSFetchedResults` controller directly (this turned out to be a very wise decision) we can tweak the `ListDatabaseObserver` and `EntityDatabaseObsever` implementation. The observers now listen for the notifications above posted by the context they observe. If the notification is received, the observers simulate a callback from the underlying FRC like when the data were deleted. The observers also call `performFetch()` on their FRC which forces …
> [CIS-300] Change `removeAllData` implementation to emit callback

- Sources_v3/APIClient/Endpoints/MemberEndpoints.swift
- Sources_v3/APIClient/Endpoints/MemberEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/ModerationEndpoints.swift
- Sources_v3/APIClient/Endpoints/ModerationEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/Payloads/ChannelMemberListPayload.swift
- Sources_v3/APIClient/Endpoints/Payloads/ChannelMemberListPayload_Tests.swift
- Sources_v3/APIClient/Endpoints/Requests/ChannelMemberBanRequestPayload.swift
- Sources_v3/APIClient/Endpoints/Requests/ChannelMemberBanRequestPayload_Tests.swift
- Sources_v3/Controllers/MemberController/MemberController.swift
- Sources_v3/Controllers/MemberController/MemberController_Tests.swift
- Sources_v3/Database/DTOs/ChannelMemberListQueryDTO.swift
- Sources_v3/Database/DTOs/ChannelMemberListQueryDTO_Tests.swift
- Sources_v3/Database/DTOs/MemberModelDTO.swift
- Sources_v3/Database/DTOs/MemberModelDTO_Tests.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Database/DatabaseSession.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/Query/ChannelMemberListQuery.swift
- Sources_v3/Query/ChannelMemberListQuery_Tests.swift
- Sources_v3/Query/Pagination.swift
- Sources_v3/Query/Sorting.swift
- Sources_v3/Workers/ChannelMemberListUpdater.swift
- Sources_v3/Workers/ChannelMemberListUpdater_Mock.swift
- Sources_v3/Workers/ChannelMemberListUpdater_Tests.swift
- Sources_v3/Workers/ChannelMemberUpdater.swift
- Sources_v3/Workers/ChannelMemberUpdater_Mock.swift
- Sources_v3/Workers/ChannelMemberUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/MockEnpointResponses/ChannelMembersQuery.json
**This PR**: 
- introduces `ChatMemberController` for actions on a channel member (currently, only **ban/unban** actions are in)
- introduces `ChannelMemberListUpdater ` and stuff for querying the channel members
- introduces `ChannelMemberUpdater`  and stuff for channel member related API calls
- introduces `ChannelMemberListQueryDTO` and database session for local representation of member queries
> [CIS-380] Implement member controller

- Sources_v3/Controllers/EntityDatabaseObserver.swift
- Sources_v3/Controllers/ListDatabaseObserver.swift
- Sources_v3/Controllers/ListDatabaseObserver_Mock.swift
- Sources_v3/Controllers/ListDatabaseObserver_Tests.swift
- Sources_v3/Controllers/MemberListController/MemberListController.swift
- Sources_v3/Controllers/MemberListController/MemberListController_Tests.swift
- Sources_v3/Database/DTOs/MemberModelDTO.swift
- Sources_v3/Database/DatabaseContainer_Mock.swift
- Sources_v3/Query/Sorting.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Dummy data/MemberPayload.swift
**This PR**:
- introduces `ChatChannelMemberListController` that manages channel member query
- introduces mock `ListDatabaseObserver`
- adds sort descriptors to `ChannelMemberListSortingKey`
> [CIS-386] Member list controller

- Sample_v3/Extensions/Channel+Extensions.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChat.storyboard
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleUsersViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChat.storyboard
- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleUsersViewController.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
- Sample_v3/Samples/SwiftUISimpleChat/UserListView.swift
- Sources_v3/APIClient/Endpoints/ChannelEndpoints.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Showcase `1-1 channels` and `UserController` in Sample app
**Notes:** 
- Kept both `Users` and `add channel` buttons for now cause probably what we need is `TabBar`.
- In `SwiftUI` sample after tapping the user direct chat will be created but not opened. (navigation limitation, decided not to dive into it at this point)
- We don't have `mutedUsers` available initially on `currentUser`. They will appear only after muting someone and receiving corresponding event. Are we aware of this?
> [CIS-378] Showcase 1-1 channels and UserController in Sample app

- Sample_v3/Base.lproj/Main.storyboard
- Sample_v3/Configuration.swift
- Sample_v3/ConfigurationViewController.swift
- Sample_v3/LoginViewController.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR separates the credentials and other configuration from the first screen into a new modal screen. It also persists these parameters in UserDefaults.
#no_changelog
> Sample v3: Separate login configurations into a new screen + persistence

- .github/workflows/beta.yml
- .github/workflows/ci.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/test-old-ios-versions.yml
- .swiftformat
- Sample_v3/Base.lproj/Main.storyboard
- Sample_v3/Configuration.swift
- Sample_v3/ConfigurationViewController.swift
- Sample_v3/LoginViewController.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
- Sample_v3/Samples/SwiftUISimpleChat/UserListView.swift
- Sources_v3/Models/User+SwiftUI.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- StreamChat_v3.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- StreamChat_v3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fastlane/Fastfile
- fastlane/README.md
Question: should we also build sample app in iOS12?
Currently, Github Actions has Xcode11.7 as default. [Default Xcode will be changed to Xcode 12.0 on October, 20](https://github.com/actions/virtual-environments/issues/1712), but we should still be fine.
> [CIS-363] Sample app improvements

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
Steps to reproduce:
1. Enable Network Link Conditioner to 3G speed
2. To any channel, write a message
3. Tap send
4. Immediately after 3, write something else
Expected:
- New text will be input on a empty field
Actual:
- New text is input after the last message (until message is actually sent)
Example:
1. Write "Hello"
2. Tap send
3. Write "Again"
Expected to see only "Again", but seeing "HelloAgain" in the text field
Unfortunately, we can't support optimistic updates for now, so messages appearing in the channel immediately after tapping send is not possible.
> Fix composerView retaining messages

- CHANGELOG.md
- Sources/Client/Client/Endpoint.swift
- Sources/Client/Model/Pagination.swift
Since we've changed the type of Pagination, replies endpoint did not encode pagination correctly. This was caused from Pagination being an array, and we don't support encoding arrays as query items.
Fixes #550
> For #550: Fix replies request pagination not encoded correctly

- Sources_v3/APIClient/Endpoints/ModerationEndpoints.swift
- Sources_v3/APIClient/Endpoints/ModerationEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/Payloads/FlagUserPayload.swift
- Sources_v3/APIClient/Endpoints/Payloads/FlagUserPayload_Tests.swift
- Sources_v3/Controllers/UserController/UserController.swift
- Sources_v3/Controllers/UserController/UserController_Tests.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/UserDTO.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/Models/CurrentUser.swift
- Sources_v3/Models/User.swift
- Sources_v3/Workers/UserUpdater.swift
- Sources_v3/Workers/UserUpdater_Mock.swift
- Sources_v3/Workers/UserUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/MockEnpointResponses/FlagUser/FlagUserPayload+CustomExtraData.json
- Tests_v3/MockEnpointResponses/FlagUser/FlagUserPayload+DefaultExtraData.json
- Tests_v3/MockEnpointResponses/FlagUser/FlagUserPayload+NoExtraData.json
**This PR**:
- exposes `flag/unflag` API by `UserController`
- adds `CurrentUserDTO <->> UserDTO` relation for flagged users and updates the models
- adds `flagUser` to `UserUpdater`
- introduces `FlagUserPayload`
- updates mock `UserUpdater` to have a `cleanUp` function
> [CIS-405] User flagging

- Sources_v3/APIClient/Endpoints/MessageEndpoints.swift
- Sources_v3/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources_v3/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources_v3/Controllers/ChannelController/ChannelController.swift
- Sources_v3/Controllers/ChannelController/ChannelController_Tests.swift
- Sources_v3/Controllers/MessageController/MessageController.swift
- Sources_v3/Controllers/MessageController/MessageController_Tests.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/DTOs/MessageDTO_Tests.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/Query/Pagination.swift
- Sources_v3/Workers/ChannelUpdater.swift
- Sources_v3/Workers/ChannelUpdater_Mock.swift
- Sources_v3/Workers/ChannelUpdater_Tests.swift
- Sources_v3/Workers/MessageUpdater.swift
- Sources_v3/Workers/MessageUpdater_Mock.swift
- Sources_v3/Workers/MessageUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Dummy data/MessagePayload.swift
- Tests_v3/MockEnpointResponses/Messages.json
- Link replies to `MessageDTO`
- Separate `createNewMessage` and `createNewReply` APIs
- Remove replies from channel message list
- Introduce `MessageRepliesPayload`
- Introduce `loadReplies` endpoint
- Add `loadReplies` method to `MessageUpdater`
- Add `loadReplies` method to `MessageController`
> [CIS-242] Implement message replies

- Sources_v3/APIClient/Endpoints/ModerationEndpoints.swift
- Sources_v3/APIClient/Endpoints/ModerationEndpoints_Tests.swift
- Sources_v3/APIClient/Endpoints/Payloads/FlagMessagePayload.swift
- Sources_v3/APIClient/Endpoints/Payloads/FlagMessagePayload_Tests.swift
- Sources_v3/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources_v3/Controllers/MessageController/MessageController.swift
- Sources_v3/Controllers/MessageController/MessageController_Tests.swift
- Sources_v3/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/Database/DTOs/MessageDTO.swift
- Sources_v3/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/Models/CurrentUser.swift
- Sources_v3/Models/Message.swift
- Sources_v3/Workers/MessageUpdater.swift
- Sources_v3/Workers/MessageUpdater_Mock.swift
- Sources_v3/Workers/MessageUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/MockEnpointResponses/FlagMessage/FlagMessagePayload+CustomExtraData.json
- Tests_v3/MockEnpointResponses/FlagMessage/FlagMessagePayload+DefaultExtraData.json
- Tests_v3/MockEnpointResponses/FlagMessage/FlagMessagePayload+NoExtraData.json
**This PR:**
- exposes `flagMessage/unflagMessage` by `MessageController`
- expose `flagMessage/unflagMessage` by `MessageUpdater`
- adds `CurrentUserDTO <->> MessageDTO` relation for flagged messages and updates the models
- introduces `FlagMessagePayload` and `flagMessage/unflagMessage` endpoints
> [CIS-406] Message flagging

- Sample_v3/Base.lproj/Main.storyboard
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatScrollView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR reworks the approach in the SwiftUI sample's chat view to use the .bottomToTop list ordering in ChatController and use a LazyVStack with a custom ScrollView wrapper instead of an inverted List which was causing visual glitches in the context menu.
#no_changelog
> Sample v3: Use non-inverted LazyVStack in SwiftUI sample's ChatView

- Tests_v3/StreamChatTests/StreamChatStressTestPlan.xctestplan
> [CIS-359] Fix stress tests, vol. 7 | Temporarily disable `MessageSender` tests

- CHANGELOG.md
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/Channel/ChannelResponse.swift
`Channel.membership` and `MembersQueryResponse.members` should've been public from the get-go
> Fix internal properties that should've been public

- CHANGELOG.md
- Sources/Client/Client/Client+WebSocket.swift
- Sources_v3/StreamChat/APIClient/RequestEncoder.swift
- Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
The default encoding when building the query parameter with `URLQueryItem` will not encode the + symbols, thus making them become spaces. I fixed it by appending the `json` query parameter manually with the proper percent encoding to include the plus sign.
This can be specially annoying if a field is a base64 string, like an encoded public key, but it's also preventing creating a user with a plus in the name which is valid in other clients such as the JS client.
Example:
mhPcgwhH8L8FqFni20qLZ/bIHbwleWvaqm+zcByNp4FWQj0ufl8H9cHV/pbAYo74gCEUdH/MxXdtX+SmW2o3Rg==
becomes
mhPcgwhH8L8FqFni20qLZ/bIHbwleWvaqm zcByNp4FWQj0ufl8H9cHV/pbAYo74gCEUdH/MxXdtX SmW2o3Rg==
which is invalid base64
> Fix plus signs in User fields becoming spaces in the set user request

- Sources_v3/StreamChat/APIClient/RequestEncoder.swift
- Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
This is a different solution for the current v3 workaround for the incorrect¹ encoding of the `+` character in the URL query. The description of the problem and other solutions can be found here https://stackoverflow.com/questions/43052657/encode-using-urlcomponents-in-swift .
@cardoso, thank you for fixing this! Great work. I just took your solution and tests and made it fit a tiny bit better into the rest of the SDK.
---
¹ _Technically, the encoding is actually correct, `+` is an allowed character in the URL query, it's just not understood as `+`_.
> Change the workaround solution for encoding `+` in URLs

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
If we reset composerView before calling presenter.send, the attachments will be reset and never sent
Fixes #584
> Fix images are not being attached to message

- Sources_v3/StreamChatUI/Utils/UIView+Extensions.swift
I wanted to implement something like SnapKit, while not having SnapKit and not building our own DSL from scratch... `NSLayoutAnchor` is not really expandable.
I could only come up with this small change, which allows us to:
```swift
let box = UIView()
let miniBox = UIView()
var widthConstraint: NSLayoutConstraint? = box.widthAnchor.constraint(equalToConstant: 50)
box.activateConstraints {
widthConstraint!
box.leftAnchor.constraint(equalTo: miniBox.leftAnchor)
box.rightAnchor.constraint(equalTo: miniBox.rightAnchor)
}
```
We can't do `box.leftAnchor.rightAnchor.constraint(equalToConstant: 10)` unfortunately.
So I've opened this PR as a discussion starter: What helpers are we seeing, other than what we currently have (`embed` and `embedUsingSystemSpacing`) that we can have?
> [CIS-414] Implement layout helpers

- bootstrap.sh
Since September, homebrew does not allow installs from GitHub.
Instead, you required to create your own tap. More info:
https://discourse.brew.sh/t/has-brew-install-force-formula-raw-path-been-taken-out/8793
> [CIS-355] Fix bootstrap script

- Sources_v3/StreamChat/Query/ChannelListQuery.swift
- Sources_v3/StreamChat/Query/ChannelListQuery_Tests.swift
- Sources_v3/StreamChat/Query/Sorting/ChannelListSortingKey.swift
- Sources_v3/StreamChat/Query/Sorting/UserListSortingKey.swift
- Sources_v3/StreamChat/Query/UserListQuery.swift
- Sources_v3/StreamChat/Query/UserListQuery_Tests.swift
- Add `cid` sorting key to `ChannelListSortingKey`
- Add safe sorting option to `ChannelListQuery`
- Add safe sorting option to `UserListQuery`
_`ChannelMemberListQuery` is left out cause there is no safe sorting option available._
> [CIS-392] Safe sorting option for queries

- Sample_v3/AppDelegate.swift
- Sample_v3/LoginViewController.swift
- Sources_v3/StreamChatUI/AppearanceSetting.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatReadStatusCheckmarkView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatUnreadCountView.swift
- Sources_v3/StreamChatUI/Common Views/AvatarView.swift
- Sources_v3/StreamChatUI/Common Views/BaseViews.swift
- Sources_v3/StreamChatUI/Common Views/ChatNavigationBar.swift
- Sources_v3/StreamChatUI/Common Views/CreateNewChannelButton.swift
- Sources_v3/StreamChatUI/Common Views/CurrentChatUserAvatarView.swift
- Sources_v3/StreamChatUI/Utils/UIConfigProvider.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Views are doing layout/setup operations in `commonInit`, which is called on `init`. These operations can be expensive, and cause performance issues [we don't have numbers yet]. We're searching for a way to "lazily" do these operations.
Comment which started the discussion: https://github.com/GetStream/stream-chat-swift/pull/577#discussion_r522078499
As #596 explores, passing `config` from views to subviews & initiating correct views from config:
> I pin hopes on this approach since it is similar to environment variables in SwiftUI, can be applied for all the views and helps to avoid storing let config + init(config). **The problem is that we create subviews from the inside of view's init and at this point the view itself hasn't yet had a superview -> there is no view hierarchy to search …
> [CIS-416] Explore lazy setup for views

- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources_v3/StreamChatUI/Common Views/OnlineIndicatorView.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Implements small view on `ChatChannelAvatarView` which indicates whether the user is online or not. This small indicator should be visible only on direct 1-1 Channels.
Fire up the test StreamChat UI and run the **Stream Design** sample. In code, you can check whether those online indicator statuses match the given status:
1. The channel mock is 1-1
2. The channel mock has 1 other user than you and he is online
3. Check if the view matches the designs
> Add online indicator for 1-1 Chat avatars

- Sources_v3/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources_v3/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources_v3/StreamChat/Controllers/UserListController/UserListController.swift
We dropped a guard and copypaste demons find a way in our codebase.
With power granted to me by supreme leader @VojtaStavik I banish them for good!
> Fix "typo" in default implementation of lowlevel controller delegates

- CHANGELOG.md
- Sample/Sources/DarkChannelsViewController.swift
- Sources/Client/Model/Event.swift
- Sources/Client/Model/EventType.swift
- Tests/Client/Unit Tests/EventTests.swift
This event was missing even from backend, but now it's here
> Add notificationChannelDeleted event

- Sample_v3/AppDelegate.swift
- Sample_v3/Configuration.swift
- Sample_v3/ConfigurationViewController.swift
- Sample_v3/Extensions/UITableViewController+KeyboardAvoidance.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelMembersViewController.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
- Sample_v3/Samples/CombineSimpleChat/CombineSimpleUsersViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChannelMembersViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChannelsViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sample_v3/Samples/SimpleChat/SimpleUsersViewController.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sample_v3/Samples/SwiftUISimpleChat/ChatView.swift
- Sample_v3/SceneDelegate.swift
- Sources/UI/Chat/Composer/ComposerView+Images.swift
- Tests/Client/Custom Assertions/AssertNetworkRequest.swift
- Tests/Client/Integration Tests/TestCase.swift
- Tests/Client/Unit Tests/AtomicTests.swift
- Tests/Client/Unit Tests/Channel+SetupTests.swift
- Tests/Client/Unit Tests/WebSocket/WebSocketEventsMock.swift
- Tests/Client/Unit Tests/WebSocket/WebSocketProviderMock.swift
- Tests_v3/Mock Network/AssertNetworkRequest.swift
Clears most Swiftlint warnings across the project. I ran `swiftlint autocorrect` to fix some issues which Swiftlint could fix on it own. I also went through files with documentation and splitted the documentation on newLines so we don't get any `line_length` swiftlint rule (It was faster than figure out some automation thing)
You can run the project go through it, run tests and see if anything is broken, but it really shouldn't be
Some place worth a logic check are: 
- `ConfigurationViewController.swift` -> `isEmpty` condition
- `WebSocketProviderMock.swift` -> Possibly if the delegate is explicitly not meant to be weak (I don't see any reason) 
- `SimpleUsersViewController.swift`  -> `super.viewDidLoad`, was this intentional?
-  `CombineSimpleUsersViewController.swift` -> …
> Delete most of Swiftlint warnings

- DemoApp/ChatPresenter.swift
- DemoApp/DemoUsers.swift
- DemoApp/LoginViewController.swift
- Sources_v3/StreamChat/Database/DTOs/CurrentUserDTO.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR replaces the built-in users in the Demo app with the ones from the Slack clone app.
> Use better built-in users for Demo app

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerAttachmentCellView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerAttachmentsView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageInputSlashCommandView.swift
- Sources_v3/StreamChatUI/Common Views/ContainerStackView.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Expose underlying container in `ContainerStackView`
- Introduce `MessageInputSlashCommandView`
- Introduce `MessageComposerAttachmentsView`
- Introduce `ChatChannelMessageInputView`
- Introduce `ChatChannelMessageComposerView`
- Introduce `MessageComposerSuggestionsViewController`
- Use `ChatChannelMessageComposerView` in `SimpleChatViewController`
> MessageComposerView prototype

- Sources_v3/StreamChat/APIClient/Endpoints/Payloads/AttachmentPayload.swift
- Sources_v3/StreamChat/APIClient/Endpoints/Payloads/AttachmentPayload_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources_v3/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources_v3/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/StreamChat/Models/Attachment.swift
- Tests_v3/Dummy data/AttachmentPayload.swift
- Tests_v3/Dummy data/ChatMessageAttachment.swift
- Tests_v3/MockEnpointResponses/Attachment/AttachmentPayload+CustomExtraData.json
- Tests_v3/MockEnpointResponses/Attachment/AttachmentPayload+NoExtraData.json
**This PR** adds `imagePreviewURL` to attachment payload, DTO, and model types
> [CIS-496] Preview URL for attachments

- DemoApp/DemoUsers.swift
- Sources_v3/StreamChatTestTools/ChatClient_Mock.swift
- Sources_v3/StreamChatTestTools/Controllers/ChannelListController_Mock.swift
- Sources_v3/StreamChatTestTools/Controllers/ChatChannelController_Mock.swift
- Sources_v3/StreamChatTestTools/Controllers/ChatMessageController_Mock.swift
- Sources_v3/StreamChatTestTools/Info.plist
- Sources_v3/StreamChatTestTools/Models/ChatChannelMember_Mock.swift
- Sources_v3/StreamChatTestTools/Models/ChatChannel_Mock.swift
- Sources_v3/StreamChatTestTools/Models/ChatMessage_Mock.swift
- Sources_v3/StreamChatTestTools/Models/ChatUser_Mock.swift
- Sources_v3/StreamChatTestTools/StreamChatTestTools.h
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- StreamChat_v3.xcodeproj/xcshareddata/xcschemes/StreamChatUI.xcscheme
- Tests_v3/StreamChatTestToolsTests/Info.plist
This is the initial PR of `StreamChatTestTools`. Currently, this new framework is meant to be used only internally for better testing of StreamChatUI. Eventually (planned for Q1), it will be available for our customers too to test their own UI.
**Features:**
- It's possible to create model objects without the DB using the `.mock(...)` static method.
- It's possible to create mock controllers and simulate their behavior using `simulate(....)` methods.
I also added an example test for `ChatChannelVC` to showcase how the usage.
> [CIS-437] Add initial `StreamChatTestTools`

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Replaces implementation of `ChatChannelMessageComposerView` which was implemented just as `accessoryInputView` to implementation which now has `UIInputViewController` to holds the `inputView` since this is for us better way to implement complex logic with the `ChatChannelMessageComposerView`. Also changes `ChatChannelMessageComposerView` to subclass `UIInputView` instead.
- Start the v3 app, go to some random chat and expect the composerView to be there and behave the same way it did in the first implementation.
Note: This PR is for us to move on and implement the logic into this separate viewController.
> Replace UIInputAccessoryView with UIInputAccessoryViewController

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerAttachmentsView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
Intermediate PR with moving logic to `MessageComposerInputAccessoryViewController` and getting rid of passing the parent `UIView` or `UIViewController` down the hierarchy.
> [CIS-481] Logic -> `MessageComposerInputAccessoryViewController`

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelCollectionViewLayout.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/UIConfig.swift
CollectionViewLayout flip comes with self-sizing cell issue: when you scroll to "estimated" cell bottom anchor, cell size calculated and you may jump right into middle of cell, because `collectionViewContentSize` have been changed, while `contentOffset` stay same.
To fight it we lock `collectionViewContentSize` to super big number simulating "infinite scroll", now newly calculated cell "expands" up into invisible yet area, removing jumps.
> [CIS-502] Prevent user from overscrolling out of visible content

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Composer.swift
- Sources/UI/Extensions/Keyboard.swift
iOS doesn't let us know if the composer is floating, but if the keyboard frame height is lower than the distance from the bottom of the screen to the keyboard's y origin, then it seems safe to say it's floating. 
Additional bug fix: KeyboardNotification calculations were incorrect if the screen rotated. Fixed this by storing the current screen bounds on initialization.
> Don't adjust composer when keyboard is floating

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageGroupPart.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageImageGallery.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatRepliedMessageContentView.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
**This PR:**
- introduces `ChatMessageImageGallery` type for displaying attachment image previews
- shows `ChatMessageImageGallery` to message bubble
- adjusts message bubble layout depending on message content
- photo gallery can have **1...4** previews, if more images are attached the `+N` overlay is shown on the last preview
- loading indicator is shown when the preview is being loaded
Screenshots:
> [CIS-450] Photo gallery

- Sources_v3/StreamChatUI/.swiftgen.yml
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageContentView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageGroupPart.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageThreadInfoView.swift
- Sources_v3/StreamChatUI/Generated/L10n.swift
- Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.stringsdict
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Adds info about number of replies to message bubble + api to open thread
Points of interest:
- `ChatMessageThreadArrowView` - dummy view that just draw reply tail for message bubble
- `ChatMessageThreadInfoView` - view that contains information about replies count and latest replier avatar
- `ChatMessageContentView` layout approach starts breaking up, since amount of states for message grows exponentially (now we on `incoming/outgoing`, `group body / footer`, part of reply or not, 8 total states).
> [CIS-462] Add UI for threads in message cell

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputTextView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
- Sources_v3/StreamChatUI/Generated/L10n.swift
- Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
In this PR: 
- Add placeholder to `ChatChannelMessageInputTextView`
Should be merged after https://github.com/GetStream/stream-chat-swift/pull/629.
> [CIS-480] Add placeholder to `ChatChannelMessageInputTextView`

- Sources_v3/StreamChatUI/UIConfig.swift
- Sources_v3/StreamChatUI/Utils/UIConfigProvider.swift
- Sources_v3/StreamChatUI/Utils/UIConfigProvider_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
If we use the VC's `view` property for storing/getting `uiConfig`, we'll assume by the time we need it, `view` will be initialised.
In the old impl, when we call:
```swift
chatList.uiConfig = uiConfig
```
we call `register`, which in turn does:
```
func register<T: ExtraDataTypes>(config: UIConfig<T>) {
view.anyUIConfig = config
}
```
which accesses `view` so `loadView` and `viewDidLoad` gets called. This initializes all subviews of the VC _before actually assigning_ `uiConfig`
So we need to be able to assign `uiConfig` before initializing `view`
> Fix UIConfig not being passed down for VCs

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
The table view always scrolls to the bottom when new messages are received. This can be annoying if you're looking at older messages and the channel is very active. I added an option `scrollOnNewData` that when set to `false` disables this behavior. If it's false, the table view will only scroll if it's already at the bottom.
Decided to rename `scrollEnabled` to `canScroll` so it reads better as a passive computed property.
> Add option to disable scroll to bottom when new messages are received

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageInputView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatReplyBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- Sources_v3/StreamChatUI/Utils/UITextView+Extensions.swift
- StreamChat_v3.xcodeproj/project.pbxproj
In this PR:
- Improve `UITextView` text height calculation
- Introduce `ChatReplyBubbleView`
- Make use of `ChatReplyBubbleView` in `ChatChannelMessageComposerView`
- Adjust `MessageComposerInputAccessoryViewController.State` and add test reply functionality
> [CIS-475] Replies UI in MessageComposer

- .github/workflows/ci.yml
- .github/workflows/ci_v2.yml
Also update the carthage key, in the hopes that this will resolve the caching issue
No longer our v2 jobs will run unnecessarily
> Add CI v2 workflow and separate v2/v3 CIs

- Sample_v3/Samples/SimpleChat/SimpleChatViewController.swift
- Sources_v3/StreamChat/APIClient/Endpoints/Endpoint.swift
- Sources_v3/StreamChat/APIClient/RequestEncoder.swift
- Sources_v3/StreamChat/APIClient/RequestEncoder_Tests.swift
They were failing since backend expects a valid body (not nil) for post requests
> Fix markRead requests failing

- Sources_v3/StreamChat/Controllers/MessageController/MessageController.swift
- Sources_v3/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources_v3/StreamChat/Workers/MessageUpdater.swift
- Sources_v3/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources_v3/StreamChat/Workers/MessageUpdater_Tests.swift
**This PR:**
- exposes restart attachment uploading API by `ChatMessageController`
- exposes restart attachment uploading API by `MessageUpdater`
- introduces `AttachmentDoesNotExist` and `AttachmentEditing` error types
> [CIS-518] Restart attachment uploading API

- Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController.swift
- Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/UserListQueryDTO.swift
- Sources_v3/StreamChat/Database/DatabaseSession.swift
- Sources_v3/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources_v3/StreamChat/Query/UserListQuery.swift
- Sources_v3/StreamChat/Workers/Background/NewUserQueryUpdater.swift
- Sources_v3/StreamChat/Workers/Background/NewUserQueryUpdater_Tests.swift
- Sources_v3/StreamChat/Workers/UserListUpdater.swift
- Sources_v3/StreamChat/Workers/UserListUpdater_Mock.swift
- Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
SearchController creates a unique query and observes DB for updates to this query. Whenever the developer calls `search(text)` searchController will update this query (in DB) and will report results to the user. In `deinit`, searchController will remove this query from DB. 
The developer will always get `.insert(item` changes, never `.update`) (will be tested)
Additionally, this query will not be observed by `NewUserQueryUpdater` since it's an "ephemeral" query.
> [CIS-499] User Search Controller

- .github/workflows/ci.yml
- .github/workflows/ci_v2.yml
Initially it was only added for push: main workflows, which caused PR workflows to run unnecessarily
> Add path and path ignore params to PR workflows

- Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageThreadInfoView.swift
Designs in Figma are made in "points" resolution -> 1pt border should be 1pt border in our project.
Arrow was drawing outside it borders, which lead to small misalignment with message bubble
> Improve thread arrow aligment with message border

- Sources_v3/StreamChatUI/ChatChannel/ChatMessageBubbleView.swift
- Sources_v3/StreamChatUI/Common Views/OnlyLinkTappableTextView.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Links were broken because to allow long press for message popup I disabled user interactions on text view.
If we just enable user interactions back, then on long press, user will select text inside text view instead of opening  message popup.
To disable press interception we have next options:
1. Use `UIGestureRecognaizerDelegate.gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)` and try to find which gesture recognizers in textview are responsible for links actions and for other actions.
This approach is unstable and rely on implementation details of text view
2. Override `hitTest` to skip all touches outside of link bounds.
Nice, simple, and elegant solution.
3. Intercept touches in some middle layer (e.g. view on top of text view) and pass only touches on links. 
Dirty, affect …
> [CIS-519] Disable all interactions with message textview except links

- .github/workflows/nightly-tests.yml
- Sources_v3/StreamChat/APIClient/APIClient_Mock.swift
- Sources_v3/StreamChat/ChatClient.swift
- Sources_v3/StreamChat/ChatClient_Tests.swift
- Sources_v3/StreamChat/Controllers/EntityDatabaseObserver.swift
- Sources_v3/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources_v3/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources_v3/StreamChat/WebSocketClient/EventMiddlewares/TypingStartCleanupMiddleware.swift
- Sources_v3/StreamChat/Workers/Background/AttachmentUploader.swift
- Sources_v3/StreamChat/Workers/Background/MessageEditor.swift
- Sources_v3/StreamChat/Workers/Background/MessageSender.swift
- Sources_v3/StreamChatUI/AppearanceSetting.swift
- Tests_v3/StreamChatTests/StreamChatStressTestPlan.xctestplan
- fastlane/Fastfile
This PR fixes many different problems with the stability of our SDK:
- CoreData was complaining about us using an incorrect initializer for `AttachmentDTO`. See the commit description for more details.
- I fixed the incorrect usage of `@Atomic` with collections (CIS-427)
- Fixed a race condition of removing notifications in `deinit`
- Fixed DB observer's `startObserving` method not being thread safe
This should also fix out test suite, so I re-enabled it. Let's see :)
I put the new findings to our [Writing stable unit tests](https://github.com/GetStream/stream-chat-swift/wiki/Writing-stable-unit-tests-checklist) checklist.
---
This PR also closes CIS-427 and CIS-359.
> [CIS-350][CIS-427][CIS-359] Fix failing LLC tests

- Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerInputAccessoryViewController.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerSuggestionsViewController.swift
- Presents SuggestionsViewController on ChatVC as a child VIewController, this eliminates problems with strange behaviour while adding it as VC on custom Window or child of `InputAccessoryViewController`. Also resizes and moves according to position of inputView. 
- Go to chat and run suggestions either with the flash button or with typing `/`, see if this works for you
> [CIS-474] Presenting Suggestions on ChatVC

- Sources_v3/StreamChatUI/ChatChannel/ChatChannelMessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposerViewController.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Switch from `inputAccessoryView` to custom one for message composer
kudos to @ManWithBear for helping with that
> [CIS-539] Switch from `inputAccessoryView` to custom one for message composer

- Sources_v3/StreamChat/ChatClient.swift
- Sources_v3/StreamChat/Utils/BundleExtensions.swift
- Sources_v3/StreamChat/WebSocketClient/WebSocketClient.swift
- StreamChat_v3.xcodeproj/project.pbxproj
This PR is a part of the changes needed to enable notification extensions for `StreamChat`. The extension is needed to support our new backend service for push notifications.
- `StreamChat` is marked as `APPLICATION_EXTENSION_API_ONLY` which means you can use it safely from app extensions.
- Accessing `UIApplication.shared` directly is no longer possible so I put it behind a check.
*However,* it can lead to issues if we run the full client from extensions. It would create a new web socket connection, mark the user as `online`, start background workers, etc. For these reasons, I made it not possible to actually create a client instance from extensions yet. Our notification extension will expose only safe API, not the full client, for the reasons above.
In general, we should make it …
> [CIS-541] Make `StreamChat` usable from app extensions

- DemoApp/ChatPresenter.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatFileAttachmentListView+ItemView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageContentView.swift
- StreamChat_v3.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
Looks like our layout was too dynamic and layout engine goes mad with it. Specifically:
- `ChatFileAttachmentListView.ItemView` 2 components that limit min height, positioned in the middle, nothing to limit max size
- `ChatMessageContentView.messageReactionsView` in general bad constraints. Will be reworked with reactions tail update
> Make file preview layout less dynamic, to prevent layout loop

- Sources_v3/StreamChat/Workers/UserListUpdater_Tests.swift
`test_updateCompletion_calledAfterDBWriteCompletes` was flaky since listUpdater.update makes a database.write call, which calls writableContext.perform , and in the same perform block accessing viewContext crashes. but using same context (writableContext ) works flawless. So we need to call `viewContext` in main queue
> Fix UserListUpdater flaky test

- Sources_v3/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
- Sources_v3/StreamChat/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Sources_v3/StreamChat/APIClient/Endpoints/Requests/AttachmentActionRequestBody.swift
- Sources_v3/StreamChat/APIClient/Endpoints/Requests/AttachmentActionRequestBody_Tests.swift
- Sources_v3/StreamChat/Controllers/MessageController/MessageController.swift
- Sources_v3/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources_v3/StreamChat/Database/DatabaseContainer_Mock.swift
- Sources_v3/StreamChat/Models/Attachment.swift
- Sources_v3/StreamChat/Models/Attachment_Tests.swift
- Sources_v3/StreamChat/Workers/MessageUpdater.swift
- Sources_v3/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources_v3/StreamChat/Workers/MessageUpdater_Tests.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Tests_v3/Shared/TemporaryData.swift
- Tests_v3/StreamChatTests/Dummy data/MessagePayload.swift
**This PR** adds LLC support for message actions:
- exposes `dispatchEphemeralMessageAction ` by `ChatMessageController`
- exposes `dispatchEphemeralMessageAction ` by `MessageUpdater`
- introduces `AttachmentActionRequestBody` type
- introduces `dispatchEphemeralMessageAction ` endpoint
**Notes and possible improvement directions:**
1. If user sends `/giphy cat` and then `/giphy wow` they will see 2 ephemeral messages in channel one for each `/giphy` command. In **v2** there's always a single ephemeral message which is updated to reflect the latest command
2. When **Cancel** action is chosen the ephemeral message is `softly` deleted -> it's content changes to `Message deleted` and stays in a channel which is not nice but cannot be fixed at this point (it is part of global issue with …
> [CIS-520] Attachment actions (LLC)

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
Added the same fallback that is on row insertion
> V2: prevent crash on inconsistent row deletion in ChatViewController

- Sources_v3/StreamChatUI/ChatChannel/ChatReplyBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputContainerView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSendButton.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
- Sources_v3/StreamChatUI/Utils/Animation.swift
- Sources_v3/StreamChatUI/Utils/UIView+Extensions.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Update `textColor` with `ColorPalette`
- Fix sendting attachments without text
- Remove left and right extra insets for `MessageComposerView`
- Add basic animation to `MessageComposer`
_Note: haven't succeeded in animating intrinsicContentSize change on textView height expand._
https://user-images.githubusercontent.com/10098359/103308065-d9912680-4a11-11eb-9fe6-c75591f47073.mp4
> [CIS-550] MessageComposer basic animation

- Sources_v3/StreamChat/Models/Channel.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelNavigationBarListener.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources_v3/StreamChatUI/Generated/L10n.swift
- Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources_v3/StreamChatUI/UIConfig.swift
- Sources_v3/StreamChatUI/Utils/ChannelNamer.swift
- StreamChat_v3.xcodeproj/project.pbxproj
We didn't implement this logic and sample data had lots of empty names, looking bad on UI
A picture tells a thousand words: before and after
> Fix empty/incorrect Channel names on ChannelList

- Sources_v3/StreamChat/Database/DatabaseContainer.swift
- Sources_v3/StreamChat/Workers/Background/AttachmentUploader.swift
- Sources_v3/StreamChat/Workers/Background/MessageEditor.swift
- Sources_v3/StreamChat/Workers/ChannelListUpdater.swift
- Sources_v3/StreamChat/Workers/ChannelUpdater.swift
We were removing `persistentStore` in `removeAllData` when we detected a new user login, but this causes crashes if there are ongoing `write` actions accessing the said store.
When we initialize the `DatabaseContainer` first, we reset ephemeral values with `resetEphemeralValues` async func:
```swift
/// Iterates over all items and if the DTO conforms to `EphemeralValueContainers` calls `resetEphemeralValues()` on
/// every object.
func resetEphemeralValues() {
write({ session in
let session = session as! NSManagedObjectContext
try self.managedObjectModel.entities.forEach { entityDescription in
guard let entityName = entityDescription.name else { return }
let fetchRequest: NSFetchRequest<NSFetchRequestResult> = NSFetchRequest(entityName: entityName)
let entities = try …
```
> Fix db crash on user change

- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatSwipeableListItemView.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
- Adds capability of swipe to delete to cell, without implemented action on tap yet. 
- Go to any user and try swipe to delete on any cell. Try scrolling around.
> [CIS-485] Swipe to delete

- Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
A Boolean value that determines whether bouncing always occurs when vertical scrolling reaches the end of the content.
```
var alwaysBounceVertical: Bool { get set }
```
If this property is set to `true` and bounces is `true`, vertical dragging is allowed even if the content is smaller than the bounds of the scroll view. The default value is `false`.
> Enable bouncing on small content message list

- Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputContainerView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputTextView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
- Sources_v3/StreamChatUI/Utils/UITextView+Extensions.swift
- Fix occasional feedback loop on setting replies and message to edit
- Fix height of `MessageComposerInputTextView`
- Adjust `MessageComposerInputContainerView` according to UI framework guidlines and fix height
- Fix ambiguity in `topStackView` `intrinsicContentSize`
- Fix composer size reset after major layout changes
https://user-images.githubusercontent.com/10098359/103549249-59524180-4ea7-11eb-8a25-56ae1bd681fb.MP4
> [CIS-552] Fix composer resizing

- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
- Fix `textView` height update after mention selection
I'm not happy with this hack but haven't found anything better.
Before: 
https://user-images.githubusercontent.com/10098359/103793491-53459780-5044-11eb-84ed-e9d166c38303.MOV
After: 
https://user-images.githubusercontent.com/10098359/103793569-58a2e200-5044-11eb-800c-c25502c807b1.MP4
> [CIS-560] Fix `textView` height update after mention selection

- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputTextView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
In this PR:
- Fix multiple `textDidChange` delegate call
- Fix `UserSearchController` delegate conformance in `MessageComposerSuggestionsViewController`
> [CIS-559] Mention suggestions crash

- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageGiphyView.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageImageGallery.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageThreadInfoView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessageListVC.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatReplyBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatSwipeableListItemView.swift
- Sources_v3/StreamChatUI/Common Views/ChatSquareButton.swift
- Sources_v3/StreamChatUI/Common Views/OnlineIndicatorView.swift
- Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView+ActionButton.swift
- Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- Fix of Access Modifiers for `View` subclasses / `Customizable` implementations  across the SDK usage, i.e. now functions that should be public are public, functions that should be open (everything except `defaultAppearance`) are open 🎊 .
- Adds `SwipeableListItemView` to `UIConfig`.
- Adds 8 points inset from top to Message List UI.
Main thing to test in here is the inset (check if autoscroll to bottom works properly), other things should be clear. :)
> Minor SDK Fixes 

- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputSlashCommandView.swift
Composer view layout is confusing and hard to understand. So I have no idea why exactly this loop happen and why removing this constraint fixes it.
But looks like it helped.
> Fix layout loop in composer command view

- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
It looks like this stopObserving logic is not needed, or else `deinit` wouldn't be called anyway.
> [V3] Fix crash when dismissing ChannelListVC presented modally

- CHANGELOG.md
- Sources/UI/Extensions/UIKit/ViewController+ImagePicker.swift
Closes #657
Tested and works. SDK can access assets selected by user, and camera asks for permission automatically.
This makes me wonder why so many apps require full access while they could get by with this approach... (Nearly all messaging apps, marketplace apps, etc...)
> Fix photo library permission asked unnecessarily

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController+Cells.swift
The new behavior, where thread is still reachable, was requested and is more like indistury (Slack)
Fixes #660
> Fix message replies are unreachable when message is deleted

- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCollectionView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCommandsHeaderView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsViewController.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerViewController.swift
- Sources_v3/StreamChatUI/Generated/L10n.swift
- Sources_v3/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources_v3/StreamChatUI/UIConfig.swift
- StreamChat_v3.xcodeproj/project.pbxproj
Fixes issues with SuggestionsViewController:
- Go to ChatVC and try suggestions, you should see header for commands right now, if you change the commands to suggestions and tagging, you should not see any header. Also check the code for the related issues :)
> [CIS-546] Fix Suggestion presenting and colors

- CHANGELOG.md
- Sources/Client/Client/Client.swift
In #401, heatUpTCPConnection was introduced to improve latency, but for unknown reasons the endpoint used was changed to queryUsers in #442. This fixes that and resolves #729
> Fix QueryUsers is used for TCP heatup

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
- Sources/UI/Extensions/UIKit/UITableView+Extensions.swift
When scroll to row command is for the last item, it's safer to scroll to the bottom of it (happens after view is loaded). When it's for another item, top is better (happens when loading more messages). 
Closes #653
> V2: Fix table view not at bottom when last message is large

- CHANGELOG.md
- Sources/Client/Model/Channel/Channel.swift
- Sources/Client/Model/Message/Message.swift
Had to add a fallback for `Config` because it doesn't come in result of message search and I didn't want to break API by making it optional.
Closes #650
> V2: Add channel property to message

- Sources_v3/StreamChat/Controllers/CurrentUserController/CurrentUserController+Combine_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources_v3/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources_v3/StreamChat/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources_v3/StreamChat/Database/DTOs/MessageReactionDTO.swift
- Sources_v3/StreamChat/Database/DTOs/MessageReactionDTO_Tests.swift
- Sources_v3/StreamChat/Database/DatabaseSession_Tests.swift
- Sources_v3/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Tests_v3/StreamChatTests/Dummy data/UnreadCount.swift
We used all variants of ints for storing numbers in the DB. To avoid overthinking in what kind of `IntXX` to use, let's use ~`Int32`~ `Int64` everywhere ( `Int16` can sometimes not be enough for certain cases - like our demo app).
We also convert any incoming number to ~`Int32`~ `Int64` safely using ~`Int32(clamping:)`~`Int34(clamping:)`. So even when the number (due to a bug on the backend for example) exceeds ~`Int32.max`~ `Int64.max`, we will just clamp it,
> [CIS-431] Use Int~32~64 for database

- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageAttachmentInfoView.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageGiphyView.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageImageGallery.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView+ActionButton.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageInteractiveAttachmentView.swift
- Sources_v3/StreamChatUI/ChatChannel/Attachments/ChatMessageLinkPreviewView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageMetadataView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatMessage/ChatMessageThreadInfoView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatReplyBubbleView.swift
- Sources_v3/StreamChatUI/ChatChannel/ChatVC.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCheckmarkControl.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerCommandCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputSlashCommandView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerInputTextView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerMentionCollectionViewCell.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerSuggestionsCommandsHeaderView.swift
- Sources_v3/StreamChatUI/ChatChannel/MessageComposer/MessageComposerView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources_v3/StreamChatUI/ChatChannelList/ChatUnreadCountView.swift
- Sources_v3/StreamChatUI/MessageActionsPopup/MessageActionsView+ActionButton.swift
- Sources_v3/StreamChatUI/UIConfig.swift
- Introduces correct TextStyles according to design team, also fixes some minor UI issues in ChannelList
- Launch the application, play with the fontSize in Accessibility settings in iOS settings, probably wait for Design to finish their QA cycle :) 
- `UIConfig.swift`, then all the files. 
NOTE: Maybe check `ChatMessageInteractiveAttachmentView` and tell me if the italic headline feels wrong, we probably need to introduce new font to our line-up.
> [CIS-581] Introduce StreamTextStyles, fix minor UI issues in ChannelList

- hooks/pre-commit.sh
**This PR** updates the pre-commit-hook script to work for the new file structure.
`./bootstrap.sh` has to be run to have the hook changes applied
> Adjust hook-script for new file structure

- Sources/StreamChatUI/ChatChannelList/ChatChannelAvatarView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewCell.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelSwipeableListItemView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelUnreadCountView.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageAttachmentInfoView.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageGiphyView.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageLinkPreviewView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageMetadataView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageThreadInfoView.swift
- Sources/StreamChatUI/ChatMessageList/ChatVC.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerCheckmarkControl.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerMentionCollectionViewCell.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerQuoteBubbleView.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerSendButton.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageInputSlashCommandView.swift
- Sources/StreamChatUI/Common Views/CurrentChatUserAvatarView.swift
- Sources/StreamChatUI/UIConfig.swift
- Sources/StreamChatUI/Utils/UIFont+Extensions.swift
In this PR:
- trying to find the happy medium between designs and iOS-ness of the UI
**Before:** 
**After:**
> [CIS-600] Font and UI improvements 

- fastlane/Fastfile
- fastlane/README.md
**This PR**:
- introduces `register_new_device_and_recreate_profiles` lane
- adds `readonly` option to`match_me` lane
#no_changelog
> [CIS-599] Introduce `register_new_device` lane

- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelReadStatusCheckmarkView.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelUnreadCountView.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerSuggestionsViewController.swift
- Sources/StreamChatUI/Common Views/ChatAvatarView.swift
- Sources/StreamChatUI/Common Views/CurrentChatUserAvatarView.swift
- Moves remaining code from `setupAppearance` to `defaultAppearance` inside SDK so the changes happen in correct functions across the SDK
> Move code from setupAppearance to defaultAppearance

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageQuoteBubbleView.swift
- Sources/StreamChatUI/ChatMessageList/ChatVC.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerQuoteBubbleView.swift
- Sources/StreamChatUI/UIConfig.swift
- Adjust navigation bar layout on `ChatVC`
Before / After
- Change the layout of the `ChatMessageComposerQuoteBubbleView`
Before / After
Before / After
> [CIS-610] Message list UI polishing

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Custom Table View like layout that position item at index path 0-0 on bottom of the list. 
Unlike `UICollectionViewFlowLayout` we ignore some invalidation calls and persist items attributes between updates.
This resolves problem when on item reload layout would change content offset and user ends up on completely different item.
Layout intended for batch updates and right now I have no idea how it will react to `collectionView.reloadData()` (so far fine).
During testing on iPhone SE (1st gen) iOS 14.2 I was able to achieve hitch ratio:
- initial scroll from bottom to top: 49 ms/s
- scroll from top to bottom on already layouted list: 46 ms/s
So whole collection view layout related logic bring almost no overhead. (This are still awful numbers, Apple do not recommend ratio over 10 ms/s) …
> Introduce custom layout for message list

- CHANGELOG.md
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Fixes a crash when reordering the channel lists that was caused by moving and updating the same IndexPath in the collection view.
- When creating a new message, the order of the channel list is now updated instantly
> [CIS-603] Fix stability issues when reordering channel list

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Requests/MessageReactionRequestPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Requests/MessageReactionRequestPayload_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
In this PR:
- Update `addReaction` API with `enforce_unique` parameter
> [CIS-511] Update `addReaction` API with `enforce_unique` parameter

- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputContainerView.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageInputSlashCommandView.swift
- Fixes issue with forgotten and commented out code while merging UIConfig...
- Go to some conversation, open composer, add some slash command and expect the badge to look according to designs.
Before:
After:
> Fix command button in composer

- Sources/StreamChatUI/ChatChannelList/ChatChannelListRouter.swift
- Sources/StreamChatUI/ChatMessageList/ChatChannelRouter.swift
- Sources/StreamChatUI/ChatMessageList/ChatVC.swift
- UserSearchController is now created from `channelController` in `ChatVC`
> Replace passing of userSearchController in ChatVC

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
- Fix issue with decoding missing `member_count` in `ChannelDetailPayload`
> [CIS-586] Fix issue with decoding missing `member_count` in `ChannelDetailPayload`

- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerMentionCollectionViewCell.swift
- Fixes text overlapping the mention image and continuing beyond screen in suggestion cells (see screenshots)
- Run suggestions in any chat screen
The problem in this case is that the collectionView cells ignored the `estimatedRowSize` width and rather use the maximum width based on cell content. because we missed the method `preferredLayoutAttributesFitting` where we set the width to be required.
So before introducing this method and changing the text stackView trailing to the image on the right,  it was actually a go for cell autoresizing width. Also without us knowing, the cell was much wider because of the long id text (had no trailing and stack view caused to expand wider).
Basically this issue could have been solved with using explicit `itemSize` with some magic height constraint …
> [CIS-623] Add text truncating in Suggestion cell

- fastlane/Matchfile
Updates the url of the certificates repo in Matchfile to SSH.
> Update certificates repo url to SSH

- Sources/StreamChatUI/Utils/Bundle+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
Fixes #783
Cause: https://github.com/yonaskolb/Mint/issues/179
Since `mint run` always installs a package, and installing `swiftlint` takes around 3-4 minutes (on my computer), I've decided it's best that developers don't have to install swiftlint to run the project.
> [CIS-629] Fix mint failing run phase if swiftlint is not installed

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
Follow up for #737 
While using zero size for non-sizided cells, we forced layout to iterate over ALL cells (who would expect from zero height cells :D ).
After quick test, this magic size worked well, and I haven't noticed any weird text cell flicks.
> Increase fake size for non-sized cells

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/MemberController/MemberController.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController.swift
- Sources/StreamChat/Controllers/UserController/UserController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- Sources/StreamChat/Models/Attachment.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/ChannelRead.swift
- Sources/StreamChat/Models/CurrentUser.swift
- Sources/StreamChat/Models/Member.swift
- Sources/StreamChat/Models/Message.swift
- Sources/StreamChat/Models/MessageReaction.swift
- Sources/StreamChat/Models/User.swift
- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/ChannelMemberListQuery.swift
- Sources/StreamChat/Query/ChannelQuery.swift
- Sources/StreamChat/Query/UserListQuery.swift
The link we used in the documentation was incorrect.
> Fix incorrect extra data cheat sheet link

- CHANGELOG.md
- DemoApp/CreateChatViewController.swift
- DemoApp/CreateGroupViewController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController+SwiftUI.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver_Tests.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController+SwiftUI.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController_Mock.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController+SwiftUI.swift
- Sources/StreamChat/Controllers/MessageController/MessageController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController+SwiftUI.swift
- Sources/StreamChat/Controllers/UserListController/UserListController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Utils/LazyCachedMapCollection.swift
- Sources/StreamChat/Utils/LazyCachedMapCollection_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
Improve performance of CoreData observers by introducing `LazyCachedMapCollection`, data structure that applies transformations to underlying sequence on read access.
Decrease amount of DB queries on DTO -> Model transformation when possible.
Huge FPS drop on channel open happens not because of message list layout or message load (affects it, but not critical).
Apparently when we open channel, channel list observer overload CPU by making useless job.
> [CIS-256] Lazy model transformation for LLC

- .github/workflows/beta.yml
Installs @Stream-iOS-Bot 's SSH key to the device when running `beta` lane such that it has access to our certs repo.
> [CIS-633] Fix beta lane

- CHANGELOG.md
- Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
We already have a fix like this at other places in the observers. I just extended it to cover the other exposed cases, too.
---
Fixed exactly as @cardoso suggested :trollface:
> [CIS-632] Fix race conditions on database observers

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Workers/Background/MessageSender_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/Dummy data/TestAttachmentEnvelope.swift
- Make it possible to save `AttachmentEnvelope` to DB
- Make it possible to create `MessageDTO` with `[AttachmentEnvelope]`
- Add possibility to send message with `[AttachmentEnvelope]` to `ChannelUpdater`
- Add possibility to send message with `[AttachmentEnvelope]` to `MessageUpdater`
- Expose possibility to send message with `[AttachmentEnvelope]` in `ChannelController`
- Expose possibility to send message with `[AttachmentEnvelope]` in `MessageController`
- Fix and update `MessageSender_Tests`
- Fix `Demo` app after API changes
> [CIS-637] Sending attachments without uploading

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Workers/Background/AttachmentUploader.swift
- Sources/StreamChat/Workers/Background/MessageSender_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
Average channel open time (duration from tap to idle state) is 1.3s.
A lot of time takes data base updates and table reloads.
But in most cases such reloads are redundant because object haven;t been changed, only touched and marked as dirty.
By reseting dirty, but not changed, objects I was able to reduce open time from 1.3s to 0.6s.
Rest of time is initial layout setup (VC and message list).  It doesn't make much sense to invest time in this, since layout policy is about to change.
> [CIS-638] Decrease channel launch times

- CHANGELOG.md
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Shared/TestDataModel2.xcdatamodeld/TestDataModel2.xcdatamodel/contents
Adds test coverage to validate that the Database is flushed when it fails to load the persistent store (For example, when there are significant DB changes that would require a migration).
> [CIS-636] Validate database flushing logic

- CHANGELOG.md
- Sources/StreamChat/Workers/Background/AttachmentUploader.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
Message edit/delete is a user permission so some users are able to edit/delete other's messages. Backend controls this, so we should let backend return an error. By default, admin/moderators have this permission, but this configurable and it's not sent by backend, so safest to let users control this logic on their end.
> Allow message edit/delete from all users

- Sources/StreamChat/Utils/SystemEnvironment+Version.swift
- Sources/StreamChat/Utils/SystemEnvironment.swift
- StreamChat.xcodeproj/project.pbxproj
- fastlane/Fastfile
- Adds generation of hardcoded `StreamChat` SDK to project, done via 2 additional lanes, one for setting the version to the project file, second for releasing the project and bumping it easily, mostly taken from v2 Fastfile but a bit modified.
- For testing setting the version, you can run `fastlane set_SDK_version version: x.y.z` and you should see change in `SystemEnvironment+Version.swift`. I wouldn't test the release lane, it can help @b-onc once we are ready for next versions.
-  Probably just `Fastfile`
> [CIS-624] Add Hardcoded SDK version generation to project

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachmentSeed.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
- Simplify attachment send API
> [CIS-661] Simplify attachment send API

- CHANGELOG.md
- Sources/UI/Chat/Chat View Controller/ChatViewController.swift
...on cold launches
When this happens:
```swift
let channel = Client.shared.channel(type: .messaging, id: channelId)
let channelPresenter = ChannelPresenter(channel: channel)
let controller = createChatViewController(with: channelPresenter)
setupChatViewController(controller, with: channelPresenter)
navigationController?.pushViewController(controller, animated: false)
```
`ChatViewController` needs to `query` the channel so it can get more info (at this point it only has `cid`). The VC setup the title and avatar before it had all the channel info.
> Fix ChatViewController title and avatar is not shown correctly

- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputTextView.swift
Before: 
After:
- Fixes issue where caret was overlapping placeholder position in `ChatMessageComposerInputTextView`
- You can run the app and check composer textview on different devices and see if the insets are same, they should be same, tested on iPhone SE (2nd Gen), iPhone 12 Pro and iPhone 12 Simulator)
- `ChatMessageComposerInputTextView`
> [CIS-675] Fix caret position overlapping placeholder in ChatMessageComposerInputTextView

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
Fixes a crash when creating a new channel by Verifying that `previousItems` are not empty when `finalLayoutAttributes` is called. This function can be called randomly before `prepare(forCollectionViewUpdates)` where `previousItems` is populated. Sometimes ChatVC calls `keyboardFrameWillChange` that triggers the `finalLayoutAttributes` function before the  `prepare(forCollectionViewUpdates)`. So we need to safely check first if the `previousItems` are not empty.
> [CIS-676] Fix crash when creating new channel

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/AttachmentPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/Attachments/ChatMessageDefaultAttachment.swift
- Sources/StreamChat/Utils/OptionalDecodable.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/DummyData/AttachmentPayload.swift
- Tests/StreamChatTests/MockEnpointResponses/MessageWithBrokenAttachments.json
- Fixes issue where malformed attachment data could cause Channel not to appear
1. Open 2 simulator device at same time and on each run the same instance of Demo App
1. Select any user 
1. Exit one of the simulators (A)
1. From the other one (B) send some messages for the selected user account
1. Start A again with the app and log in to the same user
1. Observe that all channels are displayed for the same user on both devices
> Fix Channels not showing up when Message attachment has malformed data

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
The checks were there but they were inverted. cc @nuno-vieira
> [CIS-683] Fix crash when rotating screen

- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
Changing a location of a view without not calling `super.setUpLayout()` has been so far mildly challenging as there were too many constraints from `super.setUpLayout` influencing it. 
To make such customizations easier, we can introduce `Layout` struct which will contain properties of grouped constraints. Therefore, if a client wants to change a location of eg. `timestampLabel`, he could do `NSLayoutConstraint.deactivate(layout.timestampLabelConstraints)` and then add their own constraints to make the process more straightforward.
> [CIS-690] Expose ChatChanneltemView constraints in the Layout object

- CHANGELOG.md
- Package.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
- Sources/StreamChatUI/ChatMessageList/ChatChannelNavigationBarListener.swift
- Sources/StreamChatUI/ChatMessageList/ChatChannelVC.swift
- Sources/StreamChatUI/Generated/L10n.swift
- Sources/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources/StreamChatUI/UIConfig+ChannelList.swift
- Sources/StreamChatUI/UIConfig+MessageList.swift
- Sources/StreamChatUI/Utils/ChatChannelNamer.swift
- Sources/StreamChatUI/Utils/ChatChannelNamer_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- bootstrap.sh
- Makes `ChatChannelNamer` more customizable by changing the class into one global function with same purpose as suggested by @VojtaStavik in our slack Channel
- The tests should cover all cases, you can run the demo application and check if the channel names are the same. 
- `ChatChannelNamer.swift`
Note: Maybe we could create some different `ChannelNamer` closure to show how the customization is done?
> [CIS-689] Refactor ChatChannelNamer

- CHANGELOG.md
- Package.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Utils/Logger/Logger.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelTruncatedEventMiddleware_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/ChannelEvents.swift
- Sources/StreamChat/WebSocketClient/Events/ChannelEvents_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/EventType.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/MockEnpointResponses/Events/Channel/ChannelTruncated.json
When the channel is truncated, it means all messages sent before the truncation disappear. When you query the channel, it has no messages and even the `last_message_at` value is reset.
a) Delete all messages from the DB -> hard deleting entities from CoreData is not trivial because of our complex data model scheme. This would be the most complicated way to implement this feature. 🔴 
b) Soft-delete messages by `message.type = .deleted`-> this is less complex but not ideal. Deleted messages have different semantics from the truncated messages, especially when it's the messages sent by the current user. Almost there... 🔴 
c) Do it the same way the backed does it -> I added `truncatedAt` field to `ChannelDTO` and adjusted the message predicates to ignore the message created before this date. …
> [CIS-692] Implement Channel Truncating

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC_Tests.swift
- Sources/StreamChatUI/CommonViews/ListCollectionViewLayout/ListCollectionViewLayout.swift
- fixed a bug where separators would disappear when the height of the cell would be different from estimated size
- make separators supplementary views instead of decorators
Possible Qs:
- I was not completely sure how to handle the kind and reuse identifier. As reuse identifier is quite contained, I had hard coded it in `ChatChannelListVC`. The kind identifier is then reused via a property defined in `ListCollectionViewLayout`. LMK if you'd have done it differently
> [CIS-699] Make separators supplementary views

- hooks/pre-commit.sh
- Fixes issue with pre-commit hook that header formatter was not ran due to not being compatible with bash commands in path arguments. Uses native `git-format-staged` exclusion instead 😅 
⚠️ 
**Don't forget to re-link your pre-commit hooks via `bootstrap.sh` after this is merged **
> Fix Swift file formatter pre-commit hook

- Package.swift
- Sources/StreamChatUI/UIConfig+SwiftUI.swift
- Sources/StreamChatUI/UIConfig+SwiftUI_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
This PR adds custom view modifier `setUpStreamChatUIEnvironment()` which is to be called when user desires to setup `UIConfig` environment object for usage in `SwiftUI` app.
> [CIS-702] Add custom view modifier for SwiftUI usage of UIConfig

- Package.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- StreamChat.xcodeproj/project.pbxproj
- remove initial layout hack on `ChatMessageListVC` (main issue was missing `zIndex` on layout attributes returned from layout)
- thanks to fix above there is no more need to check for Stream setup in `ChatMessageCollectionViewCell`
- implement batch update changes correctly for deletions
- add basic unit tests for layout deletions and insertions
- fix initial message list jumping by restoring `contentOffset` after batch updates
- the only reliable way I was able to find is by either updating `targetContentOffset(forProposedContentOffset:)` in layout or to scroll in `finalizeCollectionViewUpdates()` if we rely on invalidation contexts from self-sizing the changes are always visible
- this sort of mimics the behavior of `_ChatMessageListVC.scrollToMostRecentMessageIfNeeded()` so maybe it …
> [CIS-655] Remove collection view hiding hack

- CHANGELOG.md
- Sources/StreamChat/APIClient/APIPathConvertible.swift
- Sources/StreamChat/APIClient/Endpoints/AttachmentEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/AttachmentEndpoints_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelEditDetailPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelEditDetailPayload_Tests.swift
- Sources/StreamChat/Models/ChannelId.swift
- Sources/StreamChat/Models/ChannelId_Tests.swift
- Sources/StreamChat/Query/ChannelQuery.swift
- Sources/StreamChat/Query/ChannelQuery_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- introduce `APIPathConvertible` protocol to unify access to paths using `ChannelId` and its properties
- all SDK calls should now on use this API - I already updated the ones I could find (I searched for `type)` in the whole project so we might be quite safe)
- I kept original approach in tests, just added `rawValue`s (at least for now) to make sure no regressions are created
> [CIS-396] Improve ChannelId path encoding

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
Send the client header version prefixed with ´v´ so we can identify the new SDK versions in the Dashboard.
> [CIS-713] Prefix SDK Version in Client Header with 'v'

- CHANGELOG.md
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources/StreamChat/Controllers/EntityDatabaseObserver_Mock.swift
Fixes hidden message actions. When getting the `currentUser` from `CurrentUserController`, it was missing the start observing. So the `currentUser` would only be retrieved if `synchronize` was called.
> [CIS-718] Fix message actions not visible

- CHANGELOG.md
- Package.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MemberPayload.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/DummyData/MemberPayload.swift
I was surprised to see `saveMember` doesn't actually link the member to the Channel! Is that intentional? Introducing this logic didn't break any test.
> [CIS-726] Introduce MemberEventMiddleware

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
From UIBackgroundTask documentation:
> ... If you do not call endBackgroundTask(_:) for each task before time expires, the system kills the app. If you provide a block object in the handler parameter, the system calls your handler before time expires to give you a chance to end the task.
In v2, `endBackgroundTask` was being called after `disconnect` implicitly, so no crashes were observed. We oversaw this in v3. If you keep the app open long enough in background, console logs:
```
2021-03-11 14:19:30.793611+0100 ChatSample[13949:4184668] [BackgroundTask] Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x282149cc0>: taskID = 109, taskName = Called by StreamChat, from $sSo13UIApplicationC19beginBackgroundTask17expirationHandlerSo012UIBackgroundD …
```
> [CIS-719] Fix app getting terminated in bg due to unfinished task

- bootstrap.sh
Deletes post-rewrite link for git-hook which caused some trouble with duplicate commits after rewriting history.
> Delete post-rewrite hook link from bootstrap.sh

- Sources/StreamChat/ChatClient_Mock.swift
- Tests/Shared/StressTestCase.swift
- adds cleanup after each test suite so disk space issue should be resolved
- prefers test failure to crash if `DatabaseContainer_Mock` in `ChatClient_Mock` cannot be instantiated
> Add cleanup to stress tests

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/EventMiddlewares/UserWatchingEventMiddleware.swift
This happens because when we query channels with watch: true, our current user watches the channels and backend sends the `userStartedWatching` event before we save the channels that we just watched to the DB.
> Fix watcher events received for current user during query

- Sources/StreamChat/Controllers/ListDatabaseObserver_Tests.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelMemberListQueryDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/DeviceDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageReactionDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/UserDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseSession_Tests.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware_Tests.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/EventDataProcessorMiddleware_Tests.swift
- Sources/StreamChat/Workers/ChannelListUpdater_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/EventSender_Tests.swift
- Sources/StreamChat/Workers/UserListUpdater_Tests.swift
- Tests/Shared/StressTestCase.swift
- Tests/Shared/TestRunnerEnvironment.swift
- Tests/StreamChatTests/StreamChatStressTestPlan.xctestplan
- fastlane/Fastfile
Wait for release of database so CoreData tests do no affect each other. I also reduced stress tests cycles to 5 for now so we pass the 6h job limit on CI.
Seems to work well as tonight stress tests [passed](https://github.com/GetStream/stream-chat-swift/actions/runs/659391394) 🎉
> [CIS-710] Fix flaky LLC tests

- Sources/StreamChat/Utils/SystemEnvironment.swift
- Sources/StreamChatUI/Utils/SystemEnvironment.swift
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatUITests/TestImages/XCTestCase+TestImages.swift
If it's possible and the size of the `UIImageView` is known, we automatically resize the image to fit the image view. This resized image is also cached automatically by Nuke.
> [CIS-659] Resize images to fit UIImageView bounds

- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView+SwiftUI_Tests.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelUnreadCountView+SwiftUI_Tests.swift
- Sources/StreamChatUI/CommonViews/AvatarView/ChatChannelAvatarView+SwiftUI_Tests.swift
- Sources/StreamChatUI/Utils/UIView+Extensions.swift
- Removes TAMIC from pin view extensions and replaces the 
- Probably CI can take care of UI Tests, if they pass, we are fine :) 
- `UIView+Extensions.swift`
> [CIS-729] Remove setting of TAMIC inside pin methods

- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerDocumentAttachmentsView.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerImageAttachmentsView.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessagePopupVC.swift
Fixes issues with composer view having bad size because TAMIC was set to true in underlying components, causing it not to expand properly.
> Fix constraints on ChatMessageComposerVC

- CHANGELOG.md
- Sample/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
- Sample/Samples/SimpleChat/SimpleChannelsViewController.swift
- Sample/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/Message.swift
- Sources/StreamChat/Utils/Cached.swift
- Sources/StreamChatTestTools/Models/ChatChannel_Mock.swift
- Sources/StreamChatTestTools/Models/ChatMessage_Mock.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
Improve some `asModel` function performance by loading expensive top level properties lazily. This means that affected model structs are now thread-confined which should be addressed later as it does not make much sense for value types.
Some other changes were necessary:
- `@Cached` wrapper now has `computeValue` closure as `projectedValue` as otherwise it cannot be set from outside as `_cachedWrapper` property is private ➡️ this will not be possible as `__mentionedUsers` is inaccessible because it is private automatically
```
__mentionedUsers.computeValue = { Set(dto.mentionedUsers.map { $0.asModel() }) }
```
- some model inits needed to be reorder to make compiler happy
I consider the semantic change of `_ChatChannel` and `_ChatMessage` to be breaking so it is marked this way in …
> [CIS-733] Load expensive CoreData properties lazily

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/CurrentUserPayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/CurrentUserPayloads_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/UserPayloads_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/TeamDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO_Tests.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/User.swift
- Sources/StreamChatTestTools/Models/ChatUser_Mock.swift
- Tests/Shared/CustomAssertions/AssertAsync.swift
- Tests/StreamChatTests/DummyData/ChannelPayload.swift
- Tests/StreamChatTests/DummyData/UserPayload.swift
- Tests/StreamChatTests/MockEnpointResponses/Channel.json
- Tests/StreamChatTests/MockEnpointResponses/CurrentUser.json
- Tests/StreamChatTests/MockEnpointResponses/OtherUser.json
- Tests/StreamChatTests/MockEnpointResponses/UserUpdate/UserUpdateResponse.json
- codecov.yml
- Adds support for user teams and channel team inside those payloads
- Run tests if `teams` property is parsed from payload.
- `UserPayload` and `ChannelListPayload`, check if there is correct relationship between objects.
> [CIS-259] Implement teams

- Sources/StreamChat/Query/ChannelListQuery.swift
- Sources/StreamChat/Query/ChannelListQuery_Tests.swift
- Sources/StreamChat/Query/UserListQuery.swift
- Sources/StreamChat/Query/UserListQuery_Tests.swift
Just something we forgot to add in #905. This PR adds the possibility to filter users and channels using the `team(s)` keys.
> Add team filter keys

- Sources/StreamChatUI/ChatMessageList/ChatVC.swift
When few messages are displayed in messages list (`contentSize.height` is smaller than `frame.height`) the general keyboard avoiding behavior is not great. Each time the `scrollView.contentOffset` is shifted by the height of the keyboard.
In this PR I addressed this issue. The final code is documented and tested on iPhone with notch, iPhone without notch and on iPad. Both orientations – portrait and landscape – were tested as well.
You can see the result on the screenshots below.
Before             |  After
--- | ---
> Fix messages content offset when few messages displayed

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- StreamChat.xcodeproj/project.pbxproj
In most of our controllers, this was correct. However, some controllers have this done incorrectly which leads to loops when accessing controllers' variables from within delegate callbacks.
> [CIS-744] Fix observer starting logic

- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
Fixes flaky test cause by some data comparison logic errors
> Fix channelPayload_truncatedMessagesAreIgnored flaky test

- .github/actions/prepare-ios-simulator/action.yml
- .github/workflows/full-checks.yml
- .github/workflows/smoke-checks.yml
- fastlane/Fastfile
The tests were not running below < iOS 14. It would fall back to the default device 🤦‍♂️
Issues found:
- The Xcode version was hardcoded, and it can't be because each Xcode includes different default ios simulator runtimes.
- There was missing a pipe "|" for the action to actually work -.-
- The stress tests were not even running on the specified versions because it was missing the `options[:device]` parameter on the lanes. Even if the prepare-simulator-action was working, the stress tests were always running on the default device.
The script needs to have a condition because of how the Xcode path is different on 10.3 vs >10.3
More details here: https://github.com/actions/virtual-environments/issues/551#issuecomment-637344435
Now I finally got why the iOS 12 coverage was the same as the …
> Fix CI not running tests below iOS 14

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/Events/ChannelEvents.swift
- Sources/StreamChat/WebSocketClient/Events/ChannelEvents_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/MockEnpointResponses/Events/Channel/ChannelUpdated_ServerSide.json
This was due to missing `user` field. Backend doesn't send `user` field (it's optional in v2) for every event. ChannelUpdated event hasn't received much love yet
> Fix ChannelUpdatedEvent failing to parse

- CHANGELOG.md
- Sample/Samples/CombineSimpleChat/CombineSimpleChannelsViewController.swift
- Sample/Samples/SimpleChat/SimpleChannelsViewController.swift
- Sample/Samples/SwiftUISimpleChat/ChannelListView.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Mock.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Config/ChatClientConfig.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Database/DatabaseContainer_Mock.swift
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Utils/Database/NSManagedObjectContext+Extensions.swift
- Sources/StreamChatTestTools/Models/ChatChannel_Mock.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListItemView.swift
This is a follow-up PR on #911 . It improves the naming and adds a limit for `ChatChannel.latestMesages`.
> [CIS-727] `ChatChannel` limits refinements

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Well the inconsistency error we are getting is actually [docummented](https://developer.apple.com/documentation/uikit/uicollectionview/1618045-performbatchupdates#discussion).
> If the collection view's layout is not up to date before you call this method, a reload may occur. To avoid problems, you should update your data model inside the updates block or ensure the layout is updated before you call performBatchUpdates(_:completion:).
This is actually what is happening in test I added (will be removed as it only logs the error but it is not thrown 🤷)
So we need to make sure to update channel (especially its count) inside `performBatchUpdates`. Currently I thought about mirroring `controller.channels` to local property in `ChatChannelListVC`, the implementation is definitely to be …
> [CIS-674] Fix channel list inconsistency

- SlackClone/SlackChatChannelListViewController.swift
- SlackClone/SlackChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageGroupPart.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Added property to `ChatMessageGroupPart` for `isFirstInGroup` - similar to `isLastInGroup`.
I have two following questions:
- any recommendations for making tests for this?
- I was asked to look at how to refactor `ChatMessageGroupPart` - and honestly, I am not really sure how. I was thinking of adding a delegate but views should only be configurable via `content` property, so that did not seem like a good path to take. Possible refactor would probably be better to do in a different PR anyways, in order for this to be purely additional
> [CIS-753] First message in group

- .github/workflows/full-checks.yml
~Now, with the CI finally running on iOS < 14, another issue found is that the Demo App had min target of iOS 14, so the CI failed when trying to run on iOS 12 and iOS 13.~
~The issue is that changing the min target to iOS 12 has a lot of compilation errors, especially because of the SceneDelegate etc... And also other APIs that we use in the DemoApp are only iOS 13+. For now, probably the best idea is to only change the min target to 13? And actually is there any benefit in compiling the Demo Apps on iOS below 14? Since we already build the SDKs below iOS 14, what is the aim of compiling the demo apps below 14?~
Update:
Removes building demo app iOS < 14
> Remove building demo app iOS < 14 in Full Checks

- codecov.yml
Refer to: https://docs.codecov.io/docs/ignoring-paths 
and our internal conversation about code coverage
> Fix Codecov by ignoring Tests folder recursively

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- The documentation for the factory methods for `ChannelController` is improved + I added missing default parameters for convenience reasons.
- It's now possible to specify channel type when creating a controller for a DM channel
> [CIS-779] Fix hardcoded channel type for DM channels

- Sources/StreamChatUI/ChatMessageList/ChatMessageListKeyboardObserver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListTitleView.swift
- Sources/StreamChatUI/ChatMessageList/ChatVC.swift
- Sources/StreamChatUI/Utils/KeyboardFrameObserver.swift
- StreamChat.xcodeproj/project.pbxproj
Extracted common logic for `ChatVC`'s children to separate components:
* `ChatMessageListTitleView` (audit will be in future PR)
* `KeyboardFrameObserver`
> [CIS-776] Extract ChatVC logic to separate components

- Sources/StreamChatUI/CommonViews/BaseViews.swift
- Sources/StreamChatUI/Utils/UIConfigProvider.swift
Assigning `UIConfig` instance explicitly is possible only before view's subviews are instantiated. When someone assigns `UIConfig` after the view has been initialized, we should log an error. You can use the base views' `isInitialized` for this.
> [CIS-681] Log error when UIConfig is assigned after the view is initialized

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
well.. I hope the comments clarify the issue enough, for our future selves' sake
> Fix new created channels miss initial values

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Fixes incorrect position of new message in an empty channel. 
- Fixes jumps when new messages were added caused by not having enough items to scroll.
https://user-images.githubusercontent.com/12814114/113628096-501a7180-965c-11eb-8b6b-736f771b7b58.mov
https://user-images.githubusercontent.com/12814114/113628064-45f87300-965c-11eb-840d-91924475a0e3.mov
> [CIS-741] Fix incorrect new message position in empty channel

- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageCell.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageCollectionView.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift
System's `dequeueReusableCell(withReuseIdentifier:for:)` creates new cell or uses already created one if possible. Thererore the underlying cell has to be responsible for calling `setUpLayout(options:)` if needed. I created a new method `setUpLayoutIfNeeded` which determines if `setUpLayout` should be called or not.
From my experience we should be safe to call the cell registration on each dequeue but there is no documentation for this behavior. That's the reason why`identifiers: Set<String>` is used.
> Implement MessageListCollectionView reuse mechanism

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Tests/Shared/TemporaryData.swift
update the `channelDTO.lastMessageAt` based on this recommendation https://getstream.slack.com/archives/CE5N802GP/p1617215048066400?thread_ts=1617214945.066200&cid=CE5N802GP
Add calculation of `channelDTO.defaultSortingAt` to `channelDTO.willSave` to update this walue every time the messages are updated.
https://stream-io.atlassian.net/browse/CIS-780
> [CIS-780] Update channel's lastMessageAt when saving Message

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Controllers/ChannelWatcherListController/ChatChannelWatcherListController_Tests.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources/StreamChat/Controllers/MemberController/MemberController_Tests.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController_Tests.swift
- Sources/StreamChat/Controllers/UserController/UserController_Tests.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController_Tests.swift
- Sources/StreamChat/Database/DatabaseContainer_Mock.swift
This was a bug in `UserListController` reported by a customer. I added tests for this case to all controllers and found the same issue in more controllers.
> [CIS-783] Fix missing `startObservingIfNeeded` calls in some controllers

- Sources/StreamChatUI/CommonViews/ContainerView.swift
**This PR** includes `ContainerView` updates:
- new API for custom spacing after specific arranged subview
- initializer now has `spacing = .auto` and `views = []` by default
> `ContainerView` improvements

- CHANGELOG.md
- Package.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController+Combine_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController+Combine_Tests.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController+SwiftUI_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Models/Channel.swift
- Sources/StreamChat/Models/Message.swift
- Sources/StreamChat/Utils/CoreDataLazy.swift
- Sources/StreamChat/Utils/CoreDataLazy_Tests.swift
- Sources/StreamChatTestTools/Models/ChatChannel_Mock.swift
- Sources/StreamChatTestTools/Models/ChatMessage_Mock.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Shared/RandomDispatchQueue.swift
There was a regression introduced by #906 which made our models thread-unsafe. This PR fixes the problem. Instead of the `@Cached` wrapper, we're using `@CoreDataLazy` which evaluates the values on the correct `NSManagedObjectContext`.
> [CIS-792] Make models thread safe

- Sources/StreamChatUI/ChatMessageList/RETHINK/DefaultMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageThreadVC.swift
- Sources/StreamChatUI/UIConfig+MessageList.swift
- StreamChat.xcodeproj/project.pbxproj
This PR creates detail of thread.
* Message cell now contains thread reply button to display the detail
* Messages in ThreadVC don't contain `threadInfo` layout option
* Only replies are used in ThreadVC as dataSource. Parent message is inserted as a subview to the collectionView and its content has inset equal to the parent message height + spacing
> Message list thread

- DemoApp/BannerShowingConnectionDelegate.swift
- DemoApp/BannerView.swift
- DemoApp/ChatPresenter.swift
- DemoApp/DemoAppCoordinator.swift
- DemoApp/Info.plist
- DemoApp/LoginViewController.swift
- DemoApp/SceneDelegate.swift
- Package.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Utils/InternetConnection/Error+InternetNotAvailable.swift
- Sources/StreamChat/Utils/InternetConnection/Error+InternetNotAvailable_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
Mostly this change is about:
* Adding a view for displaying the banner
* Fixing an issue with `internetIsOfflineError` that prevented web socket client from reconnecting
* Fixing URLSession configuration to make reconnection logic work
* Implementing banner logic in DemoApp
* Rehauling navigation in DemoApp a bit to support presenting banner on any screen
> [CIS-528] Add connection status banner to DemoApp

- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputContainerView.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerView.swift
- Sources/StreamChatUI/CommonViews/ContainerStackView.swift
- Sources/StreamChatUI/Utils/UITextView+Extensions.swift
- iMessageClone/iMessageChatMessageComposerView.swift
- Refactors the composer view to use the new container stack view.
**Note:** Right now the composer view controller needs to know about the implementation details of ComposerView in order to use it. This will change in the next PR.
> Refactor composer view with new container view

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageCollectionViewCell.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
TL;DR of this PR is That there is no Cell Reuse identifier for message cell with no `layoutOptions`. This PR add support for this. 
- Fixes issue where application could crash when the cell has no layout options and there is no reuse identifier for such cell because there is no explicit 0 rawValue option.
- Right now if you go to Dem App -> Luke Skywalker -> C-3PO conversation, you will experience a crash associated with no reuse identifier, try this PR and see if it works.
> Fix Application Crash for ChatMessageCollectionViewCell unknown ReuseID

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Mock.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- Sources/StreamChat/Workers/ChatClientUpdater_Tests.swift
- Removes `CurrentUserUpdater.fetchDevices()` call from `CurrentUserController.synchronize()`
- Adds `CurrentUserController.synchronizeDevices()`
> [CIS-803] Change fetching devices to be called explicitly

- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Sources/StreamChat/Query/ChannelWatcherListQuery.swift
- Sources/StreamChat/Query/ChannelWatcherListQuery_Tests.swift
- StreamChat.playground/Contents.swift
- StreamChat.playground/contents.xcplayground
- StreamChat.xcodeproj/project.pbxproj
- The query endpoint had the `requiresConnectionId` incorrectly set to `false`
- Add `state` to `ChannelWatcherQuery` to make sure we always fetch all initial-state watchers
---
I also added a Playground with some basic setup to make it easier in the future to quickly test controllers and basic interactions.
> [CIS-802] `ChatChannelWatcherListController` fixes

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/ConnectionEvents.swift
- Sources/StreamChat/WebSocketClient/Events/MemberEvents.swift
- Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
- Sources/StreamChat/Workers/Background/NewChannelQueryUpdater.swift
- Sources/StreamChat/Workers/Background/NewChannelQueryUpdater_Tests.swift
- Sources/StreamChat/Workers/EventObservers/EventObserver_Tests.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
This PR makes the existing queries for a channel invalidated when the current user membership changes. In other words - when you stop being a member of a channel, you won't see it in the list :)
> [CIS-805] Refresh channel list queries when current user membership changes

- Sources/StreamChatUI/ChatMessageList/ChatMessageListKeyboardObserver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageCell.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageCollectionView.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/MessageThreadVC.swift
- Sources/StreamChatUI/ChatMessageList/RETHINK/PopupPresenter.swift
- Sources/StreamChatUI/Generated/L10n.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
- Sources/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources/StreamChatUI/UIConfig+Navigation.swift
- StreamChat.xcodeproj/project.pbxproj
Beginning of something new.
* Only view controllers are open by default and from 90 % documented, the rest is just public to make compiler happy
* `ChatMessageRouter` has no parent class
* `MessageListCollectionView` is now responsible for scrolling and updating the content. Scrolling methods are still called from the VCs but than passed directly to collection view
* `ThreadVC` has the parent message as a header
* `PopupPresenter` class is created to extract the presenting logic from both controller to one place
* Long press on ThreadVC doesn't show reply in thread option
> MessageListVC + MessageThreadVC

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelMuteDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO.swift
- Sources/StreamChat/Database/DTOs/CurrentUserDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/DeviceDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DataStore.swift
- Sources/StreamChat/Database/DataStore_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/Database/DatabaseSession_Tests.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/UserWatchingEventMiddleware.swift
- Sources/StreamChat/Workers/Background/MissingEventsPublisher.swift
- Sources/StreamChat/Workers/Background/MissingEventsPublisher_Tests.swift
- Sources/StreamChat/Workers/CurrentUserUpdater.swift
- Sources/StreamChat/Workers/CurrentUserUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChat/Workers/UserUpdater.swift
- Sources/StreamChat/Workers/UserUpdater_Tests.swift
- fetch `CurrentUserDTO` only once for each context, then rely on CoreData that its properties are up to date
- convert `func currentUser() -> CurrentUserDTO?` to `var currentUser: CurrentUserDTO?` to indicate that it is not fetched on each call
- use context's `userInfo` to store fetched user as I think this is exactly the kind of information that should be stored there (other option would be associated object)
- when `currentUser` is called for the first time (and the fetch from DB is performed) I register for the `DatabaseContainer.WillRemoveAllDataNotification` so I can clear cached user as leaving it there would create inconsistencies - there are apparently other options how to do this, but I think this responsibility should remain in this part of code
> Optimize current user fetch

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Controllers/Controller.swift
- Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver_Tests.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
This is mainly to avoid the crashes when `UICollectionView` is updated before it's fully laid out. We already try other (simpler) fixes but none of those worked properly. This is hopefully the last fix of this issue.
- I added `willChange` callback to `ListDatabaseObsever`
- I added `controllerWillChangeChannels` to `ChatChannelListController` delegate
- `ChatChannelListVC` now forces its `UICollectionView` to lay out before the update form the controller comes
---
If we see this pattern works and helps with the issue, we can extend other list controllers, too.
> [CIS-807] Add `controllerWillChangeChannels` delegate callback

- StreamChatUI.podspec
`StreamChatUI` podspec didn't specify the version of `StreamChat` explicitly which could lead to having an incompatible configuration of the frameworks resolved. By pinning the dependency explicitly to the same version as `StreamChat` we're fixing this issue + it replicates the same behavior as SPM has.
---
This was the issue behind https://github.com/GetStream/stream-chat-swift/issues/1015
> Explicitly pin `StreamChat` version in `StreamChatUI` podspec

- Sources/StreamChat/Controllers/EntityDatabaseObserver.swift
- Sources/StreamChat/Controllers/ListDatabaseObserver.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- Sources/StreamChat/Utils/CoreDataLazy_Tests.swift
- Sources/StreamChat/Workers/Background/NewChannelQueryUpdater.swift
- Sources/StreamChat/Workers/UserListUpdater_Tests.swift
- Sources/StreamChatTestTools/NSManagedObject+ContextChange.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChat.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
- Tests/StreamChatTests/StreamChatStressTestPlan.xctestplan
- Tests/StreamChatTests/StreamChatTestPlan.xctestplan
This PR fixes CoreData concurrency issues found by enabling `-com.apple.CoreData.ConcurrencyDebug` launch argument for demo app and for `StreamChat` test plans.
- I kept the launch argument for demo app and for both LLC test plans as I think it is useful to know about those issues
- fix issues in demo app
- fix issues in LLC tests
---
Closes #954
> Fix CoreData concurrency

- Sources/StreamChatUI/Appearance+Images.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerView.swift
- Sources/StreamChatUI/CommonViews/ChatInputView/ChatCommandLabel.swift
- Sources/StreamChatUI/CommonViews/ChatInputView/ChatInputTextView.swift
- Sources/StreamChatUI/CommonViews/ChatInputView/ChatMessageInputView.swift
- Sources/StreamChatUI/CommonViews/ContainerStackView.swift
- Fixes issue when a view that was already hidden would switch container, and remain with the size 0 and alpha = 0. This would cause a problem because the view would always have the size 0 and it wouldn't be possible to hide it again, because it already had alpha = 0.
- Fixes an issue on composer view that was causing the composer to layout twice
- Removes the state icon and polishes the composer layout according to Figma
With this PR, now the iMessage clone works as expected ✅
> Fix hiding issue when view switches container + Composer View Layout Polish

- Sources/StreamChat/APIClient/Endpoints/MessageEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/MessageEndpoints_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
`ChatMessageController.synchronize` fails. the followings are error logs.
```
2021-04-29 10:48:01.643 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:71]
[decodeRequestResponse(data:response:error:)] > keyNotFound(MessagePayloadsCodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key MessagePayloadsCodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))
```
In the `synchronize` implementation, `messageUpdater.getMessage` request fails because response type of `getMessage` endpoint should be `MessagePayload<ExtraData>.Boxed`, not `MessagePayload<ExtraData>`
[REST API](https://getstream.io/chat/docs/rest/#messages-getmanymessages) says successful response of `GET …
> Change response type of getMessage endpoint

- Package.swift
Fixes spm warning that showed that we need to explicilty mark .stencil file as resource or exclude it from target
> Fix Spm warning

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
In production code we had a typo in string constant that determines which media types are available for the user to pick from.
> Fix image picker crash in production

- CHANGELOG.md
- Sources/StreamChat/WebSocketClient/EventMiddlewares/ChannelReadUpdaterMiddleware.swift
- Changes log level for missing `ChannelReads` on `Channel` so they are logged as `info` rather than being `error`.
> [CIS-827] Change log level for ChannelRead in `ChannelReadUpdaterMiddleware`

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
Use separate `channelsCount` for channels in `ChatChannelListVC` so it can be updated inside `performBatchUpdates` as documented.
> Use separate `channelsCount` for `ChatChannelListVC`

- Sources/StreamChat/APIClient/APIClient_Mock.swift
- Sources/StreamChat/APIClient/APIClient_Tests.swift
- Sources/StreamChat/WebSocketClient/Engine/WebSocketEngine_Mock.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Mock.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
- FIxes `WebSocketClient_Tests` which failed on CI due to possibly bad configuration policy (using `default`, not `ehemeral`
- Check if the tests for this PR are green, if yes, this solution works
The `WebSocketClient` was initialized in tests with `default` `URLSessionConfiguration`, which stores all the caches and other session-related data on the disk. It is possible that due to unknown nature of the CI machine where github actions run tests those cached data were still persistent through all tests during the Test run. What I did is basically change the configuration to `ephemeral` which doesn't cache and any of the related data to disk and should resolve the problem.  
You can read more about the `URLSessionConfiguration` in here: …
> [CIS-828] Investigate reconnection strategy tests failure

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout_Tests.swift
In Xcode 12.5 started failing some tests - we can now fix `ChatMessageListCollectionViewLayout_Tests`. 
Cause of those tests failing is that original `prepare(forCollectionViewUpdates:)` on `UICollectionViewLayout` started to check some private API so are customized getters in `TestUpdateItem` are not called. This means that both tests in suite fail with this error:
```
*** -[NSMutableIndexSet addIndexesInRange:]: Range {9223372036854775807, 1} exceeds maximum index value of NSNotFound - 1
```
In Xcode 12.4 everything works fine.
By extracting all code that was originally in `prepare(forCollectionViewUpdates:)` to our customized method we can ensure that all work that we expect to be done is really done and also prevent calling `super.prepare(forCollectionViewUpdates:)` in tests.
Also …
> Fix `ChatMessageListCollectionViewLayout_Tests` in Xcode 12.5

- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
Seems like _just_ extraData updates correctly cause a delegate callback 🎉
> Add test for Channel extra data updates

- DemoApp/Info.plist
- Sources/StreamChat/APIClient/APIClient_Tests.swift
- Sources/StreamChat/APIClient/RequestEncoder_Tests.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Config/TokenProvider_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Controllers/UserListController/UserListController_Tests.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/ChatClientUpdater_Tests.swift
- Sources/StreamChat/Workers/CurrentUserUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC+SwiftUI.swift
- Sources/StreamChatUI/CommonViews/ListCollectionViewLayout/ListCollectionViewLayout.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/Shared/WaitFor.swift
With the new `async/await` that'll eventually be introduced to Swift, our own `await` stuff was causing a lot of warnings, now that's resolved, alongside other minor warnings.
> Fix swift warnings

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerVC.swift
Fixes a crash on iPad because it was missing the sourceView of the popover controller when presenting the attachments.
> [CIS-833] Fix crash when opening attachments on iPad

- Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
**Important note: The branch to merge is `release/beta`, we need to pick this commit into other release branches as well...** 
- Hotfixes crash that occured while longpressing message with active keyboard for composer
Follow steps in the ticket:
- Open any chat and make keyboard appear by tapping in composer input on real device or show keyboard on simulator
- Long tap on message any message cell to pupup context menu
- Expect app not to crash on layout feedback loop, because keyboard should be already hidden... 
This is hotfix, the proper fix should come with composer audit where the layout feedback loop is properly resolved
> [CIS-834] Hotfix: Layout feedback loop when longtapping message

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChatTestTools/ChatClientUpdater_Mock.swift
When websocket disconnects with token expiration error we should call `reloadUserIfNeeded` to reacquire it
> [CIS-224] Implement token refresh

- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
- Sources/StreamChat/Workers/Background/AttachmentUploader_Tests.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatFileAttachmentListView+ItemView.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageGiphyView.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageImageGallery+ImagePreview.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageInteractiveAttachmentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/ImageGallery/ImageCollectionViewCell.swift
- Sources/StreamChatUI/ImageGallery/ImageGalleryVC.swift
**This PR**:
- makes `ChatMessageAttachment.payload` non-optional
- adds dynamic payload lookup to `ChatMessageAttachment`
> Update `ChatMessageAttachment` to have non-optional payload

- Sources/StreamChatUI/ChatMessageList/MessageComposer/ChatMessageComposerInputTextView.swift
Removes the manual text view height calculation that causes UITextView layout glitches. (This is already on main)
**Before:** 
https://user-images.githubusercontent.com/12814114/118479894-788c9580-b709-11eb-957a-11302c777376.mov
**After:** 
https://user-images.githubusercontent.com/12814114/118479916-804c3a00-b709-11eb-99fa-082b4e973f94.mov
> [CIS-841] Fix custom fonts breaking composer input resizing

- CHANGELOG.md
- Sources/StreamChat/Config/ChatClientConfig.swift
make sure to connect to us-east by default, this needs to be added clearly to the changelog
> Use `usEast` as the default base URL

- Package.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessageAttachmentPayload.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessageAttachmentPayload_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/RawJSON.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment_Tests.swift
- Sources/StreamChatTestTools/DummyData/MessageAttachmentPayload.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/MockEnpointResponses/Attachment/AttachmentPayload+NoType.json
**This PR**:
- introduces an `unknown` attachment type and makes use of it when `type` field is missing in attachment JSON
- adds missing tests for attachment type erasure/recovery
- removes unused error types
> [CIS-843] Fallback to `unknown` if attachment type is missing

- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListRouter.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
- Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
UI Fixes for Thread related issues:
https://user-images.githubusercontent.com/12814114/119031855-75143b00-b9a3-11eb-90f2-cce14964f34c.mov
> Polish UI for beta release 4.0 (vol.3)

- Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
**This PR** moves documentation to the correct place
> Fix docs location for `attachment(payloadType:)`

- stream-chat-swift-docs/docs/guides/attachments-migration.md
- stream-chat-swift-docs/sidebars.js
**This PR** adds a `v3.2 -> v4.x` migration guide for attachments
> [CIS-861] Attachments migration guide

- stream-chat-swift-docs/docs/guides/attachments-migration.md
**This PR** removes tabs from the attachments migration guide
> Remove tabs from attachments migration guide

- Sources/StreamChatUI/Composer/ComposerVC.swift
The mention suggestions would still catch when a "@" was close to text, example: "sdsasd@email.com"
> Fix composer mention suggestions for missing edge case

- Sample/Samples/CombineSimpleChat/CombineSimpleChatViewController.swift
- Sample/Samples/SimpleChat/SimpleChatViewController.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
- Sources/StreamChatUI/Utils/ChatMessage+Extensions.swift
- Tests/StreamChatUITests/ChatMessage_Tests.swift
**This PR**:
- adds `ChatMessage.isDeleted` helper
- fixes `ChatMessage.isRootOfThread` helper
- adds missing tests for `ChatMessage` extensions
- renames fields to follow naming convention
> Open `ChatMessage` extensions, add missing tests

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
We don't have the functionality implemented yet, doesn't make sense to inhibit users from doing so
> Open swipeableView funcs in Channel List

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/WebSocketClient/Events/EventPayload.swift
- Sources/StreamChat/WebSocketClient/Events/TypingEvent.swift
- Sources/StreamChat/WebSocketClient/Events/TypingEvent_Tests.swift
- Sources/StreamChatTestTools/DummyData/XCTestCase+Dummy.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/MockEnpointResponses/Events/User/UserStartTypingThread.json
- Tests/StreamChatTests/MockEnpointResponses/Events/User/UserStopTypingThread.json
Add convenient helpers to check which features are enabled for a channel:
- Typing events
- Read events
- Uploads
- Replies
- Reactions
Channel Controller changes:
- `sendKeystrokeEvent` does not do anything if typing events are disabled
- `sendStartTypingEvent` and `sendStopTypingEvent` error when called on a channel with typing events disabled
- `markRead` returns an error if read events are disabled
> Do not send typing events unless they are enabled for this channel

- CHANGELOG.md
- Package.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageImageGallery+ImagePreview.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageLinkPreviewView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/CommonViews/Attachments/AttachmentViews/ImageAttachmentView.swift
- Sources/StreamChatUI/CommonViews/AvatarView/ChatChannelAvatarView.swift
- Sources/StreamChatUI/CommonViews/AvatarView/ChatUserAvatarView.swift
- Sources/StreamChatUI/CommonViews/AvatarView/CurrentChatUserAvatarView.swift
- Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView.swift
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/ImageGallery/ImageCollectionViewCell.swift
- Sources/StreamChatUI/ImageGallery/ImageGalleryVC.swift
- Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift
- Sources/StreamChatUI/Utils/ComponentsProvider_Tests.swift
- Sources/StreamChatUI/Utils/ImageCDN.swift
- Sources/StreamChatUI/Utils/ImageCDN_Tests.swift
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
- StreamChat.xcodeproj/project.pbxproj
- I created image CDN protocol to filter out query parameters from image URL and add thumbnail size parameters to the URL
- used the provider to fix an issue with constantly reloading images 
https://stream-io.atlassian.net/browse/CIS-789
https://stream-io.atlassian.net/browse/CIS-790
> [CIS-789,CIS-790] Use custom keys for image caching and Load image thumbnails correctly

- StreamChat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fastlane/Fastfile
Nuke 9.2 had a bug that spammed the console: https://github.com/kean/Nuke/issues/416
Resolved with 9.2.1, so we can update safely.
> Update SPM Dependencies

- Sources/StreamChat/Workers/Background/MissingEventsPublisher_Tests.swift
It was reported a couple of times that the test is flaky, I wasn't able to make it fail, but I think the reason is that we subscribe for things after we simulate the response. Probably it worked because usually we get to subscribe before the code we test actually execute, and in some rare cases it's faster than we get to subscribe.
So let's place response simulation below subscriptions
> [CIS-880] Fix a flaky test

- CHANGELOG.md
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
Not sure why, but Nuke sometimes fail to crop the image resulting in a full black square instead of a resized image.
I removed the `crop: true` parameter (default is `false`) and it seems to work.
> Fix invisible images in the message composer

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
**This PR** fixes the issue when the previous message bubble is not updated when the following message is deleted
https://user-images.githubusercontent.com/12818985/120696660-7a9a7680-c4b5-11eb-82c0-0de8692bdfa7.mp4
> Fix previous message bubble appearance on message deletion

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
**This PR** fixes the issue when message list jumps if new message is sent OR if an old message is edited 
https://user-images.githubusercontent.com/12818985/120686485-afa0cc00-c4a9-11eb-9068-8f0fba21cd59.mov
> Fix message list jumps

- Sources/StreamChatUI/Composer/ComposerVC.swift
Implementing this on the LLC level requires some refactoring around `TypingEventSender` (CIS-883). This is just a temporary fix until the feature is implemented on the LLC level.
(spotted on the video by @evsaev here https://github.com/GetStream/stream-chat-swift/pull/1148#issue-661089889 :) )
> Send `typingStop` event when message editing finished

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
This was removed by mistake during the merge of [1147](https://github.com/GetStream/stream-chat-swift/pull/1147)
> Reload the previous message when message is deleted

- StreamChat.xcodeproj/project.pbxproj
We need to exclude these architectures because of these warnings:
[09:08:55]: ▸ warning: The armv7 architecture is deprecated for your deployment target (iOS 11.0). You should update your ARCHS build setting to remove the armv7 architecture. (in target 'StreamChat' from project 'StreamChat')
636
[09:08:55]: ▸ warning: The armv7s architecture is deprecated for your deployment target (iOS 11.0). You should update your ARCHS build setting to remove the armv7s architecture. (in target 'StreamChat' from project 'StreamChat')
I ran Firebase distribution locally and it works, here I run the job to build it on CI, let's see if that works
https://github.com/GetStream/stream-chat-swift/actions/runs/907053373
> Fix Firebase build compilation

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionViewLayout.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListKeyboardObserver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Fixes list not scrolling when the current user sends a new message
- Removes "scrollToBottomIfNeeded" since it is not used anywhere, and is not useful
- Fixes when a new message is received, and the list is scrolled to the bottom, should remain scrolled to the bottom
- Content inset is now adjusted for typing indicator view when it appears.
- Refactors Keyboard Observer Implementation:
- Uses Apple's recommended way to get the keyboard height, to support docked keyboards.
- If the last message is hidden by the keyboard, just check if it is visible, and scroll to bottom.
> Fix scrolling when new message is sent + Refactor Keyboard Observer

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/SwipeableView.swift
- Fixes issue causing possibility of having swipe gesture recognizer on `ChatChannelListItemViewCell` to reveal the swipeable container even when there were no buttons 
- Go to `ChatChannelListVC` and go to `open func swipeableViewActionViews(for indexPath: IndexPath) -> [UIView]` from there return empty array. When you run the application, try to reveal the swipeable buttons by swiping if the swiping function is enabled.
Fixes #1159
> Disable cell swiping when there are no swipeable buttons

- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
**This PR** fixes the issue when sending a big message after a small one breaks scroll to bottom behaviour
https://user-images.githubusercontent.com/12818985/121220802-a179f380-c88d-11eb-8433-3897db6d23a2.mp4
https://user-images.githubusercontent.com/12818985/121221487-48f72600-c88e-11eb-81da-20417e278f1c.mp4
> Fix broken scroll to bottom

- CHANGELOG.md
- Dangerfile
- Sources/StreamChat/APIClient/APIClient_Tests.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Config/ChatClientConfig.swift
- Sources/StreamChat/WebSocketClient/Engine/URLSessionWebSocketEngine.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
- Sources/StreamChat/Workers/ChatClientUpdater.swift
- Sources/StreamChatTestTools/ChatClientUpdater_Mock.swift
Also moves the handling logic from WSClient to ChatClient.
Basically, when we disconnected, we automatically set a timer for reconnection, and reconnected while in background.
> Fix app auto-reconnect on background

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC+SwiftUI.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC+SwiftUI_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC+SwiftUI.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC+SwiftUI_Tests.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/CommonViews/SwiftUIViewRepresentable.swift
Now, when you subclass our VCs, you can create SwiftUI views from them. For example, for you our `CustomChatMessageListVC`:
```swift
var body: some View {
CustomChatMessageListVC.asView(channelController)
}
```
> Introduce `SwiftUIViewControllerRepresentable` and conformances

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
If the channel type doesn't support attachments or commands, shrink button shouldn't be displayed.
The change in UIImageView+Extension was to silence the Nuke deprecation warning
Also add CHANGELOG entry for #1171
> Fix shrink button is visible when it shouldn't be

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/ChannelListPayload.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
Backend doesn't send `commands` when it's empty and we initialize it as empty when it's missing, it doesn't need to be optional
> Make `ChannelConfig.commands` non-optional

- CHANGELOG.md
- Package.swift
- Sources/StreamChat/Query/Sorting/ChannelMemberListSortingKey.swift
- Sources/StreamChat/Query/Sorting/ChannelMemberListSortingKey_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
The keyPath `createdAt` didn't exist on MemberDTO and it led to a crash
> Fix sorting MemberList by createdAt causing crash

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- Tests/Shared/CustomAssertions/AssertJSONEqual.swift
1. We had some un-overridable functions in ChatChannelListVC, reported by users. First commits `open`s them
1. `mentionedUsers` was not being sent to backend, now that is fixed
1. `ComposerVC` now correctly handles mentions, and it's also possible to customize what's displayed as mention text. 
Only missing feature is editing mentions, currently not possible.
> Mentions refactoring

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/CommonViews/OnlyLinkTappableTextView.swift
I reproduced the issue @b-onc described and was able to fix it with this change.
I checked the resulting layouts before/after and they're identical.
I would really appreciate an opinion on how adequate the fix is, and if it's not, we still can figure out another solution based on the fact that this is still a root cause of the issue.
> [CIS-913] Fix layout feedback loop in ChatMessageContentView

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/Attachments/FileAttachmentViewInjector.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/GalleryAttachmentViewInjector.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/LinkAttachmentViewInjector.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/Components.swift
**This PR**:
- fixes missing handling of attachment actions in `ChatThreadVC`
- updates `GalleryContentViewDelegate` to have option index path so it work for thread root messages
https://user-images.githubusercontent.com/12818985/122929243-64286200-d373-11eb-8771-fd87901a53ba.mp4
> Fix `image/file/link/giphy` actions not being handled in threads

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListCollectionView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListUnreadCountView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ScrollToLatestMessageButton.swift
- Sources/StreamChatUI/Components.swift
- StreamChat.xcodeproj/project.pbxproj
- changes the behaviour of the `scrollToLatestMessageButton`. The button is now visible every time the last message is not visible. 
- adding badge icon to the button. Needed to create a new class with tint colour instead of alert colour on the background. 
- fixes issue where the `isLastCellFullyVisible` is `false` after calling `scrollToMostRecentMessage`
Badge preview:
Scrolling behaviour:
https://user-images.githubusercontent.com/7560049/122955624-8e345100-d380-11eb-8116-d3e9f410a5c0.mov
https://stream-io.atlassian.net/browse/CIS-928
> [CIS-928] Scroll to bottom button enahncements

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactionsBubbleView+Default.swift
We incorrectly marked those as private.
> [CIS-931] Make `ChatMessageDefaultReactionsBubbleView` subviews public

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
This happened because the textView's text was being updated unnecessarily
Fixes #1117
> [CIS-933] Fix composer textView's caret jumping to the end of input

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/Workers/Background/MessageSender_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
With this PR, sending silent messages is possible.
More about silent messages can be read here: https://getstream.io/chat/docs/react/silent_messages/?language=swift
- Add `isSilent` flag to `MessageRequestBody`
- Make changes to public APIs in `ChannelController` and `MessageController` to accept this flag
- Propagate this flag to lower levels and make relevant changes to the tests.
> [CIS-243] Implement silent messages

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
This happened for channels with typing events disabled
> [CIS-932] Fix composer overlapping last message

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
This happened when a controller's `synchronize` was called when `CurrentChatUserController`'s `didChangeUser` callback happened. The reason was nested `provideConnectionId` calls. It doesn't make sense to provide connectionId to waiters while keeping a lock to the `connectionId` resource.
> [CIS-934] Fix deadlock when connectionId is requested in a nested manner

- docusaurus/docs/iOS/basics/getting-started.md
Fixes a link that was previously going to getstream.io/chat/docs/sdk/ios/basics/getting-started/getstream.io/ when clicked.
> Fix link in Getting Started section

- CHANGELOG.md
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
We didn't include proper predicates for reply fetching
> [CIS-978] Fix deleted messages are visible in threads

- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
No CHANGELOG entry provided since this isn't a user facing change, and it's not resolving any known issue.
> [CIS-979] Change to using partial update for enabling/disabling slow mode

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListScrollOverlayView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/Utils/DateFormatter+Extensions.swift
**This PR** fixed the issue when date overlay jumps when loading more but moving an overlay outside the list view.
Tried the following first:
- `preserveSuperviewLayoutMargins = true` and keep pinning to `self.layoutMargins`
- pin to `superview.layoutMargins` directly
- create a top constraint with a constant calculated based on `contentOffset.y`
and none of it works 🚫. It seems `layoutMargins` follow the content size of table view when it changes and only after margins are updated to fit visible content area. Trying to follow the `contentOffset.y` would also involve following the `contentSize.height` which makes the logic of calculating the constraint too complicated.
https://user-images.githubusercontent.com/12818985/123954615-48dfd700-d9b1-11eb-9ac5-efd625ccee70.mp4
> [CIS-969] Date overlay jumps when loading more messages

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
**This PR** addresses the issue when local messages blink when reloaded because of local state changes
https://user-images.githubusercontent.com/12818985/124120313-4e562380-da7c-11eb-9f7f-2baf2e15fa1b.mp4
> [CIS-977] Fix flickering for messages being sent

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Models/Message.swift
- Sources/StreamChat/Workers/Background/MessageSender.swift
During the local cache invalidation process, the `channelDTO` value of the message can become `nil`. This PR fixes this edge case.
> [CIS-971] Make `Message.cid` optional

- CHANGELOG.md
- Package.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO.swift
- Sources/StreamChat/Database/DTOs/AttachmentDTO_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Models/Attachments/AnyAttachmentPayload.swift
- Sources/StreamChat/Models/Attachments/AnyAttachmentPayload_Tests.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment_Tests.swift
- Sources/StreamChat/Models/Attachments/ChatMessageFileAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageLinkAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageVideoAttachment.swift
- Sources/StreamChat/Models/Attachments/FileAttachmentPayload_Tests.swift
- Sources/StreamChat/Models/Attachments/ImageAttachmentPayload_Tests.swift
- Sources/StreamChat/Models/Attachments/VideoAttachmentPayload_Tests.swift
- Sources/StreamChat/Utils/Dictionary+Extensions.swift
- Sources/StreamChat/Workers/Background/AttachmentUploader_Tests.swift
- Sources/StreamChatTestTools/Models/Attachments/AnyAttachmentPayload_Mock.swift
- Sources/StreamChatTestTools/Models/Attachments/ChatMessageFileAttachment_Mock.swift
- Sources/StreamChatTestTools/Models/Attachments/ChatMessageImageAttachment_Mock.swift
- Sources/StreamChatUI/CommonViews/QuotedChatMessageView/QuotedChatMessageView_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatTests/DummyData/ChatMessageAttachment_Sample.swift
**This PR** addresses https://github.com/GetStream/stream-chat-swift/issues/1234 and allows to send in-rich built-in attachments with custom fields and parse it back.
To extend an image attachment with a custom fields declare a `Codable` type first:
```swift
struct CommentPayload: Codable {
let comment: String
}
```
To send an image attachment with custom payload do the following:
```swift
// 1. Create custom payload.
let commentPayload = CommentPayload(comment: "Happy birthday! 🎉")
// 2. Create an envelope for built-in attachment with custom payload.
let envelope = AnyAttachmentEnvelope(localFileURL: *url*, attachmentType: .image, extraData: commentPayload)
// 3. Send the message with attachment
channelController.createNewMessage(..., attachments: [envelope])
```
When message is sent an …
> [CIS-989] Expose extra data on built-in attachments

- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Whenever the user taps anywhere on the message list, the keyboard is dismissed. This PR closes https://github.com/GetStream/stream-chat-swift/issues/1165
> Dismiss the keyboard on tapping anywhere on the message list

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Workers/Background/MessageSender.swift
- Sources/StreamChat/Workers/Background/MessageSender_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Tests/Shared/TemporaryData.swift
[Fixes #1231]
We didn't reset `locallyCreatedAt` value after the message was sent which was causing the wrong ordering of the messages when the local time was different from the server time.
I also added an artificial time offset for the unsent messages sorting key such that the most recent message is always at the bottom of the list.
> [CIS-974] Messages maintain correct order of the local time is off

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/WebSocketClient/BackgroundTaskScheduler.swift
- Sources/StreamChat/WebSocketClient/WebSocketClient_Tests.swift
We spotted one additional case when it's possible for `ChatClientUpdater.connect` to be called before obtaining credentials:
https://github.com/GetStream/stream-chat-swift/issues/1218
It happens because we subscribe for notifications in `ChatClient`'s init
Two fixes to prevent this:
1) Do not call `ChatClientUpdater.connect` if one of  `connect` methods has not been called on `ChatClient`
2) Only listen to app state notifications in connected state, i.e. only subscribe when we connect and unsubscribe on disconnect
> [CIS-994] Fix the issue with receiving .didBecomeActive before connecting the client for the first time

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelUnreadCountView.swift
- fixes unread count badge logic allowing the badge to be shown with 0
https://stream-io.atlassian.net/browse/CIS-996
> [CIS-996] Fix unread count badge hiding logic

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
**This PR** fixes crash on `ChatThreadVC` when root message is not loaded
> [CIS-982] Crash when thread root message is not loaded

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
- This PR allows the user to copy images from anywhere and paste them into the composer.
- This support is limited to images currently, as the pasteboard readily provides us the copied image
https://user-images.githubusercontent.com/11807135/124904280-76a4cb80-e002-11eb-98d4-cdce8322c9d1.mp4
> [CIS-588] Add support for pasting images in the composer

- CHANGELOG.md
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Mock.swift
- Sources/StreamChat/ChatClient_Tests.swift
- Sources/StreamChat/Config/ChatClientConfig.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DatabaseContainer.swift
- Sources/StreamChat/Database/DatabaseContainer_Tests.swift
- Sources/StreamChat/Utils/Database/NSManagedObjectContext+Extensions.swift
- Sources/StreamChatTestTools/DatabaseContainer_Mock.swift
This PR adds an option to configure the visibility of deleted messages. This applies both to the channel messages, and to threads. 
We currently expose the following options:
```swift
/// All deleted messages are always hidden.
case alwaysHidden
/// Deleted message by current user are visible, other deleted messages are hidden.
case visibleForCurrentUser
/// Deleted messages are always visible.
case alwaysVisible
```
> [CIS-829] Make the visibility of deleted messages configurable

- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Fixes a bug where quoting a message which already quotes some message shows the already quoted message as non-quoted
**Example**
- There's message "A"
- A user creates an inline reply (quotes) "B" that quotes message "A"
- A user creates an inline reply (quotes) "C" that quotes message "B"
Result (earlier) -> message "B" no longer has the quoted message visible.
Result (now)  -> message "B" correctly displays the quoted message.
> [CIS-621] Fix quoting a quoted message bug

- CHANGELOG.md
- Sources/StreamChatTestTools/Controllers/ChatChannelController_Mock.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC_Tests.swift
If the `ChatMessageListVC` was presented without the channel list, the `commandsButton` and `attachmentsButton` would not be shown in the first render of the composer (first `updateContent()`).  Because when presenting the channel list this way the channels are not cached and so the `channelConfig` will be `nil` on the first `updateContent()`, which means that the `commandsButton` and `attachmentsButton` will be hidden. 
The solution is to call `composerVC.updateContent() ` when the `channelController.synchronize` finishes from the `MessageListVC`. With this, the composer is updated and will get the channel config properly and show the buttons.
I've changed the demo app to present a message list without the channel list to replicate the problem. In this video we can see that after the …
> [CIS-1023] Fix composer buttons not shown in first render

- CHANGELOG.md
- Sources/StreamChat/Models/Member.swift
- Sources/StreamChat/Models/Member_Tests.swift
- This PR allows the backend to send any value for the MemberRole(`role`) in the payload, thus making the SDK a bit more resilient to potential problems like [this](https://github.com/GetStream/stream-chat-swift/issues/1279)
> [CIS-1028] Allow any value for `MemberRole`

- CHANGELOG.md
- Sources/StreamChatUI/Utils/ImageCDN.swift
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
- fastlane/README.md
This will allow users to inject their HTTP headers to image loading requests
Would look like:
```swift
class CustomImageCDN: StreamImageCDN {
override func urlRequest(forImage url: URL) -> URLRequest {
var request = URLRequest(url: url)
request.setValue("Custom!", forHTTPHeaderField: "X-Custom-Header")
return request
}
}
```
and inject the class somewhere...
```swift
Components.default.imageCDN = CustomImageCDN()
```
> [CIS-1035] Introduce `urlRequest(forImage)` to ImageCDN

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerVC.swift
Composer send button should be disabled when the message is only whitespace. Sending whitespace only message breaks our UI.
Also, backend trims the whitespace when the message is published. If we send the message with leading/trailing whitespace, the UI first shows the message, but when backend sends the actual message, UI jumps. So it's better to send trimmed message to backend, to prevent UI jumps.
> [CIS-1038] Fix composer allowing whitespace only messages to be sent

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints.swift
- Sources/StreamChat/APIClient/Endpoints/ChannelEndpoints_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/MemberPayload.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Query/ChannelQuery.swift
- Sources/StreamChat/WebSocketClient/Events/EventType.swift
- Sources/StreamChat/WebSocketClient/Events/NotificationEvents.swift
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
Add methods for inviting a member, and for accepting/rejecting the invite.
```swift
channelController.inviteMembers(userIds: ["luke_skywalker", "leia_organa"]) { error in ... }
```
```swift
channelController.acceptInvite(message: "Hi everyone!") { error in ... }
```
```swift
channelController.rejectInvite() { error in ... }
```
After this change will have been merged, customers will be able to call invite/acceptInvite/rejectInvite endpoints, but they won't be able to react to events. For this to work we need changes from Pavel that introduce a mechanism for propagating events to customers' code
> [CIS-254] Implement methods for working with invites

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- This PR fixes [this](https://github.com/GetStream/stream-chat-swift/issues/1295) issue where a crash would occur when deleting a message from a channel when the deleted messages visibility is set to `alwaysHidden`
> [CIS-1043] Fix delete message action causing a crash

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageContentView.swift
- Fixes misplaced reaction bubbles on short messages caused by pinning the center X anchor to mainContainer instead of `bubbleView`/`bubbleContentContainer`. The width of `mainContainer` obviously expanded when there were threads or timestamp and it was longer than the bubble message (if user wrote short message...) 
- Go to an chat which contains short messages and scroll through the chat to find out if the reactions are pinned right
-  `ChatMessageContentView.swift ` 
Before: 
After:
> [CIS-1037] Fix misplaced reaction bubbles

- CHANGELOG.md
- Sources/StreamChat/Workers/ChannelUpdater.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
This fix is for the case where the channel is already hidden on backend but SDK is not aware of this (so channel.hiddenAt is not set)
Consecutive `hideChannel` calls won't generate `channel.hidden` events and SDK has no way to learn channel was hidden
So, ChannelUpdater marks the Channel as hidden on successful API response
> [CIS-1072] Fix hiding already hidden channels

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/ContainerStackView.swift
UIContainerView has these operations as no-op and so should we
> [CIS-1073] Change ContainerStackView assertions

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC+SwiftUI.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/AttachmentViewCatalog.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/LinkAttachmentViewInjector.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC+SwiftUI.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/Navigation/ChatChannelListRouter.swift
- Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift
- Fix SDK compilation issue for Xcode 13 beta 3  by marking functions leading to calling `UIApplication.shared.open` as `unavailable` for `iOSAppExtension`
- Run Attached demo project in Xcode 13 beta 3 and see if it compiles.
[TestingApp.zip](https://github.com/GetStream/stream-chat-swift/files/6904707/TestingApp.zip)
SPM Team is looking for different solutions to the problem, you can take a look at discussion here: 
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/24
> Fix Xcode 13 beta 3 AppExtension compilation

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware_Tests.swift
- Sources/StreamChat/Workers/ChannelUpdater_Tests.swift
This happened because we forgot to update the queries of Member when it's removed. A similar bug may be present in MemberAdded and MemberUpdated events. For those events, we need to re-fetch the queries, since Client doesn't have a way to apply filters.
> [CIS-1071] Fix member removed from Channel still present in MemberListController

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
- This PR enables us to limit the maximum height of the composer's textView before it enables scrolling behaviour. By this, we enhance the User Experience by not letting the textView grow to full screen. It fixes [this](https://github.com/GetStream/stream-chat-swift/issues/1335) reported issue.
> [CIS-558] MessageComposer - Limit the maximum height of composer's textview and add scrolling

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
CoreData entities should be accessed from their own queues only.
Resolves #1336
> [CIS-1079] Fix CoreData misuse when creating Direct Messaging channels

- docusaurus/docs/iOS/combine/channels.md
- docusaurus/docs/iOS/combine/combine-overview.md
- docusaurus/docs/iOS/combine/connection.md
- docusaurus/docs/iOS/combine/events.md
- docusaurus/docs/iOS/combine/messages.md
- docusaurus/docs/iOS/combine/users.md
- docusaurus/sidebars-ios.json
- For each controller delegate in our SDK, we also provide relevant publishers for clients that want to use `Combine` to observe the data. They can be referred to in the `Controller+Combine.swift` files
- Using these publishers, they can observe changes to the data and update their views accordingly
- Have a separate `Combine` section in the docs
- Have a separate page for each of the controllers
- In each of those pages, list down all the publishers provided by the controller, add a code snippet to use the publisher AND create some sample `UIKit` views to consume the data from these publishers.
**NOTE**: We do not cover `SwiftUI` examples here as for `SwiftUI`, we can use the `ObservableObject` versions of the controllers instead of using the publishers directly(This is the preferred …
> [CIS-1049] Add the `Combine` guide for the SDK

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
My idea was the following:
From the reports on the issue it seemed like the issue is in messages count going out of sync with view's state, so I though of caching message's count and only updating it when we need it
And then I noticed that for channel list there actually already was such a mechanism and it seems like channel list does not experience this kind of issues
The only difference of the suggested fix from the one on the channel list is that message list's structure is a little bit more complicated because it has a VC and a view, but essentially it's the same
> [CIS-1087] Fix data races in message list's message count

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
...when new replies are only added to the main chat, but not to the replies thread
The fix makes sure that we set thread message to the ComposerVC after `synchronize` executes. There is still an edge case for really fast users with really slow connection though 🙂 
Before merging this we need to run it by Oscar
> [CIS-1096] Fix an issue for ChatThreadVC opened from a deeplink

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
...when connected in offline mode
This happened because the EventObserver didn't get `connected` callback when we're already connected
> [CIS-1094] Fix ChannelListController.synchronize not calling completion

- CHANGELOG.md
- Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift
Fixes a UI jump glitch when opening the message actions popup when the message list is presented in a modal.
**Before**
**After**
> [CIS-1101] Fix jumps when presenting message popup actions in a modal

- CHANGELOG.md
- Sources/StreamChat/Models/ChannelType.swift
Backend allows this so client should too
> [CIS-1102] Fix creating custom Channel Types with uppercase letters

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/Attachments/ChatMessageImageGallery+ImagePreview.swift
Add support for `ChatMessageGalleryView.ImagePreview` to be used from Obj-c
> Fix ImagePreview nested type for objc bridging header

- CHANGELOG.md
- DemoApp/cs.lproj/Localizable.strings
- DemoApp/en.lproj/Localizable.strings
- Package.swift
- Sources/StreamChatUI/ChatMessageList/ChatChannelHeaderView.swift
- Sources/StreamChatUI/Gallery/GalleryVC.swift
- Sources/StreamChatUI/Generated/L10n.swift
- Sources/StreamChatUI/Resources/en.lproj/Localizable.strings
- Sources/StreamChatUI/Utils/DateUtils.swift
- Sources/StreamChatUI/Utils/DateUtils_Tests.swift
- StreamChat.xcodeproj/project.pbxproj
- Tests/StreamChatUITests/en.lproj/TestLocalizable.strings
Adds a utility formatter to represent a date in the past as a string, I used a homegrown approach to support iOS < 13
> CIS-1110 Fix time ago formatting

- docusaurus/docs/iOS/guides/migrating-from-1.x-and-2.x.md
Updating the existing migration guide makes more sense, since v4 and v3 are very similar and we don't support v3 with even bugfixes anymore.
> [CIS-1053] Update v2 migration guide

- CHANGELOG.md
- Sources/StreamChat/APIClient/Endpoints/Payloads/CustomDataHashMap_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/FlagMessagePayload_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/FlagUserPayload_Tests.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/RawJSON.swift
- Sources/StreamChat/APIClient/Endpoints/Payloads/RawJSON_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAudioAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageFileAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageVideoAttachment.swift
The initial implementation of RawJSON had `double` and `integer` types. This made decoding incorrect because integer values can be Int and Double and the decoder would always decode them as Int.
This PR removes `.integer` from RawJSON, adds a new case `.number` and keeps `.double` around as an "alias" of `.number`
> CIS-1113 Fix inconsistent/wrong RawJSON number type handling

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
- Sources/StreamChatUI/Utils/UIImageView+Extensions.swift
Problem: `dataSource?.tableView(self, cellForRowAt: indexPath)` is used inside the code that update the message list. 
This does not work because it accesses `controller.messages` which is on a different state than the `tableView`.
The solution: keep a copy of `controller.messages` that is consistent with the state of the table view.
> [CIS-1111] Copy messages to avoid out of sync table and collection crashes

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
- Sources/StreamChat/Utils/Atomic.swift
- Sources/StreamChat/Utils/Atomic_Tests.swift
- Sources/StreamChat/Workers/Background/DatabaseCleanupUpdater.swift
- Sources/StreamChat/Workers/Background/NewChannelQueryUpdater.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- Sources/StreamChat/Workers/ChannelListUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelListUpdater_Tests.swift
- Sources/StreamChat/Workers/MessageUpdater.swift
- Sources/StreamChat/Workers/MessageUpdater_Mock.swift
- Sources/StreamChat/Workers/MessageUpdater_Tests.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatThreadVC.swift
Ensures that Thread, MessageList and ChannelList
- Do not perform more than 1 API call in parallel to fetch prev/nex page
- Start fetching results at the right time 
- Stop paginating results when there is no more to fetch
> [CIS-1120] Fix pagination on all lists

- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
The channel list pagination was conflicting with the `scrollViewDidScroll` event as well as the `numberOfSections` was used instead of `numberOfItems` when fetching more channels.
> Fix Channel List Pagination

- Sources/StreamChat/Utils/Atomic.swift
The extension on `Atomic` in `StreamChat` needs to be public in order to be accessed outside the module
> Make extension on `Atomic` public

- CHANGELOG.md
- Sources/StreamChat/Config/ChatClientConfig.swift
- Sources/StreamChat/Database/DTOs/MemberModelDTO.swift
- Sources/StreamChat/Database/DTOs/UserDTO.swift
- Sources/StreamChatUI/Composer/ComposerVC.swift
The members that had a missing `lastActiveAt` weren't being fetched. So the sort descriptors should be `lastActiveAt` and the default so that the members and watchers are ordered by last active first, and then the default descriptor, in case the DTO doesn't have `lastActiveAt`
> [CIS-1135] Fix user mention suggestions not showing all members

- Sources/StreamChat/APIClient/Endpoints/Payloads/MessagePayloads_Tests.swift
- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
I investigated [this](https://github.com/GetStream/stream-chat-swift/issues/1377) issue and spotted this inconsistency
We don't need to pass it inside expiration handler because this is called in `BackgroundTaskScheduler` after the expiration handler. It's unclear if this caused any issues but it makes sense to fix it anyway
> [CIS-1137] Remove redundant background task cancelation

- Sources/StreamChatUI/Components.swift
Initially, `Components` were generic over extra data so we couldn't have stored type property. 
It's not generic anymore so we can simplify it.
> Simplify the way `Components.default` is stored

- CHANGELOG.md
- Sources/StreamChat/Controllers/ListDatabaseObserver_Mock.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController_Tests.swift
An issue was reported here:
https://github.com/GetStream/stream-chat-swift/issues/1389
It's easily reproducible with the local storage disabled, but when it disabled the behaviour is also not entirely correct
What's happening:
If there was a thread reply that was also sent to the channel, you get it when you fetch the channel. Then when you open the original thread, this problematic reply is in core data already, so `replies.last` won't return nil, even though the only reply in this collection has nothing to do with the last message. So we would take this `replies.last` reply and use it to start our pagination with, ignoring all the messages that are younger
> [CIS-1153] Fix an issue with thread replies not being shown if there was a reply that was also sent to a channel

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessage/ChatMessageLayoutOptionsResolver_Tests.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC.swift
- Sources/StreamChatUI/MessageActionsPopup/ChatMessageActionsVC_Tests.swift
- Removes `.threadInfo` from the message options in case threads are disabled
- Removes mute actions in case mutes are disabled
> [CIS-1156] Use remote config to disable threads and mutes

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController+SwiftUI_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Models/ChatMessage.swift
- Sources/StreamChatTestTools/Models/ChatMessage_Mock.swift
- Sources/StreamChatUI/ChatMessageList/Attachments/AttachmentViewCatalog.swift
Rewrite `attachmentCounts` to not use Core Data (previous approach with GROUP BY did not work on iOS 12 with in memory storage)
> Remove Group By from DTO

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/InputTextView/InputTextView.swift
A customer that is using MessageKit with Stream and is using Objc could not compile the app since MessageKit also contains an `InputTextView`. To fix this, we can provide a different name for Objc only.
> [CIS-1159] Provide different Objc name for `InputTextView`

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/Reactions/ChatMessageReactions+Types.swift
Makes the init public, which is required by a client.
> Make `ChatMessageReactionData.init` public

- Sample/Samples/UserUpdateViewController.swift
- Sources/StreamChat/APIClient/APIClient.swift
- Sources/StreamChat/APIClient/CDNClient.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelWatcherListController/ChatChannelWatcherListController.swift
- Sources/StreamChat/Controllers/ConnectionController/ConnectionController.swift
- Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift
- Sources/StreamChat/Controllers/EventsController/EventsController.swift
- Sources/StreamChat/Controllers/MemberController/MemberController.swift
- Sources/StreamChat/Controllers/MemberListController/MemberListController.swift
- Sources/StreamChat/Controllers/MessageController/MessageController.swift
- Sources/StreamChat/Controllers/SearchControllers/MessageSearchController/MessageSearchController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController/UserSearchController.swift
- Sources/StreamChat/Controllers/UserController/UserController.swift
- Sources/StreamChat/Controllers/UserListController/UserListController.swift
- Sources/StreamChat/Utils/InternetConnection/InternetConnection.swift
- Sources/StreamChat/Utils/InternetConnection/Reachability_Vendor.swift
- Sources/StreamChat/Workers/Background/ChannelWatchStateUpdater.swift
- Sources/StreamChat/Workers/Background/ConnectionRecoveryUpdater.swift
[-] Added replacement of unowned self everywhere in blocks
in production code to guard let self
[-] Added replacement of unowned self everywhere in blocks
in test code
[-] Improving tests to be compilable
Test plan:
- Open freshly installed app
- Select c3po user
- Open chat list
- Open chat
- Send message
- View photos
- Open chat with unread count 
- Create new chat with multiple users
All Pass
React on message - does no add reaction instantly
> [CIS-1117] Change unowned to weak self in blocks

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChatTestTools/ChatClient_Mock.swift
These new delegate funcs will be called for any inserted/updated channels which is not linked to the controller's query. Users will have a way to link new/updated channels to the query, without the need for `NewChannelQueryUpdater`
> [CIS-1157] Introduce linking delegate callbacks

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
Fixes the message list having a wrong content inset when typing events disabled. 
Also, it makes the implementation a little more robust.
> [CIS-1174] Fix message list wrong content inset when typing events disabled

- CHANGELOG.md
- Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift
When opening a channel without coming from a channel list, the typing events would be disabled even if the config had them enabled. The reason is that the `ChatMessageListVC.setUp` function is called before the `ChatChannelVC` finishing the synchronization, so at that time the channel config, won't be available. 
This fixes the issue by always adding the typing indicator view as a subview in the `setUp` function. And only uses the config when showing the typing indicator, if it is enabled, it sets `isHidden = true` , if not, it remains hidden.
> [CIS-1177] Fix typing events always disabled when channel opened without cache from Channel List

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift
For applications that are using `navigationController.navigationBar.isTranslucent = false` the keyboard handling wasn't working correctly. The reason being is that the keyboard height is not reported with the same value for when the keyboard is being dismissed, and this caused the composer view to have an extra space when hiding.
The proposed solution is much more robust and also more flexible. If previously the customer changed the bottom constraint value, it wouldn't work anyway, because we always assumed that value was 0, so the constraint would increase and decrease only accounting for the keyboard height, which is not correct. The correct approach is to distinguish when the keyboard is hiding or showing, and if it is hiding, we reset it with the original value, if it is showing, we …
> [CIS-1184] Fix keyboard handling when navigation bar is not translucent

- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
This is due to ChannelListController_Tests using ChatClientMock (and DatabaseContainerMock) and using onDisk caching. DatabaseContainerMock removed the DB file before the operations on it were not complete, and that caused undefined behavior. Switching to in-memory storage is safe.
> Fix ChannelListController_Tests failing

- CHANGELOG.md
- Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift
When the tabBar is not translucent the keyboard handling was not working properly because it changes the coordinate space of the composer view by adding the tabBar height to the origin of the composer view. For this to work in any case, what we need is to get the root view of the app which has all the info about tab bar's and nav bars when converting the keyboard frame to the current coordinate space.
> [CIS-1184] Fix composer keyboard handler when tabBar not translucent

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/ChatMessageAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageAudioAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageFileAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageGiphyAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageImageAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageLinkAttachment.swift
- Sources/StreamChat/Models/Attachments/ChatMessageVideoAttachment.swift
**This PR** makes built-it attachment payloads (and attachments with such payloads) `Hashable`
> Make attachment payloads `Hashable`

- CHANGELOG.md
- Sources/StreamChatUI/CommonViews/Attachments/AttachmentsPreviewVC.swift
Previously the size of the scroll view containing the attachment previews on the composer had a fixed height. The height should be dynamic so that the size is determined by the size of the attachment previews.
> [CIS-1195] Dynamic height for the composer attachment previews

- StreamChat.xcodeproj/project.pbxproj
- fastlane/Fastfile
There were a number of issues:
1. Dmitriy's cert was not valid anymore, we needed to manually get rid of it in ios-certificates repo and create new ones.
2. match_me had dmitriy's email hardcoded, not necessary
3. DemoAppPush needed profiles generated by match
4. DemoAppPush needed to link to StreamChat but not embed it, since DemoApp already embeds it
5. DemoAppPush needs version synced with DemoApp
> Fix fastlane testflight lane

- Sources/StreamChat/Utils/Codable+Extensions.swift
This fixes the automated code review CI Job. 
This was caused by https://github.com/GetStream/stream-chat-swift/pull/1486, since Danger is not running for forks.
> Fix styling on Codable+Extensions.swift

- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
This PR will set the image key name to `image` for the User object.
> Fixing unit tests for using closure in Xcode 13

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController.swift
- Sources/StreamChat/Controllers/ChannelListController/ChannelListController_Tests.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
This **PR** fixes the bug when all updated/inserted channels are added to the channel list before the underlaying query is synced. The fix updates `ChannelListController` to handle unlinked channels only when the `controller.synchronize` is successfully completed.
> [CIS-1187] Fix channel list showing `currentUser.mutedChannels` initially

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannel/ChatChannelVC.swift
- Sources/StreamChatUI/ChatThread/ChatThreadVC.swift
Some customers require this property to be public and it doesn't make sense to make it private anyways.
> Make `messageComposerBottomConstraint` public

- CHANGELOG.md
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/Gallery/GalleryVC.swift
- Sources/StreamChatUI/Gallery/GalleryVC_Tests.swift
**This PR** fixes the issue with `Image/VideoAttachmentGalleryCell` not taken from component.
> Take video and image cell types from components

- CHANGELOG.md
- DemoApp/ChatPresenter.swift
- Sources/StreamChatUI/Composer/ComposerKeyboardHandler.swift
- Fixes keyboard going over the composer input
- Adds debug options to QA the different keyboard handling scenarios
Related issue: https://github.com/GetStream/stream-chat-swift/issues/1494
- Slide a channel from the channel list to the left and tap on "..."
- Select "Change Nav Bar Translucency"
- Chose "Not Translucent"
- Tap on "..." again
- Select "Change channel presentation style"
- Chose "Embedded in Tab Bar"
- Tap on the channel to present it
- Tap on the composer
- Keyboard should not go over the composer
- Slide a channel from the channel list to the left and tap on "..."
- Select "Change channel presentation style"
- Chose "Modally"
- Tap on the channel to present it
- Tap on the composer
- Keyboard should not go over the composer …
> Fix keyboard over composer

- Package.swift
This will remove the warning when building the project. We no longer need to specify the folder structure.
> Removing folder structure within resource key for package.swift file

- CHANGELOG.md
- Sources/StreamChatUI/Components.swift
- Sources/StreamChatUI/Deprecations.swift
- Sources/StreamChatUI/MessageActionsPopup/MessageActionsTransitionController.swift
- Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift
CIS-1207, CIS-1232
- Fix crash when `ChatMessagePopupVC` is dismissed when the message is outside the visible area of the message list
- Fix behavior when a long-pressed message is swapped with a newly received message when they have the same style
Stop passing `ChatMessageContentView` across the message list and pop-up view hierarchies and pass the copy instead. 
Therefore, the following subviews are removed from `MessageActionsTransitionController`:
- messageContentViewFrame
- messageContentViewActivateConstraints
- messageContentViewDeactivateConstraints
- messageContentView
- messageContentViewSuperview
- mainContainerTopAnchor
Manual testing:
- Launch `DemoApp` on 2 devices
- Sign in as `Luke` and `Leia`
- Open the channel where both users are members
- Send text message as `Luke`, …
> [CIS-1207, CIS-1232] Fix crash and swapping the long-pressed message on `ChatMessagePopupVC`

- DemoApp/Base.lproj/Main.storyboard
- DemoApp/CreateChatViewController.swift
Fix the broken constraints when creating a new group
Currently, when creating a new group the constraints around the AvatarView are breaking.
I have fixed this by removing the unnecessary StackView and setting a strict TableViewCell height as is required as this doesn't need to be a dynamic cell.
1. Run the DemoApp
2. Create a new Group
> Fixing broken constraints on the CreateChatViewController

- DemoApp/DemoAppCoordinator.swift
- DocsSnippets/01-UX/00-Quick-Start/02-Channels-Code.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC_Tests.swift
- StreamChatSample/LoginViewController.swift
- docusaurus/docs/iOS/basics/getting-started.md
https://stream-io.atlassian.net/browse/CIS-1247
Introduce a new factory method to instantiate a ChatChannelListVC so that we're not relying on ViewController lifecycle. This will prevent a crash if `super` is called before instantiating. 
New factory method that will take a UIStoryboard and/or UIStoryboardId if these aren't resolved then we return a newly created ChatChannelListVC with the controller that is passed in.
The implementation will look something like this:
`let controller = ChatClient.shared.channelListController(query: .init(filter: .containMembers(userIds: [userCredentials.id])))`
`let chatList = ChatChannelListVC.make(with: controller, storyboard: nil, storyboardId: nil)`
> [CIS-1247] Adding new factory method to create ChatChannelListVC

- CHANGELOG.md
- DemoApp/DemoAppCoordinator.swift
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
In the new `make` function we have just introduced we want to enable subclasses still and set our own custom implementation as the default.
Our visible override should be shown (we have additional buttons in the navigation bar)
> Small hotfix to include subclasses within the new `make` function

- CHANGELOG.md
- Sources/StreamChatUI/Utils/ImageLoading/NukeImageLoader.swift
CIS-1252
https://github.com/GetStream/stream-chat-swift/issues/1562
Make the `NukeImageLoader` Overridable.
Simply make the `init()` accessible. Although the class was already open and with open functions, the init was not accessible, which prohibited using the custom subclass by the customer.
N/A
N/A
> [CIS-1252] Make the `NukeImageLoader` initialiser accessible

- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/WebSocketClient/EventMiddlewares/MemberEventMiddleware.swift
- StreamChat.xcodeproj/project.pbxproj
- StreamChat.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/Messenger.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/Slack.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChat.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChatSample.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChatTests.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/StreamChatUI.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/YouTube.xcscheme
- StreamChat.xcodeproj/xcshareddata/xcschemes/iMessage.xcscheme
[https://stream-io.atlassian.net/browse/CIS-1286](https://stream-io.atlassian.net/browse/CIS-1286)
Update build settings in framework targets to match the latest Xcode 13.0 defaults.
* Changed bundle identifier of `StreamChat` framework from `io.getstream.StreamChat-v3` into `io.getstream.StreamChat`
* `ARCHS_STANDARD` are used instead of custom list
```
ARCHS = (
arm64,
armv7,
armv7s,
x86_64,
);
```
* `ENABLE_TESTABILITY` turned off on release builds
* Added copyright to existing framework target's build settings
* Removed references to `v3` and `v3` betas from framework targets
* Resolves compile warnings
> [CIS-1286] Update build settings to follow Xcode 13.0 default

- CHANGELOG.md
- Sources/StreamChatUI/Utils/Bundle+Extensions.swift
- StreamChatUI.podspec
https://stream-io.atlassian.net/browse/CIS-1251
This was an ongoing issue when pulling our resources from the Bundle file. This is only affecting Xcode 13 but this bundle name has to be unique otherwise it's clashing with the target membership.
Gave the Bundle a unique name and updated the Bundle location in the Swift class.
I have tested this by having a sample cocoapods integrated StreamChatUI application and uploaded to TestFlight, the result is that all the assets are now loaded.
> [CIS-1251] Giving the Bundle resources a unique name

- CHANGELOG.md
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
- Sources/StreamChat/Database/DTOs/MessageDTO_Tests.swift
- Sources/StreamChat/Models/ChatMessage.swift
- Sources/StreamChat/Models/ChatMessage_Tests.swift
CIS-1308
A message should be pinned when there is no expiration date, and `pinned = true`.
`MessagePinDetails` should have an optional expiration date just like the documentation states.
Unit Tests were added to prove it now works properly.
N/A
> [CIS-1308] Fix message not pinned when expiration date is nil

- CHANGELOG.md
- Sources/StreamChat/Models/Attachments/AttachmentTypes.swift
- Sources/StreamChat/Models/Attachments/AttachmentTypes_Tests.swift
Android SDK wasn't able to parse our video attachments.
It turned out that iOS reports the file name uppercased (eg TRIMMED_FILE123.MOV) and we couldn't detect it was a video (MOV) so we encoded it as generic (octet-stream)
Enable logs and upload a video attachment, check the encoded mime type.
> Fix MOV attachment mime type encoding

- CHANGELOG.md
- Sources/StreamChatUI/ChatChannelList/ChatChannelListVC.swift
- Sources/StreamChatUI/ChatMessageList/ChatMessageListView.swift
- Sources/StreamChatUI/Utils/CollectionUpdatesMapper.swift
- Sources/StreamChatUI/Utils/CollectionUpdatesMapper_Tests.swift
CIS-1262
CIS-1293
- Fix message list scrolling jumps when a new message is received.
- Fix message cell size not updated when editing a message with bigger/smaller content.
- **Bonus:**
- Fix not executing the `completion` of `updateMessages()` which was not being called ever.
- Removes the list changes conflicts log.
- Scrolling jumps fix: Whenever the message list is reloaded, it re-calculates the message cell's height, causing a scrolling jump. When using `performBatchUpdates` this is not an issue. Use `performBatchUpdates` only for inserts. We also need to reload the previous cell to make sure the timestamp is removed if needed.
- Message cell resize fix: When a message is edited, previously we were just updating the message cell content and not reloading the cell. Now, if the text of …
> [CIS-1262, CIS-1293] Fix message list jumps and cell not resizing on edit

- Sources/StreamChat/Controllers/ChannelController/ChannelController.swift
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelDTO.swift
- Sources/StreamChat/Database/DTOs/ChannelListQueryDTO.swift
- Sources/StreamChat/Database/StreamChatModel.xcdatamodeld/StreamChatModel.xcdatamodel/contents
- Sources/StreamChat/Query/ChannelListQuery_Tests.swift
CIS-1320
It was decided to stop persisting active channel list queries/open channels in the database and have references to active components in memory.
Remove relation between `ChannelListQueryDTO <->> ChannelDTO`, stop labeling a channel as open.
⚠️ This is pointing to an integration branch. No changes will be made to `main` until this feature is complete
> [CIS-1320] Stop persisting open channels

- CHANGELOG.md
- Sources/StreamChatUI/Gallery/ZoomDismissalInteractionController.swift
CIS-1242
Possibly related to https://github.com/GetStream/stream-chat-swift/issues/1601 (Not sure)
Fix memory leak of GalleryVC when opening the gallery preview. There was a memory leak caused by a forgotten weak ref of the transition context in the `ZoomDismissalInteractionController`.
Make `ZoomDismissalInteractionController.transitionContext` a weak ref.
2. Open multiple times the gallery image preview
3. Go back to the channel list
4. Logout
5. Open the Memory Graph
6. Verify there are no `GalleryVC` instances in memory
(If you do these steps on main, you can see multiple instances of GalleryVC)
N/A
> [CIS-1242] Fix memory leak in GalleryVC

- DemoApp/CreateChatViewController.swift
- DemoApp/CreateGroupViewController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController/UserSearchController.swift
- Sources/StreamChat/Controllers/SearchControllers/UserSearchController/UserSearchController_Tests.swift
- Sources/StreamChat/Database/DTOs/ChannelListQueryDTO.swift
- Sources/StreamChat/Database/DatabaseSession.swift
- Sources/StreamChat/Database/DatabaseSession_Mock.swift
- Sources/StreamChat/Deprecations.swift
- Sources/StreamChat/Query/Filter.swift
- Sources/StreamChat/Query/UserListQuery.swift
- Sources/StreamChat/Query/UserListQuery_Tests.swift
- Sources/StreamChat/Workers/Background/DatabaseCleanupUpdater.swift
- Sources/StreamChat/Workers/Background/DatabaseCleanupUpdater_Tests.swift
- Sources/StreamChat/Workers/Background/NewUserQueryUpdater.swift
- Sources/StreamChat/Workers/Background/NewUserQueryUpdater_Tests.swift
- Sources/StreamChat/Workers/ChannelListUpdater.swift
- Sources/StreamChat/Workers/ChannelListUpdater_Mock.swift
- Sources/StreamChat/Workers/ChannelListUpdater_Tests.swift
- Sources/StreamChat/Workers/UserListUpdater.swift
- Sources/StreamChat/Workers/UserListUpdater_Mock.swift
- Sources/StreamChat/Workers/UserListUpdater_Tests.swift
- Sources/StreamChatTestTools/Controllers/ChatUserSearchController_Mock.swift
- Sources/StreamChatUI/CommonViews/Suggestions/ChatSuggestionsVC.swift
CIS-1329
The goal of this PR is to remove the explicit hash from the `Filter` type and the extra complexity/indirections that it's causing. 
It was initially introduced for background workers that try to link the newly inserted entity to local queries by sending the API request with `.and([originalFilter, .equals("id", to: entity.id)])` filter. If the entity was returned from the APIs the query should be updated with a new entity and filter so if `explicitHash` was not set another query is created in the database because the new filter hash is different from the hash of the original filter.
Now we are moving towards removing background workers for all the queries and moving the decision to the controller level which is more flexible, reduces the # of API calls from the client but still …
> [CIS-1329] Get rid of `Filter.explicitHash`

- CHANGELOG.md
- Sources/StreamChat/Controllers/ChannelController/ChannelController_Tests.swift
- Sources/StreamChat/Database/DTOs/MessageDTO.swift
CIS-1338
When a giphy action is sent in a thread, backend replies with an ephemeral message. This message shouldn't be shown in main channel, but it does.
Turned out we don't filter out ephemeral messages for threads.
Send a giphy action in a thread and check the main channel.
> [CIS-1338] Fix ephemeral messages in threads also shown in channel

- Sources/StreamChat/ChatClient.swift
- Sources/StreamChat/ChatClient_Tests.swift
[JIRA](https://stream-io.atlassian.net/browse/SWUI-33)
We need to track the usage of the different SDKs (low-level client, UIKit and SwiftUI), via the custom HTTP header X-Stream-Client.
In the implementation, we're relying on whether the appropriate SDK can be imported, using the `canImport` macro.
The currently provided values are "swiftui", "uikit" and "swift". The other option would be to keep "swift" for "uikit", for backward compatibility, and use something like "llc" for the low-level client.
Test the DemoApp in this repo, by putting a breakpoint after setting the `httpAdditionalHeaders` in `ChatClient`, after line  186.
Test the DemoAppSwiftUI app in https://github.com/GetStream/stream-chat-swiftui. Note that you will need to setup the Swift package dependency to this branch …
> Added identifier for tracking the usage of the different SDKs

- CHANGELOG.md
- Sources/StreamChat/Utils/Logger/Destination/LogDestination.swift
Integrators aiming to route SDK logs to their own logs couldn't access `LogDetails` fields
We actually missed this during testing, the fields should've been public
Try to subclass `BaseLogDestination` and override `process` func to access `logDetails` fields
> Make LogDestination fields public and accessible
